SoCRocket: .ycm_extra_conf.py File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
.ycm_extra_conf.py File Reference
Functions
def DirectoryOfThisScript
def MakeRelativePathsInFlagsAbsolute
def IsHeaderFile
def GetCompilationInfoForFile
def FlagsForFile
Variables
list flags
tuple compilation_database_folder = os.path.join(DirectoryOfThisScript(), "build")
tuple database = ycm_core.CompilationDatabase(compilation_database_folder)
list SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]
Function Documentation
def DirectoryOfThisScript ()
Referenced by FlagsForFile().
def FlagsForFile (filename, kwargs)
References DirectoryOfThisScript(), GetCompilationInfoForFile(), and MakeRelativePathsInFlagsAbsolute().
def GetCompilationInfoForFile (filename)
References IsHeaderFile().
Referenced by FlagsForFile().
def IsHeaderFile (filename)
Referenced by GetCompilationInfoForFile().
def MakeRelativePathsInFlagsAbsolute (flags, working_directory)
References pysc::api::cci.list().
Referenced by FlagsForFile().
Variable Documentation
tuple compilation_database_folder = os.path.join(DirectoryOfThisScript(), "build")
database = ycm_core.CompilationDatabase(compilation_database_folder)
list flags
Initial value:
 = [
 '-Wall',
 '-Wextra',
 '-Werror',
 '-Wc++98-compat',
 '-Wno-long-long',
 '-Wno-variadic-macros',
 '-fexceptions',
 '-DNDEBUG',
 '-std=c++11',
 '-x', 'c++',
 ]
Referenced by IntrinsicBase.correct_flags(), trap::OSEmulatorBase.correct_flags(), openIntrinsic< wordSize >.operator()(), trap::openSysCall< wordSize >.operator()(), and readLockFile().
list SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]