SoCRocket: core/software/grlib_tests/apbuart.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
apbuart.c File Reference
#include <stdio.h>
Classes
struct uart_regs
Macros
#define DISABLE 0x0
#define ENABLE_RX 0x1
#define ENABLE_TX 0x2
#define RX_INT 0x4
#define TX_INT 0x8
#define EVEN_PARITY 0x20
#define ODD_PARITY 0x30
#define LOOP_BACK 0x80
#define FLOW_CONTROL 0x40
#define FIFO_TX_INT 0x200
#define FIFO_RX_INT 0x400
Functions
int apbuart_test (int addr)
Macro Definition Documentation
#define DISABLE 0x0
Referenced by apbuart_test().
#define ENABLE_RX 0x1
Referenced by apbuart_test().
#define ENABLE_TX 0x2
Referenced by apbuart_test().
#define EVEN_PARITY 0x20
#define FIFO_RX_INT 0x400
#define FIFO_TX_INT 0x200
#define FLOW_CONTROL 0x40
#define LOOP_BACK 0x80
Referenced by apbuart_test().
#define ODD_PARITY 0x30
#define RX_INT 0x4
#define TX_INT 0x8
Function Documentation
int apbuart_test (int addr)
References uart_regs::control, uart_regs::data, DISABLE, ENABLE_RX, ENABLE_TX, fail, i, LOOP_BACK, report_device(), uart_regs::scaler, and uart_regs::status.
Referenced by base_test(), and base_test_tirq().