SoCRocket: core/software/grlib_tests/brm_1553.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
brm_1553.c File Reference
#include <stdlib.h>
Classes
struct brm_irq_reg
struct brm_regs
Macros
#define BRM_IRQ 14
Functions
void brm_create_cmd (unsigned short *addr, unsigned short op, unsigned short cond, unsigned short rtrt, unsigned short cw1, unsigned short cw2, unsigned short dp, unsigned short bra, unsigned short time, int bus)
void brm_bcrt (unsigned short *addr, unsigned short dp, unsigned short rtaddr, unsigned short sa, unsigned short wc, int bus)
void brm_rtbc (unsigned short *addr, unsigned short dp, unsigned short rtaddr, unsigned short sa, unsigned short wc, int bus)
void brm_sync (volatile unsigned int *gpio, int gpio_sync, int gpio_ack)
int brm_1553_test (unsigned int brm_addr, unsigned int mem_addr, unsigned int gpio_addr, int gpio_sync, int gpio_ack)
Variables
struct brm_regs * bc
volatile unsigned short * brm_bcmem = NULL
volatile unsigned int * brm_bcmemi = NULL
volatile int brm_done =0
Macro Definition Documentation
#define BRM_IRQ 14
Function Documentation
int brm_1553_test (unsigned int brm_addr, unsigned int mem_addr, unsigned int gpio_addr, int gpio_sync, int gpio_ack)
References brm_bcmem, brm_sync(), brm_regs::ctrl, brm_regs::dpoint, brm_regs::enhanced, fail, brm_regs::imask, brm_regs::ipend, brm_regs::ipoint, mem, brm_regs::oper, report_device(), report_subtest(), brm_regs::w_ahbaddr, brm_regs::w_ctrl, and brm_regs::w_irqctrl.
void brm_bcrt (unsigned short * addr, unsigned short dp, unsigned short rtaddr, unsigned short sa, unsigned short wc, int bus)
References brm_create_cmd().
void brm_create_cmd (unsigned short * addr, unsigned short op, unsigned short cond, unsigned short rtrt, unsigned short cw1, unsigned short cw2, unsigned short dp, unsigned short bra, unsigned short time, int bus)
Referenced by brm_bcrt(), and brm_rtbc().
void brm_rtbc (unsigned short * addr, unsigned short dp, unsigned short rtaddr, unsigned short sa, unsigned short wc, int bus)
References brm_create_cmd().
void brm_sync (volatile unsigned int * gpio, int gpio_sync, int gpio_ack)
Referenced by brm_1553_test().
Variable Documentation
struct brm_regs* bc
volatile unsigned short* brm_bcmem = NULL
Referenced by brm_1553_test().
volatile unsigned int* brm_bcmemi = NULL
volatile int brm_done =0