SoCRocket: core/software/grlib_tests/cache.h File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
cache.h File Reference
Functions
void flush (void)
void ifill (int)
void dfill (int)
int getitag (int addr, int set)
void setitag (int addr, int set, int data)
void setidata (int addr, int set, int data)
int getidata (int addr, int set)
int asmgetitag (int addr)
void asmsetitag (int addr, int data)
int asmgetidata (int addr)
void asmsetidata (int addr, int data)
void wsysreg (int addr, int data)
int rsysreg (int addr)
void setdtag (int addr, int set, int data)
void setddata (int addr, int set, int data)
int chkdtag (int addr)
int getdtag (int addr, int set)
int getddata (int addr, int set)
void dma (int addr, int len, int write)
int asmgetdtag (int addr)
void asmsetdtag (int addr, int data)
int asmgetddata (int addr)
void asmsetddata (int addr, int data)
void setudata (int addr, int data)
int getudata (int addr)
int asmgetudata (int addr)
int xgetpsr (void)
void setpsr (int psr)
void flushi (int addr, int data)
void flushd (int addr, int data)
int line0 ()
int line1 ()
int line2 ()
int line3 ()
int cachetest (void)
long long int getdw ()
void cache_disable (void)
void cache_enable (void)
void ramfill (void)
Function Documentation
int asmgetddata (int addr)
References result.
Referenced by getddata().
int asmgetdtag (int addr)
References result.
Referenced by chkdtag(), and getdtag().
int asmgetidata (int addr)
References result.
Referenced by getidata().
int asmgetitag (int addr)
References result.
Referenced by getitag().
int asmgetudata (int addr)
References result.
Referenced by getudata().
void asmsetddata (int addr, int data)
Referenced by setddata().
void asmsetdtag (int addr, int data)
Referenced by setdtag().
void asmsetidata (int addr, int data)
Referenced by setidata().
void asmsetitag (int addr, int data)
Referenced by setitag().
void cache_disable (void)
Referenced by cramtest(), gptimer_test(), main(), and ramfill().
void cache_enable (void)
Referenced by cramtest(), and ramfill().
int cachetest (void)
References wsysreg().
Referenced by leon3_test(), and main().
int chkdtag (int addr)
References asmgetdtag(), DDIAGMSK, and DSETS.
void dfill (int)
void dma (int addr, int len, int write)
void flush (void)
Referenced by leon3_funclt_trap::LDSBA_reg::behavior(), leon3_funclt_trap::LDUH_imm::behavior(), leon3_funclt_trap::STA_reg::behavior(), leon3_funclt_trap::LDSHA_reg::behavior(), leon3_funclt_trap::STBA_reg::behavior(), leon3_funclt_trap::ST_imm::behavior(), leon3_funclt_trap::SWAPA_reg::behavior(), leon3_funclt_trap::STH_reg::behavior(), leon3_funclt_trap::LD_reg::behavior(), leon3_funclt_trap::ST_reg::behavior(), leon3_funclt_trap::LDD_reg::behavior(), leon3_funclt_trap::LDUH_reg::behavior(), leon3_funclt_trap::SAVE_imm::behavior(), leon3_funclt_trap::STD_imm::behavior(), leon3_funclt_trap::SWAP_imm::behavior(), leon3_funclt_trap::STH_imm::behavior(), leon3_funclt_trap::LDD_imm::behavior(), leon3_funclt_trap::LDUHA_reg::behavior(), leon3_funclt_trap::RETT_imm::behavior(), leon3_funclt_trap::RESTORE_reg::behavior(), leon3_funclt_trap::LDSH_reg::behavior(), leon3_funclt_trap::STD_reg::behavior(), leon3_funclt_trap::LDSH_imm::behavior(), leon3_funclt_trap::LDSTUBA_reg::behavior(), leon3_funclt_trap::BRANCH::behavior(), leon3_funclt_trap::SWAP_reg::behavior(), leon3_funclt_trap::STDA_reg::behavior(), leon3_funclt_trap::LDUBA_reg::behavior(), leon3_funclt_trap::LDA_reg::behavior(), leon3_funclt_trap::STHA_reg::behavior(), leon3_funclt_trap::LDDA_reg::behavior(), leon3_funclt_trap::RESTORE_imm::behavior(), leon3_funclt_trap::LD_imm::behavior(), leon3_funclt_trap::RETT_reg::behavior(), leon3_funclt_trap::SAVE_reg::behavior(), cramtest(), mmu_cache::exec_data(), mmu_cache::exec_instr(), leon3_funclt_trap::Instruction::RaiseException(), ramfill(), leon3_mmu_cache::read_byte(), leon3_funclt_trap::TLMMemory::read_byte(), leon3_funclt_trap::TLMMemory::read_dword(), leon3_mmu_cache::read_dword(), leon3_mmu_cache::read_half(), leon3_funclt_trap::TLMMemory::read_half(), leon3_mmu_cache::read_instr(), leon3_funclt_trap::TLMMemory::read_instr(), leon3_funclt_trap::TLMMemory::read_word(), leon3_mmu_cache::read_word(), sc_main(), leon3_mmu_cache::write_byte(), leon3_funclt_trap::TLMMemory::write_byte(), leon3_mmu_cache::write_dword(), leon3_funclt_trap::TLMMemory::write_dword(), leon3_mmu_cache::write_half(), leon3_funclt_trap::TLMMemory::write_half(), leon3_mmu_cache::write_word(), and leon3_funclt_trap::TLMMemory::write_word().
void flushd (int addr, int data)
void flushi (int addr, int data)
int getddata (int addr, int set)
References asmgetddata(), and DDIAGMSK.
int getdtag (int addr, int set)
References asmgetdtag(), and DDIAGMSK.
long long int getdw ()
int getidata (int addr, int set)
References asmgetidata(), and IDIAGMSK.
int getitag (int addr, int set)
References asmgetitag(), and IDIAGMSK.
int getudata (int addr)
References asmgetudata().
void ifill (int)
int line0 ()
int line1 ()
int line2 ()
int line3 ()
void ramfill (void)
Referenced by main().
int rsysreg (int addr)
References result.
Referenced by cramtest(), mmu_test(), ramfill(), and spw_test().
void setddata (int addr, int set, int data)
References asmsetddata(), and DDIAGMSK.
void setdtag (int addr, int set, int data)
References asmsetdtag(), and DDIAGMSK.
void setidata (int addr, int set, int data)
References asmsetidata(), and IDIAGMSK.
void setitag (int addr, int set, int data)
References asmsetitag(), and IDIAGMSK.
void setpsr (int psr)
References psr.
Referenced by fputest(), irqtest(), and l2irqtest().
void setudata (int addr, int data)
void wsysreg (int addr, int data)
Referenced by cachetest().
int xgetpsr (void)
References result.
Referenced by fputest(), irqtest(), and l2irqtest().