SoCRocket: pysc::api::cci::CallbackAdapter Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
pysc::api::cci::CallbackAdapter Class Reference
Pysc
Public Member Functions
CallbackAdapter (PyObject *call, void *_observer_ptr, gs::gs_param_base *_caller_param)
~CallbackAdapter ()
gs::cnf::callback_return_type call (gs::gs_param_base &param, gs::cnf::callback_type &reason)
Constructor & Destructor Documentation
pysc::api::cci::CallbackAdapter::CallbackAdapter (PyObject * call, void * _observer_ptr, gs::gs_param_base * _caller_param) inline
References call().
pysc::api::cci::CallbackAdapter::~CallbackAdapter () inline
Member Function Documentation
gs::cnf::callback_return_type pysc::api::cci::CallbackAdapter::call (gs::gs_param_base & param, gs::cnf::callback_type & reason) inline
References usi.shell::args(), PythonModule::block_threads(), result, pysc::api::systemc::simulation_time(), and PythonModule::unblock_threads().
Referenced by CallbackAdapter().
The documentation for this class was generated from the following file:
pysc/usi/api/cci.cpp