SoCRocket: leon3_funcat_trap::TLMMemory Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
leon3_funcat_trap::TLMMemory Class Reference
#include <externalPorts.hpp>
Public Member Functions
TLMMemory (sc_module_name portName)
void setDebugger (MemoryToolsIf< unsigned int > *debugger)
tlm::tlm_sync_enum nb_transport_bw (tlm::tlm_generic_payload &trans, tlm::tlm_phase &phase, sc_time &delay) throw ()
void peq_cb (tlm::tlm_generic_payload &trans, const tlm::tlm_phase &phase)
sc_dt::uint64 read_dword (const unsigned int &address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw ()
unsigned int read_word (const unsigned int &address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw ()
unsigned short int read_half (const unsigned int &address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw ()
unsigned char read_byte (const unsigned int &address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw ()
unsigned int read_instr (const unsigned int &address, const unsigned int flush) throw ()
void write_dword (const unsigned int &address, sc_dt::uint64 datum, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw ()
void write_word (const unsigned int &address, unsigned int datum, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw ()
void write_half (const unsigned int &address, unsigned short int datum, unsigned int asi, unsigned int flush, unsigned int lock) throw ()
void write_byte (const unsigned int &address, unsigned char datum, unsigned int asi, unsigned int flush, unsigned int lock) throw ()
sc_dt::uint64 read_dword_dbg (const unsigned int &address) throw ()
unsigned int read_word_dbg (const unsigned int &address) throw ()
unsigned short int read_half_dbg (const unsigned int &address) throw ()
unsigned char read_byte_dbg (const unsigned int &address) throw ()
void write_dword_dbg (const unsigned int &address, sc_dt::uint64 datum) throw ()
void write_word_dbg (const unsigned int &address, unsigned int datum) throw ()
void write_half_dbg (const unsigned int &address, unsigned short int datum) throw ()
void write_byte_dbg (const unsigned int &address, unsigned char datum) throw ()
void lock ()
void unlock ()
Public Member Functions inherited from leon3_funcat_trap::MemoryInterface
void swapEndianess (unsigned int &datum) const throw ()
void swapEndianess (unsigned short int &datum) const throw ()
virtual ~MemoryInterface ()
Public Attributes
tlm_utils::simple_initiator_socket
< TLMMemory, 32 > initSocket
Constructor & Destructor Documentation
leon3_funcat_trap::TLMMemory::TLMMemory (sc_module_name portName)
References initSocket, and nb_transport_bw().
Member Function Documentation
void leon3_funcat_trap::TLMMemory::lock () virtual
Implements leon3_funcat_trap::MemoryInterface.
Referenced by read_word(), and write_word().
tlm::tlm_sync_enum leon3_funcat_trap::TLMMemory::nb_transport_bw (tlm::tlm_generic_payload & trans, tlm::tlm_phase & phase, sc_time & delay) throw () inline
References trans.
Referenced by TLMMemory().
void leon3_funcat_trap::TLMMemory::peq_cb (tlm::tlm_generic_payload & trans, const tlm::tlm_phase & phase)
unsigned char leon3_funcat_trap::TLMMemory::read_byte (const unsigned int & address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () virtual
Implements leon3_funcat_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, flush(), dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
unsigned char leon3_funcat_trap::TLMMemory::read_byte_dbg (const unsigned int & address) throw () virtual
Reimplemented from leon3_funcat_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
sc_dt::uint64 leon3_funcat_trap::TLMMemory::read_dword (const unsigned int & address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () virtual
Implements leon3_funcat_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, flush(), dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
sc_dt::uint64 leon3_funcat_trap::TLMMemory::read_dword_dbg (const unsigned int & address) throw () virtual
Reimplemented from leon3_funcat_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
unsigned short int leon3_funcat_trap::TLMMemory::read_half (const unsigned int & address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () virtual
Implements leon3_funcat_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, flush(), dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
unsigned short int leon3_funcat_trap::TLMMemory::read_half_dbg (const unsigned int & address) throw () virtual
Reimplemented from leon3_funcat_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
unsigned int leon3_funcat_trap::TLMMemory::read_instr (const unsigned int & address, const unsigned int flush) throw () inline virtual
Implements leon3_funcat_trap::MemoryInterface.
References icio_payload_extension::debug, v::debug, flush(), icio_payload_extension::flush, initSocket, leon3_funcat_trap::MemoryInterface::swapEndianess(), and trans.
unsigned int leon3_funcat_trap::TLMMemory::read_word (const unsigned int & address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () inline virtual
Implements leon3_funcat_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, flush(), dcio_payload_extension::flush, initSocket, dcio_payload_extension::lock, lock(), leon3_funcat_trap::MemoryInterface::swapEndianess(), and trans.
unsigned int leon3_funcat_trap::TLMMemory::read_word_dbg (const unsigned int & address) throw () virtual
Reimplemented from leon3_funcat_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
Referenced by sc_main().
void leon3_funcat_trap::TLMMemory::setDebugger (MemoryToolsIf< unsigned int > * debugger)
Referenced by sc_main().
void leon3_funcat_trap::TLMMemory::unlock () virtual
Implements leon3_funcat_trap::MemoryInterface.
void leon3_funcat_trap::TLMMemory::write_byte (const unsigned int & address, unsigned char datum, unsigned int asi, unsigned int flush, unsigned int lock) throw () virtual
Implements leon3_funcat_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, flush(), dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
void leon3_funcat_trap::TLMMemory::write_byte_dbg (const unsigned int & address, unsigned char datum) throw () virtual
Reimplemented from leon3_funcat_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
void leon3_funcat_trap::TLMMemory::write_dword (const unsigned int & address, sc_dt::uint64 datum, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () virtual
Implements leon3_funcat_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, flush(), dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
void leon3_funcat_trap::TLMMemory::write_dword_dbg (const unsigned int & address, sc_dt::uint64 datum) throw () virtual
Reimplemented from leon3_funcat_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
void leon3_funcat_trap::TLMMemory::write_half (const unsigned int & address, unsigned short int datum, unsigned int asi, unsigned int flush, unsigned int lock) throw () virtual
Implements leon3_funcat_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, flush(), dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
void leon3_funcat_trap::TLMMemory::write_half_dbg (const unsigned int & address, unsigned short int datum) throw () virtual
Reimplemented from leon3_funcat_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
void leon3_funcat_trap::TLMMemory::write_word (const unsigned int & address, unsigned int datum, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () inline virtual
Implements leon3_funcat_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, flush(), dcio_payload_extension::flush, initSocket, dcio_payload_extension::lock, lock(), trap::MemoryToolsIf< addressType >::notifyAddress(), leon3_funcat_trap::MemoryInterface::swapEndianess(), and trans.
void leon3_funcat_trap::TLMMemory::write_word_dbg (const unsigned int & address, unsigned int datum) throw () virtual
Reimplemented from leon3_funcat_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
Member Data Documentation
tlm_utils::simple_initiator_socket< TLMMemory, 32 > leon3_funcat_trap::TLMMemory::initSocket
Referenced by read_instr(), read_word(), sc_main(), TLMMemory(), and write_word().
The documentation for this class was generated from the following files:
core/models/extern/LEON3/simulatorSources/leon3.funcat/externalPorts.hpp
core/models/extern/LEON3/simulatorSources/leon3.funcat/externalPorts.cpp