SoCRocket: gs_config< uint64_t > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
gs_config< uint64_t > Class Template Reference
#include <gs_config_stdint.hpp>
Public Member Functions
gs_config (const std::string &nam, const unsigned int &val)
Constructor with unsigned int value.
gs_config (const char *nam, const unsigned int &val)
gs_config (const std::string nam, const unsigned int &val, gs_param_array *parent_array)
gs_config (const char *nam, const unsigned int &val, gs_param_array *parent_array)
gs_config (const std::string nam, const unsigned int &val, gs_param_array &parent_array)
gs_config (const char *nam, const unsigned int &val, gs_param_array &parent_array)
gs_config (const char *nam, const unsigned long long int &val)
gs_config (const std::string nam, const unsigned long long int &val, gs_param_array *parent_array)
gs_config (const char *nam, const unsigned long long int &val, gs_param_array *parent_array)
gs_config (const std::string nam, const unsigned long long int &val, gs_param_array &parent_array)
gs_config (const char *nam, const unsigned long long int &val, gs_param_array &parent_array)
gs_config (const std::string &nam, const int &val)
Constructor with int value.
gs_config (const char *nam, const int &val)
const std::string getTypeString () const
Overloads gs_config::getTypeString.
const Param_type getType () const
Overloads gs_config::getType.
std::string convertValueToString (const val_type &val) const
Overloads gs_config_t<T>::convertValueToString.
Static Public Member Functions
static std::string static_convertValueToString (const val_type &val)
static bool static_deserialize (val_type &target_val, const std::string &str)
Static convertion function called by virtual deserialize and others (e.g. GCnf_API)
Public Attributes
GS_CONFIG_HEAD
GC_SPECIALISATIONS_ARITHMETIC_OPERATORS
GC_SPECIALISATIONS_BINARY_OPERATORS
GC_SPECIALISATIONS_INCREMENT_OPERATORS
GC_SPECIALISATIONS_DECREMENT_OPERATORS
GS_CONFIG_DELEGATE
Detailed Description
template<>
class gs_config< uint64_t >
Template specialization for gs_config<uint64_t>. Default value = 0.
Constructor & Destructor Documentation
gs_config< uint64_t >::gs_config (const std::string & nam, const unsigned int & val) inline explicit
Constructor with unsigned int value.
References core.waf.repo::init().
gs_config< uint64_t >::gs_config (const char * nam, const unsigned int & val) inline explicit
References core.waf.repo::init().
gs_config< uint64_t >::gs_config (const std::string nam, const unsigned int & val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< uint64_t >::gs_config (const char * nam, const unsigned int & val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< uint64_t >::gs_config (const std::string nam, const unsigned int & val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< uint64_t >::gs_config (const char * nam, const unsigned int & val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< uint64_t >::gs_config (const char * nam, const unsigned long long int & val) inline explicit
References core.waf.repo::init().
gs_config< uint64_t >::gs_config (const std::string nam, const unsigned long long int & val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< uint64_t >::gs_config (const char * nam, const unsigned long long int & val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< uint64_t >::gs_config (const std::string nam, const unsigned long long int & val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< uint64_t >::gs_config (const char * nam, const unsigned long long int & val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< uint64_t >::gs_config (const std::string & nam, const int & val) inline explicit
Constructor with int value.
References core.waf.repo::init().
gs_config< uint64_t >::gs_config (const char * nam, const int & val) inline explicit
References core.waf.repo::init().
Member Function Documentation
std::string gs_config< uint64_t >::convertValueToString (const val_type & val) const inline
Overloads gs_config_t<T>::convertValueToString.
const Param_type gs_config< uint64_t >::getType () const inline
Overloads gs_config::getType.
const std::string gs_config< uint64_t >::getTypeString () const inline
Overloads gs_config::getTypeString.
static std::string gs_config< uint64_t >::static_convertValueToString (const val_type & val) inline static
static bool gs_config< uint64_t >::static_deserialize (val_type & target_val, const std::string & str) inline static
Static convertion function called by virtual deserialize and others (e.g. GCnf_API)
Member Data Documentation
gs_config< uint64_t >::GC_SPECIALISATIONS_ARITHMETIC_OPERATORS
gs_config< uint64_t >::GC_SPECIALISATIONS_BINARY_OPERATORS
gs_config< uint64_t >::GC_SPECIALISATIONS_DECREMENT_OPERATORS
gs_config< uint64_t >::GC_SPECIALISATIONS_INCREMENT_OPERATORS
gs_config< uint64_t >::GS_CONFIG_DELEGATE
gs_config< uint64_t >::GS_CONFIG_HEAD
The documentation for this class was generated from the following file:
core/common/gs_config/gs_config_stdint.hpp