SoCRocket: io_if Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
io_if Class Reference abstract
Apbuart
#include <io_if.h>
Public Member Functions
virtual uint32_t receivedChars ()=0
virtual void getReceivedChar (char *toRecv)=0
virtual void sendChar (char toSend)=0
Member Function Documentation
virtual void io_if::getReceivedChar (char * toRecv) pure virtual
Implemented in TcpIo, and NullIO.
Referenced by APBUART::data_read().
virtual uint32_t io_if::receivedChars () pure virtual
Implemented in TcpIo, and NullIO.
Referenced by APBUART::data_read(), and APBUART::status_read().
virtual void io_if::sendChar (char toSend) pure virtual
Implemented in TcpIo, and NullIO.
Referenced by APBUART::data_write().
The documentation for this class was generated from the following file:
core/models/apbuart/io_if.h