SoCRocket: leon3_funcat_trap::Instruction Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
leon3_funcat_trap::Instruction Class Reference abstract
#include <instructions.hpp>
Inherits trap::InstructionBase.
Inherited by leon3_funcat_trap::BRANCH, leon3_funcat_trap::CALL, leon3_funcat_trap::FLUSH_imm, leon3_funcat_trap::FLUSH_reg, leon3_funcat_trap::ICC_writeAdd_op [virtual], leon3_funcat_trap::ICC_writeDiv_op [virtual], leon3_funcat_trap::ICC_writeLogic_op [virtual], leon3_funcat_trap::ICC_writeSub_op [virtual], leon3_funcat_trap::ICC_writeTAdd_op [virtual], leon3_funcat_trap::ICC_writeTSub_op [virtual], leon3_funcat_trap::ICC_writeTVAdd_op [virtual], leon3_funcat_trap::ICC_writeTVSub_op [virtual], leon3_funcat_trap::InvalidInstr, leon3_funcat_trap::IRQ_IRQ_Instruction, leon3_funcat_trap::JUMP_imm, leon3_funcat_trap::JUMP_reg, leon3_funcat_trap::LD_imm, leon3_funcat_trap::LD_reg, leon3_funcat_trap::LDA_reg, leon3_funcat_trap::LDD_imm, leon3_funcat_trap::LDD_reg, leon3_funcat_trap::LDDA_reg, leon3_funcat_trap::LDSB_imm, leon3_funcat_trap::LDSB_reg, leon3_funcat_trap::LDSBA_reg, leon3_funcat_trap::LDSH_imm, leon3_funcat_trap::LDSH_reg, leon3_funcat_trap::LDSHA_reg, leon3_funcat_trap::LDSTUB_imm, leon3_funcat_trap::LDSTUB_reg, leon3_funcat_trap::LDSTUBA_reg, leon3_funcat_trap::LDUB_imm, leon3_funcat_trap::LDUB_reg, leon3_funcat_trap::LDUBA_reg, leon3_funcat_trap::LDUH_imm, leon3_funcat_trap::LDUH_reg, leon3_funcat_trap::LDUHA_reg, leon3_funcat_trap::READasr, leon3_funcat_trap::READpsr, leon3_funcat_trap::READtbr, leon3_funcat_trap::READwim, leon3_funcat_trap::READy, leon3_funcat_trap::RESTORE_imm, leon3_funcat_trap::RESTORE_reg, leon3_funcat_trap::RETT_imm, leon3_funcat_trap::RETT_reg, leon3_funcat_trap::SAVE_imm, leon3_funcat_trap::SAVE_reg, leon3_funcat_trap::ST_imm, leon3_funcat_trap::ST_reg, leon3_funcat_trap::STA_reg, leon3_funcat_trap::STB_imm, leon3_funcat_trap::STB_reg, leon3_funcat_trap::STBA_reg, leon3_funcat_trap::STBAR, leon3_funcat_trap::STD_imm, leon3_funcat_trap::STD_reg, leon3_funcat_trap::STDA_reg, leon3_funcat_trap::STH_imm, leon3_funcat_trap::STH_reg, leon3_funcat_trap::STHA_reg, leon3_funcat_trap::SWAP_imm, leon3_funcat_trap::SWAP_reg, leon3_funcat_trap::SWAPA_reg, leon3_funcat_trap::TRAP_imm, leon3_funcat_trap::TRAP_reg, leon3_funcat_trap::UNIMP, leon3_funcat_trap::WB_plain_op [virtual], leon3_funcat_trap::WB_tv_op [virtual], leon3_funcat_trap::WRITEasr_imm, leon3_funcat_trap::WRITEasr_reg, leon3_funcat_trap::WRITEpsr_imm, leon3_funcat_trap::WRITEpsr_reg, leon3_funcat_trap::WRITEtbr_imm, leon3_funcat_trap::WRITEtbr_reg, leon3_funcat_trap::WRITEwim_imm, leon3_funcat_trap::WRITEwim_reg, leon3_funcat_trap::WRITEY_imm, and leon3_funcat_trap::WRITEY_reg.
Public Member Functions
Instruction (Reg32_0 &PSR, Reg32_1 &WIM, Reg32_2 &TBR, Reg32_3 &Y, Reg32_3 &PC, Reg32_3 &NPC, RegisterBankClass &GLOBAL, Reg32_3 *WINREGS, Reg32_3 *ASR, Alias &FP, Alias &LR, Alias &SP, Alias &PCR, Alias *REGS, TLMMemory &instrMem, TLMMemory &dataMem, PinTLM_out_32 &irqAck)
virtual unsigned int behavior ()=0
virtual Instruction * replicate () const =0 throw ()
virtual void setParams (const unsigned int &bitString)=0 throw ()
virtual std::string getInstructionName () const =0 throw ()
Returns the instruction name.
virtual std::string getMnemonic () const =0 throw ()
virtual unsigned int getId () const =0 throw ()
Gets the ID of the instruction as returned by the decoder.
void annull ()
void flush ()
void stall (const unsigned int &numCycles)
bool IncrementRegWindow () throw ()
bool DecrementRegWindow () throw ()
int SignExtend (unsigned int bitSeq, unsigned int bitSeq_length) const throw ()
void RaiseException (unsigned int pcounter, unsigned int npcounter, unsigned int exceptionId, unsigned int customTrapOffset=0)
bool checkIncrementWin () const throw ()
bool checkDecrementWin () const throw ()
virtual ~Instruction ()
Public Attributes
unsigned int totalInstrCycles
Protected Member Functions
void IncrementPC () throw ()
Protected Attributes
Reg32_0 & PSR
Reg32_1 & WIM
Reg32_2 & TBR
Reg32_3 & Y
Reg32_3 & PC
Reg32_3 & NPC
RegisterBankClass & GLOBAL
Reg32_3 * WINREGS
Reg32_3 * ASR
Alias & FP
Alias & LR
Alias & SP
Alias & PCR
Alias * REGS
TLMMemory & instrMem
TLMMemory & dataMem
PinTLM_out_32 & irqAck
const unsigned int NUM_REG_WIN
const bool PIPELINED_MULT
Constructor & Destructor Documentation
leon3_funcat_trap::Instruction::Instruction (Reg32_0 & PSR, Reg32_1 & WIM, Reg32_2 & TBR, Reg32_3 & Y, Reg32_3 & PC, Reg32_3 & NPC, RegisterBankClass & GLOBAL, Reg32_3 * WINREGS, Reg32_3 * ASR, Alias & FP, Alias & LR, Alias & SP, Alias & PCR, Alias * REGS, TLMMemory & instrMem, TLMMemory & dataMem, PinTLM_out_32 & irqAck)
References totalInstrCycles.
leon3_funcat_trap::Instruction::~Instruction () virtual
Member Function Documentation
void leon3_funcat_trap::Instruction::annull () inline
virtual unsigned int leon3_funcat_trap::Instruction::behavior () pure virtual
Implemented in leon3_funcat_trap::IRQ_IRQ_Instruction, leon3_funcat_trap::ANDcc_imm, leon3_funcat_trap::WRITEpsr_reg, leon3_funcat_trap::CALL, leon3_funcat_trap::ORcc_imm, leon3_funcat_trap::OR_reg, leon3_funcat_trap::SAVE_reg, leon3_funcat_trap::SDIVcc_imm, leon3_funcat_trap::RETT_reg, leon3_funcat_trap::LDUB_imm, leon3_funcat_trap::TRAP_reg, leon3_funcat_trap::LD_imm, leon3_funcat_trap::RESTORE_imm, leon3_funcat_trap::SLL_reg, leon3_funcat_trap::LDDA_reg, leon3_funcat_trap::STHA_reg, leon3_funcat_trap::LDA_reg, leon3_funcat_trap::STBAR, leon3_funcat_trap::XNORcc_imm, leon3_funcat_trap::UDIV_reg, leon3_funcat_trap::ADDX_reg, leon3_funcat_trap::JUMP_reg, leon3_funcat_trap::LDUBA_reg, leon3_funcat_trap::ORNcc_imm, leon3_funcat_trap::XORcc_imm, leon3_funcat_trap::SMUL_reg, leon3_funcat_trap::JUMP_imm, leon3_funcat_trap::UMAC_reg, leon3_funcat_trap::STDA_reg, leon3_funcat_trap::SUBX_imm, leon3_funcat_trap::SWAP_reg, leon3_funcat_trap::SMULcc_imm, leon3_funcat_trap::SDIV_reg, leon3_funcat_trap::TADDccTV_reg, leon3_funcat_trap::SUBcc_imm, leon3_funcat_trap::XOR_reg, leon3_funcat_trap::ADDcc_reg, leon3_funcat_trap::SUB_imm, leon3_funcat_trap::SMULcc_reg, leon3_funcat_trap::BRANCH, leon3_funcat_trap::TSUBcc_reg, leon3_funcat_trap::UMAC_imm, leon3_funcat_trap::WRITEwim_reg, leon3_funcat_trap::SUB_reg, leon3_funcat_trap::XORcc_reg, leon3_funcat_trap::MULScc_imm, leon3_funcat_trap::ORcc_reg, leon3_funcat_trap::UMULcc_imm, leon3_funcat_trap::LDSTUBA_reg, leon3_funcat_trap::UNIMP, leon3_funcat_trap::LDSH_imm, leon3_funcat_trap::UDIV_imm, leon3_funcat_trap::XNOR_imm, leon3_funcat_trap::SUBX_reg, leon3_funcat_trap::WRITEtbr_reg, leon3_funcat_trap::TADDccTV_imm, leon3_funcat_trap::ANDNcc_imm, leon3_funcat_trap::STD_reg, leon3_funcat_trap::ORN_imm, leon3_funcat_trap::UDIVcc_reg, leon3_funcat_trap::LDSH_reg, leon3_funcat_trap::SRA_imm, leon3_funcat_trap::SETHI, leon3_funcat_trap::TSUBccTV_reg, leon3_funcat_trap::ANDN_reg, leon3_funcat_trap::LDSB_reg, leon3_funcat_trap::SMAC_imm, leon3_funcat_trap::LDSTUB_imm, leon3_funcat_trap::READwim, leon3_funcat_trap::UMUL_imm, leon3_funcat_trap::ADD_imm, leon3_funcat_trap::SMUL_imm, leon3_funcat_trap::AND_imm, leon3_funcat_trap::STB_reg, leon3_funcat_trap::ADDXcc_reg, leon3_funcat_trap::RESTORE_reg, leon3_funcat_trap::LDUB_reg, leon3_funcat_trap::WRITEtbr_imm, leon3_funcat_trap::TRAP_imm, leon3_funcat_trap::ADD_reg, leon3_funcat_trap::SDIVcc_reg, leon3_funcat_trap::RETT_imm, leon3_funcat_trap::ORNcc_reg, leon3_funcat_trap::FLUSH_reg, leon3_funcat_trap::TSUBccTV_imm, leon3_funcat_trap::SDIV_imm, leon3_funcat_trap::TADDcc_imm, leon3_funcat_trap::TADDcc_reg, leon3_funcat_trap::LDUHA_reg, leon3_funcat_trap::SLL_imm, leon3_funcat_trap::LDD_imm, leon3_funcat_trap::WRITEwim_imm, leon3_funcat_trap::STH_imm, leon3_funcat_trap::SRA_reg, leon3_funcat_trap::FLUSH_imm, leon3_funcat_trap::AND_reg, leon3_funcat_trap::WRITEY_imm, leon3_funcat_trap::UMUL_reg, leon3_funcat_trap::SWAP_imm, leon3_funcat_trap::ADDX_imm, leon3_funcat_trap::SUBXcc_reg, leon3_funcat_trap::STD_imm, leon3_funcat_trap::OR_imm, leon3_funcat_trap::MULScc_reg, leon3_funcat_trap::SAVE_imm, leon3_funcat_trap::SRL_reg, leon3_funcat_trap::LDUH_reg, leon3_funcat_trap::ADDcc_imm, leon3_funcat_trap::LDD_reg, leon3_funcat_trap::SUBcc_reg, leon3_funcat_trap::ST_reg, leon3_funcat_trap::LD_reg, leon3_funcat_trap::WRITEasr_reg, leon3_funcat_trap::SMAC_reg, leon3_funcat_trap::XOR_imm, leon3_funcat_trap::LDSTUB_reg, leon3_funcat_trap::UMULcc_reg, leon3_funcat_trap::WRITEasr_imm, leon3_funcat_trap::SRL_imm, leon3_funcat_trap::STH_reg, leon3_funcat_trap::SUBXcc_imm, leon3_funcat_trap::STB_imm, leon3_funcat_trap::ADDXcc_imm, leon3_funcat_trap::SWAPA_reg, leon3_funcat_trap::UDIVcc_imm, leon3_funcat_trap::READtbr, leon3_funcat_trap::ST_imm, leon3_funcat_trap::STBA_reg, leon3_funcat_trap::LDSHA_reg, leon3_funcat_trap::ORN_reg, leon3_funcat_trap::STA_reg, leon3_funcat_trap::LDUH_imm, leon3_funcat_trap::LDSBA_reg, leon3_funcat_trap::TSUBcc_imm, leon3_funcat_trap::ANDcc_reg, leon3_funcat_trap::ANDN_imm, leon3_funcat_trap::READpsr, leon3_funcat_trap::XNORcc_reg, leon3_funcat_trap::READy, leon3_funcat_trap::WRITEpsr_imm, leon3_funcat_trap::LDSB_imm, leon3_funcat_trap::ANDNcc_reg, leon3_funcat_trap::XNOR_reg, leon3_funcat_trap::WRITEY_reg, leon3_funcat_trap::READasr, and leon3_funcat_trap::InvalidInstr.
Referenced by leon3_funcat_trap::Processor_leon3_funcat::mainLoop().
bool leon3_funcat_trap::Instruction::checkDecrementWin () const throw ()
References key_CWP.
bool leon3_funcat_trap::Instruction::checkIncrementWin () const throw ()
References key_CWP.
bool leon3_funcat_trap::Instruction::DecrementRegWindow () throw ()
References key_CWP.
void leon3_funcat_trap::Instruction::flush () inline
virtual unsigned int leon3_funcat_trap::Instruction::getId () const throw () pure virtual
Gets the ID of the instruction as returned by the decoder.
Implements trap::InstructionBase.
Implemented in leon3_funcat_trap::IRQ_IRQ_Instruction, leon3_funcat_trap::ANDcc_imm, leon3_funcat_trap::WRITEpsr_reg, leon3_funcat_trap::CALL, leon3_funcat_trap::ORcc_imm, leon3_funcat_trap::OR_reg, leon3_funcat_trap::SAVE_reg, leon3_funcat_trap::SDIVcc_imm, leon3_funcat_trap::RETT_reg, leon3_funcat_trap::LDUB_imm, leon3_funcat_trap::TRAP_reg, leon3_funcat_trap::LD_imm, leon3_funcat_trap::RESTORE_imm, leon3_funcat_trap::SLL_reg, leon3_funcat_trap::LDDA_reg, leon3_funcat_trap::STHA_reg, leon3_funcat_trap::LDA_reg, leon3_funcat_trap::STBAR, leon3_funcat_trap::XNORcc_imm, leon3_funcat_trap::UDIV_reg, leon3_funcat_trap::ADDX_reg, leon3_funcat_trap::JUMP_reg, leon3_funcat_trap::LDUBA_reg, leon3_funcat_trap::ORNcc_imm, leon3_funcat_trap::XORcc_imm, leon3_funcat_trap::SMUL_reg, leon3_funcat_trap::JUMP_imm, leon3_funcat_trap::UMAC_reg, leon3_funcat_trap::STDA_reg, leon3_funcat_trap::SUBX_imm, leon3_funcat_trap::SWAP_reg, leon3_funcat_trap::SMULcc_imm, leon3_funcat_trap::SDIV_reg, leon3_funcat_trap::TADDccTV_reg, leon3_funcat_trap::SUBcc_imm, leon3_funcat_trap::XOR_reg, leon3_funcat_trap::ADDcc_reg, leon3_funcat_trap::SUB_imm, leon3_funcat_trap::SMULcc_reg, leon3_funcat_trap::BRANCH, leon3_funcat_trap::TSUBcc_reg, leon3_funcat_trap::UMAC_imm, leon3_funcat_trap::WRITEwim_reg, leon3_funcat_trap::SUB_reg, leon3_funcat_trap::XORcc_reg, leon3_funcat_trap::MULScc_imm, leon3_funcat_trap::ORcc_reg, leon3_funcat_trap::UMULcc_imm, leon3_funcat_trap::LDSTUBA_reg, leon3_funcat_trap::UNIMP, leon3_funcat_trap::LDSH_imm, leon3_funcat_trap::UDIV_imm, leon3_funcat_trap::XNOR_imm, leon3_funcat_trap::SUBX_reg, leon3_funcat_trap::WRITEtbr_reg, leon3_funcat_trap::TADDccTV_imm, leon3_funcat_trap::ANDNcc_imm, leon3_funcat_trap::STD_reg, leon3_funcat_trap::ORN_imm, leon3_funcat_trap::UDIVcc_reg, leon3_funcat_trap::LDSH_reg, leon3_funcat_trap::SRA_imm, leon3_funcat_trap::SETHI, leon3_funcat_trap::TSUBccTV_reg, leon3_funcat_trap::ANDN_reg, leon3_funcat_trap::LDSB_reg, leon3_funcat_trap::SMAC_imm, leon3_funcat_trap::LDSTUB_imm, leon3_funcat_trap::READwim, leon3_funcat_trap::UMUL_imm, leon3_funcat_trap::ADD_imm, leon3_funcat_trap::SMUL_imm, leon3_funcat_trap::AND_imm, leon3_funcat_trap::STB_reg, leon3_funcat_trap::ADDXcc_reg, leon3_funcat_trap::RESTORE_reg, leon3_funcat_trap::LDUB_reg, leon3_funcat_trap::WRITEtbr_imm, leon3_funcat_trap::TRAP_imm, leon3_funcat_trap::ADD_reg, leon3_funcat_trap::SDIVcc_reg, leon3_funcat_trap::RETT_imm, leon3_funcat_trap::ORNcc_reg, leon3_funcat_trap::FLUSH_reg, leon3_funcat_trap::TSUBccTV_imm, leon3_funcat_trap::SDIV_imm, leon3_funcat_trap::TADDcc_imm, leon3_funcat_trap::TADDcc_reg, leon3_funcat_trap::LDUHA_reg, leon3_funcat_trap::SLL_imm, leon3_funcat_trap::LDD_imm, leon3_funcat_trap::WRITEwim_imm, leon3_funcat_trap::STH_imm, leon3_funcat_trap::SRA_reg, leon3_funcat_trap::FLUSH_imm, leon3_funcat_trap::AND_reg, leon3_funcat_trap::WRITEY_imm, leon3_funcat_trap::UMUL_reg, leon3_funcat_trap::SWAP_imm, leon3_funcat_trap::ADDX_imm, leon3_funcat_trap::SUBXcc_reg, leon3_funcat_trap::STD_imm, leon3_funcat_trap::OR_imm, leon3_funcat_trap::MULScc_reg, leon3_funcat_trap::SAVE_imm, leon3_funcat_trap::SRL_reg, leon3_funcat_trap::LDUH_reg, leon3_funcat_trap::ADDcc_imm, leon3_funcat_trap::LDD_reg, leon3_funcat_trap::SUBcc_reg, leon3_funcat_trap::ST_reg, leon3_funcat_trap::LD_reg, leon3_funcat_trap::WRITEasr_reg, leon3_funcat_trap::SMAC_reg, leon3_funcat_trap::XOR_imm, leon3_funcat_trap::LDSTUB_reg, leon3_funcat_trap::UMULcc_reg, leon3_funcat_trap::WRITEasr_imm, leon3_funcat_trap::SRL_imm, leon3_funcat_trap::STH_reg, leon3_funcat_trap::SUBXcc_imm, leon3_funcat_trap::STB_imm, leon3_funcat_trap::ADDXcc_imm, leon3_funcat_trap::SWAPA_reg, leon3_funcat_trap::UDIVcc_imm, leon3_funcat_trap::READtbr, leon3_funcat_trap::ST_imm, leon3_funcat_trap::STBA_reg, leon3_funcat_trap::LDSHA_reg, leon3_funcat_trap::ORN_reg, leon3_funcat_trap::STA_reg, leon3_funcat_trap::LDUH_imm, leon3_funcat_trap::LDSBA_reg, leon3_funcat_trap::TSUBcc_imm, leon3_funcat_trap::ANDcc_reg, leon3_funcat_trap::ANDN_imm, leon3_funcat_trap::READpsr, leon3_funcat_trap::XNORcc_reg, leon3_funcat_trap::READy, leon3_funcat_trap::WRITEpsr_imm, leon3_funcat_trap::LDSB_imm, leon3_funcat_trap::ANDNcc_reg, leon3_funcat_trap::XNOR_reg, leon3_funcat_trap::WRITEY_reg, leon3_funcat_trap::READasr, and leon3_funcat_trap::InvalidInstr.
virtual std::string leon3_funcat_trap::Instruction::getInstructionName () const throw () pure virtual
Returns the instruction name.
Implements trap::InstructionBase.
Implemented in leon3_funcat_trap::IRQ_IRQ_Instruction, leon3_funcat_trap::ANDcc_imm, leon3_funcat_trap::WRITEpsr_reg, leon3_funcat_trap::CALL, leon3_funcat_trap::ORcc_imm, leon3_funcat_trap::OR_reg, leon3_funcat_trap::SAVE_reg, leon3_funcat_trap::SDIVcc_imm, leon3_funcat_trap::RETT_reg, leon3_funcat_trap::LDUB_imm, leon3_funcat_trap::TRAP_reg, leon3_funcat_trap::LD_imm, leon3_funcat_trap::RESTORE_imm, leon3_funcat_trap::SLL_reg, leon3_funcat_trap::LDDA_reg, leon3_funcat_trap::STHA_reg, leon3_funcat_trap::LDA_reg, leon3_funcat_trap::STBAR, leon3_funcat_trap::XNORcc_imm, leon3_funcat_trap::UDIV_reg, leon3_funcat_trap::ADDX_reg, leon3_funcat_trap::JUMP_reg, leon3_funcat_trap::LDUBA_reg, leon3_funcat_trap::ORNcc_imm, leon3_funcat_trap::XORcc_imm, leon3_funcat_trap::SMUL_reg, leon3_funcat_trap::JUMP_imm, leon3_funcat_trap::UMAC_reg, leon3_funcat_trap::STDA_reg, leon3_funcat_trap::SUBX_imm, leon3_funcat_trap::SWAP_reg, leon3_funcat_trap::SMULcc_imm, leon3_funcat_trap::SDIV_reg, leon3_funcat_trap::TADDccTV_reg, leon3_funcat_trap::SUBcc_imm, leon3_funcat_trap::XOR_reg, leon3_funcat_trap::ADDcc_reg, leon3_funcat_trap::SUB_imm, leon3_funcat_trap::SMULcc_reg, leon3_funcat_trap::BRANCH, leon3_funcat_trap::TSUBcc_reg, leon3_funcat_trap::UMAC_imm, leon3_funcat_trap::WRITEwim_reg, leon3_funcat_trap::SUB_reg, leon3_funcat_trap::XORcc_reg, leon3_funcat_trap::MULScc_imm, leon3_funcat_trap::ORcc_reg, leon3_funcat_trap::UMULcc_imm, leon3_funcat_trap::LDSTUBA_reg, leon3_funcat_trap::UNIMP, leon3_funcat_trap::LDSH_imm, leon3_funcat_trap::UDIV_imm, leon3_funcat_trap::XNOR_imm, leon3_funcat_trap::SUBX_reg, leon3_funcat_trap::WRITEtbr_reg, leon3_funcat_trap::TADDccTV_imm, leon3_funcat_trap::ANDNcc_imm, leon3_funcat_trap::STD_reg, leon3_funcat_trap::ORN_imm, leon3_funcat_trap::UDIVcc_reg, leon3_funcat_trap::LDSH_reg, leon3_funcat_trap::SRA_imm, leon3_funcat_trap::SETHI, leon3_funcat_trap::TSUBccTV_reg, leon3_funcat_trap::ANDN_reg, leon3_funcat_trap::LDSB_reg, leon3_funcat_trap::SMAC_imm, leon3_funcat_trap::LDSTUB_imm, leon3_funcat_trap::READwim, leon3_funcat_trap::UMUL_imm, leon3_funcat_trap::ADD_imm, leon3_funcat_trap::SMUL_imm, leon3_funcat_trap::AND_imm, leon3_funcat_trap::STB_reg, leon3_funcat_trap::ADDXcc_reg, leon3_funcat_trap::RESTORE_reg, leon3_funcat_trap::LDUB_reg, leon3_funcat_trap::WRITEtbr_imm, leon3_funcat_trap::TRAP_imm, leon3_funcat_trap::ADD_reg, leon3_funcat_trap::SDIVcc_reg, leon3_funcat_trap::RETT_imm, leon3_funcat_trap::ORNcc_reg, leon3_funcat_trap::FLUSH_reg, leon3_funcat_trap::TSUBccTV_imm, leon3_funcat_trap::SDIV_imm, leon3_funcat_trap::TADDcc_imm, leon3_funcat_trap::TADDcc_reg, leon3_funcat_trap::LDUHA_reg, leon3_funcat_trap::SLL_imm, leon3_funcat_trap::LDD_imm, leon3_funcat_trap::WRITEwim_imm, leon3_funcat_trap::STH_imm, leon3_funcat_trap::SRA_reg, leon3_funcat_trap::FLUSH_imm, leon3_funcat_trap::AND_reg, leon3_funcat_trap::WRITEY_imm, leon3_funcat_trap::UMUL_reg, leon3_funcat_trap::SWAP_imm, leon3_funcat_trap::ADDX_imm, leon3_funcat_trap::SUBXcc_reg, leon3_funcat_trap::STD_imm, leon3_funcat_trap::OR_imm, leon3_funcat_trap::MULScc_reg, leon3_funcat_trap::SAVE_imm, leon3_funcat_trap::SRL_reg, leon3_funcat_trap::LDUH_reg, leon3_funcat_trap::ADDcc_imm, leon3_funcat_trap::LDD_reg, leon3_funcat_trap::SUBcc_reg, leon3_funcat_trap::ST_reg, leon3_funcat_trap::LD_reg, leon3_funcat_trap::WRITEasr_reg, leon3_funcat_trap::SMAC_reg, leon3_funcat_trap::XOR_imm, leon3_funcat_trap::LDSTUB_reg, leon3_funcat_trap::UMULcc_reg, leon3_funcat_trap::WRITEasr_imm, leon3_funcat_trap::SRL_imm, leon3_funcat_trap::STH_reg, leon3_funcat_trap::SUBXcc_imm, leon3_funcat_trap::STB_imm, leon3_funcat_trap::ADDXcc_imm, leon3_funcat_trap::SWAPA_reg, leon3_funcat_trap::UDIVcc_imm, leon3_funcat_trap::READtbr, leon3_funcat_trap::ST_imm, leon3_funcat_trap::STBA_reg, leon3_funcat_trap::LDSHA_reg, leon3_funcat_trap::ORN_reg, leon3_funcat_trap::STA_reg, leon3_funcat_trap::LDUH_imm, leon3_funcat_trap::LDSBA_reg, leon3_funcat_trap::TSUBcc_imm, leon3_funcat_trap::ANDcc_reg, leon3_funcat_trap::ANDN_imm, leon3_funcat_trap::READpsr, leon3_funcat_trap::XNORcc_reg, leon3_funcat_trap::READy, leon3_funcat_trap::WRITEpsr_imm, leon3_funcat_trap::LDSB_imm, leon3_funcat_trap::ANDNcc_reg, leon3_funcat_trap::XNOR_reg, leon3_funcat_trap::WRITEY_reg, leon3_funcat_trap::READasr, and leon3_funcat_trap::InvalidInstr.
Referenced by leon3_funcat_trap::Processor_leon3_funcat::mainLoop().
virtual std::string leon3_funcat_trap::Instruction::getMnemonic () const throw () pure virtual
Returns the instruction mnemonic, so how the current instruction translated to assebmly code
Implements trap::InstructionBase.
Implemented in leon3_funcat_trap::IRQ_IRQ_Instruction, leon3_funcat_trap::ANDcc_imm, leon3_funcat_trap::WRITEpsr_reg, leon3_funcat_trap::CALL, leon3_funcat_trap::ORcc_imm, leon3_funcat_trap::OR_reg, leon3_funcat_trap::SAVE_reg, leon3_funcat_trap::SDIVcc_imm, leon3_funcat_trap::RETT_reg, leon3_funcat_trap::LDUB_imm, leon3_funcat_trap::TRAP_reg, leon3_funcat_trap::LD_imm, leon3_funcat_trap::RESTORE_imm, leon3_funcat_trap::SLL_reg, leon3_funcat_trap::LDDA_reg, leon3_funcat_trap::STHA_reg, leon3_funcat_trap::LDA_reg, leon3_funcat_trap::STBAR, leon3_funcat_trap::XNORcc_imm, leon3_funcat_trap::UDIV_reg, leon3_funcat_trap::ADDX_reg, leon3_funcat_trap::JUMP_reg, leon3_funcat_trap::LDUBA_reg, leon3_funcat_trap::ORNcc_imm, leon3_funcat_trap::XORcc_imm, leon3_funcat_trap::SMUL_reg, leon3_funcat_trap::JUMP_imm, leon3_funcat_trap::UMAC_reg, leon3_funcat_trap::STDA_reg, leon3_funcat_trap::SUBX_imm, leon3_funcat_trap::SWAP_reg, leon3_funcat_trap::SMULcc_imm, leon3_funcat_trap::SDIV_reg, leon3_funcat_trap::TADDccTV_reg, leon3_funcat_trap::SUBcc_imm, leon3_funcat_trap::XOR_reg, leon3_funcat_trap::ADDcc_reg, leon3_funcat_trap::SUB_imm, leon3_funcat_trap::SMULcc_reg, leon3_funcat_trap::BRANCH, leon3_funcat_trap::TSUBcc_reg, leon3_funcat_trap::UMAC_imm, leon3_funcat_trap::WRITEwim_reg, leon3_funcat_trap::SUB_reg, leon3_funcat_trap::XORcc_reg, leon3_funcat_trap::MULScc_imm, leon3_funcat_trap::ORcc_reg, leon3_funcat_trap::UMULcc_imm, leon3_funcat_trap::LDSTUBA_reg, leon3_funcat_trap::UNIMP, leon3_funcat_trap::LDSH_imm, leon3_funcat_trap::UDIV_imm, leon3_funcat_trap::XNOR_imm, leon3_funcat_trap::SUBX_reg, leon3_funcat_trap::WRITEtbr_reg, leon3_funcat_trap::TADDccTV_imm, leon3_funcat_trap::ANDNcc_imm, leon3_funcat_trap::STD_reg, leon3_funcat_trap::ORN_imm, leon3_funcat_trap::UDIVcc_reg, leon3_funcat_trap::LDSH_reg, leon3_funcat_trap::SRA_imm, leon3_funcat_trap::SETHI, leon3_funcat_trap::TSUBccTV_reg, leon3_funcat_trap::ANDN_reg, leon3_funcat_trap::LDSB_reg, leon3_funcat_trap::SMAC_imm, leon3_funcat_trap::LDSTUB_imm, leon3_funcat_trap::READwim, leon3_funcat_trap::UMUL_imm, leon3_funcat_trap::ADD_imm, leon3_funcat_trap::SMUL_imm, leon3_funcat_trap::AND_imm, leon3_funcat_trap::STB_reg, leon3_funcat_trap::ADDXcc_reg, leon3_funcat_trap::RESTORE_reg, leon3_funcat_trap::LDUB_reg, leon3_funcat_trap::WRITEtbr_imm, leon3_funcat_trap::TRAP_imm, leon3_funcat_trap::ADD_reg, leon3_funcat_trap::SDIVcc_reg, leon3_funcat_trap::RETT_imm, leon3_funcat_trap::ORNcc_reg, leon3_funcat_trap::FLUSH_reg, leon3_funcat_trap::TSUBccTV_imm, leon3_funcat_trap::SDIV_imm, leon3_funcat_trap::TADDcc_imm, leon3_funcat_trap::TADDcc_reg, leon3_funcat_trap::LDUHA_reg, leon3_funcat_trap::SLL_imm, leon3_funcat_trap::LDD_imm, leon3_funcat_trap::WRITEwim_imm, leon3_funcat_trap::STH_imm, leon3_funcat_trap::SRA_reg, leon3_funcat_trap::FLUSH_imm, leon3_funcat_trap::AND_reg, leon3_funcat_trap::WRITEY_imm, leon3_funcat_trap::UMUL_reg, leon3_funcat_trap::SWAP_imm, leon3_funcat_trap::ADDX_imm, leon3_funcat_trap::SUBXcc_reg, leon3_funcat_trap::STD_imm, leon3_funcat_trap::OR_imm, leon3_funcat_trap::MULScc_reg, leon3_funcat_trap::SAVE_imm, leon3_funcat_trap::SRL_reg, leon3_funcat_trap::LDUH_reg, leon3_funcat_trap::ADDcc_imm, leon3_funcat_trap::LDD_reg, leon3_funcat_trap::SUBcc_reg, leon3_funcat_trap::ST_reg, leon3_funcat_trap::LD_reg, leon3_funcat_trap::WRITEasr_reg, leon3_funcat_trap::SMAC_reg, leon3_funcat_trap::XOR_imm, leon3_funcat_trap::LDSTUB_reg, leon3_funcat_trap::UMULcc_reg, leon3_funcat_trap::WRITEasr_imm, leon3_funcat_trap::SRL_imm, leon3_funcat_trap::STH_reg, leon3_funcat_trap::SUBXcc_imm, leon3_funcat_trap::STB_imm, leon3_funcat_trap::ADDXcc_imm, leon3_funcat_trap::SWAPA_reg, leon3_funcat_trap::UDIVcc_imm, leon3_funcat_trap::READtbr, leon3_funcat_trap::ST_imm, leon3_funcat_trap::STBA_reg, leon3_funcat_trap::LDSHA_reg, leon3_funcat_trap::ORN_reg, leon3_funcat_trap::STA_reg, leon3_funcat_trap::LDUH_imm, leon3_funcat_trap::LDSBA_reg, leon3_funcat_trap::TSUBcc_imm, leon3_funcat_trap::ANDcc_reg, leon3_funcat_trap::ANDN_imm, leon3_funcat_trap::READpsr, leon3_funcat_trap::XNORcc_reg, leon3_funcat_trap::READy, leon3_funcat_trap::WRITEpsr_imm, leon3_funcat_trap::LDSB_imm, leon3_funcat_trap::ANDNcc_reg, leon3_funcat_trap::XNOR_reg, leon3_funcat_trap::WRITEY_reg, leon3_funcat_trap::READasr, and leon3_funcat_trap::InvalidInstr.
Referenced by leon3_funcat_trap::Processor_leon3_funcat::mainLoop(), and sc_main().
void leon3_funcat_trap::Instruction::IncrementPC () throw () inline protected
References NPC, and PC.
bool leon3_funcat_trap::Instruction::IncrementRegWindow () throw ()
References key_CWP.
void leon3_funcat_trap::Instruction::RaiseException (unsigned int pcounter, unsigned int npcounter, unsigned int exceptionId, unsigned int customTrapOffset = 0)
References CP_DISABLED, CP_EXCEPTION, DATA_ACCESS_ERROR, DATA_ACCESS_EXC, DATA_ACCESS_MMU_MISS, DATA_STORE_ERROR, DIV_ZERO, flush(), FP_DISABLED, FP_EXCEPTION, ILLEGAL_INSTR, IMPL_DEP_EXC, INSTR_ACCESS_ERROR, INSTR_ACCESS_EXC, INSTR_ACCESS_MMU_MISS, IRQ_LEV_1, IRQ_LEV_10, IRQ_LEV_11, IRQ_LEV_12, IRQ_LEV_13, IRQ_LEV_14, IRQ_LEV_15, IRQ_LEV_2, IRQ_LEV_3, IRQ_LEV_4, IRQ_LEV_5, IRQ_LEV_6, IRQ_LEV_7, IRQ_LEV_8, IRQ_LEV_9, key_CWP, key_ET, key_S, key_TT, MEM_ADDR_NOT_ALIGNED, PRIVILEDGE_INSTR, R_REGISTER_ACCESS_ERROR, RESET, TAG_OVERFLOW, THROW_EXCEPTION, TRAP_INSTRUCTION, UNIMPL_FLUSH, WATCHPOINT_DETECTED, WINDOW_OVERFLOW, and WINDOW_UNDERFLOW.
virtual Instruction* leon3_funcat_trap::Instruction::replicate () const throw () pure virtual
Implemented in leon3_funcat_trap::IRQ_IRQ_Instruction, leon3_funcat_trap::ANDcc_imm, leon3_funcat_trap::WRITEpsr_reg, leon3_funcat_trap::CALL, leon3_funcat_trap::ORcc_imm, leon3_funcat_trap::OR_reg, leon3_funcat_trap::SAVE_reg, leon3_funcat_trap::SDIVcc_imm, leon3_funcat_trap::RETT_reg, leon3_funcat_trap::LDUB_imm, leon3_funcat_trap::TRAP_reg, leon3_funcat_trap::LD_imm, leon3_funcat_trap::RESTORE_imm, leon3_funcat_trap::SLL_reg, leon3_funcat_trap::LDDA_reg, leon3_funcat_trap::STHA_reg, leon3_funcat_trap::LDA_reg, leon3_funcat_trap::STBAR, leon3_funcat_trap::XNORcc_imm, leon3_funcat_trap::UDIV_reg, leon3_funcat_trap::ADDX_reg, leon3_funcat_trap::JUMP_reg, leon3_funcat_trap::LDUBA_reg, leon3_funcat_trap::ORNcc_imm, leon3_funcat_trap::XORcc_imm, leon3_funcat_trap::SMUL_reg, leon3_funcat_trap::JUMP_imm, leon3_funcat_trap::UMAC_reg, leon3_funcat_trap::STDA_reg, leon3_funcat_trap::SUBX_imm, leon3_funcat_trap::SWAP_reg, leon3_funcat_trap::SMULcc_imm, leon3_funcat_trap::SDIV_reg, leon3_funcat_trap::TADDccTV_reg, leon3_funcat_trap::SUBcc_imm, leon3_funcat_trap::XOR_reg, leon3_funcat_trap::ADDcc_reg, leon3_funcat_trap::SUB_imm, leon3_funcat_trap::SMULcc_reg, leon3_funcat_trap::BRANCH, leon3_funcat_trap::TSUBcc_reg, leon3_funcat_trap::UMAC_imm, leon3_funcat_trap::WRITEwim_reg, leon3_funcat_trap::SUB_reg, leon3_funcat_trap::XORcc_reg, leon3_funcat_trap::MULScc_imm, leon3_funcat_trap::ORcc_reg, leon3_funcat_trap::UMULcc_imm, leon3_funcat_trap::LDSTUBA_reg, leon3_funcat_trap::UNIMP, leon3_funcat_trap::LDSH_imm, leon3_funcat_trap::UDIV_imm, leon3_funcat_trap::XNOR_imm, leon3_funcat_trap::SUBX_reg, leon3_funcat_trap::WRITEtbr_reg, leon3_funcat_trap::TADDccTV_imm, leon3_funcat_trap::ANDNcc_imm, leon3_funcat_trap::STD_reg, leon3_funcat_trap::ORN_imm, leon3_funcat_trap::UDIVcc_reg, leon3_funcat_trap::LDSH_reg, leon3_funcat_trap::SRA_imm, leon3_funcat_trap::SETHI, leon3_funcat_trap::TSUBccTV_reg, leon3_funcat_trap::ANDN_reg, leon3_funcat_trap::LDSB_reg, leon3_funcat_trap::SMAC_imm, leon3_funcat_trap::LDSTUB_imm, leon3_funcat_trap::READwim, leon3_funcat_trap::UMUL_imm, leon3_funcat_trap::ADD_imm, leon3_funcat_trap::SMUL_imm, leon3_funcat_trap::AND_imm, leon3_funcat_trap::STB_reg, leon3_funcat_trap::ADDXcc_reg, leon3_funcat_trap::RESTORE_reg, leon3_funcat_trap::LDUB_reg, leon3_funcat_trap::WRITEtbr_imm, leon3_funcat_trap::TRAP_imm, leon3_funcat_trap::ADD_reg, leon3_funcat_trap::SDIVcc_reg, leon3_funcat_trap::RETT_imm, leon3_funcat_trap::ORNcc_reg, leon3_funcat_trap::FLUSH_reg, leon3_funcat_trap::TSUBccTV_imm, leon3_funcat_trap::SDIV_imm, leon3_funcat_trap::TADDcc_imm, leon3_funcat_trap::TADDcc_reg, leon3_funcat_trap::LDUHA_reg, leon3_funcat_trap::SLL_imm, leon3_funcat_trap::LDD_imm, leon3_funcat_trap::WRITEwim_imm, leon3_funcat_trap::STH_imm, leon3_funcat_trap::SRA_reg, leon3_funcat_trap::FLUSH_imm, leon3_funcat_trap::AND_reg, leon3_funcat_trap::WRITEY_imm, leon3_funcat_trap::UMUL_reg, leon3_funcat_trap::SWAP_imm, leon3_funcat_trap::ADDX_imm, leon3_funcat_trap::SUBXcc_reg, leon3_funcat_trap::STD_imm, leon3_funcat_trap::OR_imm, leon3_funcat_trap::MULScc_reg, leon3_funcat_trap::SAVE_imm, leon3_funcat_trap::SRL_reg, leon3_funcat_trap::LDUH_reg, leon3_funcat_trap::ADDcc_imm, leon3_funcat_trap::LDD_reg, leon3_funcat_trap::SUBcc_reg, leon3_funcat_trap::ST_reg, leon3_funcat_trap::LD_reg, leon3_funcat_trap::WRITEasr_reg, leon3_funcat_trap::SMAC_reg, leon3_funcat_trap::XOR_imm, leon3_funcat_trap::LDSTUB_reg, leon3_funcat_trap::UMULcc_reg, leon3_funcat_trap::WRITEasr_imm, leon3_funcat_trap::SRL_imm, leon3_funcat_trap::STH_reg, leon3_funcat_trap::SUBXcc_imm, leon3_funcat_trap::STB_imm, leon3_funcat_trap::ADDXcc_imm, leon3_funcat_trap::SWAPA_reg, leon3_funcat_trap::UDIVcc_imm, leon3_funcat_trap::READtbr, leon3_funcat_trap::ST_imm, leon3_funcat_trap::STBA_reg, leon3_funcat_trap::LDSHA_reg, leon3_funcat_trap::ORN_reg, leon3_funcat_trap::STA_reg, leon3_funcat_trap::LDUH_imm, leon3_funcat_trap::LDSBA_reg, leon3_funcat_trap::TSUBcc_imm, leon3_funcat_trap::ANDcc_reg, leon3_funcat_trap::ANDN_imm, leon3_funcat_trap::READpsr, leon3_funcat_trap::XNORcc_reg, leon3_funcat_trap::READy, leon3_funcat_trap::WRITEpsr_imm, leon3_funcat_trap::LDSB_imm, leon3_funcat_trap::ANDNcc_reg, leon3_funcat_trap::XNOR_reg, leon3_funcat_trap::WRITEY_reg, leon3_funcat_trap::READasr, and leon3_funcat_trap::InvalidInstr.
Referenced by leon3_funcat_trap::Processor_leon3_funcat::mainLoop().
virtual void leon3_funcat_trap::Instruction::setParams (const unsigned int & bitString) throw () pure virtual
Implemented in leon3_funcat_trap::IRQ_IRQ_Instruction, leon3_funcat_trap::ANDcc_imm, leon3_funcat_trap::WRITEpsr_reg, leon3_funcat_trap::CALL, leon3_funcat_trap::ORcc_imm, leon3_funcat_trap::OR_reg, leon3_funcat_trap::SAVE_reg, leon3_funcat_trap::SDIVcc_imm, leon3_funcat_trap::RETT_reg, leon3_funcat_trap::LDUB_imm, leon3_funcat_trap::TRAP_reg, leon3_funcat_trap::LD_imm, leon3_funcat_trap::RESTORE_imm, leon3_funcat_trap::SLL_reg, leon3_funcat_trap::LDDA_reg, leon3_funcat_trap::STHA_reg, leon3_funcat_trap::LDA_reg, leon3_funcat_trap::STBAR, leon3_funcat_trap::XNORcc_imm, leon3_funcat_trap::UDIV_reg, leon3_funcat_trap::ADDX_reg, leon3_funcat_trap::JUMP_reg, leon3_funcat_trap::LDUBA_reg, leon3_funcat_trap::ORNcc_imm, leon3_funcat_trap::XORcc_imm, leon3_funcat_trap::SMUL_reg, leon3_funcat_trap::JUMP_imm, leon3_funcat_trap::UMAC_reg, leon3_funcat_trap::STDA_reg, leon3_funcat_trap::SUBX_imm, leon3_funcat_trap::SWAP_reg, leon3_funcat_trap::SMULcc_imm, leon3_funcat_trap::SDIV_reg, leon3_funcat_trap::TADDccTV_reg, leon3_funcat_trap::SUBcc_imm, leon3_funcat_trap::XOR_reg, leon3_funcat_trap::ADDcc_reg, leon3_funcat_trap::SUB_imm, leon3_funcat_trap::SMULcc_reg, leon3_funcat_trap::BRANCH, leon3_funcat_trap::TSUBcc_reg, leon3_funcat_trap::UMAC_imm, leon3_funcat_trap::WRITEwim_reg, leon3_funcat_trap::SUB_reg, leon3_funcat_trap::XORcc_reg, leon3_funcat_trap::MULScc_imm, leon3_funcat_trap::ORcc_reg, leon3_funcat_trap::UMULcc_imm, leon3_funcat_trap::LDSTUBA_reg, leon3_funcat_trap::UNIMP, leon3_funcat_trap::LDSH_imm, leon3_funcat_trap::UDIV_imm, leon3_funcat_trap::XNOR_imm, leon3_funcat_trap::SUBX_reg, leon3_funcat_trap::WRITEtbr_reg, leon3_funcat_trap::TADDccTV_imm, leon3_funcat_trap::ANDNcc_imm, leon3_funcat_trap::STD_reg, leon3_funcat_trap::ORN_imm, leon3_funcat_trap::UDIVcc_reg, leon3_funcat_trap::LDSH_reg, leon3_funcat_trap::SRA_imm, leon3_funcat_trap::SETHI, leon3_funcat_trap::TSUBccTV_reg, leon3_funcat_trap::ANDN_reg, leon3_funcat_trap::LDSB_reg, leon3_funcat_trap::SMAC_imm, leon3_funcat_trap::LDSTUB_imm, leon3_funcat_trap::READwim, leon3_funcat_trap::UMUL_imm, leon3_funcat_trap::ADD_imm, leon3_funcat_trap::SMUL_imm, leon3_funcat_trap::AND_imm, leon3_funcat_trap::STB_reg, leon3_funcat_trap::ADDXcc_reg, leon3_funcat_trap::RESTORE_reg, leon3_funcat_trap::LDUB_reg, leon3_funcat_trap::WRITEtbr_imm, leon3_funcat_trap::TRAP_imm, leon3_funcat_trap::ADD_reg, leon3_funcat_trap::SDIVcc_reg, leon3_funcat_trap::RETT_imm, leon3_funcat_trap::ORNcc_reg, leon3_funcat_trap::FLUSH_reg, leon3_funcat_trap::TSUBccTV_imm, leon3_funcat_trap::SDIV_imm, leon3_funcat_trap::TADDcc_imm, leon3_funcat_trap::TADDcc_reg, leon3_funcat_trap::LDUHA_reg, leon3_funcat_trap::SLL_imm, leon3_funcat_trap::LDD_imm, leon3_funcat_trap::WRITEwim_imm, leon3_funcat_trap::STH_imm, leon3_funcat_trap::SRA_reg, leon3_funcat_trap::FLUSH_imm, leon3_funcat_trap::AND_reg, leon3_funcat_trap::WRITEY_imm, leon3_funcat_trap::UMUL_reg, leon3_funcat_trap::SWAP_imm, leon3_funcat_trap::ADDX_imm, leon3_funcat_trap::SUBXcc_reg, leon3_funcat_trap::STD_imm, leon3_funcat_trap::OR_imm, leon3_funcat_trap::MULScc_reg, leon3_funcat_trap::SAVE_imm, leon3_funcat_trap::SRL_reg, leon3_funcat_trap::LDUH_reg, leon3_funcat_trap::ADDcc_imm, leon3_funcat_trap::LDD_reg, leon3_funcat_trap::SUBcc_reg, leon3_funcat_trap::ST_reg, leon3_funcat_trap::LD_reg, leon3_funcat_trap::WRITEasr_reg, leon3_funcat_trap::SMAC_reg, leon3_funcat_trap::XOR_imm, leon3_funcat_trap::LDSTUB_reg, leon3_funcat_trap::UMULcc_reg, leon3_funcat_trap::WRITEasr_imm, leon3_funcat_trap::SRL_imm, leon3_funcat_trap::STH_reg, leon3_funcat_trap::SUBXcc_imm, leon3_funcat_trap::STB_imm, leon3_funcat_trap::ADDXcc_imm, leon3_funcat_trap::SWAPA_reg, leon3_funcat_trap::UDIVcc_imm, leon3_funcat_trap::READtbr, leon3_funcat_trap::ST_imm, leon3_funcat_trap::STBA_reg, leon3_funcat_trap::LDSHA_reg, leon3_funcat_trap::ORN_reg, leon3_funcat_trap::STA_reg, leon3_funcat_trap::LDUH_imm, leon3_funcat_trap::LDSBA_reg, leon3_funcat_trap::TSUBcc_imm, leon3_funcat_trap::ANDcc_reg, leon3_funcat_trap::ANDN_imm, leon3_funcat_trap::READpsr, leon3_funcat_trap::XNORcc_reg, leon3_funcat_trap::READy, leon3_funcat_trap::WRITEpsr_imm, leon3_funcat_trap::LDSB_imm, leon3_funcat_trap::ANDNcc_reg, leon3_funcat_trap::XNOR_reg, leon3_funcat_trap::WRITEY_reg, leon3_funcat_trap::READasr, and leon3_funcat_trap::InvalidInstr.
Referenced by leon3_funcat_trap::Processor_leon3_funcat::decode(), and leon3_funcat_trap::Processor_leon3_funcat::mainLoop().
int leon3_funcat_trap::Instruction::SignExtend (unsigned int bitSeq, unsigned int bitSeq_length) const throw ()
void leon3_funcat_trap::Instruction::stall (const unsigned int & numCycles) inline
References totalInstrCycles.
Member Data Documentation
Reg32_3* leon3_funcat_trap::Instruction::ASR protected
TLMMemory& leon3_funcat_trap::Instruction::dataMem protected
Alias& leon3_funcat_trap::Instruction::FP protected
RegisterBankClass& leon3_funcat_trap::Instruction::GLOBAL protected
TLMMemory& leon3_funcat_trap::Instruction::instrMem protected
PinTLM_out_32& leon3_funcat_trap::Instruction::irqAck protected
Alias& leon3_funcat_trap::Instruction::LR protected
Reg32_3& leon3_funcat_trap::Instruction::NPC protected
Referenced by IncrementPC().
const unsigned int leon3_funcat_trap::Instruction::NUM_REG_WIN protected
Reg32_3& leon3_funcat_trap::Instruction::PC protected
Referenced by IncrementPC().
Alias& leon3_funcat_trap::Instruction::PCR protected
const bool leon3_funcat_trap::Instruction::PIPELINED_MULT protected
Reg32_0& leon3_funcat_trap::Instruction::PSR protected
Alias* leon3_funcat_trap::Instruction::REGS protected
Alias& leon3_funcat_trap::Instruction::SP protected
Reg32_2& leon3_funcat_trap::Instruction::TBR protected
unsigned int leon3_funcat_trap::Instruction::totalInstrCycles
Referenced by Instruction(), and stall().
Reg32_1& leon3_funcat_trap::Instruction::WIM protected
Reg32_3* leon3_funcat_trap::Instruction::WINREGS protected
Reg32_3& leon3_funcat_trap::Instruction::Y protected
The documentation for this class was generated from the following files:
core/models/extern/LEON3/simulatorSources/leon3.funcat/instructions.hpp
core/models/extern/LEON3/simulatorSources/leon3.funcat/instructions.cpp