SoCRocket: sr_param< std::string > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
sr_param< std::string > Class Template Reference
Template specialization for sr_param<std::string>.
#include <sr_param_native.h>
Public Member Functions
sr_param ()
Empty constructor. Name will be set in base.
sr_param (const std::string &nam)
Constructor with (local/hierarchical) name.
sr_param (const char *nam)
sr_param (const std::string &nam, const std::string &val, const bool force_top_level_name=false)
Constructor with (local/hierarchical) name and string representation of initial value.
sr_param (const char *nam, const char *val, const bool force_top_level_name=false)
sr_param (const std::string &nam, const char *val, const bool force_top_level_name=false)
sr_param (const char *nam, const std::string &val, const bool force_top_level_name=false)
sr_param (gs_param_array *parent_array)
sr_param (const std::string &nam, gs_param_array *parent_array)
sr_param (const char *nam, gs_param_array *parent_array)
sr_param (const std::string &nam, const std::string &val, gs_param_array *parent_array)
sr_param (const char *nam, const char *val, gs_param_array *parent_array)
sr_param (const std::string &nam, const char *val, gs_param_array *parent_array)
sr_param (const char *nam, const std::string &val, gs_param_array *parent_array)
sr_param (gs_param_array &parent_array)
sr_param (const std::string &nam, gs_param_array &parent_array)
sr_param (const char *nam, gs_param_array &parent_array)
sr_param (const std::string &nam, const std::string &val, gs_param_array &parent_array)
sr_param (const char *nam, const char *val, gs_param_array &parent_array)
sr_param (const std::string &nam, const char *val, gs_param_array &parent_array)
sr_param (const char *nam, const std::string &val, gs_param_array &parent_array)
sr_param (const std::string &nam, const std::string &val, gs_param_array *parent_array, const bool force_top_level_name, const bool register_at_db)
sr_param (const std::string &nam, const std::string &val, gs_param_array &parent_array, const bool force_top_level_name, const bool register_at_db)
const val_type convertStringToValue (const std::string &str)
void serialize (const val_type &val)
const bool deserialize (val_type &target_val, const std::string &str)
Overloads sr_param_t<T>::deserialize in sr_param_t<T>
my_type & operator= (const char *v)
Set the value of this parameter with char.
~sr_param ()
Desctructor.
const std::string getTypeString () const
Overloads sr_param::getTypeString.
gs::cnf::Param_type getType () const
Overloads sr_param::getType.
std::string convertValueToString (const val_type &val) const
Overloads sr_param_t<T>::convertValueToString.
Public Member Functions inherited from sr_param_t< std::string >
my_type & operator+= (val_type)
my_type & operator-= (val_type)
my_type & operator/= (val_type)
my_type & operator*= (val_type)
val_type operator+ (val_type)
val_type operator- (val_type)
val_type operator/ (val_type)
val_type operator* (val_type)
my_type & operator%= (val_type)
my_type & operator^= (val_type)
my_type & operator&= (val_type)
my_type & operator|= (val_type)
my_type & operator<<= (val_type)
my_type & operator>>= (val_type)
my_type & operator-- ()
val_type operator-- (int)
my_type & operator++ ()
val_type operator++ (int)
sr_param_t ()
Empty constructor. Name will be set in base. Avoid using it! You MUST call init() after instantiation!
sr_param_t (const bool force_top_level_name, gs_param_array *parent_array, const bool register_at_db)
Constructor with the special parameters. Name will be set in base. Avoid using it! You MUST call init() after instantiation!
sr_param_t (const std::string &nam)
Constructor with (local or hierarchical) name. You MUST call init() after instantiation!
sr_param_t (const std::string &nam, const bool force_top_level_name, gs_param_array *parent_array, const bool register_at_db)
Constructor with (local or hierarchical) name and special parameters. You MUST call init() after instantiation!
void init (const val_type &default_val)
Init method to set the value and add the parameter to the plugin db.
void init ()
Init method without value.
virtual ~sr_param_t ()
Destructor.
my_type & operator= (const my_type &v)
Set the value of this parameter to the value of another gs_param.
my_type & operator= (const val_type &v)
Set the value of this parameter.
operator const val_type & () const
Get the value of this parameter.
void setValue (const val_type &val)
Set the value of this parameter.
const val_type & getValue () const
Returns the value of this parameter.
const void * get_value_pointer () const
bool setString (const std::string &str)
Set the value of this parameter with a string.
const std::string & getString () const
Get the value of this parameter as a string.
void mirror (std::string &original)
Serialize this parameter.
void mirror (sr_param_t< std::string > &original)
Public Member Functions inherited from sr_param_base
sr_param_base (const std::string &n, const bool register_at_db=true, gs::cnf::gs_param_array *parent_array=NULL, const bool force_top_level_name=false)
void setProperty (std::string key, std::string value)
std::string getProperty (std::string key)
std::map< std::string,
std::string > getProperties ()
void deleteProperty (std::string key)
bool exists (std::string key)
easy_init add_properties ()
Static Public Member Functions
static std::string static_convertValueToString (const val_type &val)
static bool static_deserialize (val_type &target_val, const std::string &str)
Static convertion function called by virtual deserialize and others (e.g. GCnf_API)
Public Attributes
SR_PARAM_DELEGATE
Protected Types
typedef sr_param< std::string > my_type
Typedef for this specialized class.
typedef std::string val_type
Typedef for the value.
Additional Inherited Members
Protected Member Functions inherited from sr_param_t< std::string >
gs::cnf::callback_return_type mirror_callback (gs::gs_param_base &changed_param, gs::cnf::callback_type reason)
const val_type & convertStringToValue (const std::string &str)
Get the value the string. Needed for construction of gs_param.
Protected Attributes inherited from sr_param_t< std::string >
val_type my_value
Value of this parameter.
std::string return_string
String whose reference can be returned as string value.
sr_param_t< std::string > * m_mirror_param
std::string * m_mirror_val
Detailed Description
template<>
class sr_param< std::string >
Template specialization for sr_param<std::string>.
Member Typedef Documentation
typedef sr_param<std::string> sr_param< std::string >::my_type protected
Typedef for this specialized class.
typedef std::string sr_param< std::string >::val_type protected
Typedef for the value.
Constructor & Destructor Documentation
sr_param< std::string >::sr_param () inline explicit
Empty constructor. Name will be set in base.
References sr_param_t< T >::init().
sr_param< std::string >::sr_param (const std::string & nam) inline explicit
Constructor with (local/hierarchical) name.
References sr_param_t< T >::init().
sr_param< std::string >::sr_param (const char * nam) inline explicit
References sr_param_t< T >::init().
sr_param< std::string >::sr_param (const std::string & nam, const std::string & val, const bool force_top_level_name = false) inline explicit
Constructor with (local/hierarchical) name and string representation of initial value.
References sr_param_t< T >::convertStringToValue(), and sr_param_t< T >::init().
sr_param< std::string >::sr_param (const char * nam, const char * val, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::convertStringToValue(), and sr_param_t< T >::init().
sr_param< std::string >::sr_param (const std::string & nam, const char * val, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::convertStringToValue(), and sr_param_t< T >::init().
sr_param< std::string >::sr_param (const char * nam, const std::string & val, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::convertStringToValue(), and sr_param_t< T >::init().
sr_param< std::string >::sr_param (gs_param_array * parent_array) inline explicit
References sr_param_t< T >::init().
sr_param< std::string >::sr_param (const std::string & nam, gs_param_array * parent_array) inline explicit
References sr_param_t< T >::init().
sr_param< std::string >::sr_param (const char * nam, gs_param_array * parent_array) inline explicit
References sr_param_t< T >::init().
sr_param< std::string >::sr_param (const std::string & nam, const std::string & val, gs_param_array * parent_array) inline explicit
References sr_param_t< T >::convertStringToValue(), and sr_param_t< T >::init().
sr_param< std::string >::sr_param (const char * nam, const char * val, gs_param_array * parent_array) inline explicit
References sr_param_t< T >::convertStringToValue(), and sr_param_t< T >::init().
sr_param< std::string >::sr_param (const std::string & nam, const char * val, gs_param_array * parent_array) inline explicit
References sr_param_t< T >::convertStringToValue(), and sr_param_t< T >::init().
sr_param< std::string >::sr_param (const char * nam, const std::string & val, gs_param_array * parent_array) inline explicit
References sr_param_t< T >::convertStringToValue(), and sr_param_t< T >::init().
sr_param< std::string >::sr_param (gs_param_array & parent_array) inline explicit
References sr_param_t< T >::init().
sr_param< std::string >::sr_param (const std::string & nam, gs_param_array & parent_array) inline explicit
References sr_param_t< T >::init().
sr_param< std::string >::sr_param (const char * nam, gs_param_array & parent_array) inline explicit
References sr_param_t< T >::init().
sr_param< std::string >::sr_param (const std::string & nam, const std::string & val, gs_param_array & parent_array) inline explicit
References sr_param_t< T >::convertStringToValue(), and sr_param_t< T >::init().
sr_param< std::string >::sr_param (const char * nam, const char * val, gs_param_array & parent_array) inline explicit
References sr_param_t< T >::convertStringToValue(), and sr_param_t< T >::init().
sr_param< std::string >::sr_param (const std::string & nam, const char * val, gs_param_array & parent_array) inline explicit
References sr_param_t< T >::convertStringToValue(), and sr_param_t< T >::init().
sr_param< std::string >::sr_param (const char * nam, const std::string & val, gs_param_array & parent_array) inline explicit
References sr_param_t< T >::convertStringToValue(), and sr_param_t< T >::init().
sr_param< std::string >::sr_param (const std::string & nam, const std::string & val, gs_param_array * parent_array, const bool force_top_level_name, const bool register_at_db) inline explicit
References sr_param_t< T >::convertStringToValue(), and sr_param_t< T >::init().
sr_param< std::string >::sr_param (const std::string & nam, const std::string & val, gs_param_array & parent_array, const bool force_top_level_name, const bool register_at_db) inline explicit
References sr_param_t< T >::convertStringToValue(), and sr_param_t< T >::init().
sr_param< std::string >::~sr_param () inline
Desctructor.
Member Function Documentation
const val_type sr_param< std::string >::convertStringToValue (const std::string & str) inline
std::string sr_param< std::string >::convertValueToString (const val_type & val) const inline virtual
Overloads sr_param_t<T>::convertValueToString.
Implements sr_param_t< std::string >.
const bool sr_param< std::string >::deserialize (val_type & target_val, const std::string & str) inline virtual
Overloads sr_param_t<T>::deserialize in sr_param_t<T>
Implements sr_param_t< std::string >.
References sr_param< T >::static_deserialize().
gs::cnf::Param_type sr_param< std::string >::getType () const inline
Overloads sr_param::getType.
const std::string sr_param< std::string >::getTypeString () const inline
Overloads sr_param::getTypeString.
my_type& sr_param< std::string >::operator= (const char * v) inline
Set the value of this parameter with char.
Parameters
v Char value which has to be set.
Returns
Pointer to this.
References sr_param_t< T >::setValue().
void sr_param< std::string >::serialize (const val_type & val) inline
References sr_param_t< T >::my_value.
static std::string sr_param< std::string >::static_convertValueToString (const val_type & val) inline static
static bool sr_param< std::string >::static_deserialize (val_type & target_val, const std::string & str) inline static
Static convertion function called by virtual deserialize and others (e.g. GCnf_API)
Member Data Documentation
sr_param< std::string >::SR_PARAM_DELEGATE
The documentation for this class was generated from the following file:
core/common/sr_param/sr_param_native.h