SoCRocket: leon3_funclt_trap::MemoryInterface Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
leon3_funclt_trap::MemoryInterface Class Reference abstract
#include <memory.hpp>
Public Member Functions
virtual sc_dt::uint64 read_dword (const unsigned int &address, const unsigned int asi, const unsigned int flush, const unsigned int lock)=0 throw ()
virtual unsigned int read_word (const unsigned int &address, const unsigned int asi, const unsigned int flush, const unsigned int lock)=0 throw ()
virtual unsigned short int read_half (const unsigned int &address, const unsigned int asi, const unsigned int flush, const unsigned int lock)=0 throw ()
virtual unsigned char read_byte (const unsigned int &address, const unsigned int asi, const unsigned int flush, const unsigned int lock)=0 throw ()
virtual unsigned int read_instr (const unsigned int &address, const unsigned int flush)=0 throw ()
virtual sc_dt::uint64 read_dword_dbg (const unsigned int &address)
virtual unsigned int read_word_dbg (const unsigned int &address)
virtual unsigned short int read_half_dbg (const unsigned int &address)
virtual unsigned char read_byte_dbg (const unsigned int &address)
virtual void write_dword (const unsigned int &address, sc_dt::uint64 datum, const unsigned int asi, const unsigned int flush, const unsigned int lock)=0 throw ()
virtual void write_word (const unsigned int &address, unsigned int datum, const unsigned int asi, const unsigned int flush, const unsigned int lock)=0 throw ()
virtual void write_half (const unsigned int &address, unsigned short int datum, const unsigned int asi, const unsigned int flush, const unsigned int lock)=0 throw ()
virtual void write_byte (const unsigned int &address, unsigned char datum, const unsigned int asi, const unsigned int flush, const unsigned int lock)=0 throw ()
virtual void write_dword_dbg (const unsigned int &address, sc_dt::uint64 datum)
virtual void write_word_dbg (const unsigned int &address, unsigned int datum)
virtual void write_half_dbg (const unsigned int &address, unsigned short int datum)
virtual void write_byte_dbg (const unsigned int &address, unsigned char datum)
virtual void lock ()=0
virtual void unlock ()=0
void swapEndianess (unsigned int &datum) const throw ()
void swapEndianess (unsigned short int &datum) const throw ()
virtual ~MemoryInterface ()
Constructor & Destructor Documentation
leon3_funclt_trap::MemoryInterface::~MemoryInterface () virtual
Member Function Documentation
virtual void leon3_funclt_trap::MemoryInterface::lock () pure virtual
Implemented in leon3_funclt_trap::TLMMemory, leon3_funclt_trap::LocalMemory, and leon3_mmu_cache.
virtual unsigned char leon3_funclt_trap::MemoryInterface::read_byte (const unsigned int & address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () pure virtual
Implemented in leon3_funclt_trap::TLMMemory, leon3_funclt_trap::LocalMemory, and leon3_mmu_cache.
unsigned char leon3_funclt_trap::MemoryInterface::read_byte_dbg (const unsigned int & address) virtual
Reimplemented in leon3_funclt_trap::TLMMemory, leon3_funclt_trap::LocalMemory, and leon3_mmu_cache.
virtual sc_dt::uint64 leon3_funclt_trap::MemoryInterface::read_dword (const unsigned int & address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () pure virtual
Implemented in leon3_funclt_trap::LocalMemory, leon3_mmu_cache, and leon3_funclt_trap::TLMMemory.
sc_dt::uint64 leon3_funclt_trap::MemoryInterface::read_dword_dbg (const unsigned int & address) virtual
Reimplemented in leon3_funclt_trap::TLMMemory, leon3_funclt_trap::LocalMemory, and leon3_mmu_cache.
virtual unsigned short int leon3_funclt_trap::MemoryInterface::read_half (const unsigned int & address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () pure virtual
Implemented in leon3_funclt_trap::TLMMemory, leon3_funclt_trap::LocalMemory, and leon3_mmu_cache.
unsigned short int leon3_funclt_trap::MemoryInterface::read_half_dbg (const unsigned int & address) virtual
Reimplemented in leon3_funclt_trap::TLMMemory, leon3_funclt_trap::LocalMemory, and leon3_mmu_cache.
virtual unsigned int leon3_funclt_trap::MemoryInterface::read_instr (const unsigned int & address, const unsigned int flush) throw () pure virtual
Implemented in leon3_funclt_trap::TLMMemory, and leon3_mmu_cache.
virtual unsigned int leon3_funclt_trap::MemoryInterface::read_word (const unsigned int & address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () pure virtual
Implemented in leon3_funclt_trap::LocalMemory, leon3_mmu_cache, and leon3_funclt_trap::TLMMemory.
unsigned int leon3_funclt_trap::MemoryInterface::read_word_dbg (const unsigned int & address) virtual
Reimplemented in leon3_funclt_trap::TLMMemory, leon3_funclt_trap::LocalMemory, and leon3_mmu_cache.
Referenced by sc_main().
void leon3_funclt_trap::MemoryInterface::swapEndianess (unsigned int & datum) const throw () inline
Referenced by leon3_funclt_trap::TLMMemory::read_instr(), leon3_funclt_trap::TLMMemory::read_word(), and leon3_funclt_trap::TLMMemory::write_word().
void leon3_funclt_trap::MemoryInterface::swapEndianess (unsigned short int & datum) const throw () inline
virtual void leon3_funclt_trap::MemoryInterface::unlock () pure virtual
Implemented in leon3_funclt_trap::TLMMemory, leon3_funclt_trap::LocalMemory, and leon3_mmu_cache.
virtual void leon3_funclt_trap::MemoryInterface::write_byte (const unsigned int & address, unsigned char datum, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () pure virtual
Implemented in leon3_funclt_trap::TLMMemory, leon3_funclt_trap::LocalMemory, and leon3_mmu_cache.
void leon3_funclt_trap::MemoryInterface::write_byte_dbg (const unsigned int & address, unsigned char datum) virtual
Reimplemented in leon3_funclt_trap::TLMMemory, leon3_funclt_trap::LocalMemory, and leon3_mmu_cache.
virtual void leon3_funclt_trap::MemoryInterface::write_dword (const unsigned int & address, sc_dt::uint64 datum, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () pure virtual
Implemented in leon3_funclt_trap::TLMMemory, leon3_funclt_trap::LocalMemory, and leon3_mmu_cache.
void leon3_funclt_trap::MemoryInterface::write_dword_dbg (const unsigned int & address, sc_dt::uint64 datum) virtual
Reimplemented in leon3_funclt_trap::TLMMemory, leon3_funclt_trap::LocalMemory, and leon3_mmu_cache.
virtual void leon3_funclt_trap::MemoryInterface::write_half (const unsigned int & address, unsigned short int datum, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () pure virtual
Implemented in leon3_funclt_trap::TLMMemory, leon3_funclt_trap::LocalMemory, and leon3_mmu_cache.
void leon3_funclt_trap::MemoryInterface::write_half_dbg (const unsigned int & address, unsigned short int datum) virtual
Reimplemented in leon3_funclt_trap::TLMMemory, leon3_funclt_trap::LocalMemory, and leon3_mmu_cache.
virtual void leon3_funclt_trap::MemoryInterface::write_word (const unsigned int & address, unsigned int datum, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () pure virtual
Implemented in leon3_funclt_trap::TLMMemory, leon3_funclt_trap::LocalMemory, and leon3_mmu_cache.
void leon3_funclt_trap::MemoryInterface::write_word_dbg (const unsigned int & address, unsigned int datum) virtual
Reimplemented in leon3_funclt_trap::TLMMemory, leon3_funclt_trap::LocalMemory, and leon3_mmu_cache.
The documentation for this class was generated from the following files:
core/models/extern/LEON3/simulatorSources/leon3.funclt/memory.hpp
core/models/extern/LEON3/simulatorSources/leon3.funclt/memory.cpp