SoCRocket: sr_signal::signal_out_bind_if< TYPE > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
sr_signal::signal_out_bind_if< TYPE > Class Template Reference abstract
#include <sr_signal_ifs.h>
Public Member Functions
virtual ~signal_out_bind_if ()
Virtual destructor.
virtual signal_out_bind_if
< TYPE > * bind (signal_in_if< TYPE > &t, const unsigned int &channel=0)=0
Detailed Description
template<class TYPE>
class sr_signal::signal_out_bind_if< TYPE >
Signal output bind interface. This interface implements the bind functionality of an output signal. It's seperated from the signal output interface due to a second need in the selector signal. The selector has to implement the same bind interface but only a subclass implements the output interface for each channel.
See Also
selector
Constructor & Destructor Documentation
template<class TYPE> virtual sr_signal::signal_out_bind_if< TYPE >::~signal_out_bind_if () inline virtual
Virtual destructor.
Member Function Documentation
template<class TYPE> virtual signal_out_bind_if<TYPE>* sr_signal::signal_out_bind_if< TYPE >::bind (signal_in_if< TYPE > & t, const unsigned int & channel = 0) pure virtual
Abstract bind method interface. This method has to be implemented by each output signal to make it bind with an input.
Parameters
t Input interface to bind with.
channel The channel which has to be bind.
Implemented in sr_signal::signal_selector< TYPE, MODULE >, sr_signal::signal_out< TYPE, MODULE >, and sr_signal::signal_out< bool, Irqmp >.
Referenced by sr_signal::connect(), sr_signal::signal_in< TYPE, MODULE >::operator()(), and sr_signal::signal_infield< TYPE, MODULE >::operator()().
The documentation for this class was generated from the following file:
core/common/sr_signal/sr_signal_ifs.h