SoCRocket: Storage Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
Storage Class Reference abstract
Memory
#include <storage.h>
Public Member Functions
virtual void write (const uint32_t &addr, const uint8_t &byte)=0
virtual uint8_t read (const uint32_t &addr) const =0
virtual void write_block (const uint32_t &addr, const uint8_t *data, const uint32_t &len)=0
virtual void read_block (const uint32_t &addr, uint8_t *data, const uint32_t &len) const =0
virtual void erase (const uint32_t &start, const uint32_t &end)=0
Member Function Documentation
virtual void Storage::erase (const uint32_t & start, const uint32_t & end) pure virtual
Implemented in MapStorage, and ArrayStorage.
Referenced by BaseMemory::erase_dbg().
virtual uint8_t Storage::read (const uint32_t & addr) const pure virtual
Implemented in MapStorage, and ArrayStorage.
Referenced by BaseMemory::read_dbg().
virtual void Storage::read_block (const uint32_t & addr, uint8_t * data, const uint32_t & len) const pure virtual
Implemented in MapStorage, and ArrayStorage.
Referenced by BaseMemory::read_block_dbg().
virtual void Storage::write (const uint32_t & addr, const uint8_t & byte) pure virtual
Implemented in MapStorage, and ArrayStorage.
Referenced by BaseMemory::write_dbg().
virtual void Storage::write_block (const uint32_t & addr, const uint8_t * data, const uint32_t & len) pure virtual
Implemented in MapStorage, and ArrayStorage.
Referenced by BaseMemory::write_block_dbg().
The documentation for this class was generated from the following file:
core/models/memory/storage.h