SoCRocket: mmu_if Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
mmu_if Class Reference abstract
MMU_Cache
#include <mmu_if.h>
Public Member Functions
virtual signed tlb_lookup (unsigned int addr, unsigned asi, std::map< t_VAT, t_PTE_context > *tlb, unsigned int tlb_size, sc_core::sc_time *t, unsigned int *debug, bool is_dbg, bool &cacheable, unsigned is_write, uint64_t *paddr)=0
virtual unsigned int read_mcr ()=0
virtual unsigned int read_mctpr ()=0
virtual unsigned int read_mctxr ()=0
virtual unsigned int read_mfsr ()=0
virtual unsigned int read_mfar ()=0
virtual void write_mcr (unsigned int *data)=0
virtual void write_mctpr (unsigned int *data)=0
virtual void write_mctxr (unsigned int *data)=0
virtual void diag_read_itlb (unsigned int addr, unsigned int *data)=0
virtual void diag_write_itlb (unsigned int addr, unsigned int *data)=0
virtual void diag_read_dctlb (unsigned int addr, unsigned int *data)=0
virtual void diag_write_dctlb (unsigned int addr, unsigned int *data)=0
virtual ~mmu_if ()
Constructor & Destructor Documentation
virtual mmu_if::~mmu_if () inline virtual
Member Function Documentation
virtual void mmu_if::diag_read_dctlb (unsigned int addr, unsigned int * data) pure virtual
Implemented in mmu.
virtual void mmu_if::diag_read_itlb (unsigned int addr, unsigned int * data) pure virtual
Implemented in mmu.
virtual void mmu_if::diag_write_dctlb (unsigned int addr, unsigned int * data) pure virtual
Implemented in mmu.
virtual void mmu_if::diag_write_itlb (unsigned int addr, unsigned int * data) pure virtual
Implemented in mmu.
virtual unsigned int mmu_if::read_mcr () pure virtual
Implemented in mmu.
Referenced by tlb_adaptor::mem_read(), and tlb_adaptor::mem_write().
virtual unsigned int mmu_if::read_mctpr () pure virtual
Implemented in mmu.
virtual unsigned int mmu_if::read_mctxr () pure virtual
Implemented in mmu.
virtual unsigned int mmu_if::read_mfar () pure virtual
Implemented in mmu.
virtual unsigned int mmu_if::read_mfsr () pure virtual
Implemented in mmu.
virtual signed mmu_if::tlb_lookup (unsigned int addr, unsigned asi, std::map< t_VAT, t_PTE_context > * tlb, unsigned int tlb_size, sc_core::sc_time * t, unsigned int * debug, bool is_dbg, bool & cacheable, unsigned is_write, uint64_t * paddr) pure virtual
Implemented in mmu.
Referenced by tlb_adaptor::mem_read(), and tlb_adaptor::mem_write().
virtual void mmu_if::write_mcr (unsigned int * data) pure virtual
Implemented in mmu.
virtual void mmu_if::write_mctpr (unsigned int * data) pure virtual
Implemented in mmu.
virtual void mmu_if::write_mctxr (unsigned int * data) pure virtual
Implemented in mmu.
The documentation for this class was generated from the following file:
gaisler/leon3/mmucache/mmu_if.h