SoCRocket: sr_param< sc_dt::sc_logic > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
sr_param< sc_dt::sc_logic > Class Template Reference
Template specialization for sr_param< sc_logic >.
#include <sr_param_systemc.h>
Public Member Functions
sr_param (const std::string &nam, const sc_dt::sc_logic_value_t val)
sr_param (const char *nam, const sc_dt::sc_logic_value_t val)
sr_param (const std::string &nam, const bool &val)
sr_param (const char *nam, const bool &val)
sr_param (const std::string &nam, const char &val)
sr_param (const char *nam, const char &val)
sr_param (const std::string &nam, const int &val)
sr_param (const char *nam, const int &val)
my_type & operator= (const sc_dt::sc_logic_value_t v)
Operator = with sc_logic_value_t.
const bool operator== (sc_dt::sc_logic_value_t val2)
Operator == with sc_logic_value_t.
my_type & operator= (const bool &v)
Operator = with bool.
const bool operator== (const bool val2)
Operator == with bool.
my_type & operator= (const char &v)
Operator = with char.
const bool operator== (const char val2)
Operator == with char.
my_type & operator= (const int &v)
Operator = with int.
const bool operator== (const int val2)
Operator == with int.
const std::string getTypeString () const
Set the value of this parameter specialized for sc_logic.
gs::cnf::Param_type getType () const
Overloads sr_param_base::getType.
std::string convertValueToString (const sc_dt::sc_logic &v)
convertValueToString(sc_logic)
std::string convertValueToString (const val_type &val) const
Overloads sr_param_t<T>::convertValueToString.
Public Member Functions inherited from sr_param_t< sc_dt::sc_logic >
my_type & operator+= (val_type)
my_type & operator-= (val_type)
my_type & operator/= (val_type)
my_type & operator*= (val_type)
val_type operator+ (val_type)
val_type operator- (val_type)
val_type operator/ (val_type)
val_type operator* (val_type)
my_type & operator%= (val_type)
my_type & operator^= (val_type)
my_type & operator&= (val_type)
my_type & operator|= (val_type)
my_type & operator<<= (val_type)
my_type & operator>>= (val_type)
my_type & operator-- ()
val_type operator-- (int)
my_type & operator++ ()
val_type operator++ (int)
sr_param_t ()
Empty constructor. Name will be set in base. Avoid using it! You MUST call init() after instantiation!
sr_param_t (const bool force_top_level_name, gs_param_array *parent_array, const bool register_at_db)
Constructor with the special parameters. Name will be set in base. Avoid using it! You MUST call init() after instantiation!
sr_param_t (const std::string &nam)
Constructor with (local or hierarchical) name. You MUST call init() after instantiation!
sr_param_t (const std::string &nam, const bool force_top_level_name, gs_param_array *parent_array, const bool register_at_db)
Constructor with (local or hierarchical) name and special parameters. You MUST call init() after instantiation!
void init (const val_type &default_val)
Init method to set the value and add the parameter to the plugin db.
void init ()
Init method without value.
virtual ~sr_param_t ()
Destructor.
my_type & operator= (const my_type &v)
Set the value of this parameter to the value of another gs_param.
my_type & operator= (const val_type &v)
Set the value of this parameter.
operator const val_type & () const
Get the value of this parameter.
void setValue (const val_type &val)
Set the value of this parameter.
const val_type & getValue () const
Returns the value of this parameter.
const void * get_value_pointer () const
bool setString (const std::string &str)
Set the value of this parameter with a string.
const std::string & getString () const
Get the value of this parameter as a string.
virtual const bool deserialize (val_type &target_val, const std::string &str)=0
Deserialize for this parameter. To be implemented by the specialization.
void mirror (sc_dt::sc_logic &original)
Serialize this parameter.
void mirror (sr_param_t< sc_dt::sc_logic > &original)
Public Member Functions inherited from sr_param_base
sr_param_base (const std::string &n, const bool register_at_db=true, gs::cnf::gs_param_array *parent_array=NULL, const bool force_top_level_name=false)
void setProperty (std::string key, std::string value)
std::string getProperty (std::string key)
std::map< std::string,
std::string > getProperties ()
void deleteProperty (std::string key)
bool exists (std::string key)
easy_init add_properties ()
Static Public Member Functions
static std::string static_convertValueToString (const val_type &val)
static bool static_deserialize (val_type &target_val, const std::string &str)
Static convertion function called by virtual deserialize and others (e.g. GCnf_API)
Public Attributes
SR_PARAM_HEAD
SR_PARAM_DELEGATE
Additional Inherited Members
Protected Member Functions inherited from sr_param_t< sc_dt::sc_logic >
gs::cnf::callback_return_type mirror_callback (gs::gs_param_base &changed_param, gs::cnf::callback_type reason)
const val_type & convertStringToValue (const std::string &str)
Get the value the string. Needed for construction of gs_param.
Protected Attributes inherited from sr_param_t< sc_dt::sc_logic >
val_type my_value
Value of this parameter.
std::string return_string
String whose reference can be returned as string value.
sr_param_t< sc_dt::sc_logic > * m_mirror_param
sc_dt::sc_logic * m_mirror_val
Detailed Description
template<>
class sr_param< sc_dt::sc_logic >
Template specialization for sr_param< sc_logic >.
Default value = SC_LOGIC_0.
Constructor & Destructor Documentation
sr_param< sc_dt::sc_logic >::sr_param (const std::string & nam, const sc_dt::sc_logic_value_t val) inline explicit
References sr_param_t< T >::init().
sr_param< sc_dt::sc_logic >::sr_param (const char * nam, const sc_dt::sc_logic_value_t val) inline explicit
References sr_param_t< T >::init().
sr_param< sc_dt::sc_logic >::sr_param (const std::string & nam, const bool & val) inline explicit
References sr_param_t< T >::init().
sr_param< sc_dt::sc_logic >::sr_param (const char * nam, const bool & val) inline explicit
References sr_param_t< T >::init().
sr_param< sc_dt::sc_logic >::sr_param (const std::string & nam, const char & val) inline explicit
References sr_param_t< T >::init().
sr_param< sc_dt::sc_logic >::sr_param (const char * nam, const char & val) inline explicit
References sr_param_t< T >::init().
sr_param< sc_dt::sc_logic >::sr_param (const std::string & nam, const int & val) inline explicit
References sr_param_t< T >::init().
sr_param< sc_dt::sc_logic >::sr_param (const char * nam, const int & val) inline explicit
References sr_param_t< T >::init().
Member Function Documentation
std::string sr_param< sc_dt::sc_logic >::convertValueToString (const sc_dt::sc_logic & v) inline
convertValueToString(sc_logic)
References setup::name.
std::string sr_param< sc_dt::sc_logic >::convertValueToString (const val_type & val) const inline virtual
Overloads sr_param_t<T>::convertValueToString.
Implements sr_param_t< sc_dt::sc_logic >.
gs::cnf::Param_type sr_param< sc_dt::sc_logic >::getType () const inline
Overloads sr_param_base::getType.
const std::string sr_param< sc_dt::sc_logic >::getTypeString () const inline
Set the value of this parameter specialized for sc_logic.
Calls conversion value type –> string.
Parameters
val The new value for this parameter.Overloads sr_param_base::getTypeString
my_type& sr_param< sc_dt::sc_logic >::operator= (const sc_dt::sc_logic_value_t v) inline
Operator = with sc_logic_value_t.
References sr_param_t< T >::setValue().
my_type& sr_param< sc_dt::sc_logic >::operator= (const bool & v) inline
Operator = with bool.
References sr_param_t< T >::setValue().
my_type& sr_param< sc_dt::sc_logic >::operator= (const char & v) inline
Operator = with char.
References sr_param_t< T >::setValue().
my_type& sr_param< sc_dt::sc_logic >::operator= (const int & v) inline
Operator = with int.
References sr_param_t< T >::setValue().
const bool sr_param< sc_dt::sc_logic >::operator== (sc_dt::sc_logic_value_t val2) inline
Operator == with sc_logic_value_t.
References sr_param_t< T >::getValue().
const bool sr_param< sc_dt::sc_logic >::operator== (const bool val2) inline
Operator == with bool.
References sr_param_t< T >::getValue().
const bool sr_param< sc_dt::sc_logic >::operator== (const char val2) inline
Operator == with char.
References sr_param_t< T >::getValue().
const bool sr_param< sc_dt::sc_logic >::operator== (const int val2) inline
Operator == with int.
References sr_param_t< T >::getValue().
static std::string sr_param< sc_dt::sc_logic >::static_convertValueToString (const val_type & val) inline static
static bool sr_param< sc_dt::sc_logic >::static_deserialize (val_type & target_val, const std::string & str) inline static
Static convertion function called by virtual deserialize and others (e.g. GCnf_API)
Member Data Documentation
sr_param< sc_dt::sc_logic >::SR_PARAM_DELEGATE
sr_param< sc_dt::sc_logic >::SR_PARAM_HEAD
The documentation for this class was generated from the following file:
core/common/sr_param/sr_param_systemc.h