SoCRocket: sc_register_example::sc_register_base Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
sc_register_example::sc_register_base Class Reference abstract
#include <sc_register.h>
Public Member Functions
sc_register_base ()
sc_register_base (const char *name)
sc_register_base (const char *name, const char *desc)
virtual ~sc_register_base ()
virtual const char * kind () const
const char * desc () const
virtual sc_register_access_mode access_mode () const =0
virtual const
sc_register_field_vec & get_all_fields () const =0
Public Member Functions inherited from scireg_ns::scireg_region_if
scireg_region_if ()
virtual ~scireg_region_if ()
virtual scireg_response scireg_read (vector_byte &v, sc_dt::uint64 size, sc_dt::uint64 offset=0) const
Read a vector of "size" bytes at given offset in this region:
virtual scireg_response scireg_write (const vector_byte &v, sc_dt::uint64 size, sc_dt::uint64 offset=0)
Write a vector of "size" bytes at given offset in this region:
virtual scireg_response scireg_get_bit_attributes (vector_byte &v, scireg_bit_attributes_type t, sc_dt::uint64 size, sc_dt::uint64 offset=0) const
Get bit attributes of type "t" into "v". "size" represents number of bytes returned, offset can be used to constrain the range.
virtual sc_dt::uint64 scireg_get_bit_width () const
Get bit width and byte width of this region.
virtual sc_dt::uint64 scireg_get_byte_width () const
virtual sc_dt::uint64 scireg_get_low_pos () const
If this region is a register field, these functions return low bit and high bit positions:
virtual sc_dt::uint64 scireg_get_high_pos () const
virtual scireg_response scireg_get_parent_regions (std::vector< scireg_region_if * > &v) const
Get parent regions of this region.
virtual scireg_response scireg_add_callback (scireg_callback &cb)
Add/Delete Callback objects associated with this region.
virtual scireg_response scireg_remove_callback (scireg_callback &cb)
virtual scireg_response scireg_get_target_sockets (std::vector< sc_core::sc_object * > &v) const
Get SC TLM2 Target socket associated with this region.
virtual scireg_response scireg_get_value_info (std::vector< scireg_value_info > &v) const
Get a vector of value_info objects for this region.
virtual scireg_response scireg_get_dmi_granted (bool &granted, sc_dt::uint64 size, sc_dt::uint64 offset=0) const
Query to see if DMI access has been granted to this region. "size" and offset can be used to constrain the range.
Static Public Member Functions
static const char * access_type_to_str (sc_register_access_type accessType)
static const char * access_mode_to_str (sc_register_access_mode accessMode)
Protected Member Functions
virtual scireg_ns::scireg_response scireg_get_string_attribute (const char *&s, scireg_ns::scireg_string_attribute_type t) const
Get string attributes of type "t" associated with this region. The returned string is assigned to "s".
virtual scireg_ns::scireg_response scireg_get_region_type (scireg_ns::scireg_region_type &t) const
Get the region_type of this region:
scireg_ns::scireg_response scireg_get_child_regions (std::vector< scireg_ns::scireg_mapped_region > &mapped_regions, sc_dt::uint64 size, sc_dt::uint64 offset) const
virtual scireg_ns::scireg_response scireg_get_parent_modules (std::vector< sc_core::sc_module * > &v) const
Get parent SystemC modules associated with this region.
Protected Attributes
::std::string m_desc
Constructor & Destructor Documentation
sc_register_example::sc_register_base::sc_register_base () inline
sc_register_example::sc_register_base::sc_register_base (const char * name) inline
sc_register_example::sc_register_base::sc_register_base (const char * name, const char * desc) inline
References d, m_desc, and MAX_DESC_LENGTH.
virtual sc_register_example::sc_register_base::~sc_register_base () inline virtual
Member Function Documentation
virtual sc_register_access_mode sc_register_example::sc_register_base::access_mode () const pure virtual
Implemented in sc_register_example::sc_register< unsigned long long, M >, sc_register_example::sc_register< unsigned int, M >, sc_register_example::sc_register< unsigned short, M >, and sc_register_example::sc_register< unsigned char, M >.
const char * sc_register_example::sc_register_base::access_mode_to_str (sc_register_access_mode accessMode) inline static
References sc_register_example::SC_REG_RO_ACCESS, sc_register_example::SC_REG_RW_ACCESS, and sc_register_example::SC_REG_WO_ACCESS.
const char * sc_register_example::sc_register_base::access_type_to_str (sc_register_access_type accessType) inline static
References sc_register_example::SC_REG_READ, and sc_register_example::SC_REG_WRITE.
const char* sc_register_example::sc_register_base::desc () const inline
References m_desc.
Referenced by scireg_get_string_attribute().
virtual const sc_register_field_vec& sc_register_example::sc_register_base::get_all_fields () const pure virtual
Implemented in sc_register_example::sc_register_b< T >, sc_register_example::sc_register_b< unsigned long long >, sc_register_example::sc_register_b< unsigned int >, sc_register_example::sc_register_b< unsigned short >, and sc_register_example::sc_register_b< unsigned char >.
Referenced by scireg_get_child_regions().
virtual const char* sc_register_example::sc_register_base::kind () const inline virtual
scireg_ns::scireg_response sc_register_example::sc_register_base::scireg_get_child_regions (std::vector< scireg_ns::scireg_mapped_region > & mapped_regions, sc_dt::uint64 size, sc_dt::uint64 offset) const inline protected virtual
Get child regions mapped into this region, by returning a mapped region object representing each mapping. The size and offset parameters can be used to constrain the range of the search
Reimplemented from scireg_ns::scireg_region_if.
References get_all_fields(), scireg_ns::scireg_mapped_region::name, scireg_ns::scireg_mapped_region::offset, scireg_ns::scireg_mapped_region::region, s, scireg_ns::SCIREG_FAILURE, scireg_ns::SCIREG_NAME, scireg_ns::scireg_region_if::scireg_region_if(), and scireg_ns::SCIREG_SUCCESS.
virtual scireg_ns::scireg_response sc_register_example::sc_register_base::scireg_get_parent_modules (std::vector< sc_core::sc_module * > & v) const inline protected virtual
Get parent SystemC modules associated with this region.
Reimplemented from scireg_ns::scireg_region_if.
References scireg_ns::SCIREG_SUCCESS.
virtual scireg_ns::scireg_response sc_register_example::sc_register_base::scireg_get_region_type (scireg_ns::scireg_region_type & t) const inline protected virtual
Get the region_type of this region:
Reimplemented from scireg_ns::scireg_region_if.
References scireg_ns::SCIREG_REGISTER, and scireg_ns::SCIREG_SUCCESS.
virtual scireg_ns::scireg_response sc_register_example::sc_register_base::scireg_get_string_attribute (const char *& s, scireg_ns::scireg_string_attribute_type t) const inline protected virtual
Get string attributes of type "t" associated with this region. The returned string is assigned to "s".
Reimplemented from scireg_ns::scireg_region_if.
References desc(), setup::name, scireg_ns::SCIREG_DESCRIPTION, scireg_ns::SCIREG_FAILURE, scireg_ns::SCIREG_NAME, scireg_ns::SCIREG_STRING_VALUE, and scireg_ns::SCIREG_SUCCESS.
Member Data Documentation
::std::string sc_register_example::sc_register_base::m_desc protected
Referenced by desc(), and sc_register_base().
The documentation for this class was generated from the following file:
core/common/sc_register.h