SoCRocket: sr_signal::signal_in< TYPE, MODULE > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
sr_signal::signal_in< TYPE, MODULE > Class Template Reference
#include <sr_signal_in.h>
Public Types
typedef void(MODULE::* t_callback)(const TYPE &value, const sc_core::sc_time &time)
Public Member Functions
signal_in (sc_core::sc_module_name mn=NULL)
signal_in (t_callback callback, sc_core::sc_module_name mn=NULL)
virtual ~signal_in ()
Virtual destructor.
virtual void bind (signal_out_bind_if< TYPE > &sender, const uint32_t &channel=0)
virtual void update (signal_out_if< TYPE > *sender, const sc_core::sc_time &time)
virtual operator TYPE () const
Gets the current signal value.
virtual void operator() (signal_out_bind_if< TYPE > &sender)
Public Member Functions inherited from sr_signal::signal_base< TYPE, MODULE >
signal_base (sc_core::sc_module_name mn=NULL)
Default constructor.
virtual ~signal_base ()
Public Member Functions inherited from sr_signal::signal_in_if< TYPE >
virtual ~signal_in_if ()
Virtual destructor.
Public Member Functions inherited from sr_signal::signal_if< TYPE >
virtual ~signal_if ()
Virtual destructor.
virtual const TYPE & read ()
Read the current signal value.
operator TYPE () const
Call operator to get the current signal value.
bool operator== (const TYPE &t) const
Comparing the current signal value with a variable of the same type TYPE.
Additional Inherited Members
Protected Member Functions inherited from sr_signal::signal_base< TYPE, MODULE >
virtual MODULE * get_module ()
Protected Attributes inherited from sr_signal::signal_if< TYPE >
TYPE m_value
The signal value.
Detailed Description
template<class TYPE, class MODULE>
class sr_signal::signal_in< TYPE, MODULE >
sr_signal input signal. This class implements a TLM Signal abstraction of an incomming signal. The signal stores the value and can execute a callback.
Member Typedef Documentation
template<class TYPE, class MODULE> typedef void(MODULE::* sr_signal::signal_in< TYPE, MODULE >::t_callback)(const TYPE &value, const sc_core::sc_time &time)
Input signal callback type. The callback has two parameter.
Parameters
value The new value of the signal.
time The delay from sc_timestamp() of the propagation.
Constructor & Destructor Documentation
template<class TYPE, class MODULE> sr_signal::signal_in< TYPE, MODULE >::signal_in (sc_core::sc_module_name mn = NULL) inline
Constructor without callback.
Parameters
mn Signal name.
template<class TYPE, class MODULE> sr_signal::signal_in< TYPE, MODULE >::signal_in (t_callback callback, sc_core::sc_module_name mn = NULL) inline
Constructor with callback.
Parameters
callback A base class function which gets executed every time the value is chaned.
mn Signal name.
template<class TYPE, class MODULE> virtual sr_signal::signal_in< TYPE, MODULE >::~signal_in () inline virtual
Virtual destructor.
Member Function Documentation
template<class TYPE, class MODULE> virtual void sr_signal::signal_in< TYPE, MODULE >::bind (signal_out_bind_if< TYPE > & sender, const uint32_t & channel = 0) inline virtual
Input signal bind method. This method implements the binding mechanism with an output signal.
Parameters
sender Output interface to bind with.
channel The channel which has to be bind.
Implements sr_signal::signal_in_if< TYPE >.
Referenced by sr_signal::connect(), and sr_signal::signal_in< TYPE, MODULE >::operator()().
template<class TYPE, class MODULE> virtual sr_signal::signal_in< TYPE, MODULE >::operator TYPE () const inline virtual
Gets the current signal value.
References sr_signal::signal_if< TYPE >::m_value.
template<class TYPE, class MODULE> virtual void sr_signal::signal_in< TYPE, MODULE >::operator() (signal_out_bind_if< TYPE > & sender) inline virtual
Bind the input signal to an output signal. Calls both bind methods.
Parameters
sender The output signal.
References sr_signal::signal_in< TYPE, MODULE >::bind(), and sr_signal::signal_out_bind_if< TYPE >::bind().
template<class TYPE, class MODULE> virtual void sr_signal::signal_in< TYPE, MODULE >::update (signal_out_if< TYPE > * sender, const sc_core::sc_time & time) inline virtual
This method implements the update meachnism. It sets the new value and calls the callback if needed.
Parameters
sender Which calls update.
time Delay from sc_timestamp() after which the signal is set.
Implements sr_signal::signal_in_if< TYPE >.
References sr_signal::signal_base< TYPE, MODULE >::get_module(), sr_signal::signal_if< TYPE >::m_value, and sr_signal::signal_if< TYPE >::read().
The documentation for this class was generated from the following file:
core/common/sr_signal/sr_signal_in.h