SoCRocket: signalkit::signal_in_if< TYPE > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
signalkit::signal_in_if< TYPE > Class Template Reference abstract
Signalkit
#include <ifs.h>
Public Member Functions
virtual ~signal_in_if ()
Virtual destructor.
virtual void bind (signal_out_bind_if< TYPE > &t, const unsigned int &channel=0)=0
virtual void update (signal_out_if< TYPE > *sender, const sc_core::sc_time &time=sc_core::SC_ZERO_TIME)=0
Public Member Functions inherited from signalkit::signal_if< TYPE >
virtual ~signal_if ()
Virtual destructor.
virtual const TYPE & read ()
Read the current signal value.
operator TYPE () const
Call operator to get the current signal value.
bool operator== (const TYPE &t) const
Comparing the current signal value with a variable of the same type TYPE.
Additional Inherited Members
Protected Attributes inherited from signalkit::signal_if< TYPE >
TYPE m_value
The signal value.
Detailed Description
template<class TYPE>
class signalkit::signal_in_if< TYPE >
Signal input interface. This interface implements the bind functionality of an input signal and it provides an abstract function declarations to update the signal. The signal has to be updated by an output signal. If the write function of an output signal is called all connected input signals shall call their update functions.
Constructor & Destructor Documentation
template<class TYPE> virtual signalkit::signal_in_if< TYPE >::~signal_in_if () inline virtual
Virtual destructor.
Member Function Documentation
template<class TYPE> virtual void signalkit::signal_in_if< TYPE >::bind (signal_out_bind_if< TYPE > & t, const unsigned int & channel = 0) pure virtual
Abstract bind method interface. This method has to be implemented by each input signal to make it bind with an output.
Parameters
t Input interface to bind with.
channel The channel which has to be bind.
Implemented in signalkit::signal_infield< TYPE, MODULE >, and signalkit::signal_in< TYPE, MODULE >.
Referenced by signalkit::connect(), signalkit::signal_out< TYPE, MODULE >::operator()(), and signalkit::signal_selector< TYPE, MODULE >::operator()().
template<class TYPE> virtual void signalkit::signal_in_if< TYPE >::update (signal_out_if< TYPE > * sender, const sc_core::sc_time & time = sc_core::SC_ZERO_TIME) pure virtual
Abstract update method interface. This method has to be implemented by each input signal to update the the signal value and call all callbacks.
Parameters
sender Which calls update.
time Delay from sc_timestamp() after which the signal is set.
Implemented in signalkit::signal_infield< TYPE, MODULE >, and signalkit::signal_in< TYPE, MODULE >.
The documentation for this class was generated from the following file:
core/common/signalkit_h/ifs.h