SoCRocket: trap::ExecLoader Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
trap::ExecLoader Class Reference
#include <execLoader.hpp>
Public Member Functions
ExecLoader (std::string fileName, bool plainFile=false)
~ExecLoader ()
unsigned int getProgStart ()
unsigned int getDataStart ()
unsigned int getProgDim ()
Returns the dimension of the loaded program.
unsigned char * getProgData ()
Returns a pointer to the array contianing the program data.
Constructor & Destructor Documentation
trap::ExecLoader::ExecLoader (std::string fileName, bool plainFile = false)
Initializes the loader of executable files by creating the corresponding bfd image of the executable file specified as parameter
Here I simply have to read the input file, putting all the bytes of its content in the programData array
References trap::ELFFrontend::getInstance(), getProgDim(), and THROW_EXCEPTION.
trap::ExecLoader::~ExecLoader ()
Member Function Documentation
unsigned int trap::ExecLoader::getDataStart ()
Returns the start address of the program being loaded (the lowest address of the program)
References THROW_ERROR.
Referenced by sc_main().
unsigned char * trap::ExecLoader::getProgData ()
Returns a pointer to the array contianing the program data.
References THROW_ERROR.
Referenced by sc_main().
unsigned int trap::ExecLoader::getProgDim ()
Returns the dimension of the loaded program.
References THROW_ERROR.
Referenced by ExecLoader(), and sc_main().
unsigned int trap::ExecLoader::getProgStart ()
Returns the entry point of the loaded program (usually the same as the program start address, but not always)
References THROW_ERROR.
Referenced by sc_main().
The documentation for this class was generated from the following files:
core/common/trapgen/elfloader/execLoader.hpp
core/common/trapgen/elfloader/execLoader.cpp