SoCRocket: AMBABasePlatform Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
AMBABasePlatform Class Reference
Platform
#include <ambabase.h>
Public Member Functions
AMBABasePlatform (sc_core::sc_module_name mn, uint32_t ahbctrl_ioaddr=0xFFF, uint32_t ahbctrl_iomask=0xFFF, uint32_t ahbctrl_cfgaddr=0xFF0, uint32_t ahbctrl_cfgmask=0xFF0, bool ahbctrl_rrobin=false, bool ahbctrl_split=false, uint32_t ahbctrl_defmast=0, bool ahbctrl_ioen=true, bool ahbctrl_fixbrst=false, bool ahbctrl_fpnpen=true, bool ahbctrl_mcheck=true, uint32_t apbctrl_haddr=0xfff, uint32_t apbctrl_hmask=0, bool apbctrl_mcheck=true, uint32_t apbctrl_hindex=0, uint32_t irqmp_paddr=0, uint32_t irqmp_pmask=0xFFF, uint32_t irqmp_ncpu=2, uint32_t irqmp_eirq=1, uint32_t irqmp_pindex=0, bool pow_mon=false, amba::amba_layer_ids ambaLayer=amba::amba_LT)
void clkcng ()
void dorst ()
Public Member Functions inherited from CLKDevice
SK_HAS_SIGNALS (CLKDevice)
CLKDevice ()
virtual ~CLKDevice ()
virtual void onrst (const bool &value, const sc_core::sc_time &time)
virtual void onclk (const sc_core::sc_time &value, const sc_core::sc_time &time)
void set_clk (sc_core::sc_clock &clk)
void set_clk (sc_core::sc_time period)
void set_clk (double period, sc_core::sc_time_unit base)
Public Attributes
AHBCtrl ahbctrl
APBCtrl apbctrl
Irqmp irqmp
Public Attributes inherited from CLKDevice
signal< bool >::in rst
Reset input signal.
signal< sc_core::sc_time >::in clk
Clock input signal.
Additional Inherited Members
Protected Attributes inherited from CLKDevice
sc_core::sc_time clock_cycle
Constructor & Destructor Documentation
AMBABasePlatform::AMBABasePlatform (sc_core::sc_module_name mn, uint32_t ahbctrl_ioaddr = 0xFFF, uint32_t ahbctrl_iomask = 0xFFF, uint32_t ahbctrl_cfgaddr = 0xFF0, uint32_t ahbctrl_cfgmask = 0xFF0, bool ahbctrl_rrobin = false, bool ahbctrl_split = false, uint32_t ahbctrl_defmast = 0, bool ahbctrl_ioen = true, bool ahbctrl_fixbrst = false, bool ahbctrl_fpnpen = true, bool ahbctrl_mcheck = true, uint32_t apbctrl_haddr = 0xfff, uint32_t apbctrl_hmask = 0, bool apbctrl_mcheck = true, uint32_t apbctrl_hindex = 0, uint32_t irqmp_paddr = 0, uint32_t irqmp_pmask = 0xFFF, uint32_t irqmp_ncpu = 2, uint32_t irqmp_eirq = 1, uint32_t irqmp_pindex = 0, bool pow_mon = false, amba::amba_layer_ids ambaLayer = amba::amba_LT) inline
Parameters
ahbctrl_ioaddr The MSB address of the AHBCtrl I/O area
ahbctrl_iomask The AHBCtrl I/O area address mask
ahbctrl_cfgaddr The MSB address of the AHBCtrl configuration area (PNP)
ahbctrl_cfgmask The address mask of the AHBCtrl configuration area
ahbctrl_rrobin AHBCtrl arbitration: 1 - round robin, 0 - fixed priority arbitration (only AT)
ahbctrl_split Enable support for AHB SPLIT response in the AHBCtrl (only AT)
ahbctrl_defmast ID of the default master at the AHBCtrl
ahbctrl_ioen AHBCtrl AHB I/O area enable
ahbctrl_fixbrst Enable support for fixed-length bursts in the AHBCtrl
ahbctrl_fpnpen Enable full decoding of PnP configuration records in the AHBCtrl.
ahbctrl_mcheck Check if there are any intersections between core memory regions in the AHBCtrl.
apbctrl_haddr The MSB address of the APBCtrl AHB area. Sets the 12 MSBs in the AHB address
apbctrl_hmask The 12bit AHB area address mask of the APBCtrl
apbctrl_mcheck Check if there are any intersections between APB slave memory regions in the APBCtrl
apbctrl_hindex AHB bus index of the APBCtrl
irqmp_paddr Upper 12bit of the Irqmp APB address.
irqmp_pmask Upper 12bit of the Irqmp APB mask.
irqmp_ncpu Number of CPU which receive interupts stored in Irqmp Status Register.
irqmp_eirq Interrupt channel which hides all the extended interrupt channels.
irqmp_pindex Irqmp APB slave index.
pow_mon Enable power monitoring in AHBCtrl and APBCtrl
References AHBSlave< BASE >::ahb, ahbctrl, AHBCtrl::ahbOUT, APBCtrl::apb, and apbctrl.
Member Function Documentation
void AMBABasePlatform::clkcng () inline virtual
Reimplemented from CLKDevice.
Reimplemented in Leon3mpPlatform.
References CLKDevice::clock_cycle, and CLKDevice::set_clk().
Referenced by Leon3mpPlatform::clkcng().
void AMBABasePlatform::dorst () inline virtual
Reimplemented from CLKDevice.
Reimplemented in Leon3mpPlatform.
References APBCtrl::dorst(), AHBCtrl::dorst(), and Irqmp::dorst().
Referenced by Leon3mpPlatform::dorst().
Member Data Documentation
AHBCtrl AMBABasePlatform::ahbctrl
Referenced by AMBABasePlatform().
APBCtrl AMBABasePlatform::apbctrl
Referenced by AMBABasePlatform().
Irqmp AMBABasePlatform::irqmp
The documentation for this class was generated from the following file:
core/platforms/base/ambabase.h