SoCRocket: trap::ABIIf< regWidth > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
trap::ABIIf< regWidth > Class Template Reference abstract
#include <ABIIf.hpp>
Public Member Functions
bool matchEndian () const throw ()
virtual void preCall () throw ()
virtual void postCall () throw ()
virtual void returnFromCall () throw ()
virtual int getProcessorID () const throw ()
virtual bool isInstrExecuting () const =0 throw ()
virtual void waitInstrEnd () const =0 throw ()
virtual bool isLittleEndian () const =0 throw ()
virtual regWidth readLR () const throw ()
virtual void setLR (const regWidth &newValue) throw ()
virtual regWidth readPC () const =0 throw ()
virtual void setPC (const regWidth &newValue)=0 throw ()
virtual regWidth readSP () const throw ()
virtual void setSP (const regWidth &newValue) throw ()
virtual regWidth readFP () const throw ()
virtual void setFP (const regWidth &newValue) throw ()
virtual regWidth readRetVal () const =0 throw ()
virtual void setRetVal (const regWidth &newValue)=0 throw ()
virtual std::vector< regWidth > readArgs () const =0 throw ()
virtual unsigned int nGDBRegs () const =0 throw ()
virtual void setArgs (const std::vector< regWidth > &args)=0 throw ()
virtual regWidth readGDBReg (const unsigned int &gdbId) const =0 throw ()
virtual void setGDBReg (const regWidth &newValue, const unsigned int &gdbId)=0 throw ()
virtual regWidth readMem (const regWidth &address)=0
virtual unsigned char readCharMem (const regWidth &address)=0
virtual void writeMem (const regWidth &address, regWidth datum)=0
virtual void writeCharMem (const regWidth &address, unsigned char datum)=0
virtual regWidth getCodeLimit ()=0
virtual bool isRoutineEntry (const InstructionBase *instr)=0 throw ()
virtual bool isRoutineExit (const InstructionBase *instr)=0 throw ()
virtual unsigned char * getState () const =0 throw ()
virtual void setState (unsigned char *state)=0 throw ()
virtual boost::circular_buffer
< HistoryInstrType > & getInstructionHistory ()=0
virtual ~ABIIf ()
Constructor & Destructor Documentation
template<class regWidth> virtual trap::ABIIf< regWidth >::~ABIIf () inline virtual
Member Function Documentation
template<class regWidth> virtual regWidth trap::ABIIf< regWidth >::getCodeLimit () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
Referenced by trap::OSEmulator< unsigned int >::initSysCalls().
template<class regWidth> virtual boost::circular_buffer<HistoryInstrType>& trap::ABIIf< regWidth >::getInstructionHistory () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> virtual int trap::ABIIf< regWidth >::getProcessorID () const throw () inline virtual
Reimplemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> virtual unsigned char* trap::ABIIf< regWidth >::getState () const throw () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> virtual bool trap::ABIIf< regWidth >::isInstrExecuting () const throw () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> virtual bool trap::ABIIf< regWidth >::isLittleEndian () const throw () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
Referenced by trap::ABIIf< unsigned int >::matchEndian().
template<class regWidth> virtual bool trap::ABIIf< regWidth >::isRoutineEntry (const InstructionBase * instr) throw () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> virtual bool trap::ABIIf< regWidth >::isRoutineExit (const InstructionBase * instr) throw () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> bool trap::ABIIf< regWidth >::matchEndian () const throw () inline
template<class regWidth> virtual unsigned int trap::ABIIf< regWidth >::nGDBRegs () const throw () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> virtual void trap::ABIIf< regWidth >::postCall () throw () inline virtual
Reimplemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
Referenced by trap::openSysCall< wordSize >::operator()(), trap::creatSysCall< wordSize >::operator()(), trap::closeSysCall< wordSize >::operator()(), trap::readSysCall< wordSize >::operator()(), trap::writeSysCall< wordSize >::operator()(), trap::isattySysCall< wordSize >::operator()(), trap::sbrkSysCall< wordSize >::operator()(), trap::lseekSysCall< wordSize >::operator()(), trap::fstatSysCall< wordSize >::operator()(), trap::statSysCall< wordSize >::operator()(), trap::timesSysCall< wordSize >::operator()(), trap::timeSysCall< wordSize >::operator()(), trap::randomSysCall< wordSize >::operator()(), trap::utimesSysCall< wordSize >::operator()(), trap::lstatSysCall< wordSize >::operator()(), trap::getpidSysCall< wordSize >::operator()(), trap::chmodSysCall< wordSize >::operator()(), trap::dupSysCall< wordSize >::operator()(), trap::dup2SysCall< wordSize >::operator()(), trap::getenvSysCall< wordSize >::operator()(), trap::gettimeofdaySysCall< wordSize >::operator()(), trap::errorSysCall< wordSize >::operator()(), trap::chownSysCall< wordSize >::operator()(), trap::unlinkSysCall< wordSize >::operator()(), trap::usleepSysCall< wordSize >::operator()(), trap::mainSysCall< wordSize >::operator()(), and trap::sysconfSysCall< wordSize >::operator()().
template<class regWidth> virtual void trap::ABIIf< regWidth >::preCall () throw () inline virtual
Reimplemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
Referenced by trap::openSysCall< wordSize >::operator()(), trap::creatSysCall< wordSize >::operator()(), trap::closeSysCall< wordSize >::operator()(), trap::readSysCall< wordSize >::operator()(), trap::writeSysCall< wordSize >::operator()(), trap::isattySysCall< wordSize >::operator()(), trap::sbrkSysCall< wordSize >::operator()(), trap::lseekSysCall< wordSize >::operator()(), trap::fstatSysCall< wordSize >::operator()(), trap::statSysCall< wordSize >::operator()(), trap::_exitSysCall< wordSize >::operator()(), trap::timesSysCall< wordSize >::operator()(), trap::timeSysCall< wordSize >::operator()(), trap::randomSysCall< wordSize >::operator()(), trap::utimesSysCall< wordSize >::operator()(), trap::lstatSysCall< wordSize >::operator()(), trap::getpidSysCall< wordSize >::operator()(), trap::chmodSysCall< wordSize >::operator()(), trap::dupSysCall< wordSize >::operator()(), trap::dup2SysCall< wordSize >::operator()(), trap::getenvSysCall< wordSize >::operator()(), trap::gettimeofdaySysCall< wordSize >::operator()(), trap::errorSysCall< wordSize >::operator()(), trap::chownSysCall< wordSize >::operator()(), trap::unlinkSysCall< wordSize >::operator()(), trap::usleepSysCall< wordSize >::operator()(), trap::mainSysCall< wordSize >::operator()(), and trap::sysconfSysCall< wordSize >::operator()().
template<class regWidth> virtual std::vector<regWidth> trap::ABIIf< regWidth >::readArgs () const throw () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
Referenced by trap::openSysCall< wordSize >::operator()(), trap::creatSysCall< wordSize >::operator()(), trap::closeSysCall< wordSize >::operator()(), trap::readSysCall< wordSize >::operator()(), trap::writeSysCall< wordSize >::operator()(), trap::isattySysCall< wordSize >::operator()(), trap::sbrkSysCall< wordSize >::operator()(), trap::lseekSysCall< wordSize >::operator()(), trap::fstatSysCall< wordSize >::operator()(), trap::statSysCall< wordSize >::operator()(), trap::_exitSysCall< wordSize >::operator()(), trap::timesSysCall< wordSize >::operator()(), trap::timeSysCall< wordSize >::operator()(), trap::utimesSysCall< wordSize >::operator()(), trap::lstatSysCall< wordSize >::operator()(), trap::chmodSysCall< wordSize >::operator()(), trap::dupSysCall< wordSize >::operator()(), trap::dup2SysCall< wordSize >::operator()(), trap::getenvSysCall< wordSize >::operator()(), trap::gettimeofdaySysCall< wordSize >::operator()(), trap::errorSysCall< wordSize >::operator()(), trap::chownSysCall< wordSize >::operator()(), trap::unlinkSysCall< wordSize >::operator()(), trap::mainSysCall< wordSize >::operator()(), and trap::sysconfSysCall< wordSize >::operator()().
template<class regWidth> virtual unsigned char trap::ABIIf< regWidth >::readCharMem (const regWidth & address) pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
Referenced by trap::openSysCall< wordSize >::operator()(), trap::creatSysCall< wordSize >::operator()(), trap::writeSysCall< wordSize >::operator()(), trap::statSysCall< wordSize >::operator()(), trap::utimesSysCall< wordSize >::operator()(), trap::lstatSysCall< wordSize >::operator()(), trap::chmodSysCall< wordSize >::operator()(), trap::getenvSysCall< wordSize >::operator()(), trap::chownSysCall< wordSize >::operator()(), and trap::unlinkSysCall< wordSize >::operator()().
template<class regWidth> virtual regWidth trap::ABIIf< regWidth >::readFP () const throw () inline virtual
Reimplemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> virtual regWidth trap::ABIIf< regWidth >::readGDBReg (const unsigned int & gdbId) const throw () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> virtual regWidth trap::ABIIf< regWidth >::readLR () const throw () inline virtual
Reimplemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
Referenced by trap::ABIIf< unsigned int >::returnFromCall().
template<class regWidth> virtual regWidth trap::ABIIf< regWidth >::readMem (const regWidth & address) pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
Referenced by trap::sbrkSysCall< wordSize >::operator()(), and trap::utimesSysCall< wordSize >::operator()().
template<class regWidth> virtual regWidth trap::ABIIf< regWidth >::readPC () const throw () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> virtual regWidth trap::ABIIf< regWidth >::readRetVal () const throw () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> virtual regWidth trap::ABIIf< regWidth >::readSP () const throw () inline virtual
Reimplemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> virtual void trap::ABIIf< regWidth >::returnFromCall () throw () inline virtual
Reimplemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
Referenced by trap::openSysCall< wordSize >::operator()(), trap::creatSysCall< wordSize >::operator()(), trap::closeSysCall< wordSize >::operator()(), trap::readSysCall< wordSize >::operator()(), trap::writeSysCall< wordSize >::operator()(), trap::isattySysCall< wordSize >::operator()(), trap::sbrkSysCall< wordSize >::operator()(), trap::lseekSysCall< wordSize >::operator()(), trap::fstatSysCall< wordSize >::operator()(), trap::statSysCall< wordSize >::operator()(), trap::timesSysCall< wordSize >::operator()(), trap::timeSysCall< wordSize >::operator()(), trap::randomSysCall< wordSize >::operator()(), trap::utimesSysCall< wordSize >::operator()(), trap::lstatSysCall< wordSize >::operator()(), trap::getpidSysCall< wordSize >::operator()(), trap::chmodSysCall< wordSize >::operator()(), trap::dupSysCall< wordSize >::operator()(), trap::dup2SysCall< wordSize >::operator()(), trap::getenvSysCall< wordSize >::operator()(), trap::gettimeofdaySysCall< wordSize >::operator()(), trap::errorSysCall< wordSize >::operator()(), trap::chownSysCall< wordSize >::operator()(), trap::unlinkSysCall< wordSize >::operator()(), trap::usleepSysCall< wordSize >::operator()(), and trap::sysconfSysCall< wordSize >::operator()().
template<class regWidth> virtual void trap::ABIIf< regWidth >::setArgs (const std::vector< regWidth > & args) throw () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
Referenced by trap::mainSysCall< wordSize >::operator()().
template<class regWidth> virtual void trap::ABIIf< regWidth >::setFP (const regWidth & newValue) throw () inline virtual
Reimplemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> virtual void trap::ABIIf< regWidth >::setGDBReg (const regWidth & newValue, const unsigned int & gdbId) throw () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> virtual void trap::ABIIf< regWidth >::setLR (const regWidth & newValue) throw () inline virtual
Reimplemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> virtual void trap::ABIIf< regWidth >::setPC (const regWidth & newValue) throw () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
Referenced by trap::ABIIf< unsigned int >::returnFromCall().
template<class regWidth> virtual void trap::ABIIf< regWidth >::setRetVal (const regWidth & newValue) throw () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
Referenced by trap::openSysCall< wordSize >::operator()(), trap::creatSysCall< wordSize >::operator()(), trap::closeSysCall< wordSize >::operator()(), trap::readSysCall< wordSize >::operator()(), trap::writeSysCall< wordSize >::operator()(), trap::isattySysCall< wordSize >::operator()(), trap::sbrkSysCall< wordSize >::operator()(), trap::lseekSysCall< wordSize >::operator()(), trap::fstatSysCall< wordSize >::operator()(), trap::statSysCall< wordSize >::operator()(), trap::timesSysCall< wordSize >::operator()(), trap::timeSysCall< wordSize >::operator()(), trap::randomSysCall< wordSize >::operator()(), trap::utimesSysCall< wordSize >::operator()(), trap::lstatSysCall< wordSize >::operator()(), trap::getpidSysCall< wordSize >::operator()(), trap::chmodSysCall< wordSize >::operator()(), trap::dupSysCall< wordSize >::operator()(), trap::dup2SysCall< wordSize >::operator()(), trap::getenvSysCall< wordSize >::operator()(), trap::gettimeofdaySysCall< wordSize >::operator()(), trap::errorSysCall< wordSize >::operator()(), trap::chownSysCall< wordSize >::operator()(), trap::unlinkSysCall< wordSize >::operator()(), and trap::sysconfSysCall< wordSize >::operator()().
template<class regWidth> virtual void trap::ABIIf< regWidth >::setSP (const regWidth & newValue) throw () inline virtual
Reimplemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> virtual void trap::ABIIf< regWidth >::setState (unsigned char * state) throw () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> virtual void trap::ABIIf< regWidth >::waitInstrEnd () const throw () pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
template<class regWidth> virtual void trap::ABIIf< regWidth >::writeCharMem (const regWidth & address, unsigned char datum) pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
Referenced by trap::readSysCall< wordSize >::operator()(), trap::getenvSysCall< wordSize >::operator()(), and trap::mainSysCall< wordSize >::operator()().
template<class regWidth> virtual void trap::ABIIf< regWidth >::writeMem (const regWidth & address, regWidth datum) pure virtual
Implemented in leon3_funcat_trap::LEON3_ABIIf, and leon3_funclt_trap::LEON3_ABIIf.
Referenced by trap::fstatSysCall< wordSize >::operator()(), trap::statSysCall< wordSize >::operator()(), trap::timesSysCall< wordSize >::operator()(), trap::timeSysCall< wordSize >::operator()(), trap::lstatSysCall< wordSize >::operator()(), trap::gettimeofdaySysCall< wordSize >::operator()(), and trap::mainSysCall< wordSize >::operator()().
The documentation for this class was generated from the following file:
core/common/trapgen/ABIIf.hpp