SoCRocket: APBDeviceBase Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
APBDeviceBase Class Reference abstract
Utils
#include <apbdevice.h>
Public Member Functions
virtual ~APBDeviceBase ()
Empty destructor.
virtual uint16_t get_apb_device_id () const =0
Returns the device id.
virtual uint8_t get_apb_vendor_id () const =0
Returns the vendor id.
virtual const uint32_t * get_apb_device_info ()=0
virtual const AMBADeviceType get_apb_type () const =0
virtual uint32_t get_apb_base () const =0
virtual uint32_t get_apb_mask () const =0
virtual sc_dt::uint64 get_apb_base_addr ()=0
virtual uint32_t get_apb_base_addr_ () const =0
virtual sc_dt::uint64 get_apb_size ()=0
virtual uint32_t get_apb_size_ () const =0
virtual uint32_t get_apb_relative_addr (uint32_t addr) const =0
virtual uint32_t get_apb_pindex () const =0
Returns the bus id of the module (pindex)
virtual void print_apb_device_info (char *name) const =0
Prints the device info of the device.
Detailed Description
This class is a base class for grlib models. It implements the device plug and play informations. Together with the APBBridge class it implements the plug and play feature of the grlib.
See also
APBCtrl
Constructor & Destructor Documentation
virtual APBDeviceBase::~APBDeviceBase () inline virtual
Empty destructor.
Member Function Documentation
virtual uint32_t APBDeviceBase::get_apb_base () const pure virtual
Returns the Bus specific most significant 12bit of the base address Shifted to the lowest bits in the word.
Implemented in APBDevice< BASE >, and APBDevice< RegisterBase >.
Referenced by APBCtrl::start_of_simulation().
virtual sc_dt::uint64 APBDeviceBase::get_apb_base_addr () pure virtual
Returns the Bus specific base address of the device.
See also
get_bar_addr
Returns
The device base address.
Implemented in APBDevice< BASE >, and APBDevice< RegisterBase >.
virtual uint32_t APBDeviceBase::get_apb_base_addr_ () const pure virtual
Implemented in APBDevice< BASE >, and APBDevice< RegisterBase >.
virtual uint16_t APBDeviceBase::get_apb_device_id () const pure virtual
Returns the device id.
Implemented in APBDevice< BASE >, and APBDevice< RegisterBase >.
virtual const uint32_t* APBDeviceBase::get_apb_device_info () pure virtual
Returns the device register file. A set of 8 registers as specified by the grlib manual. See section: 14.2.2 (Page 79)
Implemented in APBDevice< BASE >, and APBDevice< RegisterBase >.
Referenced by APBCtrl::start_of_simulation().
virtual uint32_t APBDeviceBase::get_apb_mask () const pure virtual
Returns the Bus specific mask of the most significant 12bit of the address Shifted to the lowest bits in the word.
Implemented in APBDevice< BASE >, and APBDevice< RegisterBase >.
Referenced by APBCtrl::start_of_simulation().
virtual uint32_t APBDeviceBase::get_apb_pindex () const pure virtual
Returns the bus id of the module (pindex)
Implemented in APBDevice< BASE >, and APBDevice< RegisterBase >.
Referenced by APBCtrl::start_of_simulation().
virtual uint32_t APBDeviceBase::get_apb_relative_addr (uint32_t addr) const pure virtual
Implemented in APBDevice< BASE >, and APBDevice< RegisterBase >.
virtual sc_dt::uint64 APBDeviceBase::get_apb_size () pure virtual
Returns the size of the hole device as seen from the bus.
See also
get_bar_size
Returns
The device size.
Implemented in APBDevice< BASE >, and APBDevice< RegisterBase >.
virtual uint32_t APBDeviceBase::get_apb_size_ () const pure virtual
Implemented in APBDevice< BASE >, and APBDevice< RegisterBase >.
virtual const AMBADeviceType APBDeviceBase::get_apb_type () const pure virtual
Returns the device type. Should be APBIO ;-)
Implemented in APBDevice< BASE >, and APBDevice< RegisterBase >.
Referenced by APBCtrl::start_of_simulation().
virtual uint8_t APBDeviceBase::get_apb_vendor_id () const pure virtual
Returns the vendor id.
Implemented in APBDevice< BASE >, and APBDevice< RegisterBase >.
virtual void APBDeviceBase::print_apb_device_info (char * name) const pure virtual
Prints the device info of the device.
Implemented in APBDevice< BASE >, and APBDevice< RegisterBase >.
The documentation for this class was generated from the following file:
core/models/utils/apbdevice.h