SoCRocket: sc_register_example::sc_register_field_b< T > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
sc_register_example::sc_register_field_b< T > Class Template Reference abstract
#include <sc_register.h>
Public Member Functions
sc_register_field_b (const char *nm, sc_register_b< T > *r)
sc_register_field_b (const char *nm, sc_register_b< T > *r, const char *desc)
virtual ~sc_register_field_b ()
const T & read () const
void write (const T &v)
void add_value_code (const T &v, const ::std::string &n)
void add_value_code (const T &v, const ::std::string &n, const ::std::string &desc)
const char * get_value_mnemonic () const
const char * get_value_desc () const
virtual void print (::std::ostream &os) const
scireg_ns::scireg_response scireg_read (scireg_ns::vector_byte &v, sc_dt::uint64 size, sc_dt::uint64 offset) const
Read a vector of "size" bytes at given offset in this region:
scireg_ns::scireg_response scireg_write (const scireg_ns::vector_byte &v, sc_dt::uint64 size, sc_dt::uint64 offset)
Write a vector of "size" bytes at given offset in this region:
template<>
void print (::std::ostream &os) const
Public Member Functions inherited from sc_register_example::sc_register_field_base
sc_register_field_base (const char *nm)
sc_register_field_base (const char *nm, const char *desc)
virtual ~sc_register_field_base ()
const char * name () const
const char * desc () const
virtual unsigned int low_pos () const =0
virtual unsigned int high_pos () const =0
virtual unsigned int bit_width () const =0
Public Member Functions inherited from scireg_ns::scireg_region_if
scireg_region_if ()
virtual ~scireg_region_if ()
virtual scireg_response scireg_get_bit_attributes (vector_byte &v, scireg_bit_attributes_type t, sc_dt::uint64 size, sc_dt::uint64 offset=0) const
Get bit attributes of type "t" into "v". "size" represents number of bytes returned, offset can be used to constrain the range.
virtual sc_dt::uint64 scireg_get_byte_width () const
virtual scireg_response scireg_get_child_regions (std::vector< scireg_mapped_region > &mapped_regions, sc_dt::uint64 size=sc_dt::uint64(-1), sc_dt::uint64 offset=0) const
virtual scireg_response scireg_get_parent_regions (std::vector< scireg_region_if * > &v) const
Get parent regions of this region.
virtual scireg_response scireg_add_callback (scireg_callback &cb)
Add/Delete Callback objects associated with this region.
virtual scireg_response scireg_remove_callback (scireg_callback &cb)
virtual scireg_response scireg_get_target_sockets (std::vector< sc_core::sc_object * > &v) const
Get SC TLM2 Target socket associated with this region.
virtual scireg_response scireg_get_parent_modules (std::vector< sc_core::sc_module * > &v) const
Get parent SystemC modules associated with this region.
virtual scireg_response scireg_get_value_info (std::vector< scireg_value_info > &v) const
Get a vector of value_info objects for this region.
virtual scireg_response scireg_get_dmi_granted (bool &granted, sc_dt::uint64 size, sc_dt::uint64 offset=0) const
Query to see if DMI access has been granted to this region. "size" and offset can be used to constrain the range.
Protected Member Functions
virtual const T & get_mask () const =0
virtual unsigned int get_shift_bits () const =0
const sc_rf_valuecode * get_value_code (const T &v) const
const char * get_value_mnemonic (const T &v) const
const char * get_value_desc (const T &v) const
Protected Member Functions inherited from sc_register_example::sc_register_field_base
sc_dt::uint64 scireg_get_low_pos () const
If this region is a register field, these functions return low bit and high bit positions:
sc_dt::uint64 scireg_get_high_pos () const
sc_dt::uint64 scireg_get_bit_width () const
Get bit width and byte width of this region.
virtual scireg_ns::scireg_response scireg_get_region_type (scireg_ns::scireg_region_type &t) const
Get the region_type of this region:
virtual scireg_ns::scireg_response scireg_get_string_attribute (const char *&s, scireg_ns::scireg_string_attribute_type t) const
Get string attributes of type "t" associated with this region. The returned string is assigned to "s".
Protected Attributes
sc_register_b< T > * m_reg
::std::map< T, sc_rf_valuecode * > m_value_encoding_map
Protected Attributes inherited from sc_register_example::sc_register_field_base
::std::string m_name
::std::string m_desc
Constructor & Destructor Documentation
template<typename T > sc_register_example::sc_register_field_b< T >::sc_register_field_b (const char * nm, sc_register_b< T > * r) inline
References sc_register_example::sc_register_field_b< T >::m_reg.
template<typename T > sc_register_example::sc_register_field_b< T >::sc_register_field_b (const char * nm, sc_register_b< T > * r, const char * desc) inline
References sc_register_example::sc_register_field_b< T >::m_reg.
template<typename T > sc_register_example::sc_register_field_b< T >::~sc_register_field_b () inline virtual
Member Function Documentation
template<typename T > void sc_register_example::sc_register_field_b< T >::add_value_code (const T & v, const ::std::string & n) inline
References d.
template<typename T > void sc_register_example::sc_register_field_b< T >::add_value_code (const T & v, const ::std::string & n, const ::std::string & desc) inline
template<typename T > virtual const T& sc_register_example::sc_register_field_b< T >::get_mask () const protected pure virtual
Implemented in sc_register_example::sc_register_field< T, lowpos, highpos >.
template<typename T > virtual unsigned int sc_register_example::sc_register_field_b< T >::get_shift_bits () const protected pure virtual
Implemented in sc_register_example::sc_register_field< T, lowpos, highpos >.
template<typename T > const sc_rf_valuecode * sc_register_example::sc_register_field_b< T >::get_value_code (const T & v) const inline protected
template<typename T > const char* sc_register_example::sc_register_field_b< T >::get_value_desc () const inline virtual
Implements sc_register_example::sc_register_field_base.
References sc_register_example::sc_register_field_b< T >::read().
template<typename T > const char * sc_register_example::sc_register_field_b< T >::get_value_desc (const T & v) const inline protected
References sc_register_example::sc_rf_valuecode::desc().
template<typename T > const char* sc_register_example::sc_register_field_b< T >::get_value_mnemonic () const inline virtual
Implements sc_register_example::sc_register_field_base.
References sc_register_example::sc_register_field_b< T >::read().
template<typename T > const char * sc_register_example::sc_register_field_b< T >::get_value_mnemonic (const T & v) const inline protected
References sc_register_example::sc_rf_valuecode::mnemonic().
template<typename T > virtual void sc_register_example::sc_register_field_b< T >::print (::std::ostream & os) const inline virtual
Implements sc_register_example::sc_register_field_base.
References sc_register_example::sc_register_field_b< T >::read().
template<> void sc_register_example::sc_register_field_b< unsigned char >::print (::std::ostream & os) const inline virtual
Implements sc_register_example::sc_register_field_base.
template<typename T > const T & sc_register_example::sc_register_field_b< T >::read () const inline
Referenced by sc_register_example::sc_register_field_b< T >::get_value_desc(), sc_register_example::sc_register_field_b< T >::get_value_mnemonic(), sc_register_example::sc_register_field_b< T >::print(), and sc_register_example::sc_register_field_b< T >::scireg_read().
template<typename T > scireg_ns::scireg_response sc_register_example::sc_register_field_b< T >::scireg_read (scireg_ns::vector_byte & v, sc_dt::uint64 size, sc_dt::uint64 offset) const inline virtual
Read a vector of "size" bytes at given offset in this region:
Reimplemented from scireg_ns::scireg_region_if.
References sc_register_example::sc_register_field_b< T >::read(), scireg_ns::SCIREG_FAILURE, and scireg_ns::SCIREG_SUCCESS.
template<typename T > scireg_ns::scireg_response sc_register_example::sc_register_field_b< T >::scireg_write (const scireg_ns::vector_byte & v, sc_dt::uint64 size, sc_dt::uint64 offset) inline virtual
Write a vector of "size" bytes at given offset in this region:
Reimplemented from scireg_ns::scireg_region_if.
References scireg_ns::SCIREG_FAILURE, scireg_ns::SCIREG_SUCCESS, and sc_register_example::sc_register_field_b< T >::write().
template<typename T > void sc_register_example::sc_register_field_b< T >::write (const T & v) inline
Referenced by sc_register_example::sc_register_field_b< T >::scireg_write().
Member Data Documentation
template<typename T > sc_register_b<T>* sc_register_example::sc_register_field_b< T >::m_reg protected
Referenced by sc_register_example::sc_register_field_b< T >::sc_register_field_b().
template<typename T > ::std::map<T,sc_rf_valuecode*> sc_register_example::sc_register_field_b< T >::m_value_encoding_map protected
The documentation for this class was generated from the following file:
core/common/sc_register.h