SoCRocket: sr_param< sc_core::sc_event > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
sr_param< sc_core::sc_event > Class Template Reference
Template specialization for sr_param< sc_event >.
#include <sr_param_systemc.h>
Public Member Functions
sr_param ()
sr_param (const std::string &nam)
sr_param (const char *nam)
sr_param (const std::string &nam, const std::string &val, const bool force_top_level_name=false)
sr_param (const char *nam, const char *val, const bool force_top_level_name=false)
sr_param (const std::string &nam, const char *val, const bool force_top_level_name=false)
sr_param (const char *nam, const std::string &val, const bool force_top_level_name=false)
sr_param (const std::string &nam, const val_type &val, const bool force_top_level_name=false)
sr_param (const char *nam, const val_type &val, const bool force_top_level_name=false)
sr_param (gs_param_array *parent_array, const bool force_top_level_name=false)
sr_param (const std::string &nam, gs_param_array *parent_array, const bool force_top_level_name=false)
sr_param (const char *nam, gs_param_array *parent_array, const bool force_top_level_name=false)
sr_param (const std::string &nam, const std::string &val, gs_param_array *parent_array, const bool force_top_level_name=false)
sr_param (const char *nam, const char *val, gs_param_array *parent_array, const bool force_top_level_name=false)
sr_param (const std::string &nam, const char *val, gs_param_array *parent_array, const bool force_top_level_name=false)
sr_param (const char *nam, const std::string &val, gs_param_array *parent_array, const bool force_top_level_name=false)
sr_param (const std::string &nam, const val_type &val, gs_param_array *parent_array, const bool force_top_level_name=false)
sr_param (const char *nam, const val_type &val, gs_param_array *parent_array, const bool force_top_level_name=false)
sr_param (gs_param_array &parent_array, const bool force_top_level_name=false)
sr_param (const std::string &nam, gs_param_array &parent_array, const bool force_top_level_name=false)
sr_param (const char *nam, gs_param_array &parent_array, const bool force_top_level_name=false)
sr_param (const std::string &nam, const std::string &val, gs_param_array &parent_array, const bool force_top_level_name=false)
sr_param (const char *nam, const char *val, gs_param_array &parent_array, const bool force_top_level_name=false)
sr_param (const std::string &nam, const char *val, gs_param_array &parent_array, const bool force_top_level_name=false)
sr_param (const char *nam, const std::string &val, gs_param_array &parent_array, const bool force_top_level_name=false)
sr_param (const std::string &nam, const val_type &val, gs_param_array &parent_array, const bool force_top_level_name=false)
sr_param (const char *nam, const val_type &val, gs_param_array &parent_array, const bool force_top_level_name=false)
sr_param (const std::string &nam, const std::string &val, gs_param_array *parent_array, const bool force_top_level_name, const bool register_at_db)
sr_param (const std::string &nam, const std::string &val, gs_param_array &parent_array, const bool force_top_level_name, const bool register_at_db)
virtual ~sr_param ()
const bool deserialize (val_type &target_val, const std::string &str)
Deserialize for this parameter. To be implemented by the specialization.
void eventthread (void)
void init ()
void notify ()
void notify (const sc_time &t)
void notify (double d, sc_time_unit t)
void cancel ()
const std::string getTypeString () const
Overloads sr_param_base::getTypeString.
gs::cnf::Param_type getType () const
Overloads sr_param_base::getType.
std::string convertValueToString (const sc_core::sc_event &v)
convertValueToString(sc_logic)
std::string convertValueToString (const val_type &val) const
Overloads sr_param_t<T>::convertValueToString.
Public Member Functions inherited from sr_param_t< sc_core::sc_event >
my_type & operator+= (val_type)
my_type & operator-= (val_type)
my_type & operator/= (val_type)
my_type & operator*= (val_type)
val_type operator+ (val_type)
val_type operator- (val_type)
val_type operator/ (val_type)
val_type operator* (val_type)
my_type & operator%= (val_type)
my_type & operator^= (val_type)
my_type & operator&= (val_type)
my_type & operator|= (val_type)
my_type & operator<<= (val_type)
my_type & operator>>= (val_type)
my_type & operator-- ()
val_type operator-- (int)
my_type & operator++ ()
val_type operator++ (int)
sr_param_t ()
Empty constructor. Name will be set in base. Avoid using it! You MUST call init() after instantiation!
sr_param_t (const bool force_top_level_name, gs_param_array *parent_array, const bool register_at_db)
Constructor with the special parameters. Name will be set in base. Avoid using it! You MUST call init() after instantiation!
sr_param_t (const std::string &nam)
Constructor with (local or hierarchical) name. You MUST call init() after instantiation!
sr_param_t (const std::string &nam, const bool force_top_level_name, gs_param_array *parent_array, const bool register_at_db)
Constructor with (local or hierarchical) name and special parameters. You MUST call init() after instantiation!
void init (const val_type &default_val)
Init method to set the value and add the parameter to the plugin db.
void init ()
Init method without value.
virtual ~sr_param_t ()
Destructor.
my_type & operator= (const my_type &v)
Set the value of this parameter to the value of another gs_param.
my_type & operator= (const val_type &v)
Set the value of this parameter.
operator const val_type & () const
Get the value of this parameter.
void setValue (const val_type &val)
Set the value of this parameter.
const val_type & getValue () const
Returns the value of this parameter.
const void * get_value_pointer () const
bool setString (const std::string &str)
Set the value of this parameter with a string.
const std::string & getString () const
Get the value of this parameter as a string.
void mirror (sc_core::sc_event &original)
Serialize this parameter.
void mirror (sr_param_t< sc_core::sc_event > &original)
Public Member Functions inherited from sr_param_base
sr_param_base (const std::string &n, const bool register_at_db=true, gs::cnf::gs_param_array *parent_array=NULL, const bool force_top_level_name=false)
void setProperty (std::string key, std::string value)
std::string getProperty (std::string key)
std::map< std::string,
std::string > getProperties ()
void deleteProperty (std::string key)
bool exists (std::string key)
easy_init add_properties ()
Static Public Member Functions
static std::string static_convertValueToString (const val_type &val)
static bool static_deserialize (val_type &target_val, const std::string &str)
Static convertion function called by virtual deserialize and others (e.g. GCnf_API)
Protected Types
typedef sr_param< val_type > my_type
Protected Attributes
val_type intern_event
Protected Attributes inherited from sr_param_t< sc_core::sc_event >
val_type my_value
Value of this parameter.
std::string return_string
String whose reference can be returned as string value.
sr_param_t< sc_core::sc_event > * m_mirror_param
sc_core::sc_event * m_mirror_val
Additional Inherited Members
Protected Member Functions inherited from sr_param_t< sc_core::sc_event >
gs::cnf::callback_return_type mirror_callback (gs::gs_param_base &changed_param, gs::cnf::callback_type reason)
const val_type & convertStringToValue (const std::string &str)
Get the value the string. Needed for construction of gs_param.
Detailed Description
template<>
class sr_param< sc_core::sc_event >
Template specialization for sr_param< sc_event >.
This specialization has special callback behavior
Member Typedef Documentation
typedef sr_param<val_type> sr_param< sc_core::sc_event >::my_type protected
Constructor & Destructor Documentation
sr_param< sc_core::sc_event >::sr_param () inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const std::string & nam) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const char * nam) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const std::string & nam, const std::string & val, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const char * nam, const char * val, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const std::string & nam, const char * val, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const char * nam, const std::string & val, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const std::string & nam, const val_type & val, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const char * nam, const val_type & val, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (gs_param_array * parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const std::string & nam, gs_param_array * parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const char * nam, gs_param_array * parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const std::string & nam, const std::string & val, gs_param_array * parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const char * nam, const char * val, gs_param_array * parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const std::string & nam, const char * val, gs_param_array * parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const char * nam, const std::string & val, gs_param_array * parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const std::string & nam, const val_type & val, gs_param_array * parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const char * nam, const val_type & val, gs_param_array * parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (gs_param_array & parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const std::string & nam, gs_param_array & parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const char * nam, gs_param_array & parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const std::string & nam, const std::string & val, gs_param_array & parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const char * nam, const char * val, gs_param_array & parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const std::string & nam, const char * val, gs_param_array & parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const char * nam, const std::string & val, gs_param_array & parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const std::string & nam, const val_type & val, gs_param_array & parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const char * nam, const val_type & val, gs_param_array & parent_array, const bool force_top_level_name = false) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const std::string & nam, const std::string & val, gs_param_array * parent_array, const bool force_top_level_name, const bool register_at_db) inline explicit
References sr_param_t< T >::init().
sr_param< sc_core::sc_event >::sr_param (const std::string & nam, const std::string & val, gs_param_array & parent_array, const bool force_top_level_name, const bool register_at_db) inline explicit
References sr_param_t< T >::init().
virtual sr_param< sc_core::sc_event >::~sr_param () inline virtual
Member Function Documentation
void sr_param< sc_core::sc_event >::cancel () inline
References sr_param_t< T >::my_value.
std::string sr_param< sc_core::sc_event >::convertValueToString (const sc_core::sc_event & v) inline
convertValueToString(sc_logic)
std::string sr_param< sc_core::sc_event >::convertValueToString (const val_type & val) const inline virtual
Overloads sr_param_t<T>::convertValueToString.
Implements sr_param_t< sc_core::sc_event >.
const bool sr_param< sc_core::sc_event >::deserialize (val_type & target_val, const std::string & str) inline virtual
Deserialize for this parameter. To be implemented by the specialization.
Conversion string –> value type.
User implemented for each template specialization of gs_param: Do not write to target_val if deserialization fails!
Set target_val to the default value if str is empty (=="").
Do not use ANY member variables. Act as if the method is static.
Parameters
target_val Reference to the value that should be set.
str String that should be converted to a value.
Returns
If the convertion was successfull
Implements sr_param_t< sc_core::sc_event >.
References sr_param< T >::static_deserialize().
void sr_param< sc_core::sc_event >::eventthread (void) inline
References sr_param_t< T >::my_value.
gs::cnf::Param_type sr_param< sc_core::sc_event >::getType () const inline
Overloads sr_param_base::getType.
const std::string sr_param< sc_core::sc_event >::getTypeString () const inline
Overloads sr_param_base::getTypeString.
void sr_param< sc_core::sc_event >::init () inline
void sr_param< sc_core::sc_event >::notify () inline
void sr_param< sc_core::sc_event >::notify (const sc_time & t) inline
void sr_param< sc_core::sc_event >::notify (double d, sc_time_unit t) inline
static std::string sr_param< sc_core::sc_event >::static_convertValueToString (const val_type & val) inline static
static bool sr_param< sc_core::sc_event >::static_deserialize (val_type & target_val, const std::string & str) inline static
Static convertion function called by virtual deserialize and others (e.g. GCnf_API)
Member Data Documentation
val_type sr_param< sc_core::sc_event >::intern_event protected
The documentation for this class was generated from the following file:
core/common/sr_param/sr_param_systemc.h