SoCRocket: gs_config< sc_core::sc_attribute< T > > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
gs_config< sc_core::sc_attribute< T > > Class Template Reference
Template specialization for gs_config< sc_attribute<T> >.
#include <gs_config_sc_attribute.hpp>
Classes
struct wrapper
Wrapper class for value member.
Public Member Functions
gs_config (const std::string &sc_attrib_name)
Empty constructor. Name will be set in base.
gs_config (const std::string &sc_attrib_name, const std::string &nam)
Constructor with (local/hierarchical) name.
gs_config (const std::string &sc_attrib_name, const char *nam)
gs_config (const std::string &sc_attrib_name, const char *nam, const char *val, const bool force_top_level_name=false)
Constructor with (local/hierarchical) name and string representation of initial value.
gs_config (const std::string &sc_attrib_name, const std::string &nam, const char *val, const bool force_top_level_name=false)
gs_config (const std::string &sc_attrib_name, const std::string &nam, const std::string &val, const bool force_top_level_name=false)
gs_config (const std::string &sc_attrib_name, const char *nam, const std::string &val, const bool force_top_level_name=false)
gs_config (const std::string &sc_attrib_name, const std::string &nam, const T &val, const bool force_top_level_name=false)
Constructor with (local/hierarchical) name and initial value.
gs_config (const std::string &sc_attrib_name, const char *nam, const T &val, const bool force_top_level_name=false)
gs_config (const std::string &sc_attrib_name, gs_param_array *parent_array)
gs_config (const std::string &sc_attrib_name, const std::string &nam, gs_param_array *parent_array)
gs_config (const std::string &sc_attrib_name, const char *nam, gs_param_array *parent_array)
gs_config (const std::string &sc_attrib_name, const char *nam, const char *val, gs_param_array *parent_array)
gs_config (const std::string &sc_attrib_name, const std::string &nam, const char *val, gs_param_array *parent_array)
gs_config (const std::string &sc_attrib_name, const std::string &nam, const T &val, gs_param_array *parent_array)
gs_config (const std::string &sc_attrib_name, const char *nam, const T &val, gs_param_array *parent_array)
gs_config (const std::string &sc_attrib_name, const std::string &nam, const std::string &val, gs_param_array *parent_array)
gs_config (const std::string &sc_attrib_name, const char *nam, const std::string &val, gs_param_array *parent_array)
gs_config (const std::string &sc_attrib_name, gs_param_array &parent_array)
gs_config (const std::string &sc_attrib_name, const std::string &nam, gs_param_array &parent_array)
gs_config (const std::string &sc_attrib_name, const char *nam, gs_param_array &parent_array)
gs_config (const std::string &sc_attrib_name, const char *nam, const char *val, gs_param_array &parent_array)
gs_config (const std::string &sc_attrib_name, const std::string &nam, const char *val, gs_param_array &parent_array)
gs_config (const std::string &sc_attrib_name, const std::string &nam, const T &val, gs_param_array &parent_array)
gs_config (const std::string &sc_attrib_name, const char *nam, const T &val, gs_param_array &parent_array)
gs_config (const std::string &sc_attrib_name, const std::string &nam, const std::string &val, gs_param_array &parent_array)
gs_config (const std::string &sc_attrib_name, const char *nam, const std::string &val, gs_param_array &parent_array)
gs_config (const std::string &sc_attrib_name, const std::string &nam, const std::string &val, gs_param_array *parent_array, const bool force_top_level_name, const bool register_at_db)
gs_config (const std::string &sc_attrib_name, const std::string &nam, const std::string &val, gs_param_array &parent_array, const bool force_top_level_name, const bool register_at_db)
virtual void init (const T &default_val)
Init method to set the value and add the parameter to the plugin db.
virtual void init ()
Init method without value.
virtual ~gs_config ()
Destructor.
const std::string getTypeString () const
Overloads gs_config::getTypeString.
const Param_type getType () const
Overloads gs_config::getType.
std::string convertValueToString (const T &val) const
Overloads gs_config_t<T>::convertValueToString.
const bool deserialize (T &target_val, const std::string &str)
Overloads gs_config_t<T>::deserialize in gs_config_t<T>
my_type & operator= (const my_type &v)
Set the value of this parameter to the value of another gs_config.
my_type & operator= (const T &v)
Set the value of this parameter.
my_type & operator= (const val_type &v)
Set the value of this parameter.
operator const val_type & ()
Get the value of this parameter.
void setValue (const val_type &val)
Set the value of this parameter.
void setValue (const T &val)
Set the value of this parameter.
const val_type & getValue () const
Returns the value of this parameter.
const void * get_value_pointer () const
bool setString (const std::string &str)
Set the value of this parameter with a string.
const std::string & getString () const
Get the value of this parameter as a string.
Static Public Member Functions
static bool static_deserialize (T &target_val, const std::string &str)
Static convertion function called by virtual deserialize and others (e.g. GCnf_API)
Public Attributes
wrapper< T > value
Protected Types
typedef sc_core::sc_attribute< T > val_type
Typedef for the value.
typedef gs_config< val_type > my_type
Typedef for this specialized class.
Protected Member Functions
const T & convertStringToValue (const std::string &str)
Get the value the string. Needed for construction of gs_config.
Protected Attributes
val_type my_value
Value of this parameter.
std::string return_string
String whose reference can be returned as string value.
Detailed Description
template<typename T>
class gs_config< sc_core::sc_attribute< T > >
Template specialization for gs_config< sc_attribute<T> >.
Member Typedef Documentation
template<typename T > typedef gs_config<val_type> gs_config< sc_core::sc_attribute< T > >::my_type protected
Typedef for this specialized class.
template<typename T > typedef sc_core::sc_attribute<T> gs_config< sc_core::sc_attribute< T > >::val_type protected
Typedef for the value.
Constructor & Destructor Documentation
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name) inline explicit
Empty constructor. Name will be set in base.
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const std::string & nam) inline explicit
Constructor with (local/hierarchical) name.
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const char * nam) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const char * nam, const char * val, const bool force_top_level_name = false) inline explicit
Constructor with (local/hierarchical) name and string representation of initial value.
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const std::string & nam, const char * val, const bool force_top_level_name = false) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const std::string & nam, const std::string & val, const bool force_top_level_name = false) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const char * nam, const std::string & val, const bool force_top_level_name = false) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const std::string & nam, const T & val, const bool force_top_level_name = false) inline explicit
Constructor with (local/hierarchical) name and initial value.
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const char * nam, const T & val, const bool force_top_level_name = false) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const std::string & nam, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const char * nam, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const char * nam, const char * val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const std::string & nam, const char * val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const std::string & nam, const T & val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const char * nam, const T & val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const std::string & nam, const std::string & val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const char * nam, const std::string & val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const std::string & nam, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const char * nam, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const char * nam, const char * val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const std::string & nam, const char * val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const std::string & nam, const T & val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const char * nam, const T & val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const std::string & nam, const std::string & val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const char * nam, const std::string & val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const std::string & nam, const std::string & val, gs_param_array * parent_array, const bool force_top_level_name, const bool register_at_db) inline explicit
References core.waf.repo::init().
template<typename T > gs_config< sc_core::sc_attribute< T > >::gs_config (const std::string & sc_attrib_name, const std::string & nam, const std::string & val, gs_param_array & parent_array, const bool force_top_level_name, const bool register_at_db) inline explicit
References core.waf.repo::init().
template<typename T > virtual gs_config< sc_core::sc_attribute< T > >::~gs_config () inline virtual
Destructor.
Member Function Documentation
template<typename T > const T& gs_config< sc_core::sc_attribute< T > >::convertStringToValue (const std::string & str) inline protected
Get the value the string. Needed for construction of gs_config.
template<typename T > std::string gs_config< sc_core::sc_attribute< T > >::convertValueToString (const T & val) const inline
Overloads gs_config_t<T>::convertValueToString.
template<typename T > const bool gs_config< sc_core::sc_attribute< T > >::deserialize (T & target_val, const std::string & str) inline
Overloads gs_config_t<T>::deserialize in gs_config_t<T>
template<typename T > const void* gs_config< sc_core::sc_attribute< T > >::get_value_pointer () const inline
See also
gs::cnf::gs_config::get_value_pointer
template<typename T > const std::string& gs_config< sc_core::sc_attribute< T > >::getString () const inline
Get the value of this parameter as a string.
template<typename T > const Param_type gs_config< sc_core::sc_attribute< T > >::getType () const inline
Overloads gs_config::getType.
template<typename T > const std::string gs_config< sc_core::sc_attribute< T > >::getTypeString () const inline
Overloads gs_config::getTypeString.
template<typename T > const val_type& gs_config< sc_core::sc_attribute< T > >::getValue () const inline
Returns the value of this parameter.
template<typename T > virtual void gs_config< sc_core::sc_attribute< T > >::init (const T & default_val) inline virtual
Init method to set the value and add the parameter to the plugin db.
template<typename T > virtual void gs_config< sc_core::sc_attribute< T > >::init () inline virtual
Init method without value.
See also
gs::cnf::gs_config_t::init(T &default_val)
template<typename T > gs_config< sc_core::sc_attribute< T > >::operator const val_type & () inline
Get the value of this parameter.
template<typename T > my_type& gs_config< sc_core::sc_attribute< T > >::operator= (const my_type & v) inline
Set the value of this parameter to the value of another gs_config.
template<typename T > my_type& gs_config< sc_core::sc_attribute< T > >::operator= (const T & v) inline
Set the value of this parameter.
template<typename T > my_type& gs_config< sc_core::sc_attribute< T > >::operator= (const val_type & v) inline
Set the value of this parameter.
template<typename T > bool gs_config< sc_core::sc_attribute< T > >::setString (const std::string & str) inline
Set the value of this parameter with a string.
References success().
template<typename T > void gs_config< sc_core::sc_attribute< T > >::setValue (const val_type & val) inline
Set the value of this parameter.
template<typename T > void gs_config< sc_core::sc_attribute< T > >::setValue (const T & val) inline
Set the value of this parameter.
template<typename T > static bool gs_config< sc_core::sc_attribute< T > >::static_deserialize (T & target_val, const std::string & str) inline static
Static convertion function called by virtual deserialize and others (e.g. GCnf_API)
Member Data Documentation
template<typename T > val_type gs_config< sc_core::sc_attribute< T > >::my_value protected
Value of this parameter.
template<typename T > std::string gs_config< sc_core::sc_attribute< T > >::return_string mutable protected
String whose reference can be returned as string value.
template<typename T > wrapper<T> gs_config< sc_core::sc_attribute< T > >::value
Referenced by core.tools.generator.item.enum.IntegerItem::child(), core.tools.generator.item.integer.IntegerItem::child(), core.tools.generator.item.item.Item::data(), and core.tools.generator.item.item.Item::setValue().
The documentation for this class was generated from the following file:
core/common/gs_config/gs_config_sc_attribute.hpp