SoCRocket: leon3_funcat_trap::PinTLM_out_32 Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
leon3_funcat_trap::PinTLM_out_32 Class Reference
#include <externalPins.hpp>
Public Member Functions
SK_HAS_SIGNALS (PinTLM_out_32)
PinTLM_out_32 (sc_module_name portName)
void send_pin_req (const unsigned int &value) throw ()
void on_run (const bool &value, const sc_time &delay) throw ()
Public Attributes
signal< unsigned int >::out initSignal
signal< bool >::out status
signal< bool >::in run
bool stopped
Needed to halt the main processor loop.
sc_event start
Needed to start the main processor loop.
Constructor & Destructor Documentation
leon3_funcat_trap::PinTLM_out_32::PinTLM_out_32 (sc_module_name portName)
References initSignal, on_run(), run, status, and stopped.
Member Function Documentation
void leon3_funcat_trap::PinTLM_out_32::on_run (const bool & value, const sc_time & delay) throw ()
References v::debug, setup::name, and start().
Referenced by PinTLM_out_32().
void leon3_funcat_trap::PinTLM_out_32::send_pin_req (const unsigned int & value) throw ()
References v::debug, and setup::name.
leon3_funcat_trap::PinTLM_out_32::SK_HAS_SIGNALS (PinTLM_out_32)
Member Data Documentation
signal< unsigned int >::out leon3_funcat_trap::PinTLM_out_32::initSignal
Referenced by PinTLM_out_32().
signal<bool>::in leon3_funcat_trap::PinTLM_out_32::run
Will prepare the start of the processor. If set to 1 stoped will be false and the start notification will be sent.
Referenced by PinTLM_out_32().
sc_event leon3_funcat_trap::PinTLM_out_32::start
Needed to start the main processor loop.
signal<bool>::out leon3_funcat_trap::PinTLM_out_32::status
If the processor is stoped status will be true If it is running it will be false.
Referenced by PinTLM_out_32().
bool leon3_funcat_trap::PinTLM_out_32::stopped
Needed to halt the main processor loop.
Referenced by PinTLM_out_32().
The documentation for this class was generated from the following files:
core/models/extern/LEON3/simulatorSources/leon3.funcat/externalPins.hpp
core/models/extern/LEON3/simulatorSources/leon3.funcat/externalPins.cpp