SoCRocket: signalkit::signal_out< TYPE, MODULE > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
signalkit::signal_out< TYPE, MODULE > Class Template Reference
Signalkit
#include <out.h>
Public Member Functions
signal_out (sc_core::sc_module_name mn=NULL)
virtual ~signal_out ()
Virtual destructor.
virtual signal_out_bind_if
< TYPE > * bind (signal_in_if< TYPE > &receiver, const uint32_t &channel=0)
virtual void write (const TYPE &value, const sc_core::sc_time &time=sc_core::SC_ZERO_TIME)
void operator() (signal_in_if< TYPE > &receiver)
TYPE operator= (const TYPE &t)
Set the value and call updates on all receivern.
TYPE operator= (const signal_if< TYPE > &t)
Sets the value from another signal.
Public Member Functions inherited from signalkit::signal_base< TYPE, MODULE >
signal_base (sc_core::sc_module_name mn=NULL)
Default constructor.
virtual ~signal_base ()
Public Member Functions inherited from signalkit::signal_out_if< TYPE >
virtual ~signal_out_if ()
Virtual destructor.
Public Member Functions inherited from signalkit::signal_if< TYPE >
virtual ~signal_if ()
Virtual destructor.
virtual const TYPE & read ()
Read the current signal value.
operator TYPE () const
Call operator to get the current signal value.
bool operator== (const TYPE &t) const
Comparing the current signal value with a variable of the same type TYPE.
Public Member Functions inherited from signalkit::signal_out_bind_if< TYPE >
virtual ~signal_out_bind_if ()
Virtual destructor.
Protected Types
typedef std::vector
< signal_in_if< TYPE > * > t_receiver
Type of a list of receivers.
Protected Attributes
t_receiver m_receiver
List of receivers.
Protected Attributes inherited from signalkit::signal_if< TYPE >
TYPE m_value
The signal value.
Additional Inherited Members
Protected Member Functions inherited from signalkit::signal_base< TYPE, MODULE >
virtual MODULE * get_module ()
Detailed Description
template<class TYPE, class MODULE>
class signalkit::signal_out< TYPE, MODULE >
Signalkit output signal. This class implements a TLM Signal abstraction of an outgoing signal. The signal stores the value and triggers the update function of all receivers.
Member Typedef Documentation
template<class TYPE, class MODULE> typedef std::vector<signal_in_if<TYPE> *> signalkit::signal_out< TYPE, MODULE >::t_receiver protected
Type of a list of receivers.
Constructor & Destructor Documentation
template<class TYPE, class MODULE> signalkit::signal_out< TYPE, MODULE >::signal_out (sc_core::sc_module_name mn = NULL) inline
Constructor
Parameters
mn Signal name.
template<class TYPE, class MODULE> virtual signalkit::signal_out< TYPE, MODULE >::~signal_out () inline virtual
Virtual destructor.
Member Function Documentation
template<class TYPE, class MODULE> virtual signal_out_bind_if<TYPE>* signalkit::signal_out< TYPE, MODULE >::bind (signal_in_if< TYPE > & receiver, const uint32_t & channel = 0) inline virtual
Output signal bind method. This method implements the binding mechanism with an input signal.
Parameters
receiver Input interface to bind with.
channel The channel which has to be bind.
Implements signalkit::signal_out_bind_if< TYPE >.
References signalkit::signal_out< TYPE, MODULE >::m_receiver.
Referenced by signalkit::signal_selector< TYPE, MODULE >::bind(), signalkit::connect(), and signalkit::signal_out< TYPE, MODULE >::operator()().
template<class TYPE, class MODULE> void signalkit::signal_out< TYPE, MODULE >::operator() (signal_in_if< TYPE > & receiver) inline
Connecting the Signal with an input signal. Calls caller and receiver bind methods.
Parameters
receiver The input signal to connect with.
References signalkit::signal_out< TYPE, MODULE >::bind(), and signalkit::signal_in_if< TYPE >::bind().
template<class TYPE, class MODULE> TYPE signalkit::signal_out< TYPE, MODULE >::operator= (const TYPE & t) inline virtual
Set the value and call updates on all receivern.
Reimplemented from signalkit::signal_out_if< TYPE >.
References signalkit::signal_if< TYPE >::m_value, and signalkit::signal_out< TYPE, MODULE >::write().
template<class TYPE, class MODULE> TYPE signalkit::signal_out< TYPE, MODULE >::operator= (const signal_if< TYPE > & t) inline virtual
Sets the value from another signal.
Reimplemented from signalkit::signal_out_if< TYPE >.
References signalkit::signal_if< TYPE >::m_value, and signalkit::signal_out< TYPE, MODULE >::write().
template<class TYPE, class MODULE> virtual void signalkit::signal_out< TYPE, MODULE >::write (const TYPE & value, const sc_core::sc_time & time = sc_core::SC_ZERO_TIME) inline virtual
Write the value of a signal. Stores the value and triggers an update in all receivers.
Parameters
value The new value of the signal.
time The delay from sc_timestamp() at propagation.
Implements signalkit::signal_out_if< TYPE >.
References signalkit::signal_out< TYPE, MODULE >::m_receiver, and signalkit::signal_if< TYPE >::m_value.
Referenced by signalkit::signal_out< TYPE, MODULE >::operator=(), and sc_main().
Member Data Documentation
template<class TYPE, class MODULE> t_receiver signalkit::signal_out< TYPE, MODULE >::m_receiver protected
List of receivers.
Referenced by signalkit::signal_out< TYPE, MODULE >::bind(), and signalkit::signal_out< TYPE, MODULE >::write().
The documentation for this class was generated from the following file:
core/common/signalkit_h/out.h