SoCRocket: USIBaseDelegate Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
USIBaseDelegate Class Reference
#include <delegate.h>
Public Member Functions
const char * name ()
Returns the full name of the corresponding sc_object or gs_param.
const char * basename ()
Returns the name of the corresponding sc_object or gs_param.
const char * kind ()
Returns the kind of an sc_object.
size_t id ()
sc_core::sc_object * parent ()
Returns the hierachial parent of the sc_object.
std::vector< sc_core::sc_object * > children ()
Returns a list of children of the sc_object.
USIBaseDelegate ()
USIBaseDelegate (sc_core::sc_object *obj)
Detailed Description
Base delegate implements the core sc_object functionality This allows every interface to use sc_object like a primitive
Constructor & Destructor Documentation
USIBaseDelegate::USIBaseDelegate () inline
Default constructor because SWIG needs it Please never use! It will not be bound to any sc_object and therefore worthless
USIBaseDelegate::USIBaseDelegate (sc_core::sc_object * obj) inline
Constructor. The constructor takes an sc_object as parameter. It will bind to the sc_object.
Parameters
obj sc_object to bind to.
Member Function Documentation
const char* USIBaseDelegate::basename () inline
Returns the name of the corresponding sc_object or gs_param.
References offset, and parent().
std::vector<sc_core::sc_object *> USIBaseDelegate::children () inline
Returns a list of children of the sc_object.
size_t USIBaseDelegate::id () inline
const char* USIBaseDelegate::kind () inline
Returns the kind of an sc_object.
const char* USIBaseDelegate::name () inline
Returns the full name of the corresponding sc_object or gs_param.
Referenced by core.tools.generator.item.enum.IntegerItem::load(), and usi.SCCommand::register().
sc_core::sc_object* USIBaseDelegate::parent () inline
Returns the hierachial parent of the sc_object.
Referenced by basename().
The documentation for this class was generated from the following file:
pysc/usi/core/delegate.h