SoCRocket: mmu_cache_if Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
mmu_cache_if Class Reference
MMU_Cache
#include <mmu_cache_if.h>
Public Member Functions
virtual void set_irq (uint32_t tt)
virtual void trigger_exception (unsigned int exception)
virtual unsigned int read_ccr (bool internal)
virtual void write_ccr (unsigned char *data, unsigned int len, sc_core::sc_time *delay, unsigned int *debug, bool is_dbg)
virtual ~mmu_cache_if ()
Public Member Functions inherited from mem_if
virtual void mem_write (unsigned int addr, unsigned int asi, unsigned char *data, unsigned int length, sc_core::sc_time *t, unsigned int *debug, bool is_dbg, bool &cacheable, bool is_lock=false)
virtual bool mem_read (unsigned int addr, unsigned int asi, unsigned char *data, unsigned int length, sc_core::sc_time *t, unsigned int *debug, bool is_dbg, bool &cacheable, bool is_lock=false)
virtual ~mem_if ()
Constructor & Destructor Documentation
virtual mmu_cache_if::~mmu_cache_if () inline virtual
Member Function Documentation
virtual unsigned int mmu_cache_if::read_ccr (bool internal) inline virtual
Reimplemented in mmu_cache_base.
Referenced by dvectorcache::check_mode(), ivectorcache::check_mode(), and vectorcache::mem_read().
virtual void mmu_cache_if::set_irq (uint32_t tt) inline virtual
Reimplemented in mmu_cache_base.
virtual void mmu_cache_if::trigger_exception (unsigned int exception) inline virtual
Reimplemented in mmu_cache_base, and Leon3.
Referenced by mmu::tlb_lookup().
virtual void mmu_cache_if::write_ccr (unsigned char * data, unsigned int len, sc_core::sc_time * delay, unsigned int * debug, bool is_dbg) inline virtual
Reimplemented in mmu_cache_base.
The documentation for this class was generated from the following file:
gaisler/leon3/mmucache/mmu_cache_if.h