SoCRocket: msclogger Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
msclogger Class Reference
Common
#include <msclogger.h>
Public Types
typedef tlm::tlm_generic_payload payload_t
typedef
gs::socket::bindability_base
< tlm::tlm_base_protocol_types > socket_t
Static Public Member Functions
static void msc_start (const char *filename, const char *nodes)
static void msc_end ()
static void forward (sc_core::sc_object *from, amba::amba_master_socket< 32 > *ahb, tlm::tlm_generic_payload *trans, tlm::tlm_phase phase, sc_core::sc_time delay=SC_ZERO_TIME)
static void forward (sc_core::sc_object *from, amba::amba_master_socket< 32, 0 > *ahb, tlm::tlm_generic_payload *trans, tlm::tlm_phase phase, sc_core::sc_time delay=SC_ZERO_TIME, uint32_t binding=0)
static void backward (sc_core::sc_object *from, amba::amba_slave_socket< 32 > *ahb, tlm::tlm_generic_payload *trans, tlm::tlm_phase phase, sc_core::sc_time delay=SC_ZERO_TIME)
static void backward (sc_core::sc_object *from, amba::amba_slave_socket< 32, 0 > *ahb, tlm::tlm_generic_payload *trans, tlm::tlm_phase phase, sc_core::sc_time delay=SC_ZERO_TIME, uint32_t binding=0)
static void return_forward (sc_core::sc_object *from, amba::amba_master_socket< 32 > *ahb, tlm::tlm_generic_payload *trans, tlm::tlm_sync_enum status, sc_core::sc_time delay=SC_ZERO_TIME)
static void return_forward (sc_core::sc_object *from, amba::amba_master_socket< 32, 0 > *ahb, tlm::tlm_generic_payload *trans, tlm::tlm_sync_enum status, sc_core::sc_time delay=SC_ZERO_TIME, uint32_t binding=0)
static void return_backward (sc_core::sc_object *from, amba::amba_slave_socket< 32 > *ahb, tlm::tlm_generic_payload *trans, tlm::tlm_sync_enum status, sc_core::sc_time delay=SC_ZERO_TIME)
static void return_backward (sc_core::sc_object *from, amba::amba_slave_socket< 32, 0 > *ahb, tlm::tlm_generic_payload *trans, tlm::tlm_sync_enum status, sc_core::sc_time delay=SC_ZERO_TIME, uint32_t binding=0)
Member Typedef Documentation
typedef tlm::tlm_generic_payload msclogger::payload_t
typedef gs::socket::bindability_base<tlm::tlm_base_protocol_types> msclogger::socket_t
Member Function Documentation
static void msclogger::backward (sc_core::sc_object * from, amba::amba_slave_socket< 32 > * ahb, tlm::tlm_generic_payload * trans, tlm::tlm_phase phase, sc_core::sc_time delay = SC_ZERO_TIME) inline static
References msc, and trans.
Referenced by AHBCtrl::RequestThread(), and AHBCtrl::ResponseThread().
static void msclogger::backward (sc_core::sc_object * from, amba::amba_slave_socket< 32, 0 > * ahb, tlm::tlm_generic_payload * trans, tlm::tlm_phase phase, sc_core::sc_time delay = SC_ZERO_TIME, uint32_t binding = 0) inline static
References msc, and trans.
static void msclogger::forward (sc_core::sc_object * from, amba::amba_master_socket< 32 > * ahb, tlm::tlm_generic_payload * trans, tlm::tlm_phase phase, sc_core::sc_time delay = SC_ZERO_TIME) inline static
References msc, and trans.
Referenced by AHBCtrl::arbitrate(), and AHBCtrl::EndResponseThread().
static void msclogger::forward (sc_core::sc_object * from, amba::amba_master_socket< 32, 0 > * ahb, tlm::tlm_generic_payload * trans, tlm::tlm_phase phase, sc_core::sc_time delay = SC_ZERO_TIME, uint32_t binding = 0) inline static
References msc, and trans.
static void msclogger::msc_end () inline static
References msc.
static void msclogger::msc_start (const char * filename, const char * nodes) inline static
References msc.
static void msclogger::return_backward (sc_core::sc_object * from, amba::amba_slave_socket< 32 > * ahb, tlm::tlm_generic_payload * trans, tlm::tlm_sync_enum status, sc_core::sc_time delay = SC_ZERO_TIME) inline static
References msc, and trans.
Referenced by AHBCtrl::b_transport(), and AHBCtrl::nb_transport_fw().
static void msclogger::return_backward (sc_core::sc_object * from, amba::amba_slave_socket< 32, 0 > * ahb, tlm::tlm_generic_payload * trans, tlm::tlm_sync_enum status, sc_core::sc_time delay = SC_ZERO_TIME, uint32_t binding = 0) inline static
References msc, and trans.
static void msclogger::return_forward (sc_core::sc_object * from, amba::amba_master_socket< 32 > * ahb, tlm::tlm_generic_payload * trans, tlm::tlm_sync_enum status, sc_core::sc_time delay = SC_ZERO_TIME) inline static
References msc, and trans.
Referenced by AHBCtrl::nb_transport_bw().
static void msclogger::return_forward (sc_core::sc_object * from, amba::amba_master_socket< 32, 0 > * ahb, tlm::tlm_generic_payload * trans, tlm::tlm_sync_enum status, sc_core::sc_time delay = SC_ZERO_TIME, uint32_t binding = 0) inline static
References msc, and trans.
The documentation for this class was generated from the following file:
core/common/msclogger.h