SoCRocket: gs_config< std::string > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
gs_config< std::string > Class Template Reference
Template specialization for gs_config<std::string>.
#include <gs_config_native_.hpp>
Public Member Functions
gs_config ()
Empty constructor. Name will be set in base.
gs_config (const std::string &nam)
Constructor with (local/hierarchical) name.
gs_config (const char *nam)
gs_config (const std::string &nam, const std::string &val, const bool force_top_level_name=false)
Constructor with (local/hierarchical) name and string representation of initial value.
gs_config (const char *nam, const char *val, const bool force_top_level_name=false)
gs_config (const std::string &nam, const char *val, const bool force_top_level_name=false)
gs_config (const char *nam, const std::string &val, const bool force_top_level_name=false)
gs_config (gs_param_array *parent_array)
gs_config (const std::string &nam, gs_param_array *parent_array)
gs_config (const char *nam, gs_param_array *parent_array)
gs_config (const std::string &nam, const std::string &val, gs_param_array *parent_array)
gs_config (const char *nam, const char *val, gs_param_array *parent_array)
gs_config (const std::string &nam, const char *val, gs_param_array *parent_array)
gs_config (const char *nam, const std::string &val, gs_param_array *parent_array)
gs_config (gs_param_array &parent_array)
gs_config (const std::string &nam, gs_param_array &parent_array)
gs_config (const char *nam, gs_param_array &parent_array)
gs_config (const std::string &nam, const std::string &val, gs_param_array &parent_array)
gs_config (const char *nam, const char *val, gs_param_array &parent_array)
gs_config (const std::string &nam, const char *val, gs_param_array &parent_array)
gs_config (const char *nam, const std::string &val, gs_param_array &parent_array)
gs_config (const std::string &nam, const std::string &val, gs_param_array *parent_array, const bool force_top_level_name, const bool register_at_db)
gs_config (const std::string &nam, const std::string &val, gs_param_array &parent_array, const bool force_top_level_name, const bool register_at_db)
const val_type convertStringToValue (const std::string &str)
void serialize (const val_type &val)
const bool deserialize (val_type &target_val, const std::string &str)
Overloads gs_config_t<T>::deserialize in gs_config_t<T>
my_type & operator= (const char *v)
Set the value of this parameter with char.
~gs_config ()
Desctructor.
const std::string getTypeString () const
Overloads gs_config::getTypeString.
const Param_type getType () const
Overloads gs_config::getType.
std::string convertValueToString (const val_type &val) const
Overloads gs_config_t<T>::convertValueToString.
gs_param ()
Empty constructor. Name will be set in base.
gs_param (const std::string &nam)
Constructor with (local/hierarchical) name.
gs_param (const char *nam)
gs_param (const std::string &nam, const std::string &val, const bool force_top_level_name=false)
Constructor with (local/hierarchical) name and string representation of initial value.
gs_param (const char *nam, const char *val, const bool force_top_level_name=false)
gs_param (const std::string &nam, const char *val, const bool force_top_level_name=false)
gs_param (const char *nam, const std::string &val, const bool force_top_level_name=false)
gs_param (gs_param_array *parent_array)
gs_param (const std::string &nam, gs_param_array *parent_array)
gs_param (const char *nam, gs_param_array *parent_array)
gs_param (const std::string &nam, const std::string &val, gs_param_array *parent_array)
gs_param (const char *nam, const char *val, gs_param_array *parent_array)
gs_param (const std::string &nam, const char *val, gs_param_array *parent_array)
gs_param (const char *nam, const std::string &val, gs_param_array *parent_array)
gs_param (gs_param_array &parent_array)
gs_param (const std::string &nam, gs_param_array &parent_array)
gs_param (const char *nam, gs_param_array &parent_array)
gs_param (const std::string &nam, const std::string &val, gs_param_array &parent_array)
gs_param (const char *nam, const char *val, gs_param_array &parent_array)
gs_param (const std::string &nam, const char *val, gs_param_array &parent_array)
gs_param (const char *nam, const std::string &val, gs_param_array &parent_array)
gs_param (const std::string &nam, const std::string &val, gs_param_array *parent_array, const bool force_top_level_name, const bool register_at_db)
gs_param (const std::string &nam, const std::string &val, gs_param_array &parent_array, const bool force_top_level_name, const bool register_at_db)
const val_type convertStringToValue (const std::string &str)
void serialize (const val_type &val)
const bool deserialize (val_type &target_val, const std::string &str)
Overloads gs_param_t<T>::deserialize in gs_param_t<T>
my_type & operator= (const char *v)
Set the value of this parameter with char.
~gs_param ()
Desctructor.
const std::string getTypeString () const
Overloads gs_param_base::getTypeString.
const Param_type getType () const
Overloads gs_param_base::getType.
std::string convertValueToString (const val_type &val) const
Overloads gs_param_t<T>::convertValueToString.
Public Member Functions inherited from gs::cnf::gs_config_t< std::string >
my_type & operator+= (val_type)
my_type & operator-= (val_type)
my_type & operator/= (val_type)
my_type & operator*= (val_type)
val_type operator+ (val_type)
val_type operator- (val_type)
val_type operator/ (val_type)
val_type operator* (val_type)
my_type & operator%= (val_type)
my_type & operator^= (val_type)
my_type & operator&= (val_type)
my_type & operator|= (val_type)
my_type & operator<<= (val_type)
my_type & operator>>= (val_type)
my_type & operator-- ()
val_type operator-- (int)
my_type & operator++ ()
val_type operator++ (int)
gs_config_t ()
Empty constructor. Name will be set in base. Avoid using it! You MUST call init() after instantiation!
gs_config_t (const bool force_top_level_name, gs_param_array *parent_array, const bool register_at_db)
Constructor with the special parameters. Name will be set in base. Avoid using it! You MUST call init() after instantiation!
gs_config_t (const std::string &nam)
Constructor with (local or hierarchical) name. You MUST call init() after instantiation!
gs_config_t (const std::string &nam, const bool force_top_level_name, gs_param_array *parent_array, const bool register_at_db)
Constructor with (local or hierarchical) name and special parameters. You MUST call init() after instantiation!
void init (const val_type &default_val)
Init method to set the value and add the parameter to the plugin db.
void init ()
Init method without value.
virtual ~gs_config_t ()
Destructor.
my_type & operator= (const my_type &v)
Set the value of this parameter to the value of another gs_param.
my_type & operator= (const val_type &v)
Set the value of this parameter.
operator const val_type & () const
Get the value of this parameter.
void setValue (const val_type &val)
Set the value of this parameter.
const val_type & getValue () const
Returns the value of this parameter.
const void * get_value_pointer () const
bool setString (const std::string &str)
Set the value of this parameter with a string.
const std::string & getString () const
Get the value of this parameter as a string.
void mirror (std::string &original)
Serialize this parameter.
void mirror (gs_config_t< std::string > &original)
Public Member Functions inherited from gs::cnf::gs_config_base
gs_config_base (const std::string &n, const bool register_at_db=true, gs_param_array *parent_array=NULL, const bool force_top_level_name=false)
void setProperty (std::string key, std::string value)
std::string getProperty (std::string key)
std::map< std::string,
std::string > getProperties ()
void deleteProperty (std::string key)
bool exists (std::string key)
easy_init add_properties ()
Static Public Member Functions
static std::string static_convertValueToString (const val_type &val)
static bool static_deserialize (val_type &target_val, const std::string &str)
Static convertion function called by virtual deserialize and others (e.g. GCnf_API)
static std::string static_convertValueToString (const val_type &val)
static bool static_deserialize (val_type &target_val, const std::string &str)
Static convertion function called by virtual deserialize and others (e.g. GCnf_API)
Public Attributes
GS_CONFIG_DELEGATE
Protected Types
typedef gs_config< std::string > my_type
Typedef for this specialized class.
typedef std::string val_type
Typedef for the value.
typedef gs_param< std::string > my_type
Typedef for this specialized class.
typedef std::string val_type
Typedef for the value.
Additional Inherited Members
Protected Member Functions inherited from gs::cnf::gs_config_t< std::string >
gs::cnf::callback_return_type mirror_callback (gs::gs_param_base &changed_param, gs::cnf::callback_type reason)
const val_type & convertStringToValue (const std::string &str)
Get the value the string. Needed for construction of gs_param.
Protected Attributes inherited from gs::cnf::gs_config_t< std::string >
val_type my_value
Value of this parameter.
std::string return_string
String whose reference can be returned as string value.
gs_config_t< std::string > * m_mirror_param
std::string * m_mirror_val
Detailed Description
template<>
class gs_config< std::string >
Template specialization for gs_config<std::string>.
Template specialization for gs_param<std::string>.
Member Typedef Documentation
typedef gs_param<std::string> gs_config< std::string >::my_type protected
Typedef for this specialized class.
typedef gs_config<std::string> gs_config< std::string >::my_type protected
Typedef for this specialized class.
typedef std::string gs_config< std::string >::val_type protected
Typedef for the value.
typedef std::string gs_config< std::string >::val_type protected
Typedef for the value.
Constructor & Destructor Documentation
gs_config< std::string >::gs_config () inline explicit
Empty constructor. Name will be set in base.
References core.waf.repo::init().
gs_config< std::string >::gs_config (const std::string & nam) inline explicit
Constructor with (local/hierarchical) name.
References core.waf.repo::init().
gs_config< std::string >::gs_config (const char * nam) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (const std::string & nam, const std::string & val, const bool force_top_level_name = false) inline explicit
Constructor with (local/hierarchical) name and string representation of initial value.
References core.waf.repo::init().
gs_config< std::string >::gs_config (const char * nam, const char * val, const bool force_top_level_name = false) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (const std::string & nam, const char * val, const bool force_top_level_name = false) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (const char * nam, const std::string & val, const bool force_top_level_name = false) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (const std::string & nam, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (const char * nam, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (const std::string & nam, const std::string & val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (const char * nam, const char * val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (const std::string & nam, const char * val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (const char * nam, const std::string & val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (const std::string & nam, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (const char * nam, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (const std::string & nam, const std::string & val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (const char * nam, const char * val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (const std::string & nam, const char * val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (const char * nam, const std::string & val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (const std::string & nam, const std::string & val, gs_param_array * parent_array, const bool force_top_level_name, const bool register_at_db) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_config (const std::string & nam, const std::string & val, gs_param_array & parent_array, const bool force_top_level_name, const bool register_at_db) inline explicit
References core.waf.repo::init().
gs_config< std::string >::~gs_config () inline
Desctructor.
gs_config< std::string >::~gs_param () inline
Desctructor.
Member Function Documentation
const val_type gs_config< std::string >::convertStringToValue (const std::string & str) inline
const val_type gs_config< std::string >::convertStringToValue (const std::string & str) inline
std::string gs_config< std::string >::convertValueToString (const val_type & val) const inline virtual
Overloads gs_param_t<T>::convertValueToString.
Implements gs::cnf::gs_config_t< std::string >.
std::string gs_config< std::string >::convertValueToString (const val_type & val) const inline virtual
Overloads gs_config_t<T>::convertValueToString.
Implements gs::cnf::gs_config_t< std::string >.
const bool gs_config< std::string >::deserialize (val_type & target_val, const std::string & str) inline virtual
Overloads gs_param_t<T>::deserialize in gs_param_t<T>
Implements gs::cnf::gs_config_t< std::string >.
const bool gs_config< std::string >::deserialize (val_type & target_val, const std::string & str) inline virtual
Overloads gs_config_t<T>::deserialize in gs_config_t<T>
Implements gs::cnf::gs_config_t< std::string >.
const Param_type gs_config< std::string >::getType () const inline
Overloads gs_param_base::getType.
const Param_type gs_config< std::string >::getType () const inline
Overloads gs_config::getType.
const std::string gs_config< std::string >::getTypeString () const inline
Overloads gs_param_base::getTypeString.
const std::string gs_config< std::string >::getTypeString () const inline
Overloads gs_config::getTypeString.
gs_config< std::string >::gs_param () inline explicit
Empty constructor. Name will be set in base.
References core.waf.repo::init().
gs_config< std::string >::gs_param (const std::string & nam) inline explicit
Constructor with (local/hierarchical) name.
References core.waf.repo::init().
gs_config< std::string >::gs_param (const char * nam) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (const std::string & nam, const std::string & val, const bool force_top_level_name = false) inline explicit
Constructor with (local/hierarchical) name and string representation of initial value.
References core.waf.repo::init().
gs_config< std::string >::gs_param (const char * nam, const char * val, const bool force_top_level_name = false) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (const std::string & nam, const char * val, const bool force_top_level_name = false) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (const char * nam, const std::string & val, const bool force_top_level_name = false) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (const std::string & nam, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (const char * nam, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (const std::string & nam, const std::string & val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (const char * nam, const char * val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (const std::string & nam, const char * val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (const char * nam, const std::string & val, gs_param_array * parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (const std::string & nam, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (const char * nam, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (const std::string & nam, const std::string & val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (const char * nam, const char * val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (const std::string & nam, const char * val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (const char * nam, const std::string & val, gs_param_array & parent_array) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (const std::string & nam, const std::string & val, gs_param_array * parent_array, const bool force_top_level_name, const bool register_at_db) inline explicit
References core.waf.repo::init().
gs_config< std::string >::gs_param (const std::string & nam, const std::string & val, gs_param_array & parent_array, const bool force_top_level_name, const bool register_at_db) inline explicit
References core.waf.repo::init().
my_type& gs_config< std::string >::operator= (const char * v) inline
Set the value of this parameter with char.
Parameters
v Char value which has to be set.
Returns
Pointer to this.
my_type& gs_config< std::string >::operator= (const char * v) inline
Set the value of this parameter with char.
Parameters
v Char value which has to be set.
Returns
Pointer to this.
void gs_config< std::string >::serialize (const val_type & val) inline
void gs_config< std::string >::serialize (const val_type & val) inline
static std::string gs_config< std::string >::static_convertValueToString (const val_type & val) inline static
static std::string gs_config< std::string >::static_convertValueToString (const val_type & val) inline static
static bool gs_config< std::string >::static_deserialize (val_type & target_val, const std::string & str) inline static
Static convertion function called by virtual deserialize and others (e.g. GCnf_API)
static bool gs_config< std::string >::static_deserialize (val_type & target_val, const std::string & str) inline static
Static convertion function called by virtual deserialize and others (e.g. GCnf_API)
Member Data Documentation
gs_config< std::string >::GS_CONFIG_DELEGATE
The documentation for this class was generated from the following files:
core/common/gs_config/gs_config_native.hpp
core/common/gs_config/gs_config_native_.hpp