SoCRocket: signalkit::signal_out_bind_if< TYPE > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
signalkit::signal_out_bind_if< TYPE > Class Template Reference abstract
Signalkit
#include <ifs.h>
Public Member Functions
virtual ~signal_out_bind_if ()
Virtual destructor.
virtual signal_out_bind_if
< TYPE > * bind (signal_in_if< TYPE > &t, const unsigned int &channel=0)=0
Detailed Description
template<class TYPE>
class signalkit::signal_out_bind_if< TYPE >
Signal output bind interface. This interface implements the bind functionality of an output signal. It's seperated from the signal output interface due to a second need in the selector signal. The selector has to implement the same bind interface but only a subclass implements the output interface for each channel.
See also
selector
Constructor & Destructor Documentation
template<class TYPE> virtual signalkit::signal_out_bind_if< TYPE >::~signal_out_bind_if () inline virtual
Virtual destructor.
Member Function Documentation
template<class TYPE> virtual signal_out_bind_if<TYPE>* signalkit::signal_out_bind_if< TYPE >::bind (signal_in_if< TYPE > & t, const unsigned int & channel = 0) pure virtual
Abstract bind method interface. This method has to be implemented by each output signal to make it bind with an input.
Parameters
t Input interface to bind with.
channel The channel which has to be bind.
Implemented in signalkit::signal_selector< TYPE, MODULE >, and signalkit::signal_out< TYPE, MODULE >.
Referenced by signalkit::connect(), signalkit::signal_in< TYPE, MODULE >::operator()(), and signalkit::signal_infield< TYPE, MODULE >::operator()().
The documentation for this class was generated from the following file:
core/common/signalkit_h/ifs.h