SoCRocket: trap::GDBStub< issueWidth > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
trap::GDBStub< issueWidth > Class Template Reference
#include <GDBStub.hpp>
Public Member Functions
SC_HAS_PROCESS (GDBStub)
GDBStub (ABIIf< issueWidth > &processorInstance)
void pauseMethod ()
Method used to pause simulation.
void end_of_simulation ()
void initialize (unsigned int port=1500)
Starts the connection with the GDB client.
bool newIssue (const issueWidth &curPC, const InstructionBase *curInstr) throw ()
Method called at every cycle from the processor's main loop.
bool emptyPipeline (const issueWidth &curPC) const throw ()
void notifyAddress (issueWidth address, unsigned int size) throw ()
Method called whenever a particular address is written into memory.
Public Member Functions inherited from trap::ToolsIf< issueWidth >
virtual ~ToolsIf ()
Public Member Functions inherited from trap::MemoryToolsIf< issueWidth >
virtual ~MemoryToolsIf ()
Public Attributes
bool simulationPaused
Constructor & Destructor Documentation
template<class issueWidth> trap::GDBStub< issueWidth >::GDBStub (ABIIf< issueWidth > & processorInstance) inline
Member Function Documentation
template<class issueWidth> bool trap::GDBStub< issueWidth >::emptyPipeline (const issueWidth & curPC) const throw () inline virtual
The debugger needs the pipeline to be empty only in case it is going to be stopped because, for exmple, we hitted a breakpoint or we are in step mode
Implements trap::ToolsIf< issueWidth >.
template<class issueWidth> void trap::GDBStub< issueWidth >::end_of_simulation () inline
Overloading of the end_of_simulation method; it can be used to execute methods at the end of the simulation
template<class issueWidth> void trap::GDBStub< issueWidth >::initialize (unsigned int port = 1500) inline
Starts the connection with the GDB client.
Referenced by sc_main().
template<class issueWidth> bool trap::GDBStub< issueWidth >::newIssue (const issueWidth & curPC, const InstructionBase * curInstr) throw () inline virtual
Method called at every cycle from the processor's main loop.
Implements trap::ToolsIf< issueWidth >.
template<class issueWidth> void trap::GDBStub< issueWidth >::notifyAddress (issueWidth address, unsigned int size) throw () inline virtual
Method called whenever a particular address is written into memory.
Implements trap::MemoryToolsIf< issueWidth >.
Referenced by trap::GDBStub< unsigned int >::notifyAddress().
template<class issueWidth> void trap::GDBStub< issueWidth >::pauseMethod () inline
Method used to pause simulation.
Referenced by trap::GDBStub< unsigned int >::GDBStub().
template<class issueWidth> trap::GDBStub< issueWidth >::SC_HAS_PROCESS (GDBStub< issueWidth >)
Member Data Documentation
template<class issueWidth> bool trap::GDBStub< issueWidth >::simulationPaused
Referenced by stopSimFunction().
The documentation for this class was generated from the following file:
core/common/trapgen/debugger/GDBStub.hpp