SoCRocket: gs::cnf::gs_config_base Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
gs::cnf::gs_config_base Class Reference
Common
#include <gs_config.h>
Classes
class easy_init
Public Member Functions
gs_config_base (const std::string &n, const bool register_at_db=true, gs_param_array *parent_array=NULL, const bool force_top_level_name=false)
void setProperty (std::string key, std::string value)
std::string getProperty (std::string key)
std::map< std::string,
std::string > getProperties ()
void deleteProperty (std::string key)
bool exists (std::string key)
easy_init add_properties ()
Constructor & Destructor Documentation
gs::cnf::gs_config_base::gs_config_base (const std::string & n, const bool register_at_db = true, gs_param_array * parent_array = NULL, const bool force_top_level_name = false) inline explicit
Member Function Documentation
easy_init gs::cnf::gs_config_base::add_properties () inline
Referenced by AHBMem::init_generics(), APBCtrl::init_generics(), Mctrl::init_generics(), GPTimer::init_generics(), and AHBCtrl::init_generics().
void gs::cnf::gs_config_base::deleteProperty (std::string key) inline
bool gs::cnf::gs_config_base::exists (std::string key) inline
std::map<std::string, std::string> gs::cnf::gs_config_base::getProperties () inline
Referenced by paramprinter::printConfigs().
std::string gs::cnf::gs_config_base::getProperty (std::string key) inline
void gs::cnf::gs_config_base::setProperty (std::string key, std::string value) inline
Referenced by gs::cnf::gs_config_t< sc_dt::sc_uint< W > >::init(), gs::cnf::gs_config_t< sc_dt::sc_uint< W > >::mirror(), and gs::cnf::gs_config_base::easy_init::operator()().
The documentation for this class was generated from the following file:
core/common/gs_config/gs_config.h