SoCRocket: sr_signal::signal_infield< TYPE, MODULE > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
sr_signal::signal_infield< TYPE, MODULE > Class Template Reference
Sr_signal
#include <sr_signal_infield.h>
Public Types
typedef void(MODULE::* t_callback)(const TYPE &value, const uint32_t &channel, const sc_core::sc_time &time)
Public Member Functions
signal_infield (sc_core::sc_module_name mn=NULL)
signal_infield (t_callback callback, sc_core::sc_module_name mn=NULL)
virtual ~signal_infield ()
Virtual destructor.
virtual void bind (signal_out_bind_if< TYPE > &sender, const uint32_t &channel=0)
virtual void update (signal_out_if< TYPE > *sender, const sc_core::sc_time &time)
TYPE read (const uint32_t &channel) const
TYPE read (const uint32_t &channel, const TYPE &default_value) const
TYPE operator[] (const uint32_t &channel) const
Gets the value of a specific channel.
void operator() (signal_out_bind_if< TYPE > &sender, uint32_t channel)
Connect the infield with an output on a specific channel.
Public Member Functions inherited from sr_signal::signal_base< TYPE, MODULE >
signal_base (sc_core::sc_module_name mn=NULL)
Default constructor.
virtual ~signal_base ()
Public Member Functions inherited from sr_signal::signal_in_if< TYPE >
virtual ~signal_in_if ()
Virtual destructor.
Public Member Functions inherited from sr_signal::signal_if< TYPE >
virtual ~signal_if ()
Virtual destructor.
virtual const TYPE & read ()
Read the current signal value.
operator TYPE () const
Call operator to get the current signal value.
bool operator== (const TYPE &t) const
Comparing the current signal value with a variable of the same type TYPE.
Additional Inherited Members
Protected Member Functions inherited from sr_signal::signal_base< TYPE, MODULE >
virtual MODULE * get_module ()
Protected Attributes inherited from sr_signal::signal_if< TYPE >
TYPE m_value
The signal value.
Detailed Description
template<class TYPE, class MODULE>
class sr_signal::signal_infield< TYPE, MODULE >
This signal is an input signal which can be connected to multiple output signals. But altered from the input signal the infield has knowlage about the source of the arriving signal. Each output signal can be bound to a infield channel. Each hannel has its own value and the callback method can identiefy the seender.
Member Typedef Documentation
template<class TYPE , class MODULE > typedef void(MODULE::* sr_signal::signal_infield< TYPE, MODULE >::t_callback)(const TYPE &value, const uint32_t &channel, const sc_core::sc_time &time)
Callback method type The callback method must be a function with 3 parameters:
Parameters
value The new value of the signal.
channel The input channel of the signal.
time The delay of the signal.
Constructor & Destructor Documentation
template<class TYPE , class MODULE > sr_signal::signal_infield< TYPE, MODULE >::signal_infield (sc_core::sc_module_name mn = NULL) inline
Constructor without callback
Parameters
mn SystemC Signal Name
template<class TYPE , class MODULE > sr_signal::signal_infield< TYPE, MODULE >::signal_infield (t_callback callback, sc_core::sc_module_name mn = NULL) inline
Constructor with callback
Parameters
callback Callback in the base class to be executed each time a value changes.
mn SystemC Signal Name
template<class TYPE , class MODULE > virtual sr_signal::signal_infield< TYPE, MODULE >::~signal_infield () inline virtual
Virtual destructor.
Member Function Documentation
template<class TYPE , class MODULE > virtual void sr_signal::signal_infield< TYPE, MODULE >::bind (signal_out_bind_if< TYPE > & sender, const uint32_t & channel = 0) inline virtual
Bind method. This method binds a specific input channel to a corresponding output. Each channel can be bind multiple times.
Parameters
sender Input interface to bind with.
channel The channel which has to be bind.
Implements sr_signal::signal_in_if< TYPE >.
template<class TYPE , class MODULE > void sr_signal::signal_infield< TYPE, MODULE >::operator() (signal_out_bind_if< TYPE > & sender, uint32_t channel) inline
Connect the infield with an output on a specific channel.
References sr_signal::signal_out_bind_if< TYPE >::bind().
template<class TYPE , class MODULE > TYPE sr_signal::signal_infield< TYPE, MODULE >::operator[] (const uint32_t & channel) const inline
Gets the value of a specific channel.
References pysc::api::cci::read().
template<class TYPE , class MODULE > TYPE sr_signal::signal_infield< TYPE, MODULE >::read (const uint32_t & channel) const inline
Read the value of a specific channel. If the channel not exists –> error
Parameters
channel The channel to read from.
Returns
The value of the channel.
template<class TYPE , class MODULE > TYPE sr_signal::signal_infield< TYPE, MODULE >::read (const uint32_t & channel, const TYPE & default_value) const inline
Safe read reads the value of a channel. If the channel not exists return default value.
Parameters
channel The channel to read from.
default_value The default value to read in case of an error.
Returns
The value of the channel.
template<class TYPE , class MODULE > virtual void sr_signal::signal_infield< TYPE, MODULE >::update (signal_out_if< TYPE > * sender, const sc_core::sc_time & time) inline virtual
Update method. Updates the value of a channel and executes the callback.
Parameters
sender Wich calls update.
time Delay from sc_timestamp() after which the signal is set.
Implements sr_signal::signal_in_if< TYPE >.
References sr_signal::signal_if< TYPE >::read().
The documentation for this class was generated from the following file:
core/common/sr_signal/sr_signal_infield.h