SoCRocket: APBSlaveSocket< BUSWIDTH, ADDR_TYPE, DATA_TYPE > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
APBSlaveSocket< BUSWIDTH, ADDR_TYPE, DATA_TYPE > Class Template Reference
Common
#include <apbslave.h>
Public Member Functions
APBSlaveSocket (sc_core::sc_module_name mn, sr_register_bank< ADDR_TYPE, DATA_TYPE > *bank)
sc_dt::uint64 get_base_addr ()
sc_dt::uint64 get_size ()
Public Member Functions inherited from sr_register_amba_socket< BUSWIDTH, ADDR_TYPE, DATA_TYPE >
sr_register_amba_socket (sc_core::sc_module_name mn, sc_register_bank< ADDR_TYPE, DATA_TYPE > *bank,::amba::amba_bus_type type,::amba::amba_layer_ids layer, bool arbiter)
virtual ~sr_register_amba_socket ()
unsigned int transport_dbg (tlm::tlm_generic_payload &trans)
void b_transport (tlm::tlm_generic_payload &gp, sc_core::sc_time &)
Additional Inherited Members
Public Attributes inherited from sr_register_amba_socket< BUSWIDTH, ADDR_TYPE, DATA_TYPE >
sc_register_bank< ADDR_TYPE,
DATA_TYPE > * m_register
Constructor & Destructor Documentation
template<int BUSWIDTH = 32, typename ADDR_TYPE = unsigned int, typename DATA_TYPE = unsigned int> APBSlaveSocket< BUSWIDTH, ADDR_TYPE, DATA_TYPE >::APBSlaveSocket (sc_core::sc_module_name mn, sr_register_bank< ADDR_TYPE, DATA_TYPE > * bank) inline
Member Function Documentation
template<int BUSWIDTH = 32, typename ADDR_TYPE = unsigned int, typename DATA_TYPE = unsigned int> sc_dt::uint64 APBSlaveSocket< BUSWIDTH, ADDR_TYPE, DATA_TYPE >::get_base_addr () inline virtual
Implements sr_register_amba_socket< BUSWIDTH, ADDR_TYPE, DATA_TYPE >.
Referenced by APBUART::APBUART(), GPTimer::GPTimer(), and Mctrl::Mctrl().
template<int BUSWIDTH = 32, typename ADDR_TYPE = unsigned int, typename DATA_TYPE = unsigned int> sc_dt::uint64 APBSlaveSocket< BUSWIDTH, ADDR_TYPE, DATA_TYPE >::get_size () inline virtual
Implements sr_register_amba_socket< BUSWIDTH, ADDR_TYPE, DATA_TYPE >.
Referenced by APBUART::APBUART(), GPTimer::GPTimer(), and Mctrl::Mctrl().
The documentation for this class was generated from the following file:
core/common/apbslave.h