SoCRocket: mem_if Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
mem_if Class Reference
Mmu_cache
#include <mem_if.h>
Public Member Functions
virtual void mem_write (unsigned int addr, unsigned int asi, unsigned char *data, unsigned int length, sc_core::sc_time *t, unsigned int *debug, bool is_dbg, bool &cacheable, bool is_lock=false)
virtual bool mem_read (unsigned int addr, unsigned int asi, unsigned char *data, unsigned int length, sc_core::sc_time *t, unsigned int *debug, bool is_dbg, bool &cacheable, bool is_lock=false)
virtual ~mem_if ()
Constructor & Destructor Documentation
virtual mem_if::~mem_if () inline virtual
Member Function Documentation
virtual bool mem_if::mem_read (unsigned int addr, unsigned int asi, unsigned char * data, unsigned int length, sc_core::sc_time * t, unsigned int * debug, bool is_dbg, bool & cacheable, bool is_lock = false) inline virtual
Reimplemented in mmu_cache_base, tlb_adaptor, vectorcache, and nocache.
Referenced by mmu_cache_base::exec_data(), mmu_cache_base::exec_instr(), nocache::mem_read(), vectorcache::mem_read(), tlb_adaptor::mem_read(), and mmu::tlb_lookup().
virtual void mem_if::mem_write (unsigned int addr, unsigned int asi, unsigned char * data, unsigned int length, sc_core::sc_time * t, unsigned int * debug, bool is_dbg, bool & cacheable, bool is_lock = false) inline virtual
Reimplemented in mmu_cache_base, tlb_adaptor, vectorcache, and nocache.
Referenced by mmu_cache_base::exec_data(), nocache::mem_write(), vectorcache::mem_write(), and tlb_adaptor::mem_write().
The documentation for this class was generated from the following file:
core/models/mmu_cache/lib/mem_if.h