SoCRocket: trap::isattySysCall< wordSize > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
trap::isattySysCall< wordSize > Class Template Reference
#include <syscCallB.hpp>
Public Member Functions
isattySysCall (ABIIf< wordSize > &processorInstance, sc_time latency=SC_ZERO_TIME)
bool operator() ()
Public Member Functions inherited from trap::SyscallCB< wordSize >
SyscallCB (ABIIf< wordSize > &processorInstance, sc_time latency)
virtual ~SyscallCB ()
Additional Inherited Members
Protected Attributes inherited from trap::SyscallCB< wordSize >
ABIIf< wordSize > & processorInstance
sc_time latency
Constructor & Destructor Documentation
template<class wordSize> trap::isattySysCall< wordSize >::isattySysCall (ABIIf< wordSize > & processorInstance, sc_time latency = SC_ZERO_TIME) inline
Member Function Documentation
template<class wordSize> bool trap::isattySysCall< wordSize >::operator() () inline virtual
Implements trap::SyscallCB< wordSize >.
References trap::SyscallCB< wordSize >::latency, trap::ABIIf< regWidth >::postCall(), trap::ABIIf< regWidth >::preCall(), trap::SyscallCB< wordSize >::processorInstance, trap::ABIIf< regWidth >::readArgs(), trap::ABIIf< regWidth >::returnFromCall(), and trap::ABIIf< regWidth >::setRetVal().
The documentation for this class was generated from the following file:
core/common/trapgen/osEmulator/syscCallB.hpp