SoCRocket: IrqGenerator Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
IrqGenerator Class Reference
#include <irqGenerator.hpp>
Public Member Functions
SC_HAS_PROCESS (IrqGenerator)
IrqGenerator (sc_module_name generatorName, sc_time latency)
void callbackMethod (const unsigned int &value, const sc_time &delay)
void generateIrq ()
Public Attributes
signal< std::pair< unsigned
int, bool > >::out initSignal
signal< unsigned int >::in targSignal
Constructor & Destructor Documentation
IrqGenerator::IrqGenerator (sc_module_name generatorName, sc_time latency) inline
References generateIrq().
Member Function Documentation
void IrqGenerator::callbackMethod (const unsigned int & value, const sc_time & delay) inline
References initSignal, and THROW_EXCEPTION.
void IrqGenerator::generateIrq () inline
References initSignal, trans, and pysc::api::systemc::wait().
Referenced by IrqGenerator().
IrqGenerator::SC_HAS_PROCESS (IrqGenerator)
Member Data Documentation
signal< std::pair<unsigned int, bool> >::out IrqGenerator::initSignal
Referenced by callbackMethod(), generateIrq(), and sc_main().
signal< unsigned int >::in IrqGenerator::targSignal
Referenced by sc_main().
The documentation for this class was generated from the following file:
gaisler/leon3/intunit/irqGenerator.hpp