SoCRocket: sr_param_base Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
sr_param_base Class Reference
Sr_param
#include <sr_param_base.h>
Classes
class easy_init
Public Member Functions
sr_param_base (const std::string &n, const bool register_at_db=true, gs::cnf::gs_param_array *parent_array=NULL, const bool force_top_level_name=false)
void setProperty (std::string key, std::string value)
std::string getProperty (std::string key)
std::map< std::string,
std::string > getProperties ()
void deleteProperty (std::string key)
bool exists (std::string key)
easy_init add_properties ()
Constructor & Destructor Documentation
sr_param_base::sr_param_base (const std::string & n, const bool register_at_db = true, gs::cnf::gs_param_array * parent_array = NULL, const bool force_top_level_name = false) inline explicit
Member Function Documentation
easy_init sr_param_base::add_properties () inline
Referenced by APBUART::init_generics(), AHBMem::init_generics(), Irqmp::init_generics(), APBCtrl::init_generics(), Mctrl::init_generics(), Leon3::init_generics(), GPTimer::init_generics(), and AHBCtrl::init_generics().
void sr_param_base::deleteProperty (std::string key) inline
bool sr_param_base::exists (std::string key) inline
std::map<std::string, std::string> sr_param_base::getProperties () inline
Referenced by pysc::api::cci::USICCIParam::cci_properties(), and pysc::api::cci::get_properties().
std::string sr_param_base::getProperty (std::string key) inline
void sr_param_base::setProperty (std::string key, std::string value) inline
Referenced by sr_param_t< sc_dt::sc_uint< W > >::init(), sr_param_t< sc_dt::sc_uint< W > >::mirror(), and sr_param_base::easy_init::operator()().
The documentation for this class was generated from the following file:
core/common/sr_param/sr_param_base.h