SoCRocket: trap::SparseMemoryLT< N_INITIATORS, sockSize > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
trap::SparseMemoryLT< N_INITIATORS, sockSize > Class Template Reference
#include <SparseMemoryLT.hpp>
Public Member Functions
SparseMemoryLT (sc_module_name name, unsigned int size, sc_time latency=SC_ZERO_TIME)
~SparseMemoryLT ()
void b_transport (tlm::tlm_generic_payload &trans, sc_time &delay)
bool get_direct_mem_ptr (tlm::tlm_generic_payload &trans, tlm::tlm_dmi &dmi_data)
unsigned int transport_dbg (tlm::tlm_generic_payload &trans)
void write_byte_dbg (const unsigned int &address, const unsigned char &datum) throw ()
Public Attributes
tlm_utils::simple_target_socket
< SparseMemoryLT, sockSize > * socket [N_INITIATORS]
Constructor & Destructor Documentation
template<unsigned int N_INITIATORS, unsigned int sockSize> trap::SparseMemoryLT< N_INITIATORS, sockSize >::SparseMemoryLT (sc_module_name name, unsigned int size, sc_time latency = SC_ZERO_TIME) inline
References trap::SparseMemoryLT< N_INITIATORS, sockSize >::b_transport(), trap::SparseMemoryLT< N_INITIATORS, sockSize >::get_direct_mem_ptr(), and trap::SparseMemoryLT< N_INITIATORS, sockSize >::transport_dbg().
template<unsigned int N_INITIATORS, unsigned int sockSize> trap::SparseMemoryLT< N_INITIATORS, sockSize >::~SparseMemoryLT () inline
Member Function Documentation
template<unsigned int N_INITIATORS, unsigned int sockSize> void trap::SparseMemoryLT< N_INITIATORS, sockSize >::b_transport (tlm::tlm_generic_payload & trans, sc_time & delay) inline
Referenced by trap::SparseMemoryLT< N_INITIATORS, sockSize >::SparseMemoryLT().
template<unsigned int N_INITIATORS, unsigned int sockSize> bool trap::SparseMemoryLT< N_INITIATORS, sockSize >::get_direct_mem_ptr (tlm::tlm_generic_payload & trans, tlm::tlm_dmi & dmi_data) inline
Referenced by trap::SparseMemoryLT< N_INITIATORS, sockSize >::SparseMemoryLT().
template<unsigned int N_INITIATORS, unsigned int sockSize> unsigned int trap::SparseMemoryLT< N_INITIATORS, sockSize >::transport_dbg (tlm::tlm_generic_payload & trans) inline
Referenced by trap::SparseMemoryLT< N_INITIATORS, sockSize >::SparseMemoryLT().
template<unsigned int N_INITIATORS, unsigned int sockSize> void trap::SparseMemoryLT< N_INITIATORS, sockSize >::write_byte_dbg (const unsigned int & address, const unsigned char & datum) throw () inline
Referenced by sc_main().
Member Data Documentation
template<unsigned int N_INITIATORS, unsigned int sockSize> tlm_utils::simple_target_socket<SparseMemoryLT, sockSize>* trap::SparseMemoryLT< N_INITIATORS, sockSize >::socket[N_INITIATORS]
Referenced by sc_main().
The documentation for this class was generated from the following file:
core/common/trapgen/misc/SparseMemoryLT.hpp