SoCRocket: sr_register_amba_socket< BUSWIDTH, ADDR_TYPE, DATA_TYPE > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
sr_register_amba_socket< BUSWIDTH, ADDR_TYPE, DATA_TYPE > Class Template Reference abstract
Common
#include <apbslave.h>
Public Member Functions
sr_register_amba_socket (sc_core::sc_module_name mn, sc_register_bank< ADDR_TYPE, DATA_TYPE > *bank,::amba::amba_bus_type type,::amba::amba_layer_ids layer, bool arbiter)
virtual ~sr_register_amba_socket ()
unsigned int transport_dbg (tlm::tlm_generic_payload &trans)
void b_transport (tlm::tlm_generic_payload &gp, sc_core::sc_time &)
virtual sc_dt::uint64 get_base_addr ()=0
virtual sc_dt::uint64 get_size ()=0
Public Attributes
sc_register_bank< ADDR_TYPE,
DATA_TYPE > * m_register
Constructor & Destructor Documentation
template<unsigned int BUSWIDTH = 32, typename ADDR_TYPE = unsigned int, typename DATA_TYPE = unsigned int> sr_register_amba_socket< BUSWIDTH, ADDR_TYPE, DATA_TYPE >::sr_register_amba_socket (sc_core::sc_module_name mn, sc_register_bank< ADDR_TYPE, DATA_TYPE > * bank, ::amba::amba_bus_type type, ::amba::amba_layer_ids layer, bool arbiter) inline
template<unsigned int BUSWIDTH = 32, typename ADDR_TYPE = unsigned int, typename DATA_TYPE = unsigned int> virtual sr_register_amba_socket< BUSWIDTH, ADDR_TYPE, DATA_TYPE >::~sr_register_amba_socket () inline virtual
Member Function Documentation
template<unsigned int BUSWIDTH = 32, typename ADDR_TYPE = unsigned int, typename DATA_TYPE = unsigned int> void sr_register_amba_socket< BUSWIDTH, ADDR_TYPE, DATA_TYPE >::b_transport (tlm::tlm_generic_payload & gp, sc_core::sc_time &) inline
Todo:
We have to read the old data from the register first!!!!
Referenced by sr_register_amba_socket< BUSWIDTH, unsigned int, unsigned int >::sr_register_amba_socket(), and sr_register_amba_socket< BUSWIDTH, unsigned int, unsigned int >::transport_dbg().
template<unsigned int BUSWIDTH = 32, typename ADDR_TYPE = unsigned int, typename DATA_TYPE = unsigned int> virtual sc_dt::uint64 sr_register_amba_socket< BUSWIDTH, ADDR_TYPE, DATA_TYPE >::get_base_addr () pure virtual
Implemented in APBSlaveSocket< BUSWIDTH, ADDR_TYPE, DATA_TYPE >, and APBSlaveSocket< 32, unsigned int, unsigned int >.
Referenced by sr_register_amba_socket< BUSWIDTH, unsigned int, unsigned int >::b_transport().
template<unsigned int BUSWIDTH = 32, typename ADDR_TYPE = unsigned int, typename DATA_TYPE = unsigned int> virtual sc_dt::uint64 sr_register_amba_socket< BUSWIDTH, ADDR_TYPE, DATA_TYPE >::get_size () pure virtual
Implemented in APBSlaveSocket< BUSWIDTH, ADDR_TYPE, DATA_TYPE >, and APBSlaveSocket< 32, unsigned int, unsigned int >.
template<unsigned int BUSWIDTH = 32, typename ADDR_TYPE = unsigned int, typename DATA_TYPE = unsigned int> unsigned int sr_register_amba_socket< BUSWIDTH, ADDR_TYPE, DATA_TYPE >::transport_dbg (tlm::tlm_generic_payload & trans) inline
Referenced by sr_register_amba_socket< BUSWIDTH, unsigned int, unsigned int >::sr_register_amba_socket().
Member Data Documentation
template<unsigned int BUSWIDTH = 32, typename ADDR_TYPE = unsigned int, typename DATA_TYPE = unsigned int> sc_register_bank<ADDR_TYPE, DATA_TYPE>* sr_register_amba_socket< BUSWIDTH, ADDR_TYPE, DATA_TYPE >::m_register
Referenced by sr_register_amba_socket< BUSWIDTH, unsigned int, unsigned int >::b_transport().
The documentation for this class was generated from the following file:
core/common/apbslave.h