SoCRocket: klasses.SubModule Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
klasses.SubModule Class Reference
Public Member Functions
def __init__
def __dir__
def __getattr__
Public Attributes
group
Constructor & Destructor Documentation
def klasses.SubModule.__init__ (self, group)
Referenced by klasses.SubModule.__getattr__().
Member Function Documentation
def klasses.SubModule.__dir__ (self)
References klasses.SubModule.group, and pysc::api::cci.list().
def klasses.SubModule.__getattr__ (self, klass)
References klasses.SubModule.__init__(), klasses.SubModule.group, and pysc::api::cci.list().
Member Data Documentation
klasses.SubModule.group
Referenced by klasses.SubModule.__dir__(), and klasses.SubModule.__getattr__().
The documentation for this class was generated from the following file:
core/common/sr_registry/klasses.py