SoCRocket: sr_signal::signal_out_if< TYPE > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
sr_signal::signal_out_if< TYPE > Class Template Reference abstract
Sr_signal
#include <sr_signal_ifs.h>
Public Member Functions
virtual ~signal_out_if ()
Virtual destructor.
virtual void write (const TYPE &value, const sc_core::sc_time &time=sc_core::SC_ZERO_TIME)=0
virtual TYPE operator= (const TYPE &t)
virtual TYPE operator= (const signal_if< TYPE > &t)
Public Member Functions inherited from sr_signal::signal_if< TYPE >
virtual ~signal_if ()
Virtual destructor.
virtual const TYPE & read ()
Read the current signal value.
operator TYPE () const
Call operator to get the current signal value.
bool operator== (const TYPE &t) const
Comparing the current signal value with a variable of the same type TYPE.
Public Member Functions inherited from sr_signal::signal_out_bind_if< TYPE >
virtual ~signal_out_bind_if ()
Virtual destructor.
virtual signal_out_bind_if
< TYPE > * bind (signal_in_if< TYPE > &t, const unsigned int &channel=0)=0
Additional Inherited Members
Protected Attributes inherited from sr_signal::signal_if< TYPE >
TYPE m_value
The signal value.
Detailed Description
template<class TYPE>
class sr_signal::signal_out_if< TYPE >
Signal output interface This interface provides abstract function declarations to write on a signal.
Constructor & Destructor Documentation
template<class TYPE> virtual sr_signal::signal_out_if< TYPE >::~signal_out_if () inline virtual
Virtual destructor.
Member Function Documentation
template<class TYPE> virtual TYPE sr_signal::signal_out_if< TYPE >::operator= (const TYPE & t) inline virtual
Set operator. The value of the signal is changed to a new value.
Parameters
t The new value.
Returns
The new value.
Reimplemented in sr_signal::signal_out< TYPE, MODULE >, and sr_signal::signal_out< bool, Irqmp >.
template<class TYPE> TYPE sr_signal::signal_out_if< TYPE >::operator= (const signal_if< TYPE > & t) virtual
Set operator. Thets the signal to a value from another signal.
Parameters
t Signal to read the value from.
Returns
The new value.
Reimplemented in sr_signal::signal_out< TYPE, MODULE >, and sr_signal::signal_out< bool, Irqmp >.
References pysc::api::cci::write().
template<class TYPE> virtual void sr_signal::signal_out_if< TYPE >::write (const TYPE & value, const sc_core::sc_time & time = sc_core::SC_ZERO_TIME) pure virtual
Write method. This abstract method has to be implemented by each output signal. It handles the write behaviour of the signal. Therefore it will propagate the written value to the other ends of the signal (input signals).
Parameters
value The new value of the signal. Which is to set.
time Delay from sc_timestamp() after which the signal is set.
Implemented in sr_signal::signal_out< TYPE, MODULE >, and sr_signal::signal_out< bool, Irqmp >.
Referenced by usi.shell.console.Console::interact(), and sr_signal::signal_out_if< bool >::operator=().
The documentation for this class was generated from the following file:
core/common/sr_signal/sr_signal_ifs.h