SoCRocket: trap::SparseMemoryAT< N_INITIATORS, sockSize > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
trap::SparseMemoryAT< N_INITIATORS, sockSize > Class Template Reference
#include <SparseMemoryAT.hpp>
Public Member Functions
SparseMemoryAT (sc_module_name name, unsigned int size, sc_time latency=SC_ZERO_TIME)
~SparseMemoryAT ()
tlm::tlm_sync_enum nb_transport_fw (int tag, tlm::tlm_generic_payload &trans, tlm::tlm_phase &phase, sc_time &delay)
void peq_cb (tlm::tlm_generic_payload &trans, const tlm::tlm_phase &phase)
tlm::tlm_sync_enum send_end_req (tlm::tlm_generic_payload &trans)
void send_response (tlm::tlm_generic_payload &trans)
unsigned int transport_dbg (int tag, tlm::tlm_generic_payload &trans)
void write_byte_dbg (const unsigned int &address, const unsigned char &datum) throw ()
Public Attributes
tlm_utils::simple_target_socket_tagged
< SparseMemoryAT, sockSize > * socket [N_INITIATORS]
Constructor & Destructor Documentation
template<unsigned int N_INITIATORS, unsigned int sockSize> trap::SparseMemoryAT< N_INITIATORS, sockSize >::SparseMemoryAT (sc_module_name name, unsigned int size, sc_time latency = SC_ZERO_TIME) inline
References trap::SparseMemoryAT< N_INITIATORS, sockSize >::nb_transport_fw(), and trap::SparseMemoryAT< N_INITIATORS, sockSize >::transport_dbg().
template<unsigned int N_INITIATORS, unsigned int sockSize> trap::SparseMemoryAT< N_INITIATORS, sockSize >::~SparseMemoryAT () inline
Member Function Documentation
template<unsigned int N_INITIATORS, unsigned int sockSize> tlm::tlm_sync_enum trap::SparseMemoryAT< N_INITIATORS, sockSize >::nb_transport_fw (int tag, tlm::tlm_generic_payload & trans, tlm::tlm_phase & phase, sc_time & delay) inline
Referenced by trap::SparseMemoryAT< N_INITIATORS, sockSize >::SparseMemoryAT().
template<unsigned int N_INITIATORS, unsigned int sockSize> void trap::SparseMemoryAT< N_INITIATORS, sockSize >::peq_cb (tlm::tlm_generic_payload & trans, const tlm::tlm_phase & phase) inline
References trap::SparseMemoryAT< N_INITIATORS, sockSize >::send_end_req(), and trap::SparseMemoryAT< N_INITIATORS, sockSize >::send_response().
template<unsigned int N_INITIATORS, unsigned int sockSize> tlm::tlm_sync_enum trap::SparseMemoryAT< N_INITIATORS, sockSize >::send_end_req (tlm::tlm_generic_payload & trans) inline
Referenced by trap::SparseMemoryAT< N_INITIATORS, sockSize >::peq_cb().
template<unsigned int N_INITIATORS, unsigned int sockSize> void trap::SparseMemoryAT< N_INITIATORS, sockSize >::send_response (tlm::tlm_generic_payload & trans) inline
Referenced by trap::SparseMemoryAT< N_INITIATORS, sockSize >::peq_cb().
template<unsigned int N_INITIATORS, unsigned int sockSize> unsigned int trap::SparseMemoryAT< N_INITIATORS, sockSize >::transport_dbg (int tag, tlm::tlm_generic_payload & trans) inline
Referenced by trap::SparseMemoryAT< N_INITIATORS, sockSize >::SparseMemoryAT().
template<unsigned int N_INITIATORS, unsigned int sockSize> void trap::SparseMemoryAT< N_INITIATORS, sockSize >::write_byte_dbg (const unsigned int & address, const unsigned char & datum) throw () inline
Referenced by sc_main().
Member Data Documentation
template<unsigned int N_INITIATORS, unsigned int sockSize> tlm_utils::simple_target_socket_tagged<SparseMemoryAT, sockSize>* trap::SparseMemoryAT< N_INITIATORS, sockSize >::socket[N_INITIATORS]
Referenced by sc_main().
The documentation for this class was generated from the following file:
core/common/trapgen/misc/SparseMemoryAT.hpp