SoCRocket: tlb_adaptor Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
tlb_adaptor Class Reference
MMU_Cache
#include <tlb_adaptor.h>
Public Member Functions
tlb_adaptor (ModuleName name, mmu_cache_if *top, mmu_if *_mmu, std::map< t_VAT, t_PTE_context > *tlb, unsigned int tlbnum)
constructor
~tlb_adaptor ()
destructor
virtual bool mem_read (unsigned int addr, unsigned int asi, unsigned char *data, unsigned int len, sc_core::sc_time *t, unsigned int *debug, bool is_dbg, bool &cacheable, bool is_lock)
implementation of mem_read function from mem_if.h
virtual void mem_write (unsigned int addr, unsigned int asi, unsigned char *data, unsigned int len, sc_core::sc_time *t, unsigned int *debug, bool is_dbg, bool &cacheable, bool is_lock)
implementation of mem_write function from mem_if.h
Public Member Functions inherited from mem_if
virtual ~mem_if ()
Public Attributes
mmu_cache_if * m_mmu_cache
mmu_if * m_mmu
std::map< t_VAT, t_PTE_context > * m_tlb
unsigned int m_tlbnum
Constructor & Destructor Documentation
tlb_adaptor::tlb_adaptor (ModuleName name, mmu_cache_if * top, mmu_if * _mmu, std::map< t_VAT, t_PTE_context > * tlb, unsigned int tlbnum) inline
constructor
tlb_adaptor::~tlb_adaptor () inline
destructor
Member Function Documentation
virtual bool tlb_adaptor::mem_read (unsigned int addr, unsigned int asi, unsigned char * data, unsigned int len, sc_core::sc_time * t, unsigned int * debug, bool is_dbg, bool & cacheable, bool is_lock) inline virtual
implementation of mem_read function from mem_if.h
Reimplemented from mem_if.
References v::debug, m_mmu, m_mmu_cache, m_tlb, m_tlbnum, mem_if::mem_read(), setup::name, mmu_if::read_mcr(), swap_Endianess(), and mmu_if::tlb_lookup().
virtual void tlb_adaptor::mem_write (unsigned int addr, unsigned int asi, unsigned char * data, unsigned int len, sc_core::sc_time * t, unsigned int * debug, bool is_dbg, bool & cacheable, bool is_lock) inline virtual
implementation of mem_write function from mem_if.h
Reimplemented from mem_if.
References v::debug, m_mmu, m_mmu_cache, m_tlb, m_tlbnum, mem_if::mem_write(), setup::name, mmu_if::read_mcr(), swap_Endianess(), and mmu_if::tlb_lookup().
Member Data Documentation
mmu_if* tlb_adaptor::m_mmu
Referenced by mem_read(), and mem_write().
mmu_cache_if* tlb_adaptor::m_mmu_cache
Referenced by mem_read(), and mem_write().
std::map<t_VAT, t_PTE_context>* tlb_adaptor::m_tlb
Referenced by mem_read(), and mem_write().
unsigned int tlb_adaptor::m_tlbnum
Referenced by mem_read(), and mem_write().
The documentation for this class was generated from the following file:
core/models/mmu_cache/lib/tlb_adaptor.h