SoCRocket: leon3_funclt_trap::TLMMemory Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
leon3_funclt_trap::TLMMemory Class Reference
#include <externalPorts.hpp>
Public Member Functions
TLMMemory (sc_module_name portName, tlm_utils::tlm_quantumkeeper &quantKeeper)
void setDebugger (MemoryToolsIf< unsigned int > *debugger)
sc_dt::uint64 read_dword (const unsigned int &address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw ()
unsigned int read_word (const unsigned int &address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw ()
unsigned short int read_half (const unsigned int &address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw ()
unsigned char read_byte (const unsigned int &address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw ()
unsigned int read_instr (const unsigned int &address, const unsigned int flush) throw ()
void write_dword (const unsigned int &address, sc_dt::uint64 datum, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw ()
void write_word (const unsigned int &address, unsigned int datum, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw ()
void write_half (const unsigned int &address, unsigned short int datum, unsigned int asi, unsigned int flush, unsigned int lock) throw ()
void write_byte (const unsigned int &address, unsigned char datum, unsigned int asi, unsigned int flush, unsigned int lock) throw ()
sc_dt::uint64 read_dword_dbg (const unsigned int &address) throw ()
unsigned int read_word_dbg (const unsigned int &address) throw ()
unsigned short int read_half_dbg (const unsigned int &address) throw ()
unsigned char read_byte_dbg (const unsigned int &address) throw ()
void write_dword_dbg (const unsigned int &address, sc_dt::uint64 datum) throw ()
void write_word_dbg (const unsigned int &address, unsigned int datum) throw ()
void write_half_dbg (const unsigned int &address, unsigned short int datum) throw ()
void write_byte_dbg (const unsigned int &address, unsigned char datum) throw ()
void lock ()
void unlock ()
Public Member Functions inherited from leon3_funclt_trap::MemoryInterface
virtual unsigned int read_instr (const unsigned int &address, const unsigned int asi, const unsigned int flush)=0 throw ()
void swapEndianess (unsigned int &datum) const throw ()
void swapEndianess (unsigned short int &datum) const throw ()
virtual ~MemoryInterface ()
Public Attributes
tlm_utils::simple_initiator_socket
< TLMMemory, 32 > initSocket
Constructor & Destructor Documentation
leon3_funclt_trap::TLMMemory::TLMMemory (sc_module_name portName, tlm_utils::tlm_quantumkeeper & quantKeeper)
Member Function Documentation
void leon3_funclt_trap::TLMMemory::lock () virtual
Implements leon3_funclt_trap::MemoryInterface.
Referenced by read_word(), and write_word().
unsigned char leon3_funclt_trap::TLMMemory::read_byte (const unsigned int & address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () virtual
Implements leon3_funclt_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, flush(), dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
unsigned char leon3_funclt_trap::TLMMemory::read_byte_dbg (const unsigned int & address) throw () virtual
Reimplemented from leon3_funclt_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
sc_dt::uint64 leon3_funclt_trap::TLMMemory::read_dword (const unsigned int & address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () virtual
Implements leon3_funclt_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, flush(), dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
sc_dt::uint64 leon3_funclt_trap::TLMMemory::read_dword_dbg (const unsigned int & address) throw () virtual
Reimplemented from leon3_funclt_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
unsigned short int leon3_funclt_trap::TLMMemory::read_half (const unsigned int & address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () virtual
Implements leon3_funclt_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, flush(), dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
unsigned short int leon3_funclt_trap::TLMMemory::read_half_dbg (const unsigned int & address) throw () virtual
Reimplemented from leon3_funclt_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
unsigned int leon3_funclt_trap::TLMMemory::read_instr (const unsigned int & address, const unsigned int flush) throw () inline
References icio_payload_extension::debug, v::debug, flush(), icio_payload_extension::flush, initSocket, setup::name, leon3_funclt_trap::MemoryInterface::swapEndianess(), and trans.
unsigned int leon3_funclt_trap::TLMMemory::read_word (const unsigned int & address, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () inline virtual
Implements leon3_funclt_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, flush(), dcio_payload_extension::flush, initSocket, dcio_payload_extension::lock, lock(), setup::name, leon3_funclt_trap::MemoryInterface::swapEndianess(), and trans.
unsigned int leon3_funclt_trap::TLMMemory::read_word_dbg (const unsigned int & address) throw () virtual
Reimplemented from leon3_funclt_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
void leon3_funclt_trap::TLMMemory::setDebugger (MemoryToolsIf< unsigned int > * debugger)
void leon3_funclt_trap::TLMMemory::unlock () virtual
Implements leon3_funclt_trap::MemoryInterface.
void leon3_funclt_trap::TLMMemory::write_byte (const unsigned int & address, unsigned char datum, unsigned int asi, unsigned int flush, unsigned int lock) throw () virtual
Implements leon3_funclt_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, flush(), dcio_payload_extension::flush, dcio_payload_extension::lock, trans, and pysc::api::systemc::wait().
void leon3_funclt_trap::TLMMemory::write_byte_dbg (const unsigned int & address, unsigned char datum) throw () virtual
Reimplemented from leon3_funclt_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
void leon3_funclt_trap::TLMMemory::write_dword (const unsigned int & address, sc_dt::uint64 datum, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () virtual
Implements leon3_funclt_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, flush(), dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
void leon3_funclt_trap::TLMMemory::write_dword_dbg (const unsigned int & address, sc_dt::uint64 datum) throw () virtual
Reimplemented from leon3_funclt_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
void leon3_funclt_trap::TLMMemory::write_half (const unsigned int & address, unsigned short int datum, unsigned int asi, unsigned int flush, unsigned int lock) throw () virtual
Implements leon3_funclt_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, flush(), dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
void leon3_funclt_trap::TLMMemory::write_half_dbg (const unsigned int & address, unsigned short int datum) throw () virtual
Reimplemented from leon3_funclt_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
void leon3_funclt_trap::TLMMemory::write_word (const unsigned int & address, unsigned int datum, const unsigned int asi, const unsigned int flush, const unsigned int lock) throw () inline virtual
Implements leon3_funclt_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, flush(), dcio_payload_extension::flush, initSocket, dcio_payload_extension::lock, lock(), setup::name, trap::MemoryToolsIf< addressType >::notifyAddress(), leon3_funclt_trap::MemoryInterface::swapEndianess(), and trans.
void leon3_funclt_trap::TLMMemory::write_word_dbg (const unsigned int & address, unsigned int datum) throw () virtual
Reimplemented from leon3_funclt_trap::MemoryInterface.
References dcio_payload_extension::asi, dcio_payload_extension::debug, v::debug, dcio_payload_extension::flush, dcio_payload_extension::lock, and trans.
Member Data Documentation
tlm_utils::simple_initiator_socket< TLMMemory, 32 > leon3_funclt_trap::TLMMemory::initSocket
Referenced by read_instr(), read_word(), and write_word().
The documentation for this class was generated from the following files:
gaisler/leon3/intunit/externalPorts.hpp
gaisler/leon3/intunit/externalPorts.cpp