SoCRocket: trap::ToolsManager< issueWidth > Class Template Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
trap::ToolsManager< issueWidth > Class Template Reference
#include <ToolsIf.hpp>
Public Member Functions
ToolsManager ()
void addTool (ToolsIf< issueWidth > &tool)
bool newIssue (const issueWidth &curPC, const InstructionBase *curInstr) const throw ()
bool emptyPipeline (const issueWidth &curPC) const throw ()
Constructor & Destructor Documentation
template<class issueWidth> trap::ToolsManager< issueWidth >::ToolsManager () inline
Member Function Documentation
template<class issueWidth> void trap::ToolsManager< issueWidth >::addTool (ToolsIf< issueWidth > & tool) inline
Adds a tool to the list of the tool which are activated when there is a new instruction issue
Referenced by leon3_mmu_cache::g_gdb_callback(), leon3_mmu_cache::g_osemu_callback(), and sc_main().
template<class issueWidth> bool trap::ToolsManager< issueWidth >::emptyPipeline (const issueWidth & curPC) const throw () inline
Returns true if the pipeline has to be empty before being able to call the current tool, false otherwise
template<class issueWidth> bool trap::ToolsManager< issueWidth >::newIssue (const issueWidth & curPC, const InstructionBase * curInstr) const throw () inline
The only method which is called to activate the tool it signals to the tool that a new instruction issue has been started; the tool can then take the appropriate actions. the return value specifies whether the processor should skip the issue of the current instruction
The documentation for this class was generated from the following file:
core/common/trapgen/ToolsIf.hpp