SoCRocket: Leon3mpPlatform Class Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
Leon3mpPlatform Class Reference
Platform
#include <leon3mp.h>
Public Member Functions
Leon3mpPlatform (sc_core::sc_module_name mn, uint32_t ahbctrl_ioaddr=0xFFF, uint32_t ahbctrl_iomask=0xFFF, uint32_t ahbctrl_cfgaddr=0xFF0, uint32_t ahbctrl_cfgmask=0xFF0, bool ahbctrl_rrobin=false, bool ahbctrl_split=false, uint32_t ahbctrl_defmast=0, bool ahbctrl_ioen=true, bool ahbctrl_fixbrst=false, bool ahbctrl_fpnpen=true, bool ahbctrl_mcheck=true, uint32_t apbctrl_haddr=0xfff, uint32_t apbctrl_hmask=0, bool apbctrl_mcheck=true, uint32_t apbctrl_hindex=0, uint32_t irqmp_paddr=0, uint32_t irqmp_pmask=0xFFF, uint32_t irqmp_ncpu=2, uint32_t irqmp_eirq=1, uint32_t irqmp_pindex=0, bool leon3_mmu_cache_ic_en=true, uint32_t leon3_mmu_cache_irepl=1, uint32_t leon3_mmu_cache_isets=4, uint32_t leon3_mmu_cache_ilinesize=8, uint32_t leon3_mmu_cache_isetsize=8, uint32_t leon3_mmu_cache_isetlock=true, uint32_t leon3_mmu_cache_dcen=true, uint32_t leon3_mmu_cache_drepl=1, uint32_t leon3_mmu_cache_dsets=2, uint32_t leon3_mmu_cache_dlinesize=4, uint32_t leon3_mmu_cache_dsetsize=8, bool leon3_mmu_cache_dsetlock=true, bool leon3_mmu_cache_dsnoop=true, bool leon3_mmu_cache_ilram=false, uint32_t leon3_mmu_cache_ilramsize=0x000, uint32_t leon3_mmu_cache_ilramstart=0x000, uint32_t leon3_mmu_cache_dlram=false, uint32_t leon3_mmu_cache_dlramsize=0x000, uint32_t leon3_mmu_cache_dlramstart=0x000, uint32_t leon3_mmu_cache_cached=0, bool leon3_mmu_en=true, uint32_t leon3_mmu_cache_itlb_num=8, uint32_t leon3_mmu_cache_dtlb_num=8, uint32_t leon3_mmu_cache_tlb_type=0, uint32_t leon3_mmu_cache_tlb_rep=1, uint32_t leon3_mmu_cache_mmupgsz=0, uint32_t leon3_mmu_cache_hindex=0, bool pow_mon=false, amba::amba_layer_ids ambaLayer=amba::amba_LT)
~Leon3mpPlatform ()
void clkcng ()
void dorst ()
Public Member Functions inherited from AMBABasePlatform
AMBABasePlatform (sc_core::sc_module_name mn, uint32_t ahbctrl_ioaddr=0xFFF, uint32_t ahbctrl_iomask=0xFFF, uint32_t ahbctrl_cfgaddr=0xFF0, uint32_t ahbctrl_cfgmask=0xFF0, bool ahbctrl_rrobin=false, bool ahbctrl_split=false, uint32_t ahbctrl_defmast=0, bool ahbctrl_ioen=true, bool ahbctrl_fixbrst=false, bool ahbctrl_fpnpen=true, bool ahbctrl_mcheck=true, uint32_t apbctrl_haddr=0xfff, uint32_t apbctrl_hmask=0, bool apbctrl_mcheck=true, uint32_t apbctrl_hindex=0, uint32_t irqmp_paddr=0, uint32_t irqmp_pmask=0xFFF, uint32_t irqmp_ncpu=2, uint32_t irqmp_eirq=1, uint32_t irqmp_pindex=0, bool pow_mon=false, amba::amba_layer_ids ambaLayer=amba::amba_LT)
Public Member Functions inherited from CLKDevice
SK_HAS_SIGNALS (CLKDevice)
CLKDevice ()
virtual ~CLKDevice ()
virtual void onrst (const bool &value, const sc_core::sc_time &time)
virtual void onclk (const sc_core::sc_time &value, const sc_core::sc_time &time)
void set_clk (sc_core::sc_clock &clk)
void set_clk (sc_core::sc_time period)
void set_clk (double period, sc_core::sc_time_unit base)
Additional Inherited Members
Public Attributes inherited from AMBABasePlatform
AHBCtrl ahbctrl
APBCtrl apbctrl
Irqmp irqmp
Public Attributes inherited from CLKDevice
signal< bool >::in rst
Reset input signal.
signal< sc_core::sc_time >::in clk
Clock input signal.
Protected Attributes inherited from CLKDevice
sc_core::sc_time clock_cycle
Constructor & Destructor Documentation
Leon3mpPlatform::Leon3mpPlatform (sc_core::sc_module_name mn, uint32_t ahbctrl_ioaddr = 0xFFF, uint32_t ahbctrl_iomask = 0xFFF, uint32_t ahbctrl_cfgaddr = 0xFF0, uint32_t ahbctrl_cfgmask = 0xFF0, bool ahbctrl_rrobin = false, bool ahbctrl_split = false, uint32_t ahbctrl_defmast = 0, bool ahbctrl_ioen = true, bool ahbctrl_fixbrst = false, bool ahbctrl_fpnpen = true, bool ahbctrl_mcheck = true, uint32_t apbctrl_haddr = 0xfff, uint32_t apbctrl_hmask = 0, bool apbctrl_mcheck = true, uint32_t apbctrl_hindex = 0, uint32_t irqmp_paddr = 0, uint32_t irqmp_pmask = 0xFFF, uint32_t irqmp_ncpu = 2, uint32_t irqmp_eirq = 1, uint32_t irqmp_pindex = 0, bool leon3_mmu_cache_ic_en = true, uint32_t leon3_mmu_cache_irepl = 1, uint32_t leon3_mmu_cache_isets = 4, uint32_t leon3_mmu_cache_ilinesize = 8, uint32_t leon3_mmu_cache_isetsize = 8, uint32_t leon3_mmu_cache_isetlock = true, uint32_t leon3_mmu_cache_dcen = true, uint32_t leon3_mmu_cache_drepl = 1, uint32_t leon3_mmu_cache_dsets = 2, uint32_t leon3_mmu_cache_dlinesize = 4, uint32_t leon3_mmu_cache_dsetsize = 8, bool leon3_mmu_cache_dsetlock = true, bool leon3_mmu_cache_dsnoop = true, bool leon3_mmu_cache_ilram = false, uint32_t leon3_mmu_cache_ilramsize = 0x000, uint32_t leon3_mmu_cache_ilramstart = 0x000, uint32_t leon3_mmu_cache_dlram = false, uint32_t leon3_mmu_cache_dlramsize = 0x000, uint32_t leon3_mmu_cache_dlramstart = 0x000, uint32_t leon3_mmu_cache_cached = 0, bool leon3_mmu_en = true, uint32_t leon3_mmu_cache_itlb_num = 8, uint32_t leon3_mmu_cache_dtlb_num = 8, uint32_t leon3_mmu_cache_tlb_type = 0, uint32_t leon3_mmu_cache_tlb_rep = 1, uint32_t leon3_mmu_cache_mmupgsz = 0, uint32_t leon3_mmu_cache_hindex = 0, bool pow_mon = false, amba::amba_layer_ids ambaLayer = amba::amba_LT) inline
Parameters
ahbctrl_ioaddr The MSB address of the AHBCtrl I/O area
ahbctrl_iomask The AHBCtrl I/O area address mask
ahbctrl_cfgaddr The MSB address of the AHBCtrl configuration area (PNP)
ahbctrl_cfgmask The address mask of the AHBCtrl configuration area
ahbctrl_rrobin AHBCtrl arbitration: 1 - round robin, 0 - fixed priority arbitration (only AT)
ahbctrl_split Enable support for AHB SPLIT response in the AHBCtrl (only AT)
ahbctrl_defmast ID of the default master at the AHBCtrl
ahbctrl_ioen AHBCtrl AHB I/O area enable
ahbctrl_fixbrst Enable support for fixed-length bursts in the AHBCtrl
ahbctrl_fpnpen Enable full decoding of PnP configuration records in the AHBCtrl.
ahbctrl_mcheck Check if there are any intersections between core memory regions in the AHBCtrl.
apbctrl_haddr The MSB address of the APBCtrl AHB area. Sets the 12 MSBs in the AHB address
apbctrl_hmask The 12bit AHB area address mask of the APBCtrl
apbctrl_mcheck Check if there are any intersections between APB slave memory regions in the APBCtrl
apbctrl_hindex AHB bus index of the APBCtrl
irqmp_paddr Upper 12bit of the Irqmp APB address.
irqmp_pmask Upper 12bit of the Irqmp APB mask.
irqmp_ncpu Number of CPU which receive interupts stored in Irqmp Status Register.
irqmp_eirq Interrupt channel which hides all the extended interrupt channels.
irqmp_pindex Irqmp APB slave index.
leon3_mmu_cache_ic_en instruction cache enable
leon3_mmu_cache_irepl instruction cache replacement strategy
leon3_mmu_cache_isets number of instruction cache sets
leon3_mmu_cache_ilinesize instruction cache line size (in bytes)
leon3_mmu_cache_isetsize size of an instruction cache set (in kbytes)
leon3_mmu_cache_isetlock enable instruction cache locking
leon3_mmu_cache_dcen data cache enable
leon3_mmu_cache_drepl data cache replacement strategy
leon3_mmu_cache_dsets number of data cache sets
leon3_mmu_cache_dlinesize data cache line size (in bytes)
leon3_mmu_cache_dsetsize size of a data cache set (in kbytes)
leon3_mmu_cache_dsetlock enable data cache locking
leon3_mmu_cache_dsnoop enable data cache snooping
leon3_mmu_cache_ilram enable instruction scratch pad
leon3_mmu_cache_ilramsize size of the instruction scratch pad (in kbytes)
leon3_mmu_cache_ilramstart start address of the instruction scratch pad
leon3_mmu_cache_dlram enable data scratch pad
leon3_mmu_cache_dlramsize size of the data scratch pad (in kbytes)
leon3_mmu_cache_dlramstart start address of the data scratch pad
leon3_mmu_cache_cached fixed cacheability mask
leon3_mmu_en mmu enable
leon3_mmu_cache_itlb_num number of instruction TLBs
leon3_mmu_cache_dtlb_num number of data TLBs
leon3_mmu_cache_tlb_type split or shared instruction and data TLBs
leon3_mmu_cache_tlb_rep TLB replacement strategy
leon3_mmu_cache_mmupgsz MMU page size
leon3_mmu_cache_hindex ID of the bus master
pow_mon Enable power monitoring in AHBCtrl and APBCtrl
References signalkit::connect(), leon3_mmu_cache::cpu, leon3_funclt_trap::PinTLM_out_32::initSignal, leon3_funclt_trap::Processor_leon3_funclt::IRQ_port, leon3_funclt_trap::IntrTLMPort_32::irq_signal, leon3_funclt_trap::Processor_leon3_funclt::irqAck, leon3_funclt_trap::PinTLM_out_32::run, and leon3_funclt_trap::PinTLM_out_32::status.
Leon3mpPlatform::~Leon3mpPlatform () inline
Member Function Documentation
void Leon3mpPlatform::clkcng () inline virtual
Reimplemented from AMBABasePlatform.
References AMBABasePlatform::clkcng().
void Leon3mpPlatform::dorst () inline virtual
Reimplemented from AMBABasePlatform.
References AMBABasePlatform::dorst().
The documentation for this class was generated from the following file:
core/platforms/newleon3mp/leon3mp.h