SoCRocket: core/software/trapgen/dhry.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
dhry.c File Reference
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
Classes
struct record
Macros
#define HZ 60
#define Mic_secs_Per_Second 1000000.0
#define structassign(d, s) d = s
#define Null 0
#define true 1
#define false 0
#define REG
#define Too_Small_Time 120
Typedefs
typedef int One_Thirty
typedef int One_Fifty
typedef char Capital_Letter
typedef int Boolean
typedef char Str_30 [31]
typedef int Arr_1_Dim [50]
typedef int Arr_2_Dim [50][50]
typedef struct record Rec_Type
typedef struct record * Rec_Pointer
Enumerations
enum Enumeration {
Ident_1, Ident_2, Ident_3, Ident_4,
Ident_5
}
Functions
Boolean Func_3 (Enumeration Enum_Par_Val)
void Proc_1 (REG Rec_Pointer Ptr_Val_Par)
void Proc_2 (One_Fifty *Int_Par_Ref)
void Proc_3 (Rec_Pointer *Ptr_Ref_Par)
void Proc_4 (void)
void Proc_5 (void)
void Proc_6 (Enumeration Enum_Val_Par, Enumeration *Enum_Ref_Par)
void Proc_7 (One_Fifty Int_1_Par_Val, One_Fifty Int_2_Par_Val, One_Fifty *Int_Par_Ref)
void Proc_8 (Arr_1_Dim Arr_1_Par_Ref, Arr_2_Dim Arr_2_Par_Ref, int Int_1_Par_Val, int Int_2_Par_Val)
Enumeration Func_1 (Capital_Letter Ch_1_Par_Val, Capital_Letter Ch_2_Par_Val)
Boolean Func_2 (Str_30 Str_1_Par_Ref, Str_30 Str_2_Par_Ref)
Enumeration Func_1 ()
int main ()
Variables
int Int_Glob
char Ch_1_Glob
Rec_Pointer Ptr_Glob
Rec_Pointer Next_Ptr_Glob
Boolean Bool_Glob
char Ch_2_Glob
int Arr_1_Glob [50]
int Arr_2_Glob [50][50]
Boolean Reg = true
long Begin_Time
long End_Time
long User_Time
float Microseconds
float Dhrystones_Per_Second
Macro Definition Documentation
#define false 0
#define HZ 60
Referenced by main().
#define Mic_secs_Per_Second 1000000.0
Referenced by main().
#define Null 0
Referenced by Proc_3().
#define REG
Referenced by Func_2(), main(), Proc_1(), and Proc_8().
#define structassign (d, s) d = s
Referenced by Proc_1().
#define Too_Small_Time 120
Referenced by main().
#define true 1
Typedef Documentation
typedef int Arr_1_Dim[50]
typedef int Arr_2_Dim[50][50]
typedef int Boolean
typedef char Capital_Letter
typedef int One_Fifty
typedef int One_Thirty
typedef struct record * Rec_Pointer
typedef struct record Rec_Type
typedef char Str_30[31]
Enumeration Type Documentation
enum Enumeration
Enumerator
Ident_1
Ident_2
Ident_3
Ident_4
Ident_5
Function Documentation
Enumeration Func_1 (Capital_Letter Ch_1_Par_Val, Capital_Letter Ch_2_Par_Val)
References Ident_1, and Ident_2.
Referenced by Func_2(), and main().
Enumeration Func_1 ()
Boolean Func_2 (Str_30 Str_1_Par_Ref, Str_30 Str_2_Par_Ref)
References Func_1(), Ident_1, and REG.
Referenced by main().
Boolean Func_3 (Enumeration Enum_Par_Val)
References Ident_3.
Referenced by Proc_6().
int main (void)
References Begin_Time, Ch_2_Glob, record::Discr, End_Time, Func_1(), Func_2(), HZ, Ident_1, Ident_2, Ident_3, Mic_secs_Per_Second, Next_Ptr_Glob, Proc_1(), Proc_2(), Proc_4(), Proc_5(), Proc_6(), Proc_7(), Proc_8(), record::Ptr_Comp, REG, Too_Small_Time, User_Time, record::var_1, and record::variant.
void Proc_1 (REG Rec_Pointer Ptr_Val_Par)
References Ident_1, Proc_3(), Proc_6(), Proc_7(), record::Ptr_Comp, REG, and structassign.
Referenced by main().
void Proc_2 (One_Fifty * Int_Par_Ref)
References Ident_1, and Int_Glob.
Referenced by main().
void Proc_3 (Rec_Pointer * Ptr_Ref_Par)
References Null, Proc_7(), record::Ptr_Comp, record::var_1, and record::variant.
Referenced by Proc_1().
void Proc_4 (void)
References Bool_Glob.
Referenced by main().
void Proc_5 (void)
Referenced by main().
void Proc_6 (Enumeration Enum_Val_Par, Enumeration * Enum_Ref_Par)
References Func_3(), Ident_1, Ident_2, Ident_3, Ident_4, and Ident_5.
Referenced by main(), and Proc_1().
void Proc_7 (One_Fifty Int_1_Par_Val, One_Fifty Int_2_Par_Val, One_Fifty * Int_Par_Ref)
Referenced by main(), Proc_1(), and Proc_3().
void Proc_8 (Arr_1_Dim Arr_1_Par_Ref, Arr_2_Dim Arr_2_Par_Ref, int Int_1_Par_Val, int Int_2_Par_Val)
References REG.
Referenced by main().
Variable Documentation
int Arr_1_Glob[50]
int Arr_2_Glob[50][50]
long Begin_Time
Referenced by main().
Boolean Bool_Glob
Referenced by Proc_4().
char Ch_1_Glob
char Ch_2_Glob
Referenced by main().
float Dhrystones_Per_Second
long End_Time
Referenced by main().
int Int_Glob
Referenced by Proc_2().
float Microseconds
Rec_Pointer Next_Ptr_Glob
Referenced by main().
Rec_Pointer Ptr_Glob
Boolean Reg = true
long User_Time
Referenced by main().