SoCRocket: core/software/grlib_tests/divtest.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
divtest.c File Reference
#include "testmod.h"
Classes
struct divcase
struct udivcase
Functions
divtest ()
Variables
volatile struct divcase diva []
volatile struct udivcase udiva []
Function Documentation
divtest ()
References DIV_CONF_BIT, DIV_TEST, fail, get_asr17, get_pid, l2regs::leonconf, num, and report_subtest().
Referenced by leon2_test(), and leon3_test().
Variable Documentation
volatile struct divcase diva[]
Initial value:
= {
    {  2,  3, 0}, { 3, -2, -1}, {  2, -3, 0}, {  0,  1, 0}, {  0, -1, 0}, {  1, -1, -1},
    { -1,  1, -1}, { -2,  3, 0}, { -2, -3, 0}, {9, 7, 1},
    { -9, 2, -4}, {-8, 2, -4}, {-8, -4, 2}, {8, -4, -2}, {-8, -8 , 1},
    {-8, -9, 0}, {11, 2, 5}, {47, 2, 23},
    { 12345,  679, 12345/679}, { -63636,  77, -63636/77},
    { 12345,  -679, -12345/679}, { -63636,  -77, 63636/77},
    { 145,  -6079, 0}, { -636,  -77777, 0}, { 63226,  7227777, 0},
    {  0,  0, 0}
 }
volatile struct udivcase udiva[]
Initial value:
= {
    {  2,  3, 0}, {  0,  1, 0}, { 0xfffffffe,  3, 0xfffffffe/3},
    { 0xfffffffe,  3, 0xfffffffe/3}, { 0x700ffffe,  7, 0x700ffffe/7},
    {  0,  0, 0}
 }