SoCRocket: core/software/grlib_tests/dsu3.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
dsu3.c File Reference
#include "dsu3.h"
Functions
dsu3_tb_check (int dsuaddr)
check_tbuf (int addr, int ahblen)
Function Documentation
check_tbuf (int addr, int ahblen)
References fail, and report_subtest().
Referenced by dsu3_tb_check().
dsu3_tb_check (int dsuaddr)
References check_tbuf(), DSU3_AHBBUF, DSU3_AHBCTRL, DSU3_TBCTRL, DSU3_TBUF, and report_device().