SoCRocket: core/software/trapgen/fib.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
fib.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
Functions
unsigned long fib (long)
int main ()
Function Documentation
unsigned long fib (long x)
Referenced by fib(), and main().
int main (void)
References fib().