SoCRocket: core/software/trapgen/gamma.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
gamma.c File Reference
#include <stdio.h>
#include <math.h>
Functions
float gammln (float xx)
float factrl (int n)
int main ()
Function Documentation
float factrl (int n)
References gammln().
Referenced by main().
float gammln (float xx)
References x, and y.
Referenced by factrl().
int main (void)
References factrl().