SoCRocket: core/software/grlib_tests/gptimer.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
gptimer.c File Reference
#include "testmod.h"
#include "irqmp.h"
#include "cache.h"
#include "standalone.h"
#include <stdio.h>
Classes
struct timerreg
struct gptimer
Macros
#define IRQPEND 0x10
#define CHAIN_TEST 8
Functions
void gptimer_test (int addr, int irq)
Macro Definition Documentation
#define CHAIN_TEST 8
Referenced by gptimer_test().
#define IRQPEND 0x10
Referenced by gptimer_test().
Function Documentation
void gptimer_test (int addr, int irq)
References cache_disable(), catch_interrupt(), CHAIN_TEST, gptimer::configreg, timerreg::control, timerreg::counter, fail, i, init_irqmp(), irq, irqmp::irqmask, irqmp_base, IRQPEND, timerreg::reload, report_device(), report_subtest(), gptimer::scalercnt, gptimer::scalerload, success(), and gptimer::timer.
Referenced by base_test(), base_test_tirq(), and main().