SoCRocket: Input Device
SoCRocket
Transaction-Level Modeling Framework for Space Applications
Input Device
Files
file ahbin.cpp
file ahbin.h
Classes
class AHBIn
Definition of class AHBIn.
Functions
AHBIn::AHBIn (ModuleName name, unsigned int hindex, unsigned int hirq, unsigned int framesize, unsigned int frameaddr, sc_core::sc_time interval, bool pow_mon, AbstractionLayer ambaLayer)
Constructor.
void AHBIn::dorst ()
Reset function.
void AHBIn::frame_trigger ()
Thread for triggering gen_frame (generates new_frame event)
void AHBIn::gen_frame ()
Thread for generating the data frame.
void AHBIn::clkcng ()
Deal with clock changes.
sc_core::sc_time AHBIn::get_clock ()
Returns clock cycle time from master.
Detailed Description
Function Documentation
AHBIn::AHBIn (ModuleName name, unsigned int hindex, unsigned int hirq, unsigned int framesize, unsigned int frameaddr, sc_core::sc_time interval, bool pow_mon, AbstractionLayer ambaLayer)
Constructor.
References AHBIn::frame_trigger(), AHBIn::gen_frame(), v::info, and setup::name.
void AHBIn::clkcng () virtual
Deal with clock changes.
Reimplemented from CLKDevice.
void AHBIn::dorst () virtual
Reset function.
Reimplemented from CLKDevice.
void AHBIn::frame_trigger ()
Thread for triggering gen_frame (generates new_frame event)
Referenced by AHBIn::AHBIn().
void AHBIn::gen_frame ()
Thread for generating the data frame.
References AHBMaster< DefaultBase >::ahbwrite(), CLKDevice::clock_cycle, v::info, AHBIn::irq, and setup::name.
Referenced by AHBIn::AHBIn().
sc_core::sc_time AHBIn::get_clock () virtual
Returns clock cycle time from master.
Implements AHBMaster< DefaultBase >.
References CLKDevice::clock_cycle.