SoCRocket: Sr_register
SoCRocket
Transaction-Level Modeling Framework for Space Applications
Sr_register
Files
file scireg.cpp
Namespaces
scireg_ns
Classes
class sc_register_field_b< T >
T is the data type of the register that contains this field.
class sc_register_field< T, highpos, lowpos >
class sc_register_b< T >
class sc_register< T, M >
M is the access mode.
class sc_register_field_base
class sc_rf_valuecode
class sc_register_base
Register.
class sc_register_bank_base
class sc_register_bank< ADDR_TYPE, DATA_TYPE >
class sc_register< unsigned char, M >
class sc_register< unsigned short, M >
class sc_register< unsigned int, M >
class sc_register< unsigned long long, M >
class scireg_ns::scireg_notification_if
The scireg_notification_if is used to notify tools of additions/deletions of scireg region objects.
class scireg_ns::scireg_tool_registry
struct scireg_ns::scireg_mapped_region
struct scireg_ns::scireg_value_info
class scireg_ns::scireg_callback
The scireg_callback is an abstract base class that is used to implement callbacks to tools.
class scireg_ns::scireg_region_if
class sr_register_field< T >
class sr_register_callback_base
class sr_register_callback< OWNER >
class sr_register< DATA_TYPE >
class sr_register_bank< ADDR_TYPE, DATA_TYPE >
Macros
#define MAX_DESC_LENGTH 64
Typedefs
typedef ::std::vector
< sc_register_field_base * > sc_register_field_vec
Vector of register field.
typedef std::vector
< sc_register_base * > sc_register_vec
Register Bank.
Enumerations
enum sc_register_access_mode { SC_REG_RW_ACCESS = 0, SC_REG_RO_ACCESS, SC_REG_WO_ACCESS }
Register Access Mode.
enum sc_register_access_type { SC_REG_UNKNOWN_ACCESS_TYPE, SC_REG_READ, SC_REG_WRITE }
enum scireg_ns::scireg_region_type {
scireg_ns::SCIREG_MEMORY, scireg_ns::SCIREG_BANK, scireg_ns::SCIREG_REGISTER, scireg_ns::SCIREG_FIELD,
scireg_ns::SCIREG_STRING_REGISTER
}
enum scireg_ns::scireg_response { scireg_ns::SCIREG_SUCCESS, scireg_ns::SCIREG_FAILURE, scireg_ns::SCIREG_UNSUPPORTED }
SCIREG API response codes:
enum scireg_ns::scireg_bit_attributes_type { scireg_ns::SCIREG_READABLE, scireg_ns::SCIREG_WRITEABLE }
Attributes assocated with individual bits within regions:
enum scireg_ns::scireg_string_attribute_type { scireg_ns::SCIREG_NAME, scireg_ns::SCIREG_DESCRIPTION, scireg_ns::SCIREG_STRING_VALUE }
String attributes associated with region objects:
enum scireg_ns::scireg_callback_type { scireg_ns::SCIREG_READ_ACCESS, scireg_ns::SCIREG_WRITE_ACCESS, scireg_ns::SCIREG_STATE_CHANGE }
The types of callbacks that can be assocated with regions:
enum sr_register_callback_type {
SR_PRE_READ, SR_POST_READ, SR_PRE_WRITE, SR_POST_WRITE,
SR_PRE_READ, SR_POST_READ, SR_PRE_WRITE, SR_POST_WRITE
}
Functions
sc_register_field_base::sc_register_field_base (const char *nm)
sc_register_field_base::sc_register_field_base (const char *nm, const char *desc)
virtual sc_register_field_base::~sc_register_field_base ()
const char * sc_register_field_base::name () const
const char * sc_register_field_base::desc () const
virtual unsigned int sc_register_field_base::low_pos () const =0
virtual unsigned int sc_register_field_base::high_pos () const =0
virtual unsigned int sc_register_field_base::bit_width () const =0
virtual const char * sc_register_field_base::get_value_mnemonic () const =0
return mnemonic and desc, if any, for current value of field
virtual const char * sc_register_field_base::get_value_desc () const =0
virtual void sc_register_field_base::print (::std::ostream &os) const =0
sc_object style print() - print current value of field
sc_dt::uint64 sc_register_field_base::scireg_get_low_pos () const
If this region is a register field, these functions return low bit and high bit positions:
sc_dt::uint64 sc_register_field_base::scireg_get_high_pos () const
sc_dt::uint64 sc_register_field_base::scireg_get_bit_width () const
Get bit width and byte width of this region.
virtual scireg_ns::scireg_response sc_register_field_base::scireg_get_region_type (scireg_ns::scireg_region_type &t) const
Get the region_type of this region:
virtual scireg_ns::scireg_response sc_register_field_base::scireg_get_string_attribute (const char *&s, scireg_ns::scireg_string_attribute_type t) const
Get string attributes of type "t" associated with this region. The returned string is assigned to "s".
sc_rf_valuecode::sc_rf_valuecode (const ::std::string &mnemonic)
sc_rf_valuecode::sc_rf_valuecode (const std::string &mnemonic, const ::std::string &desc)
sc_rf_valuecode::~sc_rf_valuecode ()
const char * sc_rf_valuecode::mnemonic () const
const char * sc_rf_valuecode::desc () const
sc_register_field_b< T >::sc_register_field_b (const char *nm, sc_register_b< T > *r)
sc_register_field_b< T >::sc_register_field_b (const char *nm, sc_register_b< T > *r, const char *desc)
virtual sc_register_field_b< T >::~sc_register_field_b ()
const T & sc_register_field_b< T >::read () const
void sc_register_field_b< T >::write (const T &v)
void sc_register_field_b< T >::add_value_code (const T &v, const ::std::string &n)
For value-encoding.
void sc_register_field_b< T >::add_value_code (const T &v, const ::std::string &n, const ::std::string &desc)
const char * sc_register_field_b< T >::get_value_mnemonic () const
added by bpriya for debugging
const char * sc_register_field_b< T >::get_value_desc () const
virtual void sc_register_field_b< T >::print (::std::ostream &os) const
scireg_ns::scireg_response sc_register_field_b< T >::scireg_read (scireg_ns::vector_byte &v, sc_dt::uint64 size, sc_dt::uint64 offset) const
Read a vector of "size" bytes at given offset in this region:
scireg_ns::scireg_response sc_register_field_b< T >::scireg_write (const scireg_ns::vector_byte &v, sc_dt::uint64 size, sc_dt::uint64 offset)
Write a vector of "size" bytes at given offset in this region:
virtual const T & sc_register_field_b< T >::get_mask () const =0
virtual unsigned int sc_register_field_b< T >::get_shift_bits () const =0
const sc_rf_valuecode * sc_register_field_b< T >::get_value_code (const T &v) const
const char * sc_register_field_b< T >::get_value_mnemonic (const T &v) const
const char * sc_register_field_b< T >::get_value_desc (const T &v) const
sc_register_field< T, highpos, lowpos >::sc_register_field (const char *name, sc_register_b< T > *c)
sc_register_field< T, highpos, lowpos >::sc_register_field (const char *name, sc_register_b< T > *c, const char *desc)
sc_register_field< T, highpos, lowpos >::~sc_register_field ()
virtual unsigned int sc_register_field< T, highpos, lowpos >::low_pos () const
virtual unsigned int sc_register_field< T, highpos, lowpos >::high_pos () const
virtual unsigned int sc_register_field< T, highpos, lowpos >::bit_width () const
virtual const T & sc_register_field< T, highpos, lowpos >::get_mask () const
virtual unsigned int sc_register_field< T, highpos, lowpos >::get_shift_bits () const
sc_register_base::sc_register_base ()
sc_register_base::sc_register_base (const char *name)
sc_register_base::sc_register_base (const char *name, const char *desc)
virtual sc_register_base::~sc_register_base ()
virtual const char * sc_register_base::kind () const
const char * sc_register_base::desc () const
virtual sc_register_access_mode sc_register_base::access_mode () const =0
virtual const
sc_register_field_vec & sc_register_base::get_all_fields () const =0
static const char * sc_register_base::access_type_to_str (sc_register_access_type accessType)
static const char * sc_register_base::access_mode_to_str (sc_register_access_mode accessMode)
virtual scireg_ns::scireg_response sc_register_base::scireg_get_string_attribute (const char *&s, scireg_ns::scireg_string_attribute_type t) const
Get string attributes of type "t" associated with this region. The returned string is assigned to "s".
virtual scireg_ns::scireg_response sc_register_base::scireg_get_region_type (scireg_ns::scireg_region_type &t) const
Get the region_type of this region:
scireg_ns::scireg_response sc_register_base::scireg_get_child_regions (std::vector< scireg_ns::scireg_mapped_region > &mapped_regions, sc_dt::uint64 size, sc_dt::uint64 offset) const
virtual scireg_ns::scireg_response sc_register_base::scireg_get_parent_modules (std::vector< sc_core::sc_module * > &v) const
Get parent SystemC modules associated with this region.
sc_register_b< T >::sc_register_b (const char *name, const T &reset_val)
sc_register_b< T >::sc_register_b (const char *name, const T &reset_val, const char *desc)
virtual sc_register_b< T >::~sc_register_b ()
void sc_register_b< T >::reset ()
virtual const T & sc_register_b< T >::read () const
virtual void sc_register_b< T >::write (const T &)
void sc_register_b< T >::update ()
unsigned int sc_register_b< T >::number_of_fields () const
const sc_register_field_vec & sc_register_b< T >::get_all_fields () const
void sc_register_b< T >::add_field (sc_register_field_base *f)
virtual const T & sc_register_b< T >::mask_read (const T &, unsigned int) const
virtual void sc_register_b< T >::mask_write (const T &, const T &, unsigned int)
void sc_register_b< T >::check_and_init ()
virtual const T & sc_register_b< T >::get_mask () const
scireg_ns::scireg_response sc_register_b< T >::scireg_read (scireg_ns::vector_byte &v, sc_dt::uint64 size, sc_dt::uint64 offset) const
Read a vector of "size" bytes at given offset in this region:
scireg_ns::scireg_response sc_register_b< T >::scireg_write (const scireg_ns::vector_byte &v, sc_dt::uint64 size, sc_dt::uint64 offset)
Write a vector of "size" bytes at given offset in this region:
sc_dt::uint64 sc_register_b< T >::scireg_get_bit_width () const
Get bit width and byte width of this region.
scireg_ns::scireg_response sc_register_b< T >::scireg_add_callback (scireg_ns::scireg_callback &cb)
Add/Delete Callback objects associated with this region.
scireg_ns::scireg_response sc_register_b< T >::scireg_remove_callback (scireg_ns::scireg_callback &cb)
sc_register_bank_base::sc_register_bank_base ()
sc_register_bank_base::sc_register_bank_base (unsigned long long size)
sc_register_bank_base::sc_register_bank_base (const char *name, const unsigned long long size)
virtual sc_register_bank_base::~sc_register_bank_base ()
virtual const char * sc_register_bank_base::kind () const
unsigned long long sc_register_bank_base::size () const
bool sc_register_bank_base::add_associate_busport (sc_object *busport)
virtual const sc_register_vec & sc_register_bank_base::get_registers () const =0
virtual void sc_register_bank_base::print_offset (sc_register_base *reg,::std::ostream &os) const =0
const std::vector< sc_object * > & sc_register_bank_base::get_associate_busports () const
virtual scireg_ns::scireg_response sc_register_bank_base::scireg_get_string_attribute (const char *&s, scireg_ns::scireg_string_attribute_type t) const
Get string attributes of type "t" associated with this region. The returned string is assigned to "s".
virtual sc_dt::uint64 sc_register_bank_base::scireg_get_byte_width () const
virtual scireg_ns::scireg_response sc_register_bank_base::scireg_get_region_type (scireg_ns::scireg_region_type &t) const
Get the region_type of this region:
virtual scireg_ns::scireg_response sc_register_bank_base::scireg_get_target_sockets (::std::vector< sc_core::sc_object * > &v) const
virtual scireg_ns::scireg_response sc_register_bank_base::scireg_get_parent_modules (std::vector< sc_core::sc_module * > &v) const
Get parent SystemC modules associated with this region.
sc_register_bank< ADDR_TYPE, DATA_TYPE >::sc_register_bank (const unsigned long long size)
sc_register_bank< ADDR_TYPE, DATA_TYPE >::sc_register_bank (const char *name, const unsigned long long size)
virtual sc_register_bank< ADDR_TYPE, DATA_TYPE >::~sc_register_bank ()
virtual bool sc_register_bank< ADDR_TYPE, DATA_TYPE >::bus_read (const ADDR_TYPE offset, DATA_TYPE &data) const =0
virtual bool sc_register_bank< ADDR_TYPE, DATA_TYPE >::bus_write (const ADDR_TYPE offset, const DATA_TYPE data)=0
virtual bool sc_register_bank< ADDR_TYPE, DATA_TYPE >::bus_read_dbg (const ADDR_TYPE offset, DATA_TYPE &data) const =0
virtual bool sc_register_bank< ADDR_TYPE, DATA_TYPE >::bus_write_dbg (const ADDR_TYPE offset, const DATA_TYPE data)=0
virtual bool sc_register_bank< ADDR_TYPE, DATA_TYPE >::is_valid_offset (const ADDR_TYPE offset) const =0
virtual bool sc_register_bank< ADDR_TYPE, DATA_TYPE >::supports_action_type (const ADDR_TYPE offset, const sc_register_access_type accType)=0
virtual sc_register_base * sc_register_bank< ADDR_TYPE, DATA_TYPE >::get_register (const ADDR_TYPE offset)=0
virtual bool sc_register_bank< ADDR_TYPE, DATA_TYPE >::get_offset (sc_register_base *reg, ADDR_TYPE &offset) const =0
virtual void sc_register_bank< ADDR_TYPE, DATA_TYPE >::print_offset (sc_register_base *reg,::std::ostream &os) const
scireg_ns::scireg_response sc_register_bank< ADDR_TYPE, DATA_TYPE >::scireg_get_child_regions (std::vector< scireg_ns::scireg_mapped_region > &mapped_regions, sc_dt::uint64 size, sc_dt::uint64 offset) const
sc_register< unsigned char, M >::sc_register (const char *name, const unsigned char &reset_val)
sc_register< unsigned char, M >::sc_register (const char *name, const unsigned char &reset_val, const char *desc)
virtual sc_register_access_mode sc_register< unsigned char, M >::access_mode () const
void sc_register< unsigned char, M >::before_end_of_elaboration ()
sc_register< unsigned short, M >::sc_register (const char *name, const unsigned short &reset_val)
sc_register< unsigned short, M >::sc_register (const char *name, const unsigned short &reset_val, const char *desc)
virtual sc_register_access_mode sc_register< unsigned short, M >::access_mode () const
void sc_register< unsigned short, M >::before_end_of_elaboration ()
sc_register< unsigned int, M >::sc_register (const char *name, const unsigned int &reset_val)
sc_register< unsigned int, M >::sc_register (const char *name, const unsigned int &reset_val, const char *desc)
virtual sc_register_access_mode sc_register< unsigned int, M >::access_mode () const
void sc_register< unsigned int, M >::before_end_of_elaboration ()
sc_register< unsigned long long, M >::sc_register (const char *name, const unsigned long long &reset_val)
sc_register< unsigned long long, M >::sc_register (const char *name, const unsigned long long &reset_val, const char *desc)
virtual sc_register_access_mode sc_register< unsigned long long, M >::access_mode () const
void sc_register< unsigned long long, M >::before_end_of_elaboration ()
static void scireg_ns::scireg_tool_registry::add_tool (scireg_notification_if &notification)
static void scireg_ns::scireg_tool_registry::remove_tool (scireg_notification_if &notification)
static void scireg_ns::scireg_tool_registry::add_region (scireg_region_if &region)
static void scireg_ns::scireg_tool_registry::remove_region (scireg_region_if &region)
static void scireg_ns::scireg_tool_registry::check_allocation ()
static void scireg_ns::scireg_tool_registry::destroy ()
Variables
::std::string sc_register_field_base::m_name
::std::string sc_register_field_base::m_desc
::std::string sc_rf_valuecode::m_mnemonic
::std::string sc_rf_valuecode::m_desc
sc_register_b< T > * sc_register_field_b< T >::m_reg
::std::map< T, sc_rf_valuecode * > sc_register_field_b< T >::m_value_encoding_map
Value-encoding map.
T sc_register_field< T, highpos, lowpos >::m_mask
::std::string sc_register_base::m_desc
T sc_register_b< T >::m_cur_val
T sc_register_b< T >::m_reset_val
sc_core::sc_event * sc_register_b< T >::m_probe_event
::std::vector
< scireg_ns::scireg_callback * > sc_register_b< T >::scireg_callback_vec
T sc_register_b< T >::m_mask
sc_register_field_vec sc_register_b< T >::m_fields
unsigned long long sc_register_bank_base::m_size
::std::vector
< sc_core::sc_object * > sc_register_bank_base::m_associate_busports
static std::vector
< scireg_notification_if * > * scireg_ns::scireg_tool_registry::tool_vec_ptr = 0
Friends
class sc_register_b< T >::sc_register_field_b< T >
Detailed Description
Macro Definition Documentation
#define MAX_DESC_LENGTH 64
Referenced by sc_register_base::sc_register_base(), sc_register_field_base::sc_register_field_base(), and sc_rf_valuecode::sc_rf_valuecode().
Typedef Documentation
typedef ::std::vector<sc_register_field_base *> sc_register_field_vec
Vector of register field.
typedef std::vector<sc_register_base *> sc_register_vec
Register Bank.
Enumeration Type Documentation
enum sc_register_access_mode
Register Access Mode.
Enumerator
SC_REG_RW_ACCESS
SC_REG_RO_ACCESS
SC_REG_WO_ACCESS
enum sc_register_access_type
Enumerator
SC_REG_UNKNOWN_ACCESS_TYPE
SC_REG_READ
SC_REG_WRITE
enum scireg_ns::scireg_bit_attributes_type
Attributes assocated with individual bits within regions:
Enumerator
SCIREG_READABLE
< Bit is readable from perspective of HW Bus
SCIREG_WRITEABLE
< Bit is writeable from perspective of HW Bus
enum scireg_ns::scireg_callback_type
The types of callbacks that can be assocated with regions:
Enumerator
SCIREG_READ_ACCESS
< Execute callback when read occurs in region - does not include reads executed via DMI
SCIREG_WRITE_ACCESS
< Execute callback when write occurs in region - does not include writes executed via DMI
SCIREG_STATE_CHANGE
< Execute callback when there is ANY kind of state change associated with region
enum scireg_ns::scireg_region_type
A region represents a SystemC object that occupies a region (ie portion) of the address space within a SystemC model. The SCIREG API uses a single interface (scireg_region_if) to represent all types of regions. The types of regions are:
Enumerator
SCIREG_MEMORY
< A Memory
SCIREG_BANK
< A Register Bank
SCIREG_REGISTER
< A Register
SCIREG_FIELD
< A Register Field
SCIREG_STRING_REGISTER
< A string register (i.e. an object in a model which contains textual string values to be made available to tools)
enum scireg_ns::scireg_response
SCIREG API response codes:
Enumerator
SCIREG_SUCCESS
< Function succeeded.
SCIREG_FAILURE
< Function failed at runtime.
SCIREG_UNSUPPORTED
< Function failed since it is unsupported at compile time.
enum scireg_ns::scireg_string_attribute_type
String attributes associated with region objects:
Enumerator
SCIREG_NAME
< Name of object (typically short identifier, not fully rooted name)
SCIREG_DESCRIPTION
< Textual description (typically short phrase or sentence).
SCIREG_STRING_VALUE
< String Value stored in a string register
enum sr_register_callback_type
Enumerator
SR_PRE_READ
SR_POST_READ
SR_PRE_WRITE
SR_POST_WRITE
SR_PRE_READ
SR_POST_READ
SR_PRE_WRITE
SR_POST_WRITE
Function Documentation
virtual sc_register_access_mode sc_register_base::access_mode () const pure virtual
Implemented in sc_register< unsigned long long, M >, sc_register< unsigned int, M >, sc_register< unsigned short, M >, sc_register< unsigned char, M >, sr_register< DATA_TYPE >, sr_register< unsigned int >, sr_register< DATA_TYPE >, and sr_register< unsigned int >.
template<sc_register_access_mode M> virtual sc_register_access_mode sc_register< unsigned char, M >::access_mode () const inline virtual
Implements sc_register_base.
References M.
template<sc_register_access_mode M> virtual sc_register_access_mode sc_register< unsigned short, M >::access_mode () const inline virtual
Implements sc_register_base.
References M.
template<sc_register_access_mode M> virtual sc_register_access_mode sc_register< unsigned int, M >::access_mode () const inline virtual
Implements sc_register_base.
References M.
template<sc_register_access_mode M> virtual sc_register_access_mode sc_register< unsigned long long, M >::access_mode () const inline virtual
Implements sc_register_base.
References M.
const char * sc_register_base::access_mode_to_str (sc_register_access_mode accessMode) inline static
References SC_REG_RO_ACCESS, SC_REG_RW_ACCESS, and SC_REG_WO_ACCESS.
const char * sc_register_base::access_type_to_str (sc_register_access_type accessType) inline static
References SC_REG_READ, and SC_REG_WRITE.
bool sc_register_bank_base::add_associate_busport (sc_core::sc_object * obj) inline
References sc_register_bank_base::m_associate_busports.
Referenced by APBSlave::APBSlave().
template<typename T> void sc_register_b< T >::add_field (sc_register_field_base * f) inline protected
void scireg_ns::scireg_tool_registry::add_region (scireg_region_if & region) static
References scireg_ns::scireg_tool_registry::check_allocation(), and scireg_ns::scireg_tool_registry::tool_vec_ptr.
Referenced by scireg_ns::scireg_region_if::scireg_region_if().
void scireg_ns::scireg_tool_registry::add_tool (scireg_notification_if & notification) static
References scireg_ns::scireg_tool_registry::check_allocation(), and scireg_ns::scireg_tool_registry::tool_vec_ptr.
template<typename T> void sc_register_field_b< T >::add_value_code (const T & v, const ::std::string & n) inline
For value-encoding.
References d.
template<typename T> void sc_register_field_b< T >::add_value_code (const T & v, const ::std::string & n, const ::std::string & desc) inline
template<sc_register_access_mode M> void sc_register< unsigned char, M >::before_end_of_elaboration () inline
References sc_register_b< T >::check_and_init().
template<sc_register_access_mode M> void sc_register< unsigned short, M >::before_end_of_elaboration () inline
References sc_register_b< T >::check_and_init().
template<sc_register_access_mode M> void sc_register< unsigned int, M >::before_end_of_elaboration () inline
References sc_register_b< T >::check_and_init().
template<sc_register_access_mode M> void sc_register< unsigned long long, M >::before_end_of_elaboration () inline
References sc_register_b< T >::check_and_init().
virtual unsigned int sc_register_field_base::bit_width () const pure virtual
Implemented in sc_register_field< T, highpos, lowpos >, sr_register_field< T >, sr_register_field< unsigned int >, sr_register_field< DATA_TYPE >, sr_register_field< T >, sr_register_field< unsigned int >, and sr_register_field< DATA_TYPE >.
template<typename T , unsigned int highpos, unsigned int lowpos> virtual unsigned int sc_register_field< T, highpos, lowpos >::bit_width () const inline virtual
Implements sc_register_field_base.
template<typename ADDR_TYPE, typename DATA_TYPE> virtual bool sc_register_bank< ADDR_TYPE, DATA_TYPE >::bus_read (const ADDR_TYPE offset, DATA_TYPE & data) const pure virtual
Implemented in sr_register_bank< ADDR_TYPE, DATA_TYPE >, sr_register_bank< unsigned int, unsigned int >, sr_register_bank< ADDR_TYPE, DATA_TYPE >, and sr_register_bank< unsigned int, unsigned int >.
template<typename ADDR_TYPE, typename DATA_TYPE> virtual bool sc_register_bank< ADDR_TYPE, DATA_TYPE >::bus_read_dbg (const ADDR_TYPE offset, DATA_TYPE & data) const pure virtual
Implemented in sr_register_bank< ADDR_TYPE, DATA_TYPE >, sr_register_bank< unsigned int, unsigned int >, sr_register_bank< ADDR_TYPE, DATA_TYPE >, and sr_register_bank< unsigned int, unsigned int >.
template<typename ADDR_TYPE, typename DATA_TYPE> virtual bool sc_register_bank< ADDR_TYPE, DATA_TYPE >::bus_write (const ADDR_TYPE offset, const DATA_TYPE data) pure virtual
Implemented in sr_register_bank< ADDR_TYPE, DATA_TYPE >, sr_register_bank< unsigned int, unsigned int >, sr_register_bank< ADDR_TYPE, DATA_TYPE >, and sr_register_bank< unsigned int, unsigned int >.
template<typename ADDR_TYPE, typename DATA_TYPE> virtual bool sc_register_bank< ADDR_TYPE, DATA_TYPE >::bus_write_dbg (const ADDR_TYPE offset, const DATA_TYPE data) pure virtual
Implemented in sr_register_bank< ADDR_TYPE, DATA_TYPE >, sr_register_bank< unsigned int, unsigned int >, sr_register_bank< ADDR_TYPE, DATA_TYPE >, and sr_register_bank< unsigned int, unsigned int >.
void scireg_ns::scireg_tool_registry::check_allocation () static protected
References scireg_ns::scireg_tool_registry::destroy(), and scireg_ns::scireg_tool_registry::tool_vec_ptr.
Referenced by scireg_ns::scireg_tool_registry::add_region(), scireg_ns::scireg_tool_registry::add_tool(), scireg_ns::scireg_tool_registry::remove_region(), and scireg_ns::scireg_tool_registry::remove_tool().
template<typename T > void sc_register_b< T >::check_and_init () inline protected
References core.waf.cmake::f(), sc_register_field_base::high_pos(), i, sc_register_field_base::low_pos(), and pysc::api::cci::write().
Referenced by sc_register< unsigned char, M >::before_end_of_elaboration(), sc_register< unsigned short, M >::before_end_of_elaboration(), sc_register< unsigned int, M >::before_end_of_elaboration(), and sc_register< unsigned long long, M >::before_end_of_elaboration().
const char* sc_register_field_base::desc () const inline
References sc_register_field_base::m_desc.
Referenced by sc_register_field_base::scireg_get_string_attribute().
const char* sc_rf_valuecode::desc () const inline
References sc_rf_valuecode::m_desc.
Referenced by sc_register_field_b< T >::get_value_desc().
const char* sc_register_base::desc () const inline
References sc_register_base::m_desc.
Referenced by sc_register_base::scireg_get_string_attribute().
void scireg_ns::scireg_tool_registry::destroy () static protected
References scireg_ns::scireg_tool_registry::tool_vec_ptr.
Referenced by scireg_ns::scireg_tool_registry::check_allocation().
virtual const sc_register_field_vec& sc_register_base::get_all_fields () const pure virtual
Implemented in sc_register_b< T >, sc_register_b< unsigned long long >, sc_register_b< unsigned int >, sc_register_b< unsigned short >, sc_register_b< DATA_TYPE >, and sc_register_b< unsigned char >.
Referenced by sc_register_base::scireg_get_child_regions().
template<typename T> const sc_register_field_vec& sc_register_b< T >::get_all_fields () const inline virtual
Implements sc_register_base.
const std::vector<sc_object*>& sc_register_bank_base::get_associate_busports () const inline protected
References sc_register_bank_base::m_associate_busports.
Referenced by sc_register_bank_base::scireg_get_target_sockets().
template<typename T> virtual const T& sc_register_field_b< T >::get_mask () const protected pure virtual
Implemented in sc_register_field< T, highpos, lowpos >, sr_register_field< T >, sr_register_field< unsigned int >, sr_register_field< DATA_TYPE >, sr_register_field< T >, sr_register_field< unsigned int >, and sr_register_field< DATA_TYPE >.
template<typename T , unsigned int highpos, unsigned int lowpos> virtual const T& sc_register_field< T, highpos, lowpos >::get_mask () const inline protected virtual
Implements sc_register_field_b< T >.
References sc_register_field< T, highpos, lowpos >::m_mask.
template<typename T> virtual const T& sc_register_b< T >::get_mask () const inline virtual
template<typename ADDR_TYPE, typename DATA_TYPE> virtual bool sc_register_bank< ADDR_TYPE, DATA_TYPE >::get_offset (sc_register_base * reg, ADDR_TYPE & offset) const protected pure virtual
Implemented in sr_register_bank< unsigned int, unsigned int >, and sr_register_bank< unsigned int, unsigned int >.
Referenced by sc_register_bank< unsigned int, unsigned int >::scireg_get_child_regions().
template<typename ADDR_TYPE, typename DATA_TYPE> virtual sc_register_base* sc_register_bank< ADDR_TYPE, DATA_TYPE >::get_register (const ADDR_TYPE offset) protected pure virtual
Implemented in sr_register_bank< ADDR_TYPE, DATA_TYPE >, sr_register_bank< unsigned int, unsigned int >, sr_register_bank< ADDR_TYPE, DATA_TYPE >, and sr_register_bank< unsigned int, unsigned int >.
virtual const sc_register_vec& sc_register_bank_base::get_registers () const protected pure virtual
Implemented in sr_register_bank< ADDR_TYPE, DATA_TYPE >, sr_register_bank< unsigned int, unsigned int >, sr_register_bank< ADDR_TYPE, DATA_TYPE >, and sr_register_bank< unsigned int, unsigned int >.
Referenced by sc_register_bank< unsigned int, unsigned int >::scireg_get_child_regions().
template<typename T> virtual unsigned int sc_register_field_b< T >::get_shift_bits () const protected pure virtual
Implemented in sc_register_field< T, highpos, lowpos >, sr_register_field< T >, sr_register_field< unsigned int >, sr_register_field< DATA_TYPE >, sr_register_field< T >, sr_register_field< unsigned int >, and sr_register_field< DATA_TYPE >.
template<typename T , unsigned int highpos, unsigned int lowpos> virtual unsigned int sc_register_field< T, highpos, lowpos >::get_shift_bits () const inline protected virtual
Implements sc_register_field_b< T >.
References sc_register_field< T, highpos, lowpos >::low_pos().
template<typename T> const sc_rf_valuecode * sc_register_field_b< T >::get_value_code (const T & v) const inline protected
For value-encoding A field's value-encoding is optional. Furthermore, description of a value-encoding is optional.
virtual const char* sc_register_field_base::get_value_desc () const pure virtual
Implemented in sc_register_field_b< T >, sc_register_field_b< unsigned int >, and sc_register_field_b< DATA_TYPE >.
template<typename T> const char* sc_register_field_b< T >::get_value_desc () const inline virtual
Implements sc_register_field_base.
Referenced by sc_register_field_b< DATA_TYPE >::get_value_desc().
template<typename T> const char * sc_register_field_b< T >::get_value_desc (const T & v) const inline protected
References sc_rf_valuecode::desc().
virtual const char* sc_register_field_base::get_value_mnemonic () const pure virtual
return mnemonic and desc, if any, for current value of field
Implemented in sc_register_field_b< T >, sc_register_field_b< unsigned int >, and sc_register_field_b< DATA_TYPE >.
template<typename T> const char* sc_register_field_b< T >::get_value_mnemonic () const inline virtual
added by bpriya for debugging
return mnemonic and desc, if any, for current value of field
Implements sc_register_field_base.
Referenced by sc_register_field_b< DATA_TYPE >::get_value_mnemonic().
template<typename T> const char * sc_register_field_b< T >::get_value_mnemonic (const T & v) const inline protected
References sc_rf_valuecode::mnemonic().
virtual unsigned int sc_register_field_base::high_pos () const pure virtual
Implemented in sc_register_field< T, highpos, lowpos >, sr_register_field< T >, sr_register_field< unsigned int >, sr_register_field< DATA_TYPE >, sr_register_field< T >, sr_register_field< unsigned int >, and sr_register_field< DATA_TYPE >.
Referenced by sc_register_b< T >::check_and_init(), sc_register_field_base::scireg_get_bit_width(), and sc_register_field_base::scireg_get_high_pos().
template<typename T , unsigned int highpos, unsigned int lowpos> virtual unsigned int sc_register_field< T, highpos, lowpos >::high_pos () const inline virtual
Implements sc_register_field_base.
template<typename ADDR_TYPE, typename DATA_TYPE> virtual bool sc_register_bank< ADDR_TYPE, DATA_TYPE >::is_valid_offset (const ADDR_TYPE offset) const pure virtual
Implemented in sr_register_bank< ADDR_TYPE, DATA_TYPE >, sr_register_bank< unsigned int, unsigned int >, sr_register_bank< ADDR_TYPE, DATA_TYPE >, and sr_register_bank< unsigned int, unsigned int >.
virtual const char* sc_register_base::kind () const inline virtual
virtual const char* sc_register_bank_base::kind () const inline virtual
virtual unsigned int sc_register_field_base::low_pos () const pure virtual
Implemented in sc_register_field< T, highpos, lowpos >, sr_register_field< T >, sr_register_field< unsigned int >, sr_register_field< DATA_TYPE >, sr_register_field< T >, sr_register_field< unsigned int >, and sr_register_field< DATA_TYPE >.
Referenced by sc_register_b< T >::check_and_init(), sc_register_field_base::scireg_get_bit_width(), and sc_register_field_base::scireg_get_low_pos().
template<typename T , unsigned int highpos, unsigned int lowpos> virtual unsigned int sc_register_field< T, highpos, lowpos >::low_pos () const inline virtual
Implements sc_register_field_base.
Referenced by sc_register_field< T, highpos, lowpos >::get_shift_bits().
template<typename T> const T & sc_register_b< T >::mask_read (const T & mask, unsigned int rightShiftBits) const inline protected virtual
template<typename T> void sc_register_b< T >::mask_write (const T & v, const T & mask, unsigned int leftShiftBits) inline protected virtual
References pysc::api::cci::write().
const char* sc_rf_valuecode::mnemonic () const inline
References sc_rf_valuecode::m_mnemonic.
Referenced by sc_register_field_b< T >::get_value_mnemonic().
const char* sc_register_field_base::name () const inline
References sc_register_field_base::m_name.
Referenced by core.tools.generator.item.enum.IntegerItem::load(), usi.SCCommand::register(), and sc_register_field_base::scireg_get_string_attribute().
template<typename T> unsigned int sc_register_b< T >::number_of_fields () const inline
virtual void sc_register_field_base::print (::std::ostream & os) const pure virtual
sc_object style print() - print current value of field
Implemented in sc_register_field_b< T >, sc_register_field_b< T >, sc_register_field_b< unsigned int >, and sc_register_field_b< DATA_TYPE >.
template<typename T> virtual void sc_register_field_b< T >::print (::std::ostream & os) const inline virtual
sc_object style print() - print current value of field using hex format
Implements sc_register_field_base.
virtual void sc_register_bank_base::print_offset (sc_register_base * reg, ::std::ostream & os) const protected pure virtual
Implemented in sc_register_bank< ADDR_TYPE, DATA_TYPE >, and sc_register_bank< unsigned int, unsigned int >.
template<typename ADDR_TYPE , typename DATA_TYPE > void sc_register_bank< ADDR_TYPE, DATA_TYPE >::print_offset (sc_register_base * reg, ::std::ostream & os) const inline protected virtual
Implements sc_register_bank_base.
template<typename T > const T & sc_register_field_b< T >::read () const inline
Extract field value. value of the field is returned in [(bit_width-1):0] of T. The value returned is only valid before the next read of any field of the containing register.
Referenced by sc_register_field_b< DATA_TYPE >::get_value_desc(), sc_register_field_b< DATA_TYPE >::get_value_mnemonic(), sc_register_field_b< DATA_TYPE >::print(), and sc_register_field_b< DATA_TYPE >::scireg_read().
template<class T > const T & sc_register_b< T >::read () const inline virtual
Referenced by sc_register_b< unsigned char >::scireg_read().
void scireg_ns::scireg_tool_registry::remove_region (scireg_region_if & region) static
References scireg_ns::scireg_tool_registry::check_allocation(), and scireg_ns::scireg_tool_registry::tool_vec_ptr.
Referenced by scireg_ns::scireg_region_if::~scireg_region_if().
void scireg_ns::scireg_tool_registry::remove_tool (scireg_notification_if & notification) static
References scireg_ns::scireg_tool_registry::check_allocation(), find(), and scireg_ns::scireg_tool_registry::tool_vec_ptr.
template<typename T> void sc_register_b< T >::reset () inline
template<sc_register_access_mode M> sc_register< unsigned char, M >::sc_register (const char * name, const unsigned char & reset_val) inline
template<sc_register_access_mode M> sc_register< unsigned char, M >::sc_register (const char * name, const unsigned char & reset_val, const char * desc) inline
template<sc_register_access_mode M> sc_register< unsigned short, M >::sc_register (const char * name, const unsigned short & reset_val) inline
template<sc_register_access_mode M> sc_register< unsigned short, M >::sc_register (const char * name, const unsigned short & reset_val, const char * desc) inline
template<sc_register_access_mode M> sc_register< unsigned int, M >::sc_register (const char * name, const unsigned int & reset_val) inline
template<sc_register_access_mode M> sc_register< unsigned int, M >::sc_register (const char * name, const unsigned int & reset_val, const char * desc) inline
template<sc_register_access_mode M> sc_register< unsigned long long, M >::sc_register (const char * name, const unsigned long long & reset_val) inline
template<sc_register_access_mode M> sc_register< unsigned long long, M >::sc_register (const char * name, const unsigned long long & reset_val, const char * desc) inline
template<typename T> sc_register_b< T >::sc_register_b (const char * name, const T & reset_val) inline
template<typename T> sc_register_b< T >::sc_register_b (const char * name, const T & reset_val, const char * desc) inline
template<typename ADDR_TYPE, typename DATA_TYPE> sc_register_bank< ADDR_TYPE, DATA_TYPE >::sc_register_bank (const unsigned long long size) inline
template<typename ADDR_TYPE, typename DATA_TYPE> sc_register_bank< ADDR_TYPE, DATA_TYPE >::sc_register_bank (const char * name, const unsigned long long size) inline
sc_register_bank_base::sc_register_bank_base () inline
sc_register_bank_base::sc_register_bank_base (unsigned long long size) inline
sc_register_bank_base::sc_register_bank_base (const char * name, const unsigned long long size) inline
sc_register_base::sc_register_base () inline
sc_register_base::sc_register_base (const char * name) inline
sc_register_base::sc_register_base (const char * name, const char * desc) inline
References d, sc_register_base::m_desc, and MAX_DESC_LENGTH.
template<typename T , unsigned int highpos, unsigned int lowpos> sc_register_field< T, highpos, lowpos >::sc_register_field (const char * name, sc_register_b< T > * c) inline
template<typename T , unsigned int highpos, unsigned int lowpos> sc_register_field< T, highpos, lowpos >::sc_register_field (const char * name, sc_register_b< T > * c, const char * desc) inline
template<typename T> sc_register_field_b< T >::sc_register_field_b (const char * nm, sc_register_b< T > * r) inline
template<typename T> sc_register_field_b< T >::sc_register_field_b (const char * nm, sc_register_b< T > * r, const char * desc) inline
sc_register_field_base::sc_register_field_base (const char * nm) inline
sc_register_field_base::sc_register_field_base (const char * nm, const char * desc) inline
References d, sc_register_field_base::m_desc, and MAX_DESC_LENGTH.
sc_rf_valuecode::sc_rf_valuecode (const ::std::string & mnemonic) inline
sc_rf_valuecode::sc_rf_valuecode (const std::string & mnemonic, const ::std::string & desc) inline
References sc_rf_valuecode::m_desc, and MAX_DESC_LENGTH.
template<typename T> scireg_ns::scireg_response sc_register_b< T >::scireg_add_callback (scireg_ns::scireg_callback & cb) inline virtual
Add/Delete Callback objects associated with this region.
Reimplemented from scireg_ns::scireg_region_if.
sc_dt::uint64 sc_register_field_base::scireg_get_bit_width () const inline protected virtual
Get bit width and byte width of this region.
Reimplemented from scireg_ns::scireg_region_if.
References sc_register_field_base::high_pos(), and sc_register_field_base::low_pos().
template<typename T> sc_dt::uint64 sc_register_b< T >::scireg_get_bit_width () const inline virtual
Get bit width and byte width of this region.
Reimplemented from scireg_ns::scireg_region_if.
virtual sc_dt::uint64 sc_register_bank_base::scireg_get_byte_width () const inline protected virtual
Reimplemented from scireg_ns::scireg_region_if.
References sc_register_bank_base::size().
scireg_ns::scireg_response sc_register_base::scireg_get_child_regions (std::vector< scireg_ns::scireg_mapped_region > & mapped_regions, sc_dt::uint64 size, sc_dt::uint64 offset) const inline protected virtual
Get child regions mapped into this region, by returning a mapped region object representing each mapping. The size and offset parameters can be used to constrain the range of the search
Reimplemented from scireg_ns::scireg_region_if.
References sc_register_base::get_all_fields(), scireg_ns::scireg_mapped_region::name, scireg_ns::scireg_mapped_region::offset, scireg_ns::scireg_mapped_region::region, s, scireg_ns::SCIREG_FAILURE, scireg_ns::SCIREG_NAME, scireg_ns::scireg_region_if::scireg_region_if(), and scireg_ns::SCIREG_SUCCESS.
template<typename ADDR_TYPE, typename DATA_TYPE> scireg_ns::scireg_response sc_register_bank< ADDR_TYPE, DATA_TYPE >::scireg_get_child_regions (std::vector< scireg_ns::scireg_mapped_region > & mapped_regions, sc_dt::uint64 size, sc_dt::uint64 offset) const inline protected virtual
Get child regions mapped into this region, by returning a mapped region object representing each mapping. The size and offset parameters can be used to constrain the range of the search
Reimplemented from scireg_ns::scireg_region_if.
sc_dt::uint64 sc_register_field_base::scireg_get_high_pos () const inline protected virtual
Reimplemented from scireg_ns::scireg_region_if.
References sc_register_field_base::high_pos().
sc_dt::uint64 sc_register_field_base::scireg_get_low_pos () const inline protected virtual
If this region is a register field, these functions return low bit and high bit positions:
Reimplemented from scireg_ns::scireg_region_if.
References sc_register_field_base::low_pos().
virtual scireg_ns::scireg_response sc_register_base::scireg_get_parent_modules (std::vector< sc_core::sc_module * > & v) const inline protected virtual
Get parent SystemC modules associated with this region.
Reimplemented from scireg_ns::scireg_region_if.
References scireg_ns::SCIREG_SUCCESS.
virtual scireg_ns::scireg_response sc_register_bank_base::scireg_get_parent_modules (std::vector< sc_core::sc_module * > & v) const inline protected virtual
Get parent SystemC modules associated with this region.
Reimplemented from scireg_ns::scireg_region_if.
References scireg_ns::SCIREG_SUCCESS.
virtual scireg_ns::scireg_response sc_register_field_base::scireg_get_region_type (scireg_ns::scireg_region_type & t) const inline protected virtual
Get the region_type of this region:
Reimplemented from scireg_ns::scireg_region_if.
References scireg_ns::SCIREG_FIELD, and scireg_ns::SCIREG_SUCCESS.
virtual scireg_ns::scireg_response sc_register_base::scireg_get_region_type (scireg_ns::scireg_region_type & t) const inline protected virtual
Get the region_type of this region:
Reimplemented from scireg_ns::scireg_region_if.
References scireg_ns::SCIREG_REGISTER, and scireg_ns::SCIREG_SUCCESS.
virtual scireg_ns::scireg_response sc_register_bank_base::scireg_get_region_type (scireg_ns::scireg_region_type & t) const inline protected virtual
Get the region_type of this region:
Reimplemented from scireg_ns::scireg_region_if.
References scireg_ns::SCIREG_BANK, and scireg_ns::SCIREG_SUCCESS.
virtual scireg_ns::scireg_response sc_register_field_base::scireg_get_string_attribute (const char *& s, scireg_ns::scireg_string_attribute_type t) const inline protected virtual
Get string attributes of type "t" associated with this region. The returned string is assigned to "s".
Reimplemented from scireg_ns::scireg_region_if.
References sc_register_field_base::desc(), sc_register_field_base::name(), scireg_ns::SCIREG_DESCRIPTION, scireg_ns::SCIREG_FAILURE, scireg_ns::SCIREG_NAME, scireg_ns::SCIREG_STRING_VALUE, and scireg_ns::SCIREG_SUCCESS.
virtual scireg_ns::scireg_response sc_register_base::scireg_get_string_attribute (const char *& s, scireg_ns::scireg_string_attribute_type t) const inline protected virtual
Get string attributes of type "t" associated with this region. The returned string is assigned to "s".
Reimplemented from scireg_ns::scireg_region_if.
References sc_register_base::desc(), setup::name, scireg_ns::SCIREG_DESCRIPTION, scireg_ns::SCIREG_FAILURE, scireg_ns::SCIREG_NAME, scireg_ns::SCIREG_STRING_VALUE, and scireg_ns::SCIREG_SUCCESS.
virtual scireg_ns::scireg_response sc_register_bank_base::scireg_get_string_attribute (const char *& s, scireg_ns::scireg_string_attribute_type t) const inline protected virtual
Get string attributes of type "t" associated with this region. The returned string is assigned to "s".
Reimplemented from scireg_ns::scireg_region_if.
References setup::name, scireg_ns::SCIREG_FAILURE, scireg_ns::SCIREG_NAME, and scireg_ns::SCIREG_SUCCESS.
virtual scireg_ns::scireg_response sc_register_bank_base::scireg_get_target_sockets (::std::vector< sc_core::sc_object * > & v) const inline protected virtual
References sc_register_bank_base::get_associate_busports(), and scireg_ns::SCIREG_SUCCESS.
template<typename T> scireg_ns::scireg_response sc_register_field_b< T >::scireg_read (scireg_ns::vector_byte & v, sc_dt::uint64 size, sc_dt::uint64 offset) const inline virtual
Read a vector of "size" bytes at given offset in this region:
Reimplemented from scireg_ns::scireg_region_if.
template<typename T> scireg_ns::scireg_response sc_register_b< T >::scireg_read (scireg_ns::vector_byte & v, sc_dt::uint64 size, sc_dt::uint64 offset) const inline virtual
Read a vector of "size" bytes at given offset in this region:
Reimplemented from scireg_ns::scireg_region_if.
template<typename T> scireg_ns::scireg_response sc_register_b< T >::scireg_remove_callback (scireg_ns::scireg_callback & cb) inline virtual
Reimplemented from scireg_ns::scireg_region_if.
template<typename T> scireg_ns::scireg_response sc_register_field_b< T >::scireg_write (const scireg_ns::vector_byte & v, sc_dt::uint64 size, sc_dt::uint64 offset) inline virtual
Write a vector of "size" bytes at given offset in this region:
Reimplemented from scireg_ns::scireg_region_if.
template<typename T> scireg_ns::scireg_response sc_register_b< T >::scireg_write (const scireg_ns::vector_byte & v, sc_dt::uint64 size, sc_dt::uint64 offset) inline virtual
Write a vector of "size" bytes at given offset in this region:
Reimplemented from scireg_ns::scireg_region_if.
unsigned long long sc_register_bank_base::size () const inline
References sc_register_bank_base::m_size.
Referenced by sr_register_bank< unsigned int, unsigned int >::scireg_get_bit_width(), sc_register_bank_base::scireg_get_byte_width(), sr_register_bank< unsigned int, unsigned int >::scireg_read(), and sr_register_bank< unsigned int, unsigned int >::scireg_write().
template<typename ADDR_TYPE, typename DATA_TYPE> virtual bool sc_register_bank< ADDR_TYPE, DATA_TYPE >::supports_action_type (const ADDR_TYPE offset, const sc_register_access_type accType) pure virtual
Implemented in sr_register_bank< ADDR_TYPE, DATA_TYPE >, sr_register_bank< unsigned int, unsigned int >, sr_register_bank< ADDR_TYPE, DATA_TYPE >, and sr_register_bank< unsigned int, unsigned int >.
template<typename T> void sc_register_b< T >::update () inline
template<typename T> void sc_register_field_b< T >::write (const T & v) inline
Write [(bit_width-1):0] of T to field. The written value is retrievable after the register is updated.
Referenced by usi.shell.console.Console::interact(), and sc_register_field_b< DATA_TYPE >::scireg_write().
template<typename T> void sc_register_b< T >::write (const T & v) inline virtual
References scireg_ns::scireg_callback::do_callback(), scireg_ns::SCIREG_WRITE_ACCESS, and scireg_ns::scireg_callback::type.
Referenced by usi.shell.console.Console::interact(), sc_register_b< unsigned char >::reset(), and sc_register_b< unsigned char >::scireg_write().
template<typename T> virtual sc_register_b< T >::~sc_register_b () inline virtual
template<typename ADDR_TYPE, typename DATA_TYPE> virtual sc_register_bank< ADDR_TYPE, DATA_TYPE >::~sc_register_bank () inline virtual
virtual sc_register_bank_base::~sc_register_bank_base () inline virtual
virtual sc_register_base::~sc_register_base () inline virtual
template<typename T , unsigned int highpos, unsigned int lowpos> sc_register_field< T, highpos, lowpos >::~sc_register_field () inline
template<typename T > sc_register_field_b< T >::~sc_register_field_b () inline virtual
virtual sc_register_field_base::~sc_register_field_base () inline virtual
sc_rf_valuecode::~sc_rf_valuecode () inline
Variable Documentation
::std::vector<sc_core::sc_object*> sc_register_bank_base::m_associate_busports protected
Referenced by sc_register_bank_base::add_associate_busport(), and sc_register_bank_base::get_associate_busports().
template<typename T> T sc_register_b< T >::m_cur_val protected
::std::string sc_register_field_base::m_desc protected
Referenced by sc_register_field_base::desc(), and sc_register_field_base::sc_register_field_base().
::std::string sc_rf_valuecode::m_desc protected
Referenced by sc_rf_valuecode::desc(), and sc_rf_valuecode::sc_rf_valuecode().
::std::string sc_register_base::m_desc protected
Referenced by sc_register_base::desc(), and sc_register_base::sc_register_base().
template<typename T> sc_register_field_vec sc_register_b< T >::m_fields protected
Referenced by sc_register_b< unsigned char >::add_field(), sc_register_b< unsigned char >::get_all_fields(), and sc_register_b< unsigned char >::number_of_fields().
template<typename T , unsigned int highpos, unsigned int lowpos> T sc_register_field< T, highpos, lowpos >::m_mask protected
Referenced by sc_register_field< T, highpos, lowpos >::get_mask().
template<typename T> T sc_register_b< T >::m_mask protected
Referenced by sc_register_b< unsigned char >::get_mask().
::std::string sc_rf_valuecode::m_mnemonic protected
Referenced by sc_rf_valuecode::mnemonic().
::std::string sc_register_field_base::m_name protected
Referenced by sc_register_field_base::name().
template<typename T> sc_core::sc_event* sc_register_b< T >::m_probe_event protected
template<typename T> sc_register_b<T>* sc_register_field_b< T >::m_reg protected
Referenced by sc_register_field_b< DATA_TYPE >::sc_register_field_b().
template<typename T> T sc_register_b< T >::m_reset_val protected
Referenced by sc_register_b< unsigned char >::reset().
unsigned long long sc_register_bank_base::m_size protected
Referenced by sr_register_bank< unsigned int, unsigned int >::create_register(), and sc_register_bank_base::size().
template<typename T> ::std::map<T,sc_rf_valuecode*> sc_register_field_b< T >::m_value_encoding_map protected
Value-encoding map.
template<typename T> ::std::vector<scireg_ns::scireg_callback*> sc_register_b< T >::scireg_callback_vec protected
Referenced by sc_register_b< unsigned char >::scireg_add_callback(), and sc_register_b< unsigned char >::scireg_remove_callback().
std::vector< scireg_notification_if * > * scireg_ns::scireg_tool_registry::tool_vec_ptr = 0 static protected
Referenced by scireg_ns::scireg_tool_registry::add_region(), scireg_ns::scireg_tool_registry::add_tool(), scireg_ns::scireg_tool_registry::check_allocation(), scireg_ns::scireg_tool_registry::destroy(), scireg_ns::scireg_tool_registry::remove_region(), and scireg_ns::scireg_tool_registry::remove_tool().
Friends
template<typename T> friend class sc_register_field_b< T > friend