SoCRocket: AHBCtrl
SoCRocket
Transaction-Level Modeling Framework for Space Applications
AHBCtrl
Files
file ahbctrl.cpp
file ahbctrl.h
Classes
struct ahb_check_slave_type
class AHBCtrl
Functions
AHBCtrl::AHBCtrl (ModuleName nm, uint32_t ioaddr=0xFFF, uint32_t iomask=0xFFF, uint32_t cfgaddr=0xFF0, uint32_t cfgmask=0xFF0, bool rrobin=false, bool split=false, uint32_t defmast=0, bool ioen=true, bool fixbrst=false, bool fpnpen=true, bool mcheck=true, bool pow_mon=false, AbstractionLayer ambaLayer=amba::amba_LT)
Constructor.
void AHBCtrl::dorst ()
Reset Callback.
AHBCtrl::~AHBCtrl ()
Desctructor.
void AHBCtrl::init_generics ()
Initialisation function for model generics.
void AHBCtrl::b_transport (uint32_t id, tlm::tlm_generic_payload &gp, sc_core::sc_time &delay)
TLM blocking transport method.
tlm::tlm_sync_enum AHBCtrl::nb_transport_fw (uint32_t id, tlm::tlm_generic_payload &gp, tlm::tlm_phase &phase, sc_core::sc_time &delay)
TLM non-blocking transport forward (for AHB slave multi-sock)
tlm::tlm_sync_enum AHBCtrl::nb_transport_bw (uint32_t id, tlm::tlm_generic_payload &gp, tlm::tlm_phase &phase, sc_core::sc_time &delay)
TLM non-blocking transport backward (for AHB master multi-sock)
void AHBCtrl::print_requests ()
Helper function - prints pending requests in arbiter.
void AHBCtrl::arbitrate ()
The arbiter thread. Responsible for arbitrating transactions in AT mode.
void AHBCtrl::AcceptThread ()
void AHBCtrl::RequestThread ()
void AHBCtrl::ResponseThread ()
void AHBCtrl::EndResponseThread ()
unsigned int AHBCtrl::transport_dbg (uint32_t id, tlm::tlm_generic_payload &gp)
TLM debug interface.
void AHBCtrl::transport_statistics (tlm::tlm_generic_payload &gp)
Collect common transport statistics.
void AHBCtrl::print_transport_statistics (const char *name) const
Print common transport statistics.
Detailed Description
Function Documentation
void AHBCtrl::AcceptThread ()
References AHBCtrl::ahbIN, v::debug, v::error, setup::name, trans, and v::warn.
Referenced by AHBCtrl::AHBCtrl().
AHBCtrl::AHBCtrl (ModuleName nm, uint32_t ioaddr = 0xFFF, uint32_t iomask = 0xFFF, uint32_t cfgaddr = 0xFF0, uint32_t cfgmask = 0xFF0, bool rrobin = false, bool split = false, uint32_t defmast = 0, bool ioen = true, bool fixbrst = false, bool fpnpen = true, bool mcheck = true, bool pow_mon = false, AbstractionLayer ambaLayer = amba::amba_LT)
Constructor.
Parameters
nm SystemC name
ioaddr The MSB address of the I/O area
iomask The I/O area address mask
cfgaddr The MSB address of the configuration area (PNP)
cfgmask The address mask of the configuration area
rrobin 1 - round robin, 0 - fixed priority arbitration (only AT)
split Enable support for AHB SPLIT response (only AT)
defmast ID of the default master
ioen AHB I/O area enable
fixbrst Enable support for fixed-length bursts
fpnpen Enable full decoding of PnP configuration records.
mcheck Check if there are any intersections between core memory regions.
pow_mon Enable power monitoring
References AHBCtrl::AcceptThread(), AHBCtrl::ahbIN, AHBCtrl::ahbOUT, AHBCtrl::arbitrate(), AHBCtrl::b_transport(), AHBCtrl::EndResponseThread(), AHBCtrl::nb_transport_bw(), AHBCtrl::nb_transport_fw(), AHBCtrl::RequestThread(), AHBCtrl::ResponseThread(), srInfo, and AHBCtrl::transport_dbg().
void AHBCtrl::arbitrate ()
The arbiter thread. Responsible for arbitrating transactions in AT mode.
References AHBCtrl::ahbIN, AHBCtrl::ahbOUT, CLKDevice::clock_cycle, v::debug, msclogger::forward(), setup::name, and trans.
Referenced by AHBCtrl::AHBCtrl().
void AHBCtrl::b_transport (uint32_t id, tlm::tlm_generic_payload & gp, sc_core::sc_time & delay)
TLM blocking transport method.
References t_snoop::address, AHBCtrl::ahbIN, AHBCtrl::ahbOUT, CLKDevice::clock_cycle, v::debug, v::error, t_snoop::length, t_snoop::master_id, setup::name, msclogger::return_backward(), AHBCtrl::snoop, trans, and AHBCtrl::transport_statistics().
Referenced by AHBCtrl::AHBCtrl().
void AHBCtrl::dorst () virtual
Reset Callback.
Reimplemented from CLKDevice.
Referenced by AMBABasePlatform::dorst().
void AHBCtrl::EndResponseThread ()
References AHBCtrl::ahbIN, AHBCtrl::ahbOUT, v::debug, msclogger::forward(), setup::name, and trans.
Referenced by AHBCtrl::AHBCtrl().
void AHBCtrl::init_generics () virtual
Initialisation function for model generics.
Reimplemented from BaseModule< DefaultBase >.
References gs::cnf::gs_config_base::add_properties().
tlm::tlm_sync_enum AHBCtrl::nb_transport_bw (uint32_t id, tlm::tlm_generic_payload & gp, tlm::tlm_phase & phase, sc_core::sc_time & delay)
TLM non-blocking transport backward (for AHB master multi-sock)
References AHBCtrl::ahbOUT, v::debug, v::error, setup::name, and msclogger::return_forward().
Referenced by AHBCtrl::AHBCtrl().
tlm::tlm_sync_enum AHBCtrl::nb_transport_fw (uint32_t id, tlm::tlm_generic_payload & gp, tlm::tlm_phase & phase, sc_core::sc_time & delay)
TLM non-blocking transport forward (for AHB slave multi-sock)
References AHBCtrl::ahbIN, v::debug, v::error, setup::name, msclogger::return_backward(), trans, and AHBCtrl::transport_statistics().
Referenced by AHBCtrl::AHBCtrl().
void AHBCtrl::print_requests ()
Helper function - prints pending requests in arbiter.
References v::info, and setup::name.
void AHBCtrl::print_transport_statistics (const char * name) const
Print common transport statistics.
References v::report.
void AHBCtrl::RequestThread ()
References t_snoop::address, AHBCtrl::ahbIN, msclogger::backward(), v::debug, t_snoop::length, t_snoop::master_id, setup::name, AHBCtrl::snoop, and trans.
Referenced by AHBCtrl::AHBCtrl().
void AHBCtrl::ResponseThread ()
References AHBCtrl::ahbIN, msclogger::backward(), v::debug, setup::name, and trans.
Referenced by AHBCtrl::AHBCtrl().
unsigned int AHBCtrl::transport_dbg (uint32_t id, tlm::tlm_generic_payload & gp)
TLM debug interface.
References AHBCtrl::ahbIN, AHBCtrl::ahbOUT, v::debug, v::error, ahb_check_slave_type::index, setup::name, and v::warn.
Referenced by AHBCtrl::AHBCtrl().
void AHBCtrl::transport_statistics (tlm::tlm_generic_payload & gp)
Collect common transport statistics.
Referenced by AHBCtrl::b_transport(), and AHBCtrl::nb_transport_fw().
AHBCtrl::~AHBCtrl ()
Desctructor.