SoCRocket: Platform
SoCRocket
Transaction-Level Modeling Framework for Space Applications
Platform
Files
file leon3processor.h
file sc_main.cpp
Classes
class AMBABasePlatform
class Leon3Processor
class irqmp_rst_stimuli
Functions
void stopSimFunction (int sig)
void grethVPHYHook (char *dev_name)
int sc_main (int argc, char **argv)
Variables
int exitValue
string greth_script_path
Detailed Description
Function Documentation
void grethVPHYHook (char * dev_name)
References v::error, greth_script_path, and v::info.
Referenced by sc_main().
int sc_main (int argc, char ** argv)
References AHBSlave< BASE >::ahb, AHBMaster< BASE >::ahb, AHBCtrl::ahbIN, AHBCtrl::ahbOUT, APBCtrl::apb, APBSlave::apb, Memory::bus, sr_signal::connect(), Leon3::cpu, Irqmp::cpu_rst, Irqmp::cpu_stat, sr_report_handler::default_handler(), Leon3::g_gdb, Leon3::g_history, Leon3::g_osemu, leon3_funclt_trap::LEON3_ABIIf::getExitValue(), leon3_funclt_trap::Processor_leon3_funclt::getInterface(), greth, grethVPHYHook(), i, v::info, leon3_funclt_trap::PinTLM_out_32::initSignal, MEMDevice::IO, APBUART::irq, GPTimer::irq, AHBIn::irq, Irqmp::irq_ack, Irqmp::irq_in, leon3_funclt_trap::Processor_leon3_funclt::IRQ_port, Irqmp::irq_req, leon3_funclt_trap::IntrTLMPort_32::irq_signal, leon3_funclt_trap::Processor_leon3_funclt::irqAck, irqmp_rst_stimuli::irqmp_rst, Mctrl::mem, v::report, MEMDevice::ROM, CLKDevice::rst, leon3_funclt_trap::PinTLM_out_32::run, MEMDevice::SDRAM, CLKDevice::set_clk(), AHBCtrl::snoop, mmu_cache_base::snoop, SR_INCLUDE_MODULE, MEMDevice::SRAM, leon3_funclt_trap::PinTLM_out_32::status, stopSimFunction(), USI_HAS_MODULE, usi_init, usi_load, usi_start, and usi_start_of_initialization.
void stopSimFunction (int sig)
References pysc::api::systemc::wait(), and v::warn.
Referenced by sc_main().
Variable Documentation
int exitValue
Referenced by trap::_exitSysCall< wordSize >::operator()().
string greth_script_path
Referenced by grethVPHYHook().