SoCRocket: Platforms
SoCRocket
Transaction-Level Modeling Framework for Space Applications
Platforms
Files
file leon3processor.h
file leon3mp.h
Namespaces
trap
Classes
class Leon3Processor
class Leon3mpPlatform
Functions
void stopSimFunction (int sig)
boost::filesystem::path find_top_path (char *start)
void grethVPHYHook (char *dev_name)
int sc_main (int argc, char **argv)
Variables
string greth_script_path
Detailed Description
Function Documentation
boost::filesystem::path find_top_path (char * start)
Referenced by sc_main().
void grethVPHYHook (char * dev_name)
References v::error, greth_script_path, and v::info.
Referenced by sc_main().
int sc_main (int argc, char ** argv)
References AHBSlave< BASE >::ahb, AHBMaster< BASE >::ahb, AHBCtrl::ahbIN, AHBCtrl::ahbOUT, APBCtrl::apb, Mctrl::apb, Irqmp::apb_slv, BaseMemory::ARRAY, atoi(), APBUART::bus, Memory::bus, GPTimer::bus, json_parser::config(), signalkit::connect(), leon3_mmu_cache::cpu, Irqmp::cpu_rst, Irqmp::cpu_stat, exit, trap::exitValue, find_top_path(), flush(), leon3_mmu_cache::g_args, leon3_mmu_cache::g_gdb, leon3_mmu_cache::g_history, leon3_mmu_cache::g_osemu, trap::ExecLoader::getDataStart(), trap::ExecLoader::getProgData(), trap::ExecLoader::getProgDim(), greth, greth_script_path, grethVPHYHook(), v::info, leon3_funclt_trap::PinTLM_out_32::initSignal, MEMDevice::IO, APBUART::irq, AHBIn::irq, GPTimer::irq, Irqmp::irq_ack, Irqmp::irq_in, leon3_funclt_trap::Processor_leon3_funclt::IRQ_port, Irqmp::irq_req, leon3_funclt_trap::IntrTLMPort_32::irq_signal, leon3_funclt_trap::Processor_leon3_funclt::irqAck, BaseMemory::MAP, Mctrl::mem, setup::options, paramprinter::printConfigs(), paramprinter::printParams(), MEMDevice::ROM, CLKDevice::rst, leon3_funclt_trap::PinTLM_out_32::run, MEMDevice::SDRAM, CLKDevice::set_clk(), AHBCtrl::snoop, mmu_cache_base::snoop, MEMDevice::SRAM, leon3_funclt_trap::PinTLM_out_32::status, stopSimFunction(), getSpeedResults::store, v::warn, signalkit::signal_out< TYPE, MODULE >::write(), BaseMemory::write_dbg(), and AHBMem::writeByteDBG().
void stopSimFunction (int sig)
References v::warn.
Referenced by sc_main().
Variable Documentation
string greth_script_path
Referenced by grethVPHYHook(), and sc_main().