SoCRocket: AHB Profiler
SoCRocket
Transaction-Level Modeling Framework for Space Applications
AHB Profiler
Files
file ahbprof.cpp
file ahbprof.h
Classes
struct prof_info
class AHBProf
Functions
AHBProf::AHBProf (const ModuleName nm, uint32_t index=0, uint16_t addr=0, uint16_t mask=0, AbstractionLayer ambaLayer=amba::amba_LT)
Constructor for the test bench memory class.
AHBProf::~AHBProf ()
Destructor.
uint32_t AHBProf::exec_func (tlm::tlm_generic_payload &gp, sc_time &delay, bool debug=false)
Interface to functional part of the model.
sc_core::sc_time AHBProf::get_clock ()
Returns clock cycle time from child.
Detailed Description
Function Documentation
AHBProf::AHBProf (const ModuleName nm, uint32_t index = 0, uint16_t addr = 0, uint16_t mask = 0, AbstractionLayer ambaLayer = amba::amba_LT)
Constructor for the test bench memory class.
Constructor
Parameters
haddr AHB address of the AHB slave socket (12 bit)
hmask AHB address mask (12 bit)
ambaLayer Abstraction layer used (AT/LT)
slave_id AHB Slave id
outfile File name of a text file to initialize the memory from
References AHBDevice< BASE >::get_ahb_base_addr(), AHBDevice< BASE >::get_ahb_size(), v::info, setup::name, and v::uint32.
uint32_t AHBProf::exec_func (tlm::tlm_generic_payload & gp, sc_time & delay, bool debug = false) virtual
Interface to functional part of the model.
Implements AHBSlave<>.
References CLKDevice::clock_cycle, v::error, AHBProf::info, setup::name, v::report, swap_Endianess(), and v::warn.
sc_core::sc_time AHBProf::get_clock () virtual
Returns clock cycle time from child.
Implements AHBSlave<>.
References CLKDevice::clock_cycle.
AHBProf::~AHBProf ()
Destructor.