SoCRocket: Common
SoCRocket
Transaction-Level Modeling Framework for Space Applications
Common
Files
file block_allocator.cpp
file block_allocator.h
file common.h
file gs_config_class.h
file gs_config_operator_macros.h
file gs_config_t.h
file json_parser.cpp
file json_parser.h
file msb_lsb.h
file msclogger.cpp
file msclogger.h
file paramprinter.cpp
file paramprinter.h
file powermonitor.cpp
file powermonitor.h
file reliabilitymanager.h
file report.h
file report.h
file sc_api.h
file sc_find.h
file socrocket.h
file systemc.h
file timingmonitor.cpp
file timingmonitor.h
file vendian.h
file verbose.cpp
file verbose.h
file vmap.h
file waf.cpp
file waf.h
Namespaces
gs
#include "greencontrol/gcnf/apis/utils/envvar_subst.h"
gs::cnf
v
Classes
class BAR
class SCBaseModule< BASE >
class BaseModule< BASE >
class block_allocator
class gs::cnf::gs_config_base
class gs::cnf::gs_config_base::easy_init
class gs::cnf::gs_config< T >
The parameters, gs_config class, templated.
class gs::cnf::gs_config< int >
Template specialization for gs_config<int>.
class gs::cnf::gs_config< unsigned int >
Template specialization for gs_config<unsigned int>.
class gs::cnf::gs_config< bool >
Template specialization for gs_config<bool>.
class gs::cnf::gs_config< double >
Template specialization for gs_config<double>.
class gs::cnf::gs_config< float >
Template specialization for gs_config<float>.
class gs::cnf::gs_config< std::string >
Template specialization for gs_config<std::string>.
class gs::cnf::gs_config< std::vector< std::string > >
class gs::cnf::gs_config< unsigned long long >
Template specialization for gs_config<unsigned long long int>.
class gs::cnf::gs_config< long long >
Template specialization for gs_config<long long int>.
class gs::cnf::gs_config< unsigned char >
Template specialization for gs_config<unsigned char>.
class gs::cnf::gs_config< signed char >
Template specialization for gs_config<signed char>.
class gs::cnf::gs_config< char >
Template specialization for gs_config<char>.
class gs::cnf::gs_config< unsigned short >
Template specialization for gs_config<unsigned short>.
class gs::cnf::gs_config< int16_t >
class gs::cnf::gs_config< uint64_t >
class gs::cnf::gs_config< int64_t >
class gs::cnf::gs_config< sc_dt::sc_int_base >
Template specialization for gs_config< sc_int_base >.
class gs::cnf::gs_config< sc_dt::sc_int< W > >
Template specialization for gs_config< sc_int<W> >.
class gs::cnf::gs_config< sc_dt::sc_uint_base >
Template specialization for gs_config< sc_uint_base >.
class gs::cnf::gs_config< sc_dt::sc_uint< W > >
Template specialization for gs_config< sc_uint<W> >.
class gs::cnf::gs_config< sc_dt::sc_signed >
Template specialization for gs_config< sc_signed >.
class gs::cnf::gs_config< sc_dt::sc_bigint< W > >
Template specialization for gs_config< sc_bigint<W> >.
class gs::cnf::gs_config< sc_dt::sc_unsigned >
Template specialization for gs_config< sc_unsigned >.
class gs::cnf::gs_config< sc_dt::sc_biguint< W > >
Template specialization for gs_config< sc_biguint<W> >.
class gs::cnf::gs_config< sc_dt::sc_bit >
Template specialization for gs_config< sc_bit >.
class gs::cnf::gs_config< sc_dt::sc_logic >
Template specialization for gs_config< sc_logic >.
class gs::cnf::gs_config< sc_core::sc_time >
Template specialization for gs_config< sc_time >.
class gs::cnf::gs_config< sc_core::sc_event >
Template specialization for gs_config< sc_event >.
class gs::cnf::gs_config_t< T >
Template specialized base class for configuration parameters.
struct json_value
class json_parser
class msclogger
class paramprinter
class powermonitor
class FaultDectect_if
struct ReliabilityCell< WIDTH >
class ReliabilityManager
class v::pair
class sr_report
class sr_report_handler
struct t_snoop
class TimingMonitor
struct TimingMonitor::t_timing_rec
Content of a timing_map entry.
class v::basic_teebuf< char_type, traits >
class v::Color
Output colors.
class v::Number
Output colors.
class v::msgstream< level >
class v::logstream< level >
Macros
#define GC_RETURN_OK gs::cnf::return_nothing
#define GC_SPECIALISATIONS_DECREMENT_OPERATORS
#define GC_SPECIALISATIONS_INCREMENT_OPERATORS
#define GC_SPECIALISATIONS_ARITHMETIC_OPERATORS_
#define GC_SPECIALISATIONS_BINARY_OPERATORS
#define IS_DIGIT(c) (c >= '0' && c <= '9')
#define ERROR(it, desc)
#define CHECK_TOP() if (!top) {ERROR(it, "Unexpected character"); }
#define _GET_MACRO_(dummy, _1, NAME,...) NAME
#define _GET_MACRO_2_(dummy, _1, _2, NAME,...) NAME
#define srDebug(...) _GET_MACRO_(dummy,##__VA_ARGS__,srDebug_1(__VA_ARGS__),srDebug_0())
#define srDebug_0()
#define srDebug_1(id)
#define srConfig(...) _GET_MACRO_(dummy,##__VA_ARGS__,srConfig_1(__VA_ARGS__),srConfig_0())
#define srConfig_0()
#define srConfig_1(id)
#define srReport(...) _GET_MACRO_(dummy,##__VA_ARGS__,srReport_1(__VA_ARGS__),srReport_0())
#define srReport_0()
#define srReport_1(id)
#define srAnalyse(...) _GET_MACRO_(dummy,##__VA_ARGS__,srAnalyse_1(__VA_ARGS__),srAnalyse_0())
#define srAnalyse_0()
#define srAnalyse_1(id)
#define srInfo(...) _GET_MACRO_(dummy,##__VA_ARGS__,srInfo_1(__VA_ARGS__),srInfo_0())
#define srInfo_0()
#define srInfo_1(id)
#define srMessage(...) _GET_MACRO_2_(dummy,##__VA_ARGS__,srMessage_2(__VA_ARGS__),srMessage_1(__VA_ARGS__))
#define srMessage_1(verbosity)
#define srMessage_2(id, verbosity)
#define srWarn(...) _GET_MACRO_(dummy,##__VA_ARGS__,srWarn_1(__VA_ARGS__),srWarn_0())
#define srWarn_0()
#define srWarn_1(id)
#define srError(...) _GET_MACRO_(dummy,##__VA_ARGS__,srError_1(__VA_ARGS__),srError_0())
#define srError_0()
#define srError_1(id)
#define srFatal(...) _GET_MACRO_(dummy,##__VA_ARGS__,srFatal_1(__VA_ARGS__),srFatal_0())
#define srFatal_0()
#define srFatal_1(id)
#define vmap std::map
Typedefs
typedef sc_core::sc_module_name ModuleName
typedef sc_core::sc_module DefaultBase
typedef gs::reg::gr_device RegisterBase
typedef amba::amba_layer_ids AbstractionLayer
typedef
gs::reg::greenreg_socket
< gs::amba::amba_slave< 32 > > RegisterSocket
typedef gs::cnf::cnf_api ParameterAPI
typedef gs::cnf::gs_param_array ParameterArray
Enumerations
enum AMBADeviceType { NONE = 0, APBIO = 1, AHBMEM = 2, AHBIO = 3 }
enum json_type {
JSON_NULL, JSON_OBJECT, JSON_ARRAY, JSON_STRING,
JSON_INT, JSON_FLOAT, JSON_BOOL
}
enum ReliabilityCell< WIDTH >::Mode { ReliabilityCell< WIDTH >::NONE, ReliabilityCell< WIDTH >::PERMANENT_DAMAGED, ReliabilityCell< WIDTH >::TRANSIENT_NOTE, ReliabilityCell< WIDTH >::TRANSIENT_DAMAGED }
enum ReliabilityCell< WIDTH >::Type { ReliabilityCell< WIDTH >::NONE, ReliabilityCell< WIDTH >::ADDRESS, ReliabilityCell< WIDTH >::DATA }
enum v::pair::type {
v::pair::INT32, v::pair::UINT32, v::pair::INT64, v::pair::UINT64,
v::pair::STRING, v::pair::BOOL, v::pair::DOUBLE, v::pair::TIME
}
Functions
SCBaseModule< BASE >::SCBaseModule (ModuleName mn, uint32_t register_count=0)
virtual SCBaseModule< BASE >::~SCBaseModule ()
BaseModule< BASE >::BaseModule (ModuleName mn, uint32_t register_count=0)
virtual BaseModule< BASE >::~BaseModule ()
virtual void BaseModule< BASE >::init_generics ()
virtual void BaseModule< BASE >::init_registers ()
virtual void BaseModule< BASE >::init_counters ()
virtual void BaseModule< BASE >::init_power ()
void vwait (sc_core::sc_time &delay)
void await (sc_core::sc_time time)
char * atoi (char *first, char *last, int *out)
char * hatoui (char *first, char *last, unsigned int *out)
char * atof (char *first, char *last, float *out)
json_value * json_alloc (block_allocator *allocator)
void json_append (json_value *lhs, json_value *rhs)
template<uint32_t w, class T >
T msb_lsb (T a)
sc_core::sc_object * findInSimContextByName (const char *name, sc_core::sc_object *node=0)
template<class T >
void find_or_create_new (T *&obj, const char *name)
template<class T , class ARG1 >
void find_or_create_new (T *&obj, const char *name, ARG1 *&arg1)
void swap_Endianess (uint64_t &datum)
void swap_Endianess (uint32_t &datum)
void swap_Endianess (uint16_t &datum)
void swap_Endianess (uint8_t &datum)
boost::filesystem::path findPath (std::string filename, std::string start)
std::map< std::string,
std::string > * readLockFile (std::string top)
std::map< std::string,
std::string > * getWafConfig (std::string top)
SCBaseModule< DefaultBase >::SCBaseModule (ModuleName mn, uint32_t register_count=0)
SCBaseModule< RegisterBase >::SCBaseModule (ModuleName mn, uint32_t register_count=0)
SCBaseModule< APBDevice< RegisterBase > >::SCBaseModule (ModuleName mn, uint32_t register_count=0)
block_allocator::block_allocator (size_t blocksize)
block_allocator::~block_allocator ()
void block_allocator::swap (block_allocator &rhs)
void * block_allocator::malloc (size_t size)
void block_allocator::free ()
json_parser::json_parser ()
json_parser::~json_parser ()
void json_parser::config (const char *filename)
void json_parser::save (std::string path, gs::cnf::cnf_api *api)
paramprinter::paramprinter ()
paramprinter::~paramprinter ()
void paramprinter::printParams ()
void paramprinter::printParams (std::string key)
void paramprinter::printConfigs ()
void paramprinter::printConfigs (std::string key)
powermonitor::powermonitor (sc_core::sc_module_name name, sc_core::sc_time m_report_time=sc_core::SC_ZERO_TIME, bool exram=false)
void powermonitor::report_trigger ()
std::string powermonitor::get_model_name (std::string &param)
std::vector< std::string > powermonitor::get_IP_params (std::vector< std::string > &params)
void powermonitor::gen_report ()
void powermonitor::end_of_simulation ()
ReliabilityCell< WIDTH >::ReliabilityCell ()
void sr_report::operator() (const std::string &name="")
static void TimingMonitor::phase_start_timing (const unsigned int id, const char *name="")
Create a new timing record and set starting time.
static void TimingMonitor::phase_end_timing (const unsigned int id)
Enter phase finishing time.
static sc_core::sc_time TimingMonitor::phase_systime (const unsigned int id)
Return simulation time of phase id.
static double TimingMonitor::phase_realtime (const unsigned int id)
Return real time for processing phase id.
static const char * TimingMonitor::phase_get_name (const unsigned int id)
Return name of phase id.
static void TimingMonitor::report_timing ()
Generate timing report for all phases at 'info' level.
Variables
ParameterAPI * BaseModule< BASE >::m_api
Internal module gs param api instance.
ParameterArray BaseModule< BASE >::m_generics
Configuration generic container.
ParameterArray BaseModule< BASE >::m_counters
Performance counter container.
ParameterArray BaseModule< BASE >::m_power
Power counters container.
std::ofstream msc
sc_core::sc_time msclogger_start
sc_core::sc_time msclogger_end
std::ofstream msc
sc_core::sc_time msclogger_start
sc_core::sc_time msclogger_end
ReliabilityManager * RM
std::map< std::string,
std::string > * wafConfigMap = NULL
static t_timing_map TimingMonitor::timing_map
The map for tracking phases & time.
Detailed Description
Macro Definition Documentation
#define _GET_MACRO_ (dummy, _1, NAME, ...) NAME
#define _GET_MACRO_2_ (dummy, _1, _2, NAME, ...) NAME
#define CHECK_TOP () if (!top) {ERROR(it, "Unexpected character"); }
#define ERROR (it, desc)
Value:
*error_pos = it; \
  *error_desc = const_cast<char *>(desc); \
  *error_line = 1 - escaped_newlines; \
  for (char *c = it; c != source; --c) { \
    if (*c == '\n') {++*error_line; } \
  } \
  return 0
#define GC_RETURN_OK gs::cnf::return_nothing
Referenced by MemoryPower::dyn_reads_cb(), MemoryPower::dyn_reads_write_cb(), MemoryPower::dyn_writes_cb(), MemoryPower::dyn_writes_write_cb(), leon3_mmu_cache::g_args_callback(), leon3_mmu_cache::g_gdb_callback(), leon3_mmu_cache::g_history_callback(), leon3_mmu_cache::g_osemu_callback(), dvectorcache::int_power_cb(), ivectorcache::int_power_cb(), localram::int_power_cb(), AHBMem::int_power_cb(), Irqmp::int_power_cb(), APBCtrl::int_power_cb(), leon3_funcat_trap::Processor_leon3_funcat::int_power_cb(), leon3_funclt_trap::Processor_leon3_funclt::int_power_cb(), Mctrl::int_power_cb(), mmu::int_power_cb(), GPTimer::int_power_cb(), mmu_cache_base::int_power_cb(), Memory::m_reads_cb(), Memory::m_writes_cb(), gs::cnf::gs_config_t< sc_dt::sc_uint< W > >::mirror_callback(), dvectorcache::sta_power_cb(), ivectorcache::sta_power_cb(), localram::sta_power_cb(), AHBMem::sta_power_cb(), Irqmp::sta_power_cb(), APBCtrl::sta_power_cb(), leon3_funcat_trap::Processor_leon3_funcat::sta_power_cb(), leon3_funclt_trap::Processor_leon3_funclt::sta_power_cb(), Mctrl::sta_power_cb(), mmu::sta_power_cb(), GPTimer::sta_power_cb(), mmu_cache_base::sta_power_cb(), MemoryPower::swi_power_cb(), dvectorcache::swi_power_cb(), ivectorcache::swi_power_cb(), localram::swi_power_cb(), AHBMem::swi_power_cb(), leon3_funcat_trap::Processor_leon3_funcat::swi_power_cb(), leon3_funclt_trap::Processor_leon3_funclt::swi_power_cb(), APBCtrl::swi_power_cb(), mmu::swi_power_cb(), Mctrl::swi_power_cb(), and mmu_cache_base::swi_power_cb().
#define GC_SPECIALISATIONS_ARITHMETIC_OPERATORS_
#define GC_SPECIALISATIONS_BINARY_OPERATORS
#define GC_SPECIALISATIONS_DECREMENT_OPERATORS
Value:
inline my_type&                                                    \
    operator -- ()                                                     \
  {                                                                  \
  val_type tmp_val = getValue();                                   \
  --tmp_val;                                                       \
  this->setValue( tmp_val );                                       \
  return *this;                                                    \
  }                                                                  \
  \
  inline val_type                                                    \
  operator -- (int)                                                  \
  {                                                                  \
  val_type tmp_old_val = getValue();                               \
  val_type tmp_set_val = tmp_old_val;                              \
  tmp_set_val--;                                                   \
  this->setValue( tmp_set_val );                                   \
  return tmp_old_val;                                              \
  }                                                                  \
#define GC_SPECIALISATIONS_INCREMENT_OPERATORS
Value:
inline my_type&                                                    \
    operator ++ ()                                                     \
  {                                                                  \
  val_type tmp_val = getValue();                                   \
  ++tmp_val;                                                       \
  this->setValue( tmp_val );                                       \
  return *this;                                                    \
  }                                                                  \
  \
  inline val_type                                                    \
  operator ++ (int)                                                  \
  {                                                                  \
  val_type tmp_old_val = getValue();                               \
  val_type tmp_set_val = tmp_old_val;                              \
  tmp_set_val++;                                                   \
  this->setValue( tmp_set_val);                                    \
  return tmp_old_val;                                              \
  }
#define IS_DIGIT (c) (c >= '0' && c <= '9')
Referenced by atof(), atoi(), and hatoui().
#define srAnalyse (...) _GET_MACRO_(dummy,##__VA_ARGS__,srAnalyse_1(__VA_ARGS__),srAnalyse_0())
Referenced by Memory::b_transport().
#define srAnalyse_0 ()
Value:
sr_report_handler::report(\
      sc_core::SC_INFO, this->name(), "", \
      sc_core::SC_FULL, __FILE__ , __LINE__)
#define srAnalyse_1 (id)
Value:
sr_report_handler::report(\
      sc_core::SC_INFO, id, "", \
      sc_core::SC_FULL, __FILE__ , __LINE__)
#define srConfig (...) _GET_MACRO_(dummy,##__VA_ARGS__,srConfig_1(__VA_ARGS__),srConfig_0())
#define srConfig_0 ()
Value:
sr_report_handler::report(\
      sc_core::SC_INFO, this->name(), "", \
      sc_core::SC_MEDIUM, __FILE__ , __LINE__)
#define srConfig_1 (id)
Value:
sr_report_handler::report(\
      sc_core::SC_INFO, id, "", \
      sc_core::SC_MEDIUM, __FILE__ , __LINE__)
#define srDebug (...) _GET_MACRO_(dummy,##__VA_ARGS__,srDebug_1(__VA_ARGS__),srDebug_0())
Referenced by AHBMem::exec_func().
#define srDebug_0 ()
Value:
sr_report_handler::report(\
      sc_core::SC_INFO, this->name(), "", \
      sc_core::SC_DEBUG, __FILE__ , __LINE__)
#define srDebug_1 (id)
Value:
sr_report_handler::report(\
      sc_core::SC_INFO, id, "", \
      sc_core::SC_DEBUG, __FILE__ , __LINE__)
#define srError (...) _GET_MACRO_(dummy,##__VA_ARGS__,srError_1(__VA_ARGS__),srError_0())
Referenced by BaseModule< DefaultBase >::BaseModule(), AHBMem::exec_func(), and mmu_cache::mmu_cache().
#define srError_0 ()
Value:
sr_report_handler::report(\
      sc_core::SC_ERROR, this->name(), "", \
      sc_core::SC_LOW, __FILE__ , __LINE__)
#define srError_1 (id)
Value:
sr_report_handler::report(\
      sc_core::SC_ERROR, id, "", \
      sc_core::SC_LOW, __FILE__ , __LINE__)
#define srFatal (...) _GET_MACRO_(dummy,##__VA_ARGS__,srFatal_1(__VA_ARGS__),srFatal_0())
#define srFatal_0 ()
Value:
sr_report_handler::report(\
      sc_core::SC_FATAL, this->name(), "", \
      sc_core::SC_LOW, __FILE__ , __LINE__)
#define srFatal_1 (id)
Value:
sr_report_handler::report(\
      sc_core::SC_FATAL, id, "", \
      sc_core::SC_LOW, __FILE__ , __LINE__)
#define srInfo (...) _GET_MACRO_(dummy,##__VA_ARGS__,srInfo_1(__VA_ARGS__),srInfo_0())
Referenced by AHBCtrl::AHBCtrl(), AHBMem::AHBMem(), APBCtrl::APBCtrl(), GPTimer::GPTimer(), Irqmp::Irqmp(), Mctrl::Mctrl(), and mmu_cache_base::mmu_cache_base().
#define srInfo_0 ()
Value:
sr_report_handler::report(\
      sc_core::SC_INFO, this->name(), "", \
      sc_core::SC_LOW, __FILE__ , __LINE__)
#define srInfo_1 (id)
Value:
sr_report_handler::report(\
      sc_core::SC_INFO, id, "", \
      sc_core::SC_LOW, __FILE__ , __LINE__)
#define srMessage (...) _GET_MACRO_2_(dummy,##__VA_ARGS__,srMessage_2(__VA_ARGS__),srMessage_1(__VA_ARGS__))
#define srMessage_1 (verbosity)
Value:
sr_report_handler::report(\
      sc_core::SC_INFO, this->name(), "", \
      verbosity, __FILE__ , __LINE__)
#define srMessage_2 (id, verbosity)
Value:
sr_report_handler::report(\
      sc_core::SC_INFO, id, "", \
      verbosity, __FILE__ , __LINE__)
#define srReport (...) _GET_MACRO_(dummy,##__VA_ARGS__,srReport_1(__VA_ARGS__),srReport_0())
#define srReport_0 ()
Value:
sr_report_handler::report(\
      sc_core::SC_INFO, this->name(), "", \
      sc_core::SC_MEDIUM, __FILE__ , __LINE__)
#define srReport_1 (id)
Value:
sr_report_handler::report(\
      sc_core::SC_INFO, id, "", \
      sc_core::SC_MEDIUM, __FILE__ , __LINE__)
#define srWarn (...) _GET_MACRO_(dummy,##__VA_ARGS__,srWarn_1(__VA_ARGS__),srWarn_0())
Referenced by Memory::b_transport(), and AHBMem::exec_func().
#define srWarn_0 ()
Value:
sr_report_handler::report(\
      sc_core::SC_WARNING, this->name(), "", \
      sc_core::SC_MEDIUM, __FILE__ , __LINE__)
#define srWarn_1 (id)
Value:
sr_report_handler::report(\
      sc_core::SC_WARNING, id, "", \
      sc_core::SC_MEDIUM, __FILE__ , __LINE__)
#define vmap std::map
Typedef Documentation
typedef amba::amba_layer_ids AbstractionLayer
typedef sc_core::sc_module DefaultBase
typedef sc_core::sc_module_name ModuleName
typedef gs::cnf::cnf_api ParameterAPI
typedef gs::cnf::gs_param_array ParameterArray
typedef gs::reg::gr_device RegisterBase
typedef gs::reg::greenreg_socket<gs::amba::amba_slave<32> > RegisterSocket
Enumeration Type Documentation
enum AMBADeviceType
Device type See grlib manual for more information Section 4.2.3
Enumerator
NONE
Bar is not existing.
APBIO
Bar is an APB Device.
AHBMEM
Bar is absolute addressed to 0 at AHB Bus.
AHBIO
Bar is relative to AHBIO region.
enum json_type
Enumerator
JSON_NULL
JSON_OBJECT
JSON_ARRAY
JSON_STRING
JSON_INT
JSON_FLOAT
JSON_BOOL
template<class WIDTH > enum ReliabilityCell::Mode
Enumerator
NONE
PERMANENT_DAMAGED
TRANSIENT_NOTE
TRANSIENT_DAMAGED
template<class WIDTH > enum ReliabilityCell::Type
Enumerator
NONE
ADDRESS
DATA
enum v::pair::type
Enumerator
INT32
UINT32
INT64
UINT64
STRING
BOOL
DOUBLE
TIME
Function Documentation
char* atof (char * first, char * last, float * out)
References IS_DIGIT, and result.
char* atoi (char * first, char * last, int * out)
References IS_DIGIT, and result.
Referenced by MDR_dataset_read(), and sc_main().
void await (sc_core::sc_time time) inline
template<class BASE = DefaultBase> BaseModule< BASE >::BaseModule (ModuleName mn, uint32_t register_count = 0) inline
block_allocator::block_allocator (size_t blocksize) explicit
void json_parser::config (const char * filename)
Referenced by sc_main().
void powermonitor::end_of_simulation ()
References powermonitor::gen_report(), and powermonitor::m_report_time.
template<class T > void find_or_create_new (T *& obj, const char * name) inline
References findInSimContextByName().
template<class T , class ARG1 > void find_or_create_new (T *& obj, const char * name, ARG1 *& arg1) inline
References findInSimContextByName().
sc_core::sc_object* findInSimContextByName (const char * name, sc_core::sc_object * node = 0) inline
References setup::name.
Referenced by find_or_create_new().
boost::filesystem::path findPath (std::string filename, std::string start)
References file.
Referenced by readLockFile().
void block_allocator::free ()
References block_allocator::swap().
Referenced by block_allocator::~block_allocator().
void powermonitor::gen_report ()
References powermonitor::get_IP_params(), powermonitor::get_model_name(), v::info, powermonitor::m_exram, and setup::name.
Referenced by powermonitor::end_of_simulation(), and powermonitor::report_trigger().
std::vector< std::string > powermonitor::get_IP_params (std::vector< std::string > & params)
References powermonitor::get_model_name().
Referenced by powermonitor::gen_report().
std::string powermonitor::get_model_name (std::string & param)
References setup::name, and v::warn.
Referenced by powermonitor::gen_report(), and powermonitor::get_IP_params().
std::map< std::string, std::string > * getWafConfig (std::string top)
References readLockFile(), and wafConfigMap.
char* hatoui (char * first, char * last, unsigned int * out)
References IS_DIGIT, last, and result.
template<class BASE = DefaultBase> virtual void BaseModule< BASE >::init_counters () inline virtual
Reimplemented in BaseModule< APBDevice< RegisterBase > >.
Referenced by BaseModule< DefaultBase >::BaseModule().
template<class BASE = DefaultBase> virtual void BaseModule< BASE >::init_generics () inline virtual
Reimplemented in AHBCtrl, GPTimer, Mctrl, APBCtrl, BaseModule< APBDevice< RegisterBase > >, and AHBMem.
Referenced by BaseModule< DefaultBase >::BaseModule().
template<class BASE = DefaultBase> virtual void BaseModule< BASE >::init_power () inline virtual
Reimplemented in BaseModule< APBDevice< RegisterBase > >.
Referenced by BaseModule< DefaultBase >::BaseModule().
template<class BASE = DefaultBase> virtual void BaseModule< BASE >::init_registers () inline virtual
Reimplemented in GPTimer, and BaseModule< APBDevice< RegisterBase > >.
Referenced by BaseModule< DefaultBase >::BaseModule().
json_value* json_alloc (block_allocator * allocator)
References block_allocator::malloc().
void json_append (json_value * lhs, json_value * rhs)
References json_value::first_child, json_value::last_child, json_value::next_sibling, and json_value::parent.
json_parser::json_parser ()
void * block_allocator::malloc (size_t size)
Referenced by json_alloc().
template<uint32_t w, class T > T msb_lsb (T a)
References h, and r.
void sr_report::operator() (const std::string & name = "") inline
References sr_report::actions, and sr_report::set_msg().
paramprinter::paramprinter ()
void TimingMonitor::phase_end_timing (const unsigned int id) static
Enter phase finishing time.
References v::error, TimingMonitor::t_timing_rec::rt_end, TimingMonitor::t_timing_rec::st_end, and TimingMonitor::timing_map.
const char * TimingMonitor::phase_get_name (const unsigned int id) static
Return name of phase id.
References v::error, and TimingMonitor::timing_map.
double TimingMonitor::phase_realtime (const unsigned int id) static
Return real time for processing phase id.
References v::error, and TimingMonitor::timing_map.
Referenced by TimingMonitor::report_timing().
void TimingMonitor::phase_start_timing (const unsigned int id, const char * name = "") static
Create a new timing record and set starting time.
References setup::name, TimingMonitor::t_timing_rec::name, TimingMonitor::t_timing_rec::rt_end, TimingMonitor::t_timing_rec::rt_start, TimingMonitor::t_timing_rec::st_end, TimingMonitor::t_timing_rec::st_start, and TimingMonitor::timing_map.
sc_core::sc_time TimingMonitor::phase_systime (const unsigned int id) static
Return simulation time of phase id.
References v::error, and TimingMonitor::timing_map.
Referenced by TimingMonitor::report_timing().
powermonitor::powermonitor (sc_core::sc_module_name name, sc_core::sc_time m_report_time = sc_core::SC_ZERO_TIME, bool exram = false)
References powermonitor::report_trigger().
void paramprinter::printConfigs ()
References gs::cnf::gs_config_base::getProperties().
Referenced by sc_main().
void paramprinter::printConfigs (std::string key)
References gs::cnf::gs_config_base::getProperties().
void paramprinter::printParams ()
Referenced by sc_main().
void paramprinter::printParams (std::string key)
References find().
std::map< std::string, std::string > * readLockFile (std::string top)
References findPath(), flags, result, and start().
Referenced by getWafConfig().
template<uint32_t > ReliabilityCell< uint32_t >::ReliabilityCell ()
void TimingMonitor::report_timing () static
Generate timing report for all phases at 'info' level.
References setup::name, TimingMonitor::phase_realtime(), TimingMonitor::phase_systime(), v::report, TimingMonitor::t_timing_rec::st_end, TimingMonitor::t_timing_rec::st_start, and TimingMonitor::timing_map.
void powermonitor::report_trigger ()
References powermonitor::gen_report(), and powermonitor::m_report_time.
Referenced by powermonitor::powermonitor().
void json_parser::save (std::string path, gs::cnf::cnf_api * api)
Referenced by core.tools.generator.model.TreeModel::saveToJsonFile().
SCBaseModule< DefaultBase >::SCBaseModule (ModuleName mn, uint32_t register_count = 0)
SCBaseModule< RegisterBase >::SCBaseModule (ModuleName mn, uint32_t register_count = 0)
template<class BASE = DefaultBase> SCBaseModule< BASE >::SCBaseModule (ModuleName mn, uint32_t register_count = 0)
SCBaseModule< APBDevice< RegisterBase > >::SCBaseModule (ModuleName mn, uint32_t register_count = 0)
void block_allocator::swap (block_allocator & rhs)
References swap().
Referenced by block_allocator::free().
void swap_Endianess (uint64_t & datum) inline
Referenced by gs::amba::amba_slave< 32 >::b_transport(), vectorcache::dbg_out(), mmu::diag_read_dctlb(), mmu::diag_read_itlb(), AHBProf::exec_func(), APBCtrl::getPNPReg(), tlb_adaptor::mem_read(), tlb_adaptor::mem_write(), vectorcache::read_cache_tag(), mmu_cache_base::read_ccr(), vectorcache::read_config_reg(), mmu::read_mcr(), mmu::read_mctpr(), mmu::read_mctxr(), mmu::read_mfar(), mmu::read_mfsr(), mmu::tlb_lookup(), vectorcache::write_cache_tag(), mmu_cache_base::write_ccr(), mmu::write_mcr(), mmu::write_mctpr(), and mmu::write_mctxr().
void swap_Endianess (uint32_t & datum) inline
void swap_Endianess (uint16_t & datum) inline
void swap_Endianess (uint8_t & datum) inline
void vwait (sc_core::sc_time & delay) inline
template<class BASE = DefaultBase> virtual BaseModule< BASE >::~BaseModule () inline virtual
Reimplemented in BaseModule< APBDevice< RegisterBase > >.
block_allocator::~block_allocator ()
References block_allocator::free().
json_parser::~json_parser ()
paramprinter::~paramprinter ()
template<class BASE = DefaultBase> virtual SCBaseModule< BASE >::~SCBaseModule () inline virtual
Reimplemented in SCBaseModule< APBDevice< RegisterBase > >.
Variable Documentation
template<class BASE = DefaultBase> ParameterAPI* BaseModule< BASE >::m_api protected
Internal module gs param api instance.
Referenced by BaseModule< DefaultBase >::BaseModule().
template<class BASE = DefaultBase> ParameterArray BaseModule< BASE >::m_counters protected
Performance counter container.
template<class BASE = DefaultBase> ParameterArray BaseModule< BASE >::m_generics protected
Configuration generic container.
template<class BASE = DefaultBase> ParameterArray BaseModule< BASE >::m_power protected
Power counters container.
std::ofstream msc
Referenced by msclogger::backward(), msclogger::forward(), msclogger::msc_end(), msclogger::msc_start(), msclogger::return_backward(), and msclogger::return_forward().
std::ofstream msc
Referenced by msclogger::backward(), msclogger::forward(), msclogger::msc_end(), msclogger::msc_start(), msclogger::return_backward(), and msclogger::return_forward().
sc_core::sc_time msclogger_end
sc_core::sc_time msclogger_end
sc_core::sc_time msclogger_start
sc_core::sc_time msclogger_start
ReliabilityManager* RM
TimingMonitor::t_timing_map TimingMonitor::timing_map static
The map for tracking phases & time.
Referenced by TimingMonitor::phase_end_timing(), TimingMonitor::phase_get_name(), TimingMonitor::phase_realtime(), TimingMonitor::phase_start_timing(), TimingMonitor::phase_systime(), and TimingMonitor::report_timing().
std::map<std::string, std::string>* wafConfigMap = NULL
Referenced by getWafConfig().