SoCRocket: Sr_param
SoCRocket
Transaction-Level Modeling Framework for Space Applications
Sr_param
Files
file sr_param_base.h
file sr_param_class.h
Classes
class sr_param_base
class sr_param< T >
The parameters, sr_param class, templated.
Macros
#define SR_PARAM_HEAD
Functions
template<class T >
bool operator== (sr_param< T > &p1, sr_param< T > &p2)
template<class T >
bool operator== (sr_param< T > &p1, T &p2)
template<class T >
bool operator== (T &p1, sr_param< T > &p2)
Detailed Description
Macro Definition Documentation
#define SR_PARAM_HEAD
Function Documentation
template<class T > bool operator== (sr_param< T > & p1, sr_param< T > & p2)
References sr_param_t< T >::getValue().
template<class T > bool operator== (sr_param< T > & p1, T & p2)
References sr_param_t< T >::getValue(), and p2.
template<class T > bool operator== (T & p1, sr_param< T > & p2)
References sr_param_t< T >::getValue().