SoCRocket: core/software/grlib_tests/grtm.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
grtm.c File Reference
Functions
TMTF (int SpacecraftID, int VCID, int OCFFlag, int MCFrameCntr, int VCFrameCntr, int FSHFlag, int SyncFlag, int PktOrderFlag, int SegmentID, int FHP, long int OCF, int FECF, long int SequenceCount, int FrameLength, unsigned char *data)
grtm_test (int paddr, int descsize, int buffersize, int buffers, int rsdepth, int reed, int reed8, int pseudo, int conv, int mark, int split, int sub)
Function Documentation
grtm_test (int paddr, int descsize, int buffersize, int buffers, int rsdepth, int reed, int reed8, int pseudo, int conv, int mark, int split, int sub)
References conf, fail, report_device(), report_subtest(), LEON3Arch::SP, and TMTF().
TMTF (int SpacecraftID, int VCID, int OCFFlag, int MCFrameCntr, int VCFrameCntr, int FSHFlag, int SyncFlag, int PktOrderFlag, int SegmentID, int FHP, long int OCF, int FECF, long int SequenceCount, int FrameLength, unsigned char * data)
Referenced by grtm_test().