SoCRocket: core/software/grlib_tests/hpi_functions.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
hpi_functions.c File Reference
#include "hpi_defs.h"
#include "hpi_functions.h"
Functions
void kill_time (int num)
USHORT inw (PUSHORT b)
VOID outw (USHORT a, PUSHORT b)
void lcd_hpi_write_word (unsigned short chip_addr, unsigned short value)
unsigned short lcd_hpi_read_status ()
void lcd_hpi_write_mailbox (unsigned short value)
unsigned short lcd_hpi_read_mailbox ()
unsigned short lcd_hpi_read_word (unsigned short chip_addr)
void lcd_hpi_write_words (unsigned short chip_addr, unsigned short *data, int num_words)
void lcd_hpi_read_words (unsigned short chip_addr, unsigned short *data, int num_words)
Function Documentation
USHORT inw (PUSHORT b)
References PUSHORT.
Referenced by lcd_hpi_read_mailbox(), lcd_hpi_read_status(), lcd_hpi_read_word(), and lcd_hpi_read_words().
void kill_time (int num) inline
References num.
unsigned short lcd_hpi_read_mailbox ()
References HPI_BASE, HPI_MBX_ADDR, inw(), and USHORT.
unsigned short lcd_hpi_read_status ()
References HPI_BASE, HPI_STAT_ADDR, inw(), and USHORT.
unsigned short lcd_hpi_read_word (unsigned short chip_addr)
References HPI_ADDR_ADDR, HPI_BASE, HPI_DATA_ADDR, inw(), outw(), and USHORT.
Referenced by main().
void lcd_hpi_read_words (unsigned short chip_addr, unsigned short * data, int num_words)
References HPI_ADDR_ADDR, HPI_BASE, HPI_DATA_ADDR, inw(), outw(), and PUSHORT.
void lcd_hpi_write_mailbox (unsigned short value)
References HPI_BASE, HPI_MBX_ADDR, outw(), and USHORT.
void lcd_hpi_write_word (unsigned short chip_addr, unsigned short value)
References HPI_ADDR_ADDR, HPI_BASE, HPI_DATA_ADDR, outw(), and USHORT.
Referenced by main().
void lcd_hpi_write_words (unsigned short chip_addr, unsigned short * data, int num_words)
References HPI_ADDR_ADDR, HPI_BASE, HPI_DATA_ADDR, outw(), and PUSHORT.
VOID outw (USHORT a, PUSHORT b)
References PUSHORT.
Referenced by lcd_hpi_read_word(), lcd_hpi_read_words(), lcd_hpi_write_mailbox(), lcd_hpi_write_word(), and lcd_hpi_write_words().