SoCRocket: core/software/trapgen/io_less/engine.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
engine.c File Reference
Classes
struct table
struct rtable
Macros
#define MINCOUNT 4000
#define MAXCOUNT 60000
#define STEPCOUNT 25
Typedefs
typedef unsigned char uchar
typedef unsigned short ushort
typedef unsigned int uint
Functions
void interpolate (void)
int edge_to_rpm (int)
void fdiv_func (int, int, int *, int *)
void engine (void)
int main (void)
Variables
int debug_val
int debug_base
int debug_interval
struct table vaf_fi_tab0 []
struct table vaf_fi_tab1000 []
struct table vaf_fi_tab1500 []
struct table vaf_fi_tab2000 []
struct table vaf_fi_tab4000 []
struct table vaf_fi_tab4500 []
struct table vaf_fi_tab5000 []
struct table vaf_fi_tab8000 []
struct rtable rpm_vfi_tab []
struct table * tab1
struct table * tab2
ushort rpm1
ushort rpm2
ushort rpm
uchar ival
ushort inter_val
struct table * tabptr
ushort rpm_delta
ushort inter1
ushort inter2
ushort inter_delta
ushort offset
ushort inter_temp
uint big_temp
Macro Definition Documentation
#define MAXCOUNT 60000
Referenced by engine().
#define MINCOUNT 4000
Referenced by engine().
#define STEPCOUNT 25
Referenced by engine().
Typedef Documentation
typedef unsigned char uchar
typedef unsigned int uint
typedef unsigned short ushort
Function Documentation
int edge_to_rpm (int count)
References fdiv_func(), and rpm.
void engine (void)
References edge_to_rpm(), inter_val, interpolate(), MAXCOUNT, MINCOUNT, rtable::r_rpm, rtable::r_tab, rpm, rpm1, rpm2, rpm_vfi_tab, and STEPCOUNT.
void fdiv_func (int num, int den, int * quot, int * rem)
void interpolate (void)
References inter1, inter2, inter_delta, inter_temp, inter_val, offset, rpm, rpm1, rpm2, rpm_delta, table::t_base, table::t_increment, table::t_val, tab1, and tab2.
int main (void)
References engine(), and fail.
Variable Documentation
uint big_temp
int debug_base
int debug_interval
int debug_val
ushort inter1
ushort inter2
ushort inter_delta
ushort inter_temp
ushort inter_val
uchar ival
ushort offset
ushort rpm
ushort rpm1
ushort rpm2
ushort rpm_delta
struct rtable rpm_vfi_tab[]
Initial value:
= {
    {   0, vaf_fi_tab0 },
    { 1000, vaf_fi_tab1000 },
    { 1500, vaf_fi_tab1500 },
    { 2000, vaf_fi_tab2000 },
    { 4000, vaf_fi_tab4000 },
    { 4500, vaf_fi_tab4500 },
    { 5000, vaf_fi_tab5000 },
    { 8000, vaf_fi_tab8000 }
}
struct table* tab1
struct table* tab2
struct table* tabptr
struct table vaf_fi_tab0[]
Initial value:
= {
    { 0, 2400, 20 },
    { 50, 3400, 115 },
    { 100, 9150, 120 },  { 150, 15150, 100 },
    { 200, 20150, 100 },
    { 255, 25650, 0 }
}
struct table vaf_fi_tab1000[]
Initial value:
= {
    { 0, 2500, 20 },
    { 50, 3500, 40 },  { 75, 4500, 150 },  { 100, 8250, 200 },
    { 200, 28250, 200 },
    { 255, 39250, 0 }
}
struct table vaf_fi_tab1500[]
Initial value:
= {
    { 0, 2600, 20 },
    { 50, 3600, 40 },
    { 75, 4600, 200 },  { 100, 9600, 150 },  { 150, 17100, 100 },
    { 200, 22100, 200 },
    { 255, 33100, 0 }
}
struct table vaf_fi_tab2000[]
Initial value:
= {
    { 0, 2500, 10 },  { 50, 3000, 30 },
    { 100, 4500, 120 },  { 125, 7500, 180 },
    { 150, 12000, 300 },
    { 175, 19500, 400 },
    { 200, 29500, 300 },
    { 255, 46000, 0 }
}
struct table vaf_fi_tab4000[]
Initial value:
= {
    { 0, 2500, 10 },  { 50, 3000, 30 },
    { 100, 4500, 180 },
    { 125, 9000, 250 },
    { 150, 15250, 300 },  { 175, 22750, 300 },
    { 200, 30250, 300 },
    { 255, 46750, 0 }
}
struct table vaf_fi_tab4500[]
Initial value:
= {
    { 0, 2500, 10 },  { 50, 3000, 30 },
    { 100, 4500, 180 },
    { 125, 9000, 250 },
    { 150, 15250, 325 },  { 175, 23375, 325 },
    { 200, 31500, 300 },
    { 255, 48000, 0 }
}
struct table vaf_fi_tab5000[]
Initial value:
= {
    { 0, 2500, 10 },  { 50, 3000, 30 },
    { 100, 4500, 180 },
    { 125, 9000, 200 },
    { 150, 14000, 300 },  { 175, 21500, 300 },
    { 200, 29000, 300 },
    { 255, 45500, 0 }
}
struct table vaf_fi_tab8000[]
Initial value:
= {
    { 0, 2500, 10 },
    { 50, 3000, 30 },
    { 100, 4500, 180 },  { 150, 13500, 275 },
    { 175, 20375, 280 },
    { 200, 27375, 290 },
    { 225, 34625, 300 },
    { 255, 43625, 0 }
}