SoCRocket: core/software/trapgen/io_less/crc.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
crc.c File Reference
Macros
#define LOBYTE(x) ((uchar)((x) & 0xFF))
#define HIBYTE(x) ((uchar)((x) >> 8))
Typedefs
typedef unsigned char uchar
Functions
unsigned short icrc1 (unsigned short crc, unsigned char onech)
unsigned short icrc (unsigned short crc, unsigned char *lin, unsigned int len, short jinit, int jrev)
int main (void)
Variables
unsigned char aa [] = "asdffeagewaHAFEFaeDsFEawFdsFaefaeerdjgpim23eDsFEawFdsFaefaeerdjgpim23faeerdjgpim23eDsFEawFdsFaefaeerdjgpim23asdffeagewaHAFEFaeDsFEawFdsFaefaeerdjgpim23eDsFEawFdsFaefaeerdjgpim23faeerdjgpim23eDsFEawFdsFaefaeerdjgpim23"
Macro Definition Documentation
#define HIBYTE (x) ((uchar)((x) >> 8))
Referenced by icrc().
#define LOBYTE (x) ((uchar)((x) & 0xFF))
Referenced by icrc().
Typedef Documentation
typedef unsigned char uchar
Function Documentation
unsigned short icrc (unsigned short crc, unsigned char * lin, unsigned int len, short jinit, int jrev)
References HIBYTE, icrc1(), core.waf.repo::init(), and LOBYTE.
unsigned short icrc1 (unsigned short crc, unsigned char onech)
int main (void)
References i2, and icrc().
Variable Documentation
unsigned char aa[] = "asdffeagewaHAFEFaeDsFEawFdsFaefaeerdjgpim23eDsFEawFdsFaefaeerdjgpim23faeerdjgpim23eDsFEawFdsFaefaeerdjgpim23asdffeagewaHAFEFaeDsFEawFdsFaefaeerdjgpim23eDsFEawFdsFaefaeerdjgpim23faeerdjgpim23eDsFEawFdsFaefaeerdjgpim23"