SoCRocket: core/software/trapgen/io_less/hanoi.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
hanoi.c File Reference
Macros
#define other(i, j) (6-(i+j))
Functions
int main ()
mov (n, f, t)
Variables
int num [4]
long count
Macro Definition Documentation
#define other (i, j) (6-(i+j))
Referenced by mov().
Function Documentation
int main (void)
References count, and mov().
mov (n , f , t)
References count, core.waf.cmake::f(), mov(), and other.
Variable Documentation
long count
int num[4]