SoCRocket: core/software/trapgen/jpeg.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
jpeg.c File Reference
#include <math.h>
#include <stdio.h>
Macros
#define SHORT_BENCH
#define ncols 40
#define nrows 40
#define EOB 0x00
#define ZRL 0xF0
#define ONE 1L
#define LG2_DCT_SCALE 16
#define RIGHT_SHIFT(_x, _shft) ((_x) >> (_shft))
#define DCT_SCALE (ONE << LG2_DCT_SCALE)
#define LG2_OVERSCALE 2
#define OVERSCALE (ONE << LG2_OVERSCALE)
#define UNFIX(x) RIGHT_SHIFT((x) + (ONE << (LG2_DCT_SCALE-1)), LG2_DCT_SCALE)
#define UNFIXH(x) RIGHT_SHIFT((x) + (ONE << LG2_DCT_SCALE), LG2_DCT_SCALE+1)
#define UNFIXO(x) RIGHT_SHIFT((x) + (ONE << (LG2_DCT_SCALE-1-LG2_OVERSCALE)), LG2_DCT_SCALE-LG2_OVERSCALE)
#define OVERSH(x) ((x) << LG2_OVERSCALE)
#define SIN_1_4 46341
#define COS_1_4 46341
#define SIN_1_8 25080
#define COS_1_8 60547
#define SIN_3_8 60547
#define COS_3_8 25080
#define SIN_1_16 12785
#define COS_1_16 64277
#define SIN_7_16 64277
#define COS_7_16 12785
#define SIN_3_16 36410
#define COS_3_16 54491
#define SIN_5_16 54491
#define COS_5_16 36410
#define OSIN_1_4 11585
#define OCOS_1_4 11585
#define OSIN_1_8 6270
#define OCOS_1_8 15137
#define OSIN_3_8 15137
#define OCOS_3_8 6270
#define OSIN_1_16 3196
#define OCOS_1_16 16069
#define OSIN_7_16 16069
#define OCOS_7_16 3196
#define OSIN_3_16 9102
#define OCOS_3_16 13623
#define OSIN_5_16 13623
#define OCOS_5_16 9102
#define DCTSIZE 8
#define INT32 int
#define DCTSIZE 8
#define BLKSIZE 64
#define NBLKS ((ncols*nrows)/BLKSIZE)
Functions
int getbit ()
void huff_dc_dec (int *retval)
void huff_ac_dec (short *data)
void fast_idct_8 (short *in, int stride)
void j_rev_dct (short *data)
void dquantz_lum (short *data)
int main ()
Variables
unsigned long huffbits []
unsigned char val_dc_lum []
unsigned char val_ac_lum []
unsigned char zz_tbl [32]
int mincode_dc []
int maxcode_dc []
unsigned char valptr_dc []
int mincode_ac []
int maxcode_ac []
unsigned char valptr_ac []
unsigned char qtbl_lum []
Macro Definition Documentation
#define BLKSIZE 64
Referenced by main().
#define COS_1_16 64277
#define COS_1_4 46341
Referenced by fast_idct_8().
#define COS_1_8 60547
Referenced by fast_idct_8().
#define COS_3_16 54491
#define COS_3_8 25080
#define COS_5_16 36410
#define COS_7_16 12785
#define DCT_SCALE (ONE << LG2_DCT_SCALE)
#define DCTSIZE 8
Referenced by dquantz_lum(), j_rev_dct(), and main().
#define DCTSIZE 8
#define EOB 0x00
Referenced by huff_ac_dec().
#define INT32 int
Referenced by fast_idct_8().
#define LG2_DCT_SCALE 16
#define LG2_OVERSCALE 2
#define NBLKS ((ncols*nrows)/BLKSIZE)
Referenced by main().
#define ncols 40
Referenced by main().
#define nrows 40
#define OCOS_1_16 16069
Referenced by fast_idct_8().
#define OCOS_1_4 11585
#define OCOS_1_8 15137
#define OCOS_3_16 13623
#define OCOS_3_8 6270
#define OCOS_5_16 9102
Referenced by fast_idct_8().
#define OCOS_7_16 3196
#define ONE 1L
#define OSIN_1_16 3196
Referenced by fast_idct_8().
#define OSIN_1_4 11585
#define OSIN_1_8 6270
#define OSIN_3_16 9102
#define OSIN_3_8 15137
#define OSIN_5_16 13623
Referenced by fast_idct_8().
#define OSIN_7_16 16069
#define OVERSCALE (ONE << LG2_OVERSCALE)
#define OVERSH (x) ((x) << LG2_OVERSCALE)
Referenced by fast_idct_8().
#define RIGHT_SHIFT (_x, _shft) ((_x) >> (_shft))
#define SHORT_BENCH
#define SIN_1_16 12785
#define SIN_1_4 46341
#define SIN_1_8 25080
Referenced by fast_idct_8().
#define SIN_3_16 36410
#define SIN_3_8 60547
#define SIN_5_16 54491
#define SIN_7_16 64277
#define UNFIX (x) RIGHT_SHIFT((x) + (ONE << (LG2_DCT_SCALE-1)), LG2_DCT_SCALE)
#define UNFIXH (x) RIGHT_SHIFT((x) + (ONE << LG2_DCT_SCALE), LG2_DCT_SCALE+1)
Referenced by fast_idct_8().
#define UNFIXO (x) RIGHT_SHIFT((x) + (ONE << (LG2_DCT_SCALE-1-LG2_OVERSCALE)), LG2_DCT_SCALE-LG2_OVERSCALE)
Referenced by fast_idct_8().
#define ZRL 0xF0
Referenced by huff_ac_dec().
Function Documentation
void dquantz_lum (short * data)
References DCTSIZE, and i.
Referenced by main().
void fast_idct_8 (short * in, int stride)
References COS_1_4, COS_1_8, INT32, OCOS_1_16, OCOS_5_16, OSIN_1_16, OSIN_5_16, OVERSH, SIN_1_8, UNFIXH, and UNFIXO.
Referenced by j_rev_dct().
int getbit ()
References huffbits.
Referenced by huff_ac_dec(), and huff_dc_dec().
void huff_ac_dec (short * data)
References EOB, getbit(), i, s, and ZRL.
Referenced by main().
void huff_dc_dec (int * retval)
References getbit(), i, and s.
Referenced by main().
void j_rev_dct (short * data)
References DCTSIZE, fast_idct_8(), and i.
Referenced by main().
int main (void)
References BLKSIZE, DCTSIZE, dquantz_lum(), huff_ac_dec(), huff_dc_dec(), huffbits, i, j_rev_dct(), NBLKS, and ncols.
Variable Documentation
unsigned long huffbits[]
Referenced by getbit(), and main().
int maxcode_ac[]
Initial value:
= {
    0x0,
        0xffffffff,
        0x1,
        0x4,
        0xc,
        0x1c,
        0x3b,
        0x7b,
        0xfa,
        0x1fa,
        0x3fa,
        0x7f9,
        0xff7,
        0xffffffff,
        0xffffffff,
        0x7fc0,
        0xffff
}
int maxcode_dc[]
Initial value:
= {
    0x0,
        0xffffffff,
        0x0,
        0x6,
        0xe,
        0x1e,
        0x3e,
        0x7e,
        0xfe,
        0x1ff
}
int mincode_ac[]
Initial value:
= {
    0x0,
        0x0,
        0x0,
        0x4,
        0xa,
        0x1a,
        0x3a,
        0x78,
        0xf8,
        0x1f6,
        0x3f6,
        0x7f6,
        0xff4,
        0x0,
        0x0,
        0x7fc0,
        0xff82
}
int mincode_dc[]
Initial value:
= {
    0x0,
        0x0,
        0x0,
        0x2,
        0xe,
        0x1e,
        0x3e,
        0x7e,
        0xfe,
        0x1fe
}
unsigned char qtbl_lum[]
Initial value:
= { 16, 11, 10, 16, 24, 40, 51, 61,
12, 12, 14, 19, 26, 58, 60, 55,
14, 13, 16, 24, 40, 57, 69, 56,
14, 17, 22, 29, 51, 87, 80, 62,
18, 22, 37, 56, 68, 109, 103, 77,
24, 35, 55, 64, 81, 104, 113, 92,
49, 64, 78, 87, 103, 121, 120, 101,
72, 92, 95, 98, 112, 100, 103, 99 }
unsigned char val_ac_lum[]
Initial value:
= { 0x01, 0x02, 0x03, 0x00, 0x04, 0x11, 0x05, 0x12, 0x21,
0x31, 0x41, 0x06, 0x13, 0x51, 0x61, 0x07, 0x22, 0x71, 0x14,
0x32, 0x81, 0x91, 0xa1, 0x08, 0x23, 0x42, 0xb1, 0xc1, 0x15,
0x52, 0xd1, 0xf0, 0x24, 0x33, 0x62, 0x72, 0x82, 0x09, 0x0a,
0x16, 0x17, 0x18, 0x19, 0x1a, 0x25, 0x26, 0x27, 0x28, 0x29,
0x2a, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x43, 0x44,
0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x53, 0x54, 0x55, 0x56,
0x57, 0x58, 0x59, 0x5a, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68,
0x69, 0x6a, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7a,
0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x92, 0x93,
0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0xa2, 0xa3,
0xa4, 0xa5, 0xa6, 0xa7, 0xa8, 0xa9, 0xaa, 0xb2, 0xb3,
0xb4, 0xb5, 0xb6, 0xb7, 0xb8, 0xb9, 0xba, 0xc2, 0xc3,
0xc4, 0xc5, 0xc6, 0xc7, 0xc8, 0xc9, 0xca, 0xd2, 0xd3,
0xd4, 0xd5, 0xd6, 0xd7, 0xd8, 0xd9, 0xda, 0xe1, 0xe2, 0xe3,
0xe4, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xf1, 0xf2, 0xf3,
0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9, 0xfa }
unsigned char val_dc_lum[]
Initial value:
= { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06,
0x07, 0x08, 0x09, 0x0A, 0x0B }
unsigned char valptr_ac[]
Initial value:
= {
    0,
        0,
        0,
        2,
        3,
        6,
        9,
        11,
        15,
        18,
        23,
        28,
        32,
        0,
        0,
        36,
        37
}
unsigned char valptr_dc[]
Initial value:
= {
    0,
        0,
        0,
        1,
        6,
        7,
        8,
        9,
        10,
        11
}
unsigned char zz_tbl[32]
Initial value:
= {
    0,1,8,16,9,2,3,10,17,24,32,25,18,11,4,5,12,19,26,33,40,48,41,34,27,
        20,13,6,7,14,21,28
}