SoCRocket: core/software/grlib_tests/l2irqctrl.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
l2irqctrl.c File Reference
#include "testmod.h"
Classes
struct irqctrl
Functions
l2irqtest (int addr)
Function Documentation
l2irqtest (int addr)
References catch_interrupt(), fail, irqctrl::irqclear, irqctrl::irqforce, irqctrl::irqmask, report_device(), setpsr(), and xgetpsr().