SoCRocket: core/software/grlib_tests/leon2_test.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
leon2_test.c File Reference
#include "testmod.h"
Functions
leon2_test (volatile int *irqmp, int mtest)
Function Documentation
leon2_test (volatile int * irqmp, int mtest)
References divtest(), fail, fputest(), i, mmu_test(), multest(), REGFILE, regtest(), report_device(), and report_subtest().