SoCRocket: core/software/grlib_tests/leon3_test.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
leon3_test.c File Reference
#include "testmod.h"
Functions
leon3_test (int domp, volatile int *irqmp, int mtest)
Variables
void(* mpfunc [16])(int index)
Function Documentation
leon3_test (int domp, volatile int * irqmp, int mtest)
References cachetest(), cramtest(), divtest(), fail, fputest(), get_pid, grfpu_test(), mmu_test(), mpfunc, mptest_end(), mptest_start(), multest(), REGFILE, regtest(), report_device(), and report_subtest().
Referenced by base_test(), base_test_tirq(), and main().
Variable Documentation
void(* mpfunc[16])(int index)
Referenced by leon3_test().