SoCRocket: core/models/extern/LEON3/simulatorSources/leon3.funcat/main.cpp File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
main.cpp File Reference
#include <string>
#include <iostream>
#include <vector>
#include <set>
#include <signal.h>
#include <boost/program_options.hpp>
#include <boost/timer.hpp>
#include <boost/filesystem.hpp>
#include "core/common/trapgen/misc/SparseMemoryAT.hpp"
#include "core/models/extern/LEON3/simulatorSources/leon3.funcat/processor.hpp"
#include "core/models/extern/LEON3/simulatorSources/leon3.funcat/instructions.hpp"
#include "core/common/trapgen/utils/trap_utils.hpp"
#include "core/common/trapgen/elfloader/elfFrontend.hpp"
#include "core/common/trapgen/elfloader/execLoader.hpp"
#include <stdexcept>
#include "core/common/trapgen/debugger/GDBStub.hpp"
#include "core/common/trapgen/profiler/profiler.hpp"
#include "core/common/trapgen/osEmulator/osEmulator.hpp"
#include "core/common/systemc.h"
Macros
#define WIN32_LEAN_AND_MEAN
Functions
void stopSimFunction (int sig)
unsigned int toIntNum (std::string &toConvert)
std::pair< unsigned int,
unsigned int > getCycleRange (const std::string &cycles_range, const std::string &application)
int sc_main (int argc, char **argv)
Variables
std::string banner
GDBStub< unsigned int > * gdbStub_ref = NULL
Macro Definition Documentation
#define WIN32_LEAN_AND_MEAN
Function Documentation
std::pair< unsigned int, unsigned int > getCycleRange (const std::string & cycles_range, const std::string & application)
References trap::ELFFrontend::getInstance(), trap::ELFFrontend::getSymAddr(), start, THROW_EXCEPTION, and toIntNum().
Referenced by sc_main().
int sc_main (int argc, char ** argv)
References leon3_funcat_trap::Processor_leon3_funcat::abiIf, trap::ToolsManager< issueWidth >::addTool(), banner, leon3_funcat_trap::Processor_leon3_funcat::dataMem, leon3_funcat_trap::Processor_leon3_funcat::decode(), leon3_funcat_trap::Processor_leon3_funcat::enableHistory(), leon3_funcat_trap::Processor_leon3_funcat::ENTRY_POINT, v::error, getCycleRange(), trap::ExecLoader::getDataStart(), leon3_funcat_trap::Instruction::getMnemonic(), trap::ExecLoader::getProgData(), trap::ExecLoader::getProgDim(), trap::ExecLoader::getProgStart(), trap::OSEmulator< issueWidth >::getRegisteredFunctions(), trap::GDBStub< issueWidth >::initialize(), leon3_funcat_trap::TLMMemory::initSocket, trap::OSEmulator< issueWidth >::initSysCalls(), leon3_funcat_trap::Processor_leon3_funcat::instrMem, mem, leon3_funcat_trap::Processor_leon3_funcat::numInstructions, setup::options, leon3_funcat_trap::Processor_leon3_funcat::profTimeEnd, leon3_funcat_trap::Processor_leon3_funcat::profTimeStart, leon3_funcat_trap::Processor_leon3_funcat::PROGRAM_LIMIT, leon3_funcat_trap::Processor_leon3_funcat::PROGRAM_START, leon3_funcat_trap::TLMMemory::read_word_dbg(), trap::OSEmulatorBase::set_environ(), trap::OSEmulatorBase::set_program_args(), trap::OSEmulatorBase::set_sysconf(), leon3_funcat_trap::TLMMemory::setDebugger(), leon3_funcat_trap::Processor_leon3_funcat::setProfilingRange(), trap::SparseMemoryAT< N_INITIATORS, sockSize >::socket, stopSimFunction(), getSpeedResults::store, leon3_funcat_trap::Processor_leon3_funcat::toolManager, and trap::SparseMemoryAT< N_INITIATORS, sockSize >::write_byte_dbg().
void stopSimFunction (int sig)
References trap::GDBStub< issueWidth >::simulationPaused.
Referenced by sc_main().
unsigned int toIntNum (std::string & toConvert)
References result.
Referenced by getCycleRange(), and trap::GDBConnectionManager::processRequest().
Variable Documentation
std::string banner
Initial value:
= std::string("\n\
\t\n\
\t      _/        _/_/_/_/    _/_/    _/      _/   _/_/_/\n\
\t     _/        _/        _/    _/  _/_/    _/         _/\n\
\t    _/        _/_/_/    _/    _/  _/  _/  _/     _/_/\n\
\t   _/        _/        _/    _/  _/    _/_/         _/\n\
\t  _/_/_/_/  _/_/_/_/    _/_/    _/      _/   _/_/_/\n\
\t\n\
\n\n\tLuca Fossati  -    email: fossati.l@gmail.com\n\n")
Referenced by sc_main().
GDBStub< unsigned int >* gdbStub_ref = NULL