SoCRocket: core/software/trapgen/lms.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
lms.c File Reference
Macros
#define N 512000 /* number of coefficient taps */
Functions
void lms_pin_down (int *d, int *x, int *delta, int *p_H, int *p_X)
int main ()
Variables
int H [N]
int X [N]
Macro Definition Documentation
#define N 512000 /* number of coefficient taps */
Referenced by lms_pin_down(), and main().
Function Documentation
void lms_pin_down (int * d, int * x, int * delta, int * p_H, int * p_X)
References core.waf.cmake::f(), and N.
Referenced by main().
int main (void)
References d, v::error, core.waf.cmake::f(), lms_pin_down(), N, and x.
Variable Documentation
int H[N]
Referenced by ols().
int X[N]