SoCRocket: gaisler/leon3/intunit/main.cpp File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
main.cpp File Reference
#include <string>
#include <iostream>
#include <vector>
#include <set>
#include <signal.h>
#include <boost/program_options.hpp>
#include <boost/timer.hpp>
#include <boost/filesystem.hpp>
#include "core/common/trapgen/misc/SparseMemoryLT.hpp"
#include "gaisler/leon3/intunit/processor.hpp"
#include "gaisler/leon3/intunit/instructions.hpp"
#include "core/common/trapgen/utils/trap_utils.hpp"
#include "core/common/trapgen/elfloader/elfFrontend.hpp"
#include "core/common/trapgen/elfloader/execLoader.hpp"
#include <stdexcept>
#include "core/common/trapgen/debugger/GDBStub.hpp"
#include "core/common/trapgen/profiler/profiler.hpp"
#include "core/common/trapgen/osEmulator/osEmulator.hpp"
#include "core/common/systemc.h"
#include "gaisler/leon3/intunit/irqGenerator.hpp"
Macros
#define WIN32_LEAN_AND_MEAN
Functions
void stopSimFunction (int sig)
unsigned int toIntNum (std::string &toConvert)
std::pair< unsigned int,
unsigned int > getCycleRange (const std::string &cycles_range,\const std::string &application)
int sc_main (int argc, char **argv)
Variables
std::string banner
GDBStub< unsigned int > * gdbStub_ref = NULL
Macro Definition Documentation
#define WIN32_LEAN_AND_MEAN
Function Documentation
std::pair< unsigned int, unsigned int > getCycleRange (const std::string & cycles_range, \const std::string & application)
References trap::ELFFrontend::getInstance(), trap::ELFFrontend::getSymAddr(), start, THROW_EXCEPTION, and toIntNum().
Referenced by sc_main().
int sc_main (int argc, char ** argv)
References leon3_funclt_trap::Processor_leon3_funclt::abiIf, trap::ToolsManager< issueWidth >::addTool(), banner, leon3_funclt_trap::Processor_leon3_funclt::dataMem, leon3_funclt_trap::Processor_leon3_funclt::decode(), leon3_funclt_trap::Processor_leon3_funclt::ENTRY_POINT, v::error, usi.cci.parameter::exists, getCycleRange(), trap::ExecLoader::getDataStart(), leon3_funclt_trap::Instruction::getMnemonic(), trap::ExecLoader::getProgData(), trap::ExecLoader::getProgDim(), trap::ExecLoader::getProgStart(), trap::OSEmulator< issueWidth >::getRegisteredFunctions(), i, trap::GDBStub< issueWidth >::initialize(), leon3_funclt_trap::PinTLM_out_32::initSignal, IrqGenerator::initSignal, trap::OSEmulator< issueWidth >::initSysCalls(), leon3_funclt_trap::Processor_leon3_funclt::instrMem, leon3_funclt_trap::Processor_leon3_funclt::IRQ_port, leon3_funclt_trap::IntrTLMPort_32::irq_signal, leon3_funclt_trap::Processor_leon3_funclt::irqAck, mem, leon3_funclt_trap::Processor_leon3_funclt::numInstructions, setup::options, leon3_funclt_trap::Processor_leon3_funclt::profTimeEnd, leon3_funclt_trap::Processor_leon3_funclt::profTimeStart, leon3_funclt_trap::Processor_leon3_funclt::PROGRAM_LIMIT, leon3_funclt_trap::Processor_leon3_funclt::PROGRAM_START, leon3_funclt_trap::MemoryInterface::read_word_dbg(), trap::OSEmulatorBase::set_environ(), trap::OSEmulatorBase::set_program_args(), trap::OSEmulatorBase::set_sysconf(), leon3_funclt_trap::Processor_leon3_funclt::setProfilingRange(), trap::SparseMemoryLT< N_INITIATORS, sockSize >::socket, stopSimFunction(), getSpeedResults::store, IrqGenerator::targSignal, leon3_funclt_trap::Processor_leon3_funclt::toolManager, and trap::SparseMemoryLT< N_INITIATORS, sockSize >::write_byte_dbg().
void stopSimFunction (int sig)
References trap::GDBStub< issueWidth >::simulationPaused, and pysc::api::systemc::wait().
Referenced by sc_main().
unsigned int toIntNum (std::string & toConvert)
References result.
Referenced by getCycleRange(), and trap::GDBConnectionManager::processRequest().
Variable Documentation
std::string banner
Initial value:
= std::string("\n\
\t\n\
\t      _/        _/_/_/_/    _/_/    _/      _/   _/_/_/\n\
\t     _/        _/        _/    _/  _/_/    _/         _/\n\
\t    _/        _/_/_/    _/    _/  _/  _/  _/     _/_/\n\
\t   _/        _/        _/    _/  _/    _/_/         _/\n\
\t  _/_/_/_/  _/_/_/_/    _/_/    _/      _/   _/_/_/\n\
\t\n\
\n\n\tLuca Fossati  -    email: fossati.l@gmail.com\n\n")
Referenced by sc_main().
GDBStub< unsigned int >* gdbStub_ref = NULL