SoCRocket: core/software/grlib_tests/mptest.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
mptest.c File Reference
#include "testmod.h"
Macros
#define MPLOOPS 10
Functions
asm (" .text\n"" .align 4\n"" .global get_pid\n""get_sem:\n"" set mpsem, %o1\n"" set 0, %o0\n"" retl\n"" ldstuba [%o1] 1, %o0 \n""ret_sem:\n"" set 0, %o0 \n"" set mpsem, %o1\n"" retl\n"" st %o0, [%o1] \n""get_pid:\n"" mov %asr17, %o0\n"" srl %o0, 28, %o0\n"" retl\n"" and %o0, 0xf, %o0\n""mread: retl\n"" lda [%o0] 1, %o0\n""getccfg: set 0xc, %o0\n"" retl\n"" lda [%o0] 2, %o0\n"" .data\n"" .align 4\n"" .global mpsem\n""mpsem: .word 0\n")
int mptest (volatile int *irqmp_ptr)
int mptest_start (volatile int *irqmp_ptr)
int mptest_end (volatile int *irqmp_ptr)
Variables
volatile int cnt = 0
volatile int pstart [17] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1}
volatile int pdone [17] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1}
volatile int pindex [17] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1}
Macro Definition Documentation
#define MPLOOPS 10
Referenced by mptest(), and mptest_end().
Function Documentation
asm (" .text\n"" .align 4\n"" .global get_pid\n""get_sem:\n"" set mpsem, %o1\n""set 0, %o0\n""retl\n"" ldstuba1[%o1], %o0\n""ret_sem:\n""set 0, %o0\n""set mpsem, %o1\n""retl\n""st% o0, [%o1] \n""get_pid:\n""mov% asr17, %o0\n""srl% o0, 28 , %o0\n""retl\n""and% o0, 0xf , %o0\n""mread:retl\n"" lda1[%o0], %o0\n""getccfg:set 0xc, %o0\n""retl\n"" lda2[%o0], %o0\n"".data\n"".align 4\n"".global mpsem\n""mpsem:.word 0\n")
int mptest (volatile int * irqmp_ptr)
References fail, get_pid, get_sem, getccfg, i, MP_TEST, MPLOOPS, report_subtest(), and ret_sem.
int mptest_end (volatile int * irqmp_ptr)
References fail, get_pid, get_sem, getccfg, i, MP_TEST, MPLOOPS, report_subtest(), and ret_sem.
Referenced by leon3_test().
int mptest_start (volatile int * irqmp_ptr)
References get_pid, and i.
Referenced by leon3_test().
Variable Documentation
volatile int cnt = 0
volatile int pdone[17] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1}
volatile int pindex[17] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1}
Referenced by Irqmp::Irqmp(), Mctrl::Mctrl(), and APBCtrl::setAddressMap().
volatile int pstart[17] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1}