SoCRocket: core/software/grlib_tests/multest.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
multest.c File Reference
#include "testmod.h"
Classes
struct mulcase
Functions
multest ()
Variables
volatile struct mulcase mula []
int mulscctmp = 0xfffff000
int ddd [8] = {0,0,0,0,0,0,0,0}
Function Documentation
multest ()
References fail, get_asr17, get_pid, i, l2regs::leonconf, MAC_CONF_BIT, macpipe, MUL_CONF_BIT, MUL_TEST, mulpipe, mulscc_test, and report_subtest().
Referenced by leon2_test(), and leon3_test().
Variable Documentation
int ddd[8] = {0,0,0,0,0,0,0,0}
volatile struct mulcase mula[]
Initial value:
= { { 2, 3, 6}, { 2, -3, -6}, { 0,  1, 0},
    { 0, -1, 0}, {  1, -1, -1}, { -1,  1, -1}, { -2,  3, -6},
    { -2, -3, 6}, {  0,  0, 9}}
int mulscctmp = 0xfffff000