SoCRocket: shell Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
shell Namespace Reference
Classes
class Bash
Functions
def options
def configure
def vexecute
def bash
Variables
list packages
string ACTIVATE
Function Documentation
def shell.bash (self)
References vexecute().
def shell.configure (self)
def shell.options (self)
def shell.vexecute (self, cmd = "")
References pysc::api::cci.list().
Referenced by bash().
Variable Documentation
string shell.ACTIVATE
Initial value:
 = """
 #!/bin/bash
 . ~/.bashrc
 . %(venv)s/bin/activate
 export LD_LIBRARY_PATH="%(libpath)s:$LD_LIBRARY_PATH"
 export PYTHONPATH="%(pythonpath)s:$PYTHONPATH"
 export PATH="%(path)s:$PATH"
 alias deactivate=exit
 """
list shell.packages
Initial value:
 = [
 #    "Pillow==2.2.1",
 #    "docutils==0.11",
 #    "actdiag==0.5.0",
 #    "nwdiag==1.0.0",
 #    "seqdiag==0.9.0",
 #    "blockdiag==1.3.0",
     "Pygments==1.6",
     "six==1.4.1",
     "cython==0.20.2",
 #    "Sphinx==1.1.3",
     "Jinja2==2.7.1",
     "termcolor==1.1.0",
     "python-dateutil==2.1",
     "pyelftools",
 #    "pydot",
     "tmuxp",
     "numpy==1.9.1",
     "scipy==0.12.1",
     "numexpr==2.4",
     "pandas==0.14.1",
     "tables==3.1.1",
     "future"
 ]