SoCRocket: usi.sc_object Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
usi.sc_object Namespace Reference
Functions
def attach
def usi_extend_creation
def usi_extend_delegate
Variables
dictionary FACTORYSTORE = {}
dictionary OBJECTSTORE = {}
Function Documentation
def usi.sc_object.attach (klass, name, member)
def usi.sc_object.usi_extend_creation (obj, klass)
Referenced by usi.sc_object.usi_extend_delegate().
def usi.sc_object.usi_extend_delegate (obj)
   Must be documentet!
   Why this might be a bad idea for bound functions!
   (Garbage collector)
   Object cache?
References pysc::api::cci.list(), and usi.sc_object.usi_extend_creation().
Variable Documentation
dictionary usi.sc_object.FACTORYSTORE = {}
dictionary usi.sc_object.OBJECTSTORE = {}