SoCRocket: statemachine Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
statemachine Namespace Reference
Classes
class Enumerate
Functions
def EscapeForRegExp
def IsAcceptableCharacter
def SanitiseDotLink
def DebugPrintCases
def ProcessStateCases
def ProcessStateMachine
def StateMachineHandler
Variables
string iskeyword = '[A-Za-z0-9_]'
StateList = \
string StateAddRegExpString = r'^AddState\s+(?P<statename>'
tuple StateAddRE = re.compile(StateAddRegExpString)
Function Documentation
def statemachine.DebugPrintCases (Cases)
def statemachine.EscapeForRegExp (string)
Referenced by ProcessStateMachine().
def statemachine.IsAcceptableCharacter (ch)
def statemachine.ProcessStateCases (Cases, GlobalStates, InitialLines, FunctionName = None)
References error_handler.ReportError(), and SanitiseDotLink().
Referenced by ProcessStateMachine().
def statemachine.ProcessStateMachine (lineArray, StateMachinePositions, CommentBlocks)
References EscapeForRegExp(), doxycomment.IsCommentBlockEnd(), doxycomment.IsCommentBlockStart(), and ProcessStateCases().
def statemachine.SanitiseDotLink (dotlink)
Referenced by ProcessStateCases().
def statemachine.StateMachineHandler (lineArray, options)
Top level state machine handler.
Find the lines containing state machine implementations and pass them
onto the detailed handler.
References doxycomment.BlockHandler(), doxygen_preprocessor.CommandLineHandler(), and filterprocessor.FilterFiles().
Variable Documentation
string statemachine.iskeyword = '[A-Za-z0-9_]'
tuple statemachine.StateAddRE = re.compile(StateAddRegExpString)
string statemachine.StateAddRegExpString = r'^AddState\s+(?P<statename>'
statemachine.StateList = \