SoCRocket: usi.shell Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
usi.shell Namespace Reference
Namespaces
console
Functions
def start
def stop
def is_running
def args
def install
Variables
help_text = help
string credits_text = ""
string copyright_text = ""
string license_text = ""
CONSOLE = None
Function Documentation
def usi.shell.args (k, kw)
References usi.tools.args.get_args(), and usi.shell.start().
Referenced by pysc::api::cci::CallbackAdapter.call(), PythonModule.PythonModule(), leon3_funclt_trap::LEON3_ABIIf.readArgs(), IntrinsicBase.set_program_args(), trap::OSEmulatorBase.set_program_args(), and leon3_funclt_trap::LEON3_ABIIf.setArgs().
def usi.shell.install ()
References usi.on(), and usi.shell.start().
def usi.shell.is_running (k, kw)
def usi.shell.start (k, kw)
Referenced by usi.shell.args(), and usi.shell.install().
def usi.shell.stop (k, kw)
Variable Documentation
usi.shell.CONSOLE = None
string usi.shell.copyright_text = ""
string usi.shell.credits_text = ""
usi.shell.help_text = help
string usi.shell.license_text = ""