SoCRocket: core.waf.repository Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
core.waf.repository Namespace Reference
Classes
class repo
Functions
def read_repos
def write_repos
def get_repo_vals
def f
def replace
def rmlinematch
def export_have_define
def loadrepos
def iterrepos
def options
def configure
Variables
string WAF_REPO_LOCK = '.lock_repo.json'
dictionary REPOS = {}
repositories
repository_root
Function Documentation
def core.waf.repository.configure (self)
def core.waf.repository.export_have_define (self)
This function extends the C compiler functionality to register precompiler defines for each repository
References core.waf.repository.read_repos(), and core.waf.repository.replace().
def core.waf.repository.f (popenargs, kwargs)
def core.waf.repository.get_repo_vals (directory)
Return configuration key value pairs for a repository directory
Referenced by core.waf.repository.repo.add_repo(), core.waf.repository.repo.init_repo(), core.waf.repository.loadrepos(), and core.waf.repository.repo.show_repo().
def core.waf.repository.iterrepos (self)
    Iterate through repositories.
    It is simmilar to recurse.
    But it does not work on subdirectories but repos.
References core.waf.repository.read_repos().
def core.waf.repository.loadrepos (self)
Load repositories
References conf, core.waf.repository.get_repo_vals(), and core.waf.repository.read_repos().
def core.waf.repository.options (self)
def core.waf.repository.read_repos ()
Read the repository database file
Referenced by core.waf.repository.export_have_define(), core.waf.repository.iterrepos(), core.waf.repository.loadrepos(), and core.waf.repository.repo.work().
def core.waf.repository.replace (oldstr, newstr, infile)
   Sed-like Replace function..
Referenced by core.waf.repository.export_have_define().
def core.waf.repository.rmlinematch (oldstr, infile)
   Sed-like line deletion function based on given string..
def core.waf.repository.write_repos (repos)
Write the repository database file
Referenced by core.waf.repository.repo.work().
Variable Documentation
dictionary core.waf.repository.REPOS = {}
core.waf.repository.repositories
core.waf.repository.repository_root
string core.waf.repository.WAF_REPO_LOCK = '.lock_repo.json'