SoCRocket: sr_signal Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
sr_signal Namespace Reference
Sr_signal
Classes
class scin_tlmout_adapter
class signal_base
class signal_if
class signal_in_if
class signal_out_bind_if
class signal_out_if
class signal_in
class signal_infield
class signal_inout
class sr_signal_module
class signal_out
class signal_selector
class tlmin_scout_adapter
class tlmsc_inout_adapter
Functions
template<class TYPE >
void connect (signal_in_if< TYPE > &in, signal_out_bind_if< TYPE > &out, int channel=0)
Connects an input signal with an output signal.
template<class TYPE >
void connect (signal_out_bind_if< TYPE > &out, signal_in_if< TYPE > &in, int channel=0)
Connects an input signal with an output signal.
template<class TYPE >
void connect (signal_in_if< TYPE > &in, signal_out_bind_if< TYPE > &out, int inchannel, int outchannel)
Connects an input signal with an output signal.
template<class TYPE >
void connect (signal_out_bind_if< TYPE > &out, signal_in_if< TYPE > &in, int outchannel, int inchannel)
Connects an input signal with an output signal.
template<class INTYPE , class OUTTYPE , class MODULE >
sc_core::sc_module * connect (signal_out< INTYPE, MODULE > &in, sc_core::sc_signal< OUTTYPE > &out, int channel=0)
Special connect mehtod to connect an sr_signal output with an systemc input signal.
template<class INTYPE , class OUTTYPE , class MODULE >
sc_core::sc_module * connect (signal_out< INTYPE, MODULE > &in, sc_core::sc_in< OUTTYPE > &out, int channel=0)
Special connect mehtod to connect an sr_signal output with an systemc sc_in.
template<class INTYPE , class OUTTYPE , class MODULE >
sc_core::sc_module * connect (sc_core::sc_signal< INTYPE > &in, signal_in< OUTTYPE, MODULE > &out, int channel=0)
Special connect mehtod to connect an sr_signal input with an systemc output signal.
template<class INTYPE , class OUTTYPE , class MODULE >
sc_core::sc_module * connect (sc_core::sc_out< INTYPE > &in, signal_in< OUTTYPE, MODULE > &out, uint32_t channel=0)
Special connect mehtod to connect an sr_signal input with an systemc sc_out.
Function Documentation
template<class TYPE > void sr_signal::connect (signal_in_if< TYPE > & in, signal_out_bind_if< TYPE > & out, int channel = 0)
Connects an input signal with an output signal.
References sr_signal::signal_out_bind_if< TYPE >::bind(), and sr_signal::signal_in_if< TYPE >::bind().
Referenced by sc_main().
template<class TYPE > void sr_signal::connect (signal_out_bind_if< TYPE > & out, signal_in_if< TYPE > & in, int channel = 0)
Connects an input signal with an output signal.
References sr_signal::signal_out_bind_if< TYPE >::bind(), and sr_signal::signal_in_if< TYPE >::bind().
template<class TYPE > void sr_signal::connect (signal_in_if< TYPE > & in, signal_out_bind_if< TYPE > & out, int inchannel, int outchannel)
Connects an input signal with an output signal.
References sr_signal::signal_out_bind_if< TYPE >::bind(), and sr_signal::signal_in_if< TYPE >::bind().
template<class TYPE > void sr_signal::connect (signal_out_bind_if< TYPE > & out, signal_in_if< TYPE > & in, int outchannel, int inchannel)
Connects an input signal with an output signal.
References sr_signal::signal_out_bind_if< TYPE >::bind(), and sr_signal::signal_in_if< TYPE >::bind().
template<class INTYPE , class OUTTYPE , class MODULE > sc_core::sc_module* sr_signal::connect (signal_out< INTYPE, MODULE > & in, sc_core::sc_signal< OUTTYPE > & out, int channel = 0)
Special connect mehtod to connect an sr_signal output with an systemc input signal.
References sr_signal::signal_out< TYPE, MODULE >::bind(), sr_signal::tlmin_scout_adapter< INTYPE, OUTTYPE >::in, sr_signal::tlmin_scout_adapter< INTYPE, OUTTYPE >::out, and result.
template<class INTYPE , class OUTTYPE , class MODULE > sc_core::sc_module* sr_signal::connect (signal_out< INTYPE, MODULE > & in, sc_core::sc_in< OUTTYPE > & out, int channel = 0)
Special connect mehtod to connect an sr_signal output with an systemc sc_in.
References sr_signal::signal_out< TYPE, MODULE >::bind(), sr_signal::tlmin_scout_adapter< INTYPE, OUTTYPE >::in, sr_signal::tlmin_scout_adapter< INTYPE, OUTTYPE >::out, and result.
template<class INTYPE , class OUTTYPE , class MODULE > sc_core::sc_module* sr_signal::connect (sc_core::sc_signal< INTYPE > & in, signal_in< OUTTYPE, MODULE > & out, int channel = 0)
Special connect mehtod to connect an sr_signal input with an systemc output signal.
References sr_signal::signal_in< TYPE, MODULE >::bind(), sr_signal::scin_tlmout_adapter< INTYPE, OUTTYPE >::in, sr_signal::scin_tlmout_adapter< INTYPE, OUTTYPE >::out, and result.
template<class INTYPE , class OUTTYPE , class MODULE > sc_core::sc_module* sr_signal::connect (sc_core::sc_out< INTYPE > & in, signal_in< OUTTYPE, MODULE > & out, uint32_t channel = 0)
Special connect mehtod to connect an sr_signal input with an systemc sc_out.
References sr_signal::signal_in< TYPE, MODULE >::bind(), sr_signal::scin_tlmout_adapter< INTYPE, OUTTYPE >::in, sr_signal::scin_tlmout_adapter< INTYPE, OUTTYPE >::out, and result.