SoCRocket: tools.python.power Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
tools.python.power Namespace Reference
Functions
def load
def view
def install
Function Documentation
def tools.python.power.install ()
References usi.on().
def tools.python.power.load (k, kw)
Load initial model configuration
def tools.python.power.view (k, kw)
View detailed model configuration
References usi.cci.parameter.filterDict(), pysc::api::cci.list(), usi.cci.parameter.paramsToDict(), and usi.cci.parameter.readPropertyDict().