SoCRocket: pysc::api::systemc Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
pysc::api::systemc Namespace Reference
Functions
void start ()
void start (double time, sc_core::sc_time_unit tu)
void stop ()
void pause ()
void wait (double time, sc_core::sc_time_unit tu)
double simulation_time (sc_core::sc_time_unit tu)
double delta_count ()
int set_verbosity (int verbosity)
long get_curr_process_handle ()
bool is_running ()
std::vector< sc_core::sc_object * > get_top_level_objects ()
Function Documentation
double pysc::api::systemc::delta_count ()
long pysc::api::systemc::get_curr_process_handle ()
std::vector< sc_core::sc_object * > pysc::api::systemc::get_top_level_objects ()
bool pysc::api::systemc::is_running ()
void pysc::api::systemc::pause ()
int pysc::api::systemc::set_verbosity (int verbosity)
double pysc::api::systemc::simulation_time (sc_core::sc_time_unit tu)
Referenced by pysc::api::cci::CallbackAdapter::call().
void pysc::api::systemc::start ()
void pysc::api::systemc::start (double time, sc_core::sc_time_unit tu)
void pysc::api::systemc::stop ()
void pysc::api::systemc::wait (double time, sc_core::sc_time_unit tu)
Referenced by AHBCtrl::AcceptThread(), AHBCtrl::arbitrate(), await(), AHBCtrl::b_transport(), leon3_funclt_trap::TRAP_imm::behavior(), leon3_funclt_trap::TRAP_reg::behavior(), mmu_cache::dcio_service_thread(), AHBCtrl::EndResponseThread(), AHBIn::frame_trigger(), AHBIn::gen_frame(), IrqGenerator::generateIrq(), mmu_cache::icio_service_thread(), Irqmp::launch_irq(), leon3_funclt_trap::Processor_leon3_funclt::mainLoop(), mmu_cache_base::mem_access(), mmu_cache_base::mem_read(), mmu_cache_base::mem_write(), trap::SparseMemoryAT< N_INITIATORS, sockSize >::nb_transport_fw(), trap::MemoryAT< N_INITIATORS, sockSize >::nb_transport_fw(), openIntrinsic< wordSize >::operator()(), trap::openSysCall< wordSize >::operator()(), creatIntrinsic< wordSize >::operator()(), trap::creatSysCall< wordSize >::operator()(), closeIntrinsic< wordSize >::operator()(), trap::closeSysCall< wordSize >::operator()(), readIntrinsic< wordSize >::operator()(), trap::readSysCall< wordSize >::operator()(), writeIntrinsic< wordSize >::operator()(), trap::writeSysCall< wordSize >::operator()(), isattyIntrinsic< wordSize >::operator()(), sbrkIntrinsic< wordSize >::operator()(), trap::isattySysCall< wordSize >::operator()(), lseekIntrinsic< wordSize >::operator()(), trap::sbrkSysCall< wordSize >::operator()(), fstatIntrinsic< wordSize >::operator()(), trap::lseekSysCall< wordSize >::operator()(), trap::fstatSysCall< wordSize >::operator()(), statIntrinsic< wordSize >::operator()(), trap::statSysCall< wordSize >::operator()(), _exitIntrinsic< wordSize >::operator()(), timesIntrinsic< wordSize >::operator()(), trap::_exitSysCall< wordSize >::operator()(), timeIntrinsic< wordSize >::operator()(), trap::timesSysCall< wordSize >::operator()(), randomIntrinsic< wordSize >::operator()(), utimesIntrinsic< wordSize >::operator()(), trap::timeSysCall< wordSize >::operator()(), trap::randomSysCall< wordSize >::operator()(), lstatIntrinsic< wordSize >::operator()(), trap::utimesSysCall< wordSize >::operator()(), getpidIntrinsic< wordSize >::operator()(), trap::lstatSysCall< wordSize >::operator()(), chmodIntrinsic< wordSize >::operator()(), dupIntrinsic< wordSize >::operator()(), trap::getpidSysCall< wordSize >::operator()(), trap::chmodSysCall< wordSize >::operator()(), dup2Intrinsic< wordSize >::operator()(), getenvIntrinsic< wordSize >::operator()(), trap::dupSysCall< wordSize >::operator()(), trap::dup2SysCall< wordSize >::operator()(), gettimeofdayIntrinsic< wordSize >::operator()(), trap::getenvSysCall< wordSize >::operator()(), killIntrinsic< wordSize >::operator()(), errorIntrinsic< wordSize >::operator()(), trap::gettimeofdaySysCall< wordSize >::operator()(), chownIntrinsic< wordSize >::operator()(), trap::killSysCall< wordSize >::operator()(), unlinkIntrinsic< wordSize >::operator()(), trap::errorSysCall< wordSize >::operator()(), usleepIntrinsic< wordSize >::operator()(), trap::chownSysCall< wordSize >::operator()(), trap::unlinkSysCall< wordSize >::operator()(), trap::usleepSysCall< wordSize >::operator()(), sysconfIntrinsic< wordSize >::operator()(), trap::sysconfSysCall< wordSize >::operator()(), pysc_signal_handler(), powermonitor::report_trigger(), AHBCtrl::RequestThread(), AHBCtrl::ResponseThread(), APBUART::send_irq(), stopSimFunction(), Initiator::thread_process(), GPCounter::ticking(), APBUART::uart_ticks(), vwait(), leon3_funclt_trap::LEON3_ABIIf::waitInstrEnd(), and leon3_funclt_trap::TLMMemory::write_byte().