SoCRocket: core.waf.cpplint Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
core.waf.cpplint Namespace Reference
Classes
class cpplint
class CPPLint
class cpplint_formatter
class cpplint_wrapper
Functions
def init_env_from_options
def get_cpplint_logger
def cpplint_includes
def run_cpplint
def options
def configure
def lint
Variables
int critical_errors = 0
string CPPLINT_FORMAT = '[CPPLINT] %(filename)s:\nline %(linenum)s, severity %(confidence)s, category: %(category)s\n%(message)s\n'
tuple RE_EMACS = re.compile('(?P<filename>.*):(?P<linenum>\d+): (?P<message>.*) \[(?P<category>.*)\] \[(?P<confidence>\d+)\]')
dictionary CPPLINT_RE
cpplint_logger = None
Function Documentation
def core.waf.cpplint.configure (self)
def core.waf.cpplint.cpplint_includes (self, node)
def core.waf.cpplint.get_cpplint_logger (fmt)
Referenced by core.waf.cpplint.cpplint.run().
def core.waf.cpplint.init_env_from_options (env)
Referenced by core.waf.cpplint.run_cpplint().
def core.waf.cpplint.lint (self)
Use cpplint to check all files
def core.waf.cpplint.options (opt)
def core.waf.cpplint.run_cpplint (self)
References core.waf.cpplint.init_env_from_options().
Variable Documentation
string core.waf.cpplint.CPPLINT_FORMAT = '[CPPLINT] %(filename)s:\nline %(linenum)s, severity %(confidence)s, category: %(category)s\n%(message)s\n'
core.waf.cpplint.cpplint_logger = None
dictionary core.waf.cpplint.CPPLINT_RE
Initial value:
 = {
     'waf': RE_EMACS,
     'emacs': RE_EMACS,
     'vs7': re.compile('(?P<filename>.*)\((?P<linenum>\d+)\):  (?P<message>.*)  \[(?P<category>.*)\] \[(?P<confidence>\d+)\]'),
     'eclipse': re.compile('(?P<filename>.*):(?P<linenum>\d+): warning: (?P<message>.*)  \[(?P<category>.*)\] \[(?P<confidence>\d+)\]'),
 }
int core.waf.cpplint.critical_errors = 0
tuple core.waf.cpplint.RE_EMACS = re.compile('(?P<filename>.*):(?P<linenum>\d+): (?P<message>.*) \[(?P<category>.*)\] \[(?P<confidence>\d+)\]')