SoCRocket: usi Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
usi Namespace Reference
Namespaces
api
cci
gdb
log
sc_object
shell
systemc
tools
usage
Classes
class ThreadKill
class ThreadReset
class DuplicateThreadHandle
class REPEAT_SPAWN
class PromptStr
class DebugWrapper
class SCCallback
class SCCommand
Functions
def find
def refind
def add_to_reporting_list
def remove_from_reporting_list
def get_current_callback
def interpreter_name
def on
def onCommandFrom
Variables
list __all__ = ["systemc", "api.delegate", "api.registry", "api.report"]
__standalone__ = True
string __interpreter_name__ = ""
sc_callback_debug_wrapper = DebugWrapper
dictionary PHASE
tuple waf_out_dir = waf.get_lockfile_attr("out_dir")
tuple fullname = os.path.normpath(os.path.join(waf_out_dir, filename))
tuple pypath = os.path.splitext(fullname)
tuple pymodule = os.path.basename(os.path.splitext(fullname)[0])
Function Documentation
def usi.add_to_reporting_list (name, severity, verbosity)
References find().
def usi.find (name)
  Finds SystemC sc_objects and returns USIDelegates to each matching object
  Simply provide the name: find('mctrl') -> [USIDelegate('mctrl')]
  Use dots to seperate in hierachy like in SystemC: find('top.leon3_0.mmu.tlb')
  The function can handle wildcards: find('mctrl') -> [USIDelegate('mctrl'), USIDelegate('mctrl.generics'), ...]
  To simplify the function always returns a list of USIDelegate objects.
References usi.systemc.get_top_level_objects, and pysc::api::cci.list().
Referenced by add_to_reporting_list(), refind(), remove_from_reporting_list(), and usi.tools.elf.start_of_simulation().
def usi.get_current_callback ()
May be a spawned thread or a call-in from C++, or in elaboration
Referenced by interpreter_name().
def usi.interpreter_name ()
Return the interpreter name
References get_current_callback().
Referenced by usi.SCCallback.call(), usi.SCCallback.register(), and usi.SCCommand.register().
def usi.on (phase, obj = None, debug = False, time_unit = NS, keyargs = {})
Register phase sccallback handler
Referenced by usi.log.db_reporter.Logger.__del__(), usi.tools.execute.execscript(), usi.log.full_console_reporter.get_actions_str(), usi.tools.args.get_args(), tools.python.power.install(), usi.shell.install(), usi.tools.elf.load_elf_intrinsics_to_processor(), onCommandFrom(), usi.cci.parse_args(), and usi.log.start_of_initialization().
def usi.onCommandFrom (obj, debug = False, time_unit = NS, keyargs = {})
References on().
def usi.refind (regex)
References find().
def usi.remove_from_reporting_list (name)
References find().
Variable Documentation
list usi.__all__ = ["systemc", "api.delegate", "api.registry", "api.report"]
string usi.__interpreter_name__ = ""
usi.__standalone__ = True
tuple usi.fullname = os.path.normpath(os.path.join(waf_out_dir, filename))
dictionary usi.PHASE
Initial value:
 = {
     "start_of_initialization": SCCallback("start_of_initialization"),
     "end_of_initialization": SCCallback("end_of_initialization"),
     "start_of_elaboration": SCCallback("start_of_elaboration"),
     "end_of_elaboration": SCCallback("end_of_elaboration"),
     "start_of_simulation": SCCallback("start_of_simulation"),
     "end_of_simulation": SCCallback("end_of_simulation"),
     "start_of_evaluation": SCCallback("start_of_evaluation"),
     "end_of_evaluation": SCCallback("end_of_evaluation"),
     "pause_of_simulation": SCCallback("pause_of_simulation"),
     "report": SCCallback("report"),
     "command": SCCommand()
 }
tuple usi.pymodule = os.path.basename(os.path.splitext(fullname)[0])
tuple usi.pypath = os.path.splitext(fullname)
usi.sc_callback_debug_wrapper = DebugWrapper
Referenced by usi.SCCallback.register(), and usi.SCCommand.register().
tuple usi.waf_out_dir = waf.get_lockfile_attr("out_dir")