SoCRocket: transcript2db Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
transcript2db Namespace Reference
Functions
def read_log
def time_unit_factor
Variables
list filename = sys.argv[1]
Function Documentation
def transcript2db.read_log (filename)
References pysc::api::cci.list(), and time_unit_factor().
def transcript2db.time_unit_factor (unit)
Referenced by read_log().
Variable Documentation
list transcript2db.filename = sys.argv[1]