SoCRocket: doxygen_preprocessor Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
doxygen_preprocessor Namespace Reference
Functions
def CommandLineHandler
def main
Variables
list ProcessOrder = []
Function Documentation
def doxygen_preprocessor.CommandLineHandler ()
Option parser interface.
Referenced by doxycomment.BlockHandler(), comments.CommentsHandler(), filterprocessor.main(), main(), enhancedtable.ProcessTable(), register.RegisterHandler(), and statemachine.StateMachineHandler().
def doxygen_preprocessor.main (void)
References CommandLineHandler(), and filterprocessor.FilterFiles().
Variable Documentation
list doxygen_preprocessor.ProcessOrder = []