SoCRocket: usi.systemc Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
usi.systemc Namespace Reference
Functions
def start
def stop
def pause
def wait
def time
Variables
FS = api.SC_FS
PS = api.SC_PS
NS = api.SC_NS
US = api.SC_US
MS = api.SC_MS
SEC = api.SC_SEC
dictionary TIME_UNITS
simulation_time = api.simulation_time
delta_count = api.delta_count
set_verbosity = api.set_verbosity
is_running = api.is_running
get_top_level_objects = api.get_top_level_objects
Function Documentation
def usi.systemc.pause (k, kw)
def usi.systemc.start (k, kw)
def usi.systemc.stop (k, kw)
def usi.systemc.time (tu = None)
References usi.systemc.delta_count, and usi.systemc.simulation_time.
Referenced by brm_create_cmd(), GPCounter.calculate(), main(), pout(), trap::ProfInstruction.ProfInstruction(), timeIntrinsic< wordSize >.timeIntrinsic(), trap::timeSysCall< wordSize >.timeSysCall(), sr_signal::signal_out< bool, Irqmp >.write(), and sr_signal::signal_selector< TYPE, MODULE >.write().
def usi.systemc.wait (obj, tu = None)
   if obj is event or event tree,
   call obj.wait(); else it is a scalar
Variable Documentation
usi.systemc.delta_count = api.delta_count
Referenced by usi.systemc.time().
usi.systemc.FS = api.SC_FS
usi.systemc.get_top_level_objects = api.get_top_level_objects
Referenced by usi.find().
usi.systemc.is_running = api.is_running
usi.systemc.MS = api.SC_MS
usi.systemc.NS = api.SC_NS
usi.systemc.PS = api.SC_PS
usi.systemc.SEC = api.SC_SEC
usi.systemc.set_verbosity = api.set_verbosity
usi.systemc.simulation_time = api.simulation_time
Referenced by usi.PromptStr.__str__(), and usi.systemc.time().
dictionary usi.systemc.TIME_UNITS
Initial value:
 = {
     FS:"fs",
     PS:"ps",
     NS:"ns",
     US:"us",
     MS:"ms",
     SEC:"s"
 }
usi.systemc.US = api.SC_US