SoCRocket: core.tools.fixheaderguards Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
core.tools.fixheaderguards Namespace Reference
Functions
def default_guard_define_name_generator
def clean_include_guard
def main
Function Documentation
def core.tools.fixheaderguards.clean_include_guard (file, guard_define_name_generator, check_only)
References pysc::api::cci.write().
Referenced by core.tools.fixheaderguards.main().
def core.tools.fixheaderguards.default_guard_define_name_generator (filename, directory)
Referenced by core.tools.fixheaderguards.main().
def core.tools.fixheaderguards.main (void)
References core.tools.fixheaderguards.clean_include_guard(), and core.tools.fixheaderguards.default_guard_define_name_generator().