SoCRocket: filterprocessor Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
filterprocessor Namespace Reference
Functions
def FilterFiles
def main
Function Documentation
def filterprocessor.FilterFiles (ProcessOrder, options, remainder)
References LEON3Arch.processor.
Referenced by comments.CommentsHandler(), main(), doxygen_preprocessor.main(), enhancedtable.ProcessTable(), register.RegisterHandler(), and statemachine.StateMachineHandler().
def filterprocessor.main (void)
References doxygen_preprocessor.CommandLineHandler(), and FilterFiles().