SoCRocket: comments Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
comments Namespace Reference
Functions
def ProcessComments
def CommentsHandler
Function Documentation
def comments.CommentsHandler (lineArray, options)
References doxycomment.BlockHandler(), doxygen_preprocessor.CommandLineHandler(), and filterprocessor.FilterFiles().
def comments.ProcessComments (lineArray, registerPosition, CommentBlocks)