SoCRocket: usi.cci.parameter Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
usi.cci.parameter Namespace Reference
Classes
class GSParamNonExistent
Functions
def addIndex
def read
def write
def readList
def writeList
def getHead
def getTail
def makeDict
def listParams
def readPropertyDict
def readValueDict
def writeValueDict
def printDict
def filterDict
def paramsToDict
Variables
exists = api.exists
getType = api.get_type_string
getDocumentation = api.get_documentation
getProperties = api.get_properties
Function Documentation
def usi.cci.parameter.addIndex (name, index)
Referenced by usi.cci.parameter.listParams(), usi.cci.parameter.makeDict(), usi.cci.parameter.paramsToDict(), usi.cci.parameter.readList(), usi.cci.parameter.writeList(), and usi.cci.parameter.writeValueDict().
def usi.cci.parameter.filterDict (params, match, parents = [], result = {})
Referenced by tools.python.power.view().
def usi.cci.parameter.getHead (name)
Referenced by usi.cci.parameter.getTail(), and usi.cci.parameter.makeDict().
def usi.cci.parameter.getTail (name)
References usi.cci.parameter.getHead().
Referenced by usi.cci.parameter.makeDict().
def usi.cci.parameter.listParams (name = "")
References usi.cci.parameter.addIndex().
Referenced by usi.cci.parameter.readPropertyDict(), and usi.cci.parameter.readValueDict().
def usi.cci.parameter.makeDict (name, list_of_names, readProperties = False)
References usi.cci.parameter.addIndex(), usi.cci.parameter.getDocumentation, usi.cci.parameter.getHead(), usi.cci.parameter.getProperties, usi.cci.parameter.getTail(), usi.cci.parameter.getType, and usi.cci.parameter.read().
Referenced by usi.cci.parameter.readPropertyDict(), and usi.cci.parameter.readValueDict().
def usi.cci.parameter.paramsToDict (params, base = "")
References usi.cci.parameter.addIndex().
Referenced by tools.python.power.view().
def usi.cci.parameter.printDict (params, indent = 0)
def usi.cci.parameter.read (name)
References usi.cci.parameter.exists.
Referenced by usi.cci.parameter.makeDict(), and usi.cci.parameter.readList().
def usi.cci.parameter.readList (name)
References usi.cci.parameter.addIndex(), usi.cci.parameter.exists, and usi.cci.parameter.read().
def usi.cci.parameter.readPropertyDict (name = "")
References usi.cci.parameter.listParams(), and usi.cci.parameter.makeDict().
Referenced by tools.python.power.view().
def usi.cci.parameter.readValueDict (name = "")
References usi.cci.parameter.listParams(), and usi.cci.parameter.makeDict().
def usi.cci.parameter.write (name, val)
References encode().
Referenced by usi.cci.parameter.writeList(), and usi.cci.parameter.writeValueDict().
def usi.cci.parameter.writeList (name, values)
References usi.cci.parameter.addIndex(), and usi.cci.parameter.write().
def usi.cci.parameter.writeValueDict (name, values)
References usi.cci.parameter.addIndex(), and usi.cci.parameter.write().
Variable Documentation
usi.cci.parameter.exists = api.exists
Referenced by trap::ExecLoader.ExecLoader(), findPath(), usi.cci.parameter.read(), usi.cci.parameter.readList(), and sc_main().
usi.cci.parameter.getDocumentation = api.get_documentation
Referenced by usi.cci.parameter.makeDict().
usi.cci.parameter.getProperties = api.get_properties
Referenced by usi.cci.parameter.makeDict().
usi.cci.parameter.getType = api.get_type_string
Referenced by usi.cci.parameter.makeDict().