SoCRocket: LEON3Methods Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
LEON3Methods Namespace Reference
Functions
def updateAliasCode_abi
def updateAliasCode_decode
def updateAliasCode_exception
Variables
string checkIncrementWin_code
tuple opCode = cxx_writer.writer_code.Code(checkIncrementWin_code)
tuple checkIncrementWin_method = trap.HelperMethod('checkIncrementWin', opCode, 'decode', exception = False, const = True)
string checkDecrementWin_code
tuple checkDecrementWin_method = trap.HelperMethod('checkDecrementWin', opCode, 'decode', exception = False, const = True)
string IncrementRegWindow_code
tuple IncrementRegWindow_method = trap.HelperMethod('IncrementRegWindow', opCode, 'decode', exception = False)
string DecrementRegWindow_code
tuple DecrementRegWindow_method = trap.HelperMethod('DecrementRegWindow', opCode, 'decode', exception = False)
tuple SignExtend_method = trap.HelperMethod('SignExtend', opCode, 'execute', exception = False, const = True)
string raiseExcCode
tuple RaiseException_method = trap.HelperMethod('RaiseException', cxx_writer.writer_code.Code(raiseExcCode), 'exception')
list RaiseException_methodParams = []
tuple IncrementPC = trap.HelperOperation('IncrementPC', opCode, exception = False)
tuple WB_plain = trap.HelperOperation('WB_plain', opCode, exception = False)
tuple WB_tv = trap.HelperOperation('WB_tv', opCode, exception = False)
tuple ICC_writeLogic = trap.HelperOperation('ICC_writeLogic', opCode, exception = False)
tuple ICC_writeAdd = trap.HelperOperation('ICC_writeAdd', opCode, exception = False)
tuple ICC_writeTAdd = trap.HelperOperation('ICC_writeTAdd', opCode, exception = False)
tuple ICC_writeDiv = trap.HelperOperation('ICC_writeDiv', opCode, exception = False)
tuple ICC_writeTVAdd = trap.HelperOperation('ICC_writeTVAdd', opCode, exception = False)
tuple ICC_writeSub = trap.HelperOperation('ICC_writeSub', opCode, exception = False)
tuple ICC_writeTSub = trap.HelperOperation('ICC_writeTSub', opCode, exception = False)
tuple ICC_writeTVSub = trap.HelperOperation('ICC_writeTVSub', opCode, exception = False)
Function Documentation
def LEON3Methods.updateAliasCode_abi ()
def LEON3Methods.updateAliasCode_decode ()
def LEON3Methods.updateAliasCode_exception ()
Variable Documentation
string LEON3Methods.checkDecrementWin_code
Initial value:
 = """
 unsigned int newCwp = ((unsigned int)(PSR[key_CWP] - 1)) % NUM_REG_WIN;
 if(((0x01 << (newCwp)) & WIM) != 0){
     return false;
 }
 else{
     return true;
 }
 """
tuple LEON3Methods.checkDecrementWin_method = trap.HelperMethod('checkDecrementWin', opCode, 'decode', exception = False, const = True)
string LEON3Methods.checkIncrementWin_code
Initial value:
 = """
 unsigned int newCwp = ((unsigned int)(PSR[key_CWP] + 1)) % NUM_REG_WIN;
 if(((0x01 << (newCwp)) & WIM) != 0){
     return false;
 }
 else{
     return true;
 }
 """
tuple LEON3Methods.checkIncrementWin_method = trap.HelperMethod('checkIncrementWin', opCode, 'decode', exception = False, const = True)
string LEON3Methods.DecrementRegWindow_code
Initial value:
 = """
 newCwp = ((unsigned int)(PSR[key_CWP] - 1)) % NUM_REG_WIN;
 if(((0x01 << (newCwp)) & WIM) != 0){
     return false;
 }
 PSR = (PSR & 0xFFFFFFE0) | newCwp;
 """
tuple LEON3Methods.DecrementRegWindow_method = trap.HelperMethod('DecrementRegWindow', opCode, 'decode', exception = False)
tuple LEON3Methods.ICC_writeAdd = trap.HelperOperation('ICC_writeAdd', opCode, exception = False)
Referenced by leon3_funcat_trap::ADDXcc_imm.behavior(), leon3_funclt_trap::ADDXcc_imm.behavior(), leon3_funcat_trap::ADDcc_imm.behavior(), leon3_funclt_trap::ADDcc_imm.behavior(), leon3_funclt_trap::MULScc_reg.behavior(), leon3_funcat_trap::MULScc_reg.behavior(), leon3_funcat_trap::ADDXcc_reg.behavior(), leon3_funclt_trap::ADDXcc_reg.behavior(), leon3_funclt_trap::MULScc_imm.behavior(), leon3_funcat_trap::MULScc_imm.behavior(), leon3_funcat_trap::ADDcc_reg.behavior(), and leon3_funclt_trap::ADDcc_reg.behavior().
tuple LEON3Methods.ICC_writeDiv = trap.HelperOperation('ICC_writeDiv', opCode, exception = False)
Referenced by leon3_funcat_trap::UDIVcc_imm.behavior(), leon3_funclt_trap::UDIVcc_imm.behavior(), leon3_funcat_trap::SDIVcc_reg.behavior(), leon3_funclt_trap::SDIVcc_reg.behavior(), leon3_funclt_trap::UDIVcc_reg.behavior(), leon3_funcat_trap::UDIVcc_reg.behavior(), leon3_funcat_trap::SDIVcc_imm.behavior(), and leon3_funclt_trap::SDIVcc_imm.behavior().
tuple LEON3Methods.ICC_writeLogic = trap.HelperOperation('ICC_writeLogic', opCode, exception = False)
Referenced by leon3_funcat_trap::ANDNcc_reg.behavior(), leon3_funclt_trap::ANDNcc_reg.behavior(), leon3_funcat_trap::XNORcc_reg.behavior(), leon3_funclt_trap::XNORcc_reg.behavior(), leon3_funclt_trap::ANDcc_reg.behavior(), leon3_funcat_trap::ANDcc_reg.behavior(), leon3_funcat_trap::UMULcc_reg.behavior(), leon3_funclt_trap::UMULcc_reg.behavior(), leon3_funcat_trap::ORNcc_reg.behavior(), leon3_funclt_trap::ORNcc_reg.behavior(), leon3_funclt_trap::ANDNcc_imm.behavior(), leon3_funcat_trap::ANDNcc_imm.behavior(), leon3_funclt_trap::UMULcc_imm.behavior(), leon3_funcat_trap::UMULcc_imm.behavior(), leon3_funcat_trap::ORcc_reg.behavior(), leon3_funclt_trap::ORcc_reg.behavior(), leon3_funcat_trap::XORcc_reg.behavior(), leon3_funclt_trap::XORcc_reg.behavior(), leon3_funcat_trap::SMULcc_reg.behavior(), leon3_funclt_trap::SMULcc_reg.behavior(), leon3_funclt_trap::SMULcc_imm.behavior(), leon3_funcat_trap::SMULcc_imm.behavior(), leon3_funclt_trap::XORcc_imm.behavior(), leon3_funcat_trap::XORcc_imm.behavior(), leon3_funclt_trap::ORNcc_imm.behavior(), leon3_funcat_trap::ORNcc_imm.behavior(), leon3_funcat_trap::XNORcc_imm.behavior(), leon3_funclt_trap::XNORcc_imm.behavior(), leon3_funcat_trap::ORcc_imm.behavior(), leon3_funclt_trap::ORcc_imm.behavior(), leon3_funclt_trap::ANDcc_imm.behavior(), and leon3_funcat_trap::ANDcc_imm.behavior().
tuple LEON3Methods.ICC_writeSub = trap.HelperOperation('ICC_writeSub', opCode, exception = False)
Referenced by leon3_funcat_trap::SUBXcc_imm.behavior(), leon3_funclt_trap::SUBXcc_imm.behavior(), leon3_funcat_trap::SUBcc_reg.behavior(), leon3_funclt_trap::SUBcc_reg.behavior(), leon3_funclt_trap::SUBXcc_reg.behavior(), leon3_funcat_trap::SUBXcc_reg.behavior(), leon3_funcat_trap::SUBcc_imm.behavior(), and leon3_funclt_trap::SUBcc_imm.behavior().
tuple LEON3Methods.ICC_writeTAdd = trap.HelperOperation('ICC_writeTAdd', opCode, exception = False)
Referenced by leon3_funcat_trap::TADDcc_reg.behavior(), leon3_funclt_trap::TADDcc_reg.behavior(), leon3_funclt_trap::TADDcc_imm.behavior(), and leon3_funcat_trap::TADDcc_imm.behavior().
tuple LEON3Methods.ICC_writeTSub = trap.HelperOperation('ICC_writeTSub', opCode, exception = False)
Referenced by leon3_funcat_trap::TSUBcc_imm.behavior(), leon3_funclt_trap::TSUBcc_imm.behavior(), leon3_funclt_trap::TSUBcc_reg.behavior(), and leon3_funcat_trap::TSUBcc_reg.behavior().
tuple LEON3Methods.ICC_writeTVAdd = trap.HelperOperation('ICC_writeTVAdd', opCode, exception = False)
Referenced by leon3_funcat_trap::TADDccTV_imm.behavior(), leon3_funclt_trap::TADDccTV_imm.behavior(), leon3_funclt_trap::TADDccTV_reg.behavior(), and leon3_funcat_trap::TADDccTV_reg.behavior().
tuple LEON3Methods.ICC_writeTVSub = trap.HelperOperation('ICC_writeTVSub', opCode, exception = False)
Referenced by leon3_funcat_trap::TSUBccTV_imm.behavior(), leon3_funclt_trap::TSUBccTV_imm.behavior(), leon3_funclt_trap::TSUBccTV_reg.behavior(), and leon3_funcat_trap::TSUBccTV_reg.behavior().
tuple LEON3Methods.IncrementPC = trap.HelperOperation('IncrementPC', opCode, exception = False)
Referenced by leon3_funcat_trap::READasr.behavior(), leon3_funclt_trap::READasr.behavior(), leon3_funcat_trap::WRITEY_reg.behavior(), leon3_funclt_trap::WRITEY_reg.behavior(), leon3_funclt_trap::XNOR_reg.behavior(), leon3_funcat_trap::XNOR_reg.behavior(), leon3_funcat_trap::ANDNcc_reg.behavior(), leon3_funclt_trap::ANDNcc_reg.behavior(), leon3_funclt_trap::LDSB_imm.behavior(), leon3_funcat_trap::LDSB_imm.behavior(), leon3_funclt_trap::WRITEpsr_imm.behavior(), leon3_funcat_trap::WRITEpsr_imm.behavior(), leon3_funclt_trap::READy.behavior(), leon3_funcat_trap::READy.behavior(), leon3_funcat_trap::XNORcc_reg.behavior(), leon3_funclt_trap::XNORcc_reg.behavior(), leon3_funcat_trap::READpsr.behavior(), leon3_funclt_trap::READpsr.behavior(), leon3_funclt_trap::ANDN_imm.behavior(), leon3_funcat_trap::ANDN_imm.behavior(), leon3_funclt_trap::ANDcc_reg.behavior(), leon3_funcat_trap::ANDcc_reg.behavior(), leon3_funclt_trap::TSUBcc_imm.behavior(), leon3_funcat_trap::TSUBcc_imm.behavior(), leon3_funclt_trap::LDSBA_reg.behavior(), leon3_funcat_trap::LDSBA_reg.behavior(), leon3_funclt_trap::LDUH_imm.behavior(), leon3_funcat_trap::LDUH_imm.behavior(), leon3_funclt_trap::STA_reg.behavior(), leon3_funcat_trap::STA_reg.behavior(), leon3_funcat_trap::ORN_reg.behavior(), leon3_funclt_trap::ORN_reg.behavior(), leon3_funcat_trap::LDSHA_reg.behavior(), leon3_funclt_trap::LDSHA_reg.behavior(), leon3_funcat_trap::STBA_reg.behavior(), leon3_funclt_trap::STBA_reg.behavior(), leon3_funcat_trap::ST_imm.behavior(), leon3_funclt_trap::ST_imm.behavior(), leon3_funclt_trap::READtbr.behavior(), leon3_funcat_trap::READtbr.behavior(), leon3_funclt_trap::UDIVcc_imm.behavior(), leon3_funcat_trap::UDIVcc_imm.behavior(), leon3_funclt_trap::SWAPA_reg.behavior(), leon3_funcat_trap::SWAPA_reg.behavior(), leon3_funclt_trap::ADDXcc_imm.behavior(), leon3_funcat_trap::ADDXcc_imm.behavior(), leon3_funclt_trap::STB_imm.behavior(), leon3_funcat_trap::STB_imm.behavior(), leon3_funclt_trap::SUBXcc_imm.behavior(), leon3_funcat_trap::SUBXcc_imm.behavior(), leon3_funclt_trap::STH_reg.behavior(), leon3_funcat_trap::STH_reg.behavior(), leon3_funclt_trap::SRL_imm.behavior(), leon3_funcat_trap::SRL_imm.behavior(), leon3_funclt_trap::WRITEasr_imm.behavior(), leon3_funcat_trap::WRITEasr_imm.behavior(), leon3_funclt_trap::UMULcc_reg.behavior(), leon3_funcat_trap::UMULcc_reg.behavior(), leon3_funclt_trap::LDSTUB_reg.behavior(), leon3_funcat_trap::LDSTUB_reg.behavior(), leon3_funclt_trap::XOR_imm.behavior(), leon3_funcat_trap::XOR_imm.behavior(), leon3_funcat_trap::SMAC_reg.behavior(), leon3_funclt_trap::SMAC_reg.behavior(), leon3_funcat_trap::WRITEasr_reg.behavior(), leon3_funclt_trap::WRITEasr_reg.behavior(), leon3_funcat_trap::LD_reg.behavior(), leon3_funclt_trap::LD_reg.behavior(), leon3_funcat_trap::ST_reg.behavior(), leon3_funclt_trap::ST_reg.behavior(), leon3_funcat_trap::SUBcc_reg.behavior(), leon3_funclt_trap::SUBcc_reg.behavior(), leon3_funcat_trap::LDD_reg.behavior(), leon3_funclt_trap::LDD_reg.behavior(), leon3_funcat_trap::ADDcc_imm.behavior(), leon3_funclt_trap::ADDcc_imm.behavior(), leon3_funcat_trap::LDUH_reg.behavior(), leon3_funclt_trap::LDUH_reg.behavior(), leon3_funcat_trap::SRL_reg.behavior(), leon3_funclt_trap::SRL_reg.behavior(), leon3_funcat_trap::SAVE_imm.behavior(), leon3_funclt_trap::SAVE_imm.behavior(), leon3_funcat_trap::MULScc_reg.behavior(), leon3_funclt_trap::MULScc_reg.behavior(), leon3_funcat_trap::OR_imm.behavior(), leon3_funclt_trap::OR_imm.behavior(), leon3_funcat_trap::STD_imm.behavior(), leon3_funclt_trap::STD_imm.behavior(), leon3_funcat_trap::SUBXcc_reg.behavior(), leon3_funclt_trap::SUBXcc_reg.behavior(), leon3_funcat_trap::ADDX_imm.behavior(), leon3_funclt_trap::ADDX_imm.behavior(), leon3_funclt_trap::SWAP_imm.behavior(), leon3_funcat_trap::SWAP_imm.behavior(), leon3_funclt_trap::UMUL_reg.behavior(), leon3_funcat_trap::UMUL_reg.behavior(), leon3_funclt_trap::WRITEY_imm.behavior(), leon3_funcat_trap::WRITEY_imm.behavior(), leon3_funclt_trap::AND_reg.behavior(), leon3_funcat_trap::AND_reg.behavior(), leon3_funclt_trap::FLUSH_imm.behavior(), leon3_funcat_trap::FLUSH_imm.behavior(), leon3_funclt_trap::SRA_reg.behavior(), leon3_funcat_trap::SRA_reg.behavior(), leon3_funclt_trap::STH_imm.behavior(), leon3_funcat_trap::STH_imm.behavior(), leon3_funclt_trap::WRITEwim_imm.behavior(), leon3_funcat_trap::WRITEwim_imm.behavior(), leon3_funclt_trap::LDD_imm.behavior(), leon3_funcat_trap::LDD_imm.behavior(), leon3_funclt_trap::SLL_imm.behavior(), leon3_funcat_trap::SLL_imm.behavior(), leon3_funclt_trap::LDUHA_reg.behavior(), leon3_funcat_trap::LDUHA_reg.behavior(), leon3_funclt_trap::TADDcc_reg.behavior(), leon3_funcat_trap::TADDcc_reg.behavior(), leon3_funclt_trap::TADDcc_imm.behavior(), leon3_funcat_trap::TADDcc_imm.behavior(), leon3_funclt_trap::SDIV_imm.behavior(), leon3_funcat_trap::SDIV_imm.behavior(), leon3_funclt_trap::TSUBccTV_imm.behavior(), leon3_funcat_trap::TSUBccTV_imm.behavior(), leon3_funclt_trap::FLUSH_reg.behavior(), leon3_funcat_trap::FLUSH_reg.behavior(), leon3_funclt_trap::ORNcc_reg.behavior(), leon3_funcat_trap::ORNcc_reg.behavior(), leon3_funcat_trap::RETT_imm.behavior(), leon3_funclt_trap::RETT_imm.behavior(), leon3_funcat_trap::SDIVcc_reg.behavior(), leon3_funclt_trap::SDIVcc_reg.behavior(), leon3_funcat_trap::ADD_reg.behavior(), leon3_funclt_trap::ADD_reg.behavior(), leon3_funcat_trap::WRITEtbr_imm.behavior(), leon3_funclt_trap::WRITEtbr_imm.behavior(), leon3_funcat_trap::LDUB_reg.behavior(), leon3_funclt_trap::LDUB_reg.behavior(), leon3_funcat_trap::RESTORE_reg.behavior(), leon3_funclt_trap::RESTORE_reg.behavior(), leon3_funcat_trap::ADDXcc_reg.behavior(), leon3_funclt_trap::ADDXcc_reg.behavior(), leon3_funcat_trap::STB_reg.behavior(), leon3_funclt_trap::STB_reg.behavior(), leon3_funcat_trap::AND_imm.behavior(), leon3_funclt_trap::AND_imm.behavior(), leon3_funcat_trap::SMUL_imm.behavior(), leon3_funclt_trap::SMUL_imm.behavior(), leon3_funcat_trap::ADD_imm.behavior(), leon3_funclt_trap::ADD_imm.behavior(), leon3_funcat_trap::UMUL_imm.behavior(), leon3_funclt_trap::UMUL_imm.behavior(), leon3_funcat_trap::READwim.behavior(), leon3_funclt_trap::READwim.behavior(), leon3_funcat_trap::LDSTUB_imm.behavior(), leon3_funclt_trap::LDSTUB_imm.behavior(), leon3_funcat_trap::SMAC_imm.behavior(), leon3_funclt_trap::SMAC_imm.behavior(), leon3_funcat_trap::LDSB_reg.behavior(), leon3_funclt_trap::LDSB_reg.behavior(), leon3_funcat_trap::ANDN_reg.behavior(), leon3_funclt_trap::ANDN_reg.behavior(), leon3_funcat_trap::TSUBccTV_reg.behavior(), leon3_funclt_trap::TSUBccTV_reg.behavior(), leon3_funcat_trap::SETHI.behavior(), leon3_funclt_trap::SETHI.behavior(), leon3_funcat_trap::SRA_imm.behavior(), leon3_funclt_trap::SRA_imm.behavior(), leon3_funcat_trap::LDSH_reg.behavior(), leon3_funclt_trap::LDSH_reg.behavior(), leon3_funclt_trap::UDIVcc_reg.behavior(), leon3_funcat_trap::UDIVcc_reg.behavior(), leon3_funcat_trap::ORN_imm.behavior(), leon3_funclt_trap::ORN_imm.behavior(), leon3_funcat_trap::STD_reg.behavior(), leon3_funclt_trap::STD_reg.behavior(), leon3_funcat_trap::ANDNcc_imm.behavior(), leon3_funclt_trap::ANDNcc_imm.behavior(), leon3_funclt_trap::TADDccTV_imm.behavior(), leon3_funcat_trap::TADDccTV_imm.behavior(), leon3_funcat_trap::WRITEtbr_reg.behavior(), leon3_funclt_trap::WRITEtbr_reg.behavior(), leon3_funclt_trap::SUBX_reg.behavior(), leon3_funcat_trap::SUBX_reg.behavior(), leon3_funclt_trap::XNOR_imm.behavior(), leon3_funcat_trap::XNOR_imm.behavior(), leon3_funcat_trap::UDIV_imm.behavior(), leon3_funclt_trap::UDIV_imm.behavior(), leon3_funcat_trap::LDSH_imm.behavior(), leon3_funclt_trap::LDSH_imm.behavior(), leon3_funclt_trap::UNIMP.behavior(), leon3_funcat_trap::UNIMP.behavior(), leon3_funclt_trap::LDSTUBA_reg.behavior(), leon3_funcat_trap::LDSTUBA_reg.behavior(), leon3_funcat_trap::UMULcc_imm.behavior(), leon3_funclt_trap::UMULcc_imm.behavior(), leon3_funcat_trap::ORcc_reg.behavior(), leon3_funclt_trap::ORcc_reg.behavior(), leon3_funclt_trap::MULScc_imm.behavior(), leon3_funcat_trap::MULScc_imm.behavior(), leon3_funclt_trap::XORcc_reg.behavior(), leon3_funcat_trap::XORcc_reg.behavior(), leon3_funcat_trap::SUB_reg.behavior(), leon3_funclt_trap::SUB_reg.behavior(), leon3_funcat_trap::WRITEwim_reg.behavior(), leon3_funclt_trap::WRITEwim_reg.behavior(), leon3_funcat_trap::UMAC_imm.behavior(), leon3_funclt_trap::UMAC_imm.behavior(), leon3_funcat_trap::TSUBcc_reg.behavior(), leon3_funclt_trap::TSUBcc_reg.behavior(), leon3_funcat_trap::SMULcc_reg.behavior(), leon3_funclt_trap::SMULcc_reg.behavior(), leon3_funcat_trap::SUB_imm.behavior(), leon3_funclt_trap::SUB_imm.behavior(), leon3_funcat_trap::ADDcc_reg.behavior(), leon3_funclt_trap::ADDcc_reg.behavior(), leon3_funclt_trap::XOR_reg.behavior(), leon3_funcat_trap::XOR_reg.behavior(), leon3_funclt_trap::SUBcc_imm.behavior(), leon3_funcat_trap::SUBcc_imm.behavior(), leon3_funcat_trap::TADDccTV_reg.behavior(), leon3_funclt_trap::TADDccTV_reg.behavior(), leon3_funclt_trap::SDIV_reg.behavior(), leon3_funcat_trap::SDIV_reg.behavior(), leon3_funclt_trap::SMULcc_imm.behavior(), leon3_funcat_trap::SMULcc_imm.behavior(), leon3_funclt_trap::SWAP_reg.behavior(), leon3_funcat_trap::SWAP_reg.behavior(), leon3_funcat_trap::SUBX_imm.behavior(), leon3_funclt_trap::SUBX_imm.behavior(), leon3_funcat_trap::STDA_reg.behavior(), leon3_funclt_trap::STDA_reg.behavior(), leon3_funclt_trap::UMAC_reg.behavior(), leon3_funcat_trap::UMAC_reg.behavior(), leon3_funclt_trap::SMUL_reg.behavior(), leon3_funcat_trap::SMUL_reg.behavior(), leon3_funclt_trap::XORcc_imm.behavior(), leon3_funcat_trap::XORcc_imm.behavior(), leon3_funclt_trap::ORNcc_imm.behavior(), leon3_funcat_trap::ORNcc_imm.behavior(), leon3_funcat_trap::LDUBA_reg.behavior(), leon3_funclt_trap::LDUBA_reg.behavior(), leon3_funclt_trap::ADDX_reg.behavior(), leon3_funcat_trap::ADDX_reg.behavior(), leon3_funcat_trap::UDIV_reg.behavior(), leon3_funclt_trap::UDIV_reg.behavior(), leon3_funcat_trap::XNORcc_imm.behavior(), leon3_funclt_trap::XNORcc_imm.behavior(), leon3_funclt_trap::STBAR.behavior(), leon3_funcat_trap::STBAR.behavior(), leon3_funclt_trap::LDA_reg.behavior(), leon3_funcat_trap::LDA_reg.behavior(), leon3_funcat_trap::STHA_reg.behavior(), leon3_funclt_trap::STHA_reg.behavior(), leon3_funcat_trap::LDDA_reg.behavior(), leon3_funclt_trap::LDDA_reg.behavior(), leon3_funclt_trap::SLL_reg.behavior(), leon3_funcat_trap::SLL_reg.behavior(), leon3_funclt_trap::RESTORE_imm.behavior(), leon3_funcat_trap::RESTORE_imm.behavior(), leon3_funcat_trap::LD_imm.behavior(), leon3_funclt_trap::LD_imm.behavior(), leon3_funcat_trap::LDUB_imm.behavior(), leon3_funclt_trap::LDUB_imm.behavior(), leon3_funclt_trap::RETT_reg.behavior(), leon3_funcat_trap::RETT_reg.behavior(), leon3_funclt_trap::SDIVcc_imm.behavior(), leon3_funcat_trap::SDIVcc_imm.behavior(), leon3_funclt_trap::SAVE_reg.behavior(), leon3_funcat_trap::SAVE_reg.behavior(), leon3_funcat_trap::OR_reg.behavior(), leon3_funclt_trap::OR_reg.behavior(), leon3_funcat_trap::ORcc_imm.behavior(), leon3_funclt_trap::ORcc_imm.behavior(), leon3_funcat_trap::WRITEpsr_reg.behavior(), leon3_funclt_trap::WRITEpsr_reg.behavior(), leon3_funclt_trap::ANDcc_imm.behavior(), and leon3_funcat_trap::ANDcc_imm.behavior().
string LEON3Methods.IncrementRegWindow_code
Initial value:
 = """
 newCwp = ((unsigned int)(PSR[key_CWP] + 1)) % NUM_REG_WIN;
 if(((0x01 << (newCwp)) & WIM) != 0){
     return false;
 }
 PSR = (PSR & 0xFFFFFFE0) | newCwp;
 """
tuple LEON3Methods.IncrementRegWindow_method = trap.HelperMethod('IncrementRegWindow', opCode, 'decode', exception = False)
tuple LEON3Methods.opCode = cxx_writer.writer_code.Code(checkIncrementWin_code)
string LEON3Methods.raiseExcCode
Initial value:
 = """
 if(PSR[key_ET] == 0){
     if(exceptionId < IRQ_LEV_15){
         // I print a core dump and then I signal an error: an exception happened while
         // exceptions were disabled in the processor core
         THROW_EXCEPTION("Exception " << exceptionId << " happened while the PSR[ET] = 0; PC = " << std::hex << std::showbase << PC << std::endl << "Instruction " << getMnemonic());
     }
 }
 else{
     unsigned int curPSR = PSR;
     curPSR = (curPSR & 0xffffffbf) | (PSR[key_S] << 6);
     curPSR = (curPSR & 0xffffff7f) | 0x00000080;
     curPSR &= 0xffffffdf;
     unsigned int newCwp = ((unsigned int)(PSR[key_CWP] - 1)) % NUM_REG_WIN;
 """
tuple LEON3Methods.RaiseException_method = trap.HelperMethod('RaiseException', cxx_writer.writer_code.Code(raiseExcCode), 'exception')
list LEON3Methods.RaiseException_methodParams = []
tuple LEON3Methods.SignExtend_method = trap.HelperMethod('SignExtend', opCode, 'execute', exception = False, const = True)
tuple LEON3Methods.WB_plain = trap.HelperOperation('WB_plain', opCode, exception = False)
Referenced by leon3_funcat_trap::XNOR_reg.behavior(), leon3_funclt_trap::XNOR_reg.behavior(), leon3_funcat_trap::ANDNcc_reg.behavior(), leon3_funclt_trap::ANDNcc_reg.behavior(), leon3_funclt_trap::XNORcc_reg.behavior(), leon3_funcat_trap::XNORcc_reg.behavior(), leon3_funcat_trap::ANDN_imm.behavior(), leon3_funclt_trap::ANDN_imm.behavior(), leon3_funclt_trap::ANDcc_reg.behavior(), leon3_funcat_trap::ANDcc_reg.behavior(), leon3_funclt_trap::TSUBcc_imm.behavior(), leon3_funcat_trap::TSUBcc_imm.behavior(), leon3_funclt_trap::ORN_reg.behavior(), leon3_funcat_trap::ORN_reg.behavior(), leon3_funcat_trap::UDIVcc_imm.behavior(), leon3_funclt_trap::UDIVcc_imm.behavior(), leon3_funcat_trap::ADDXcc_imm.behavior(), leon3_funclt_trap::ADDXcc_imm.behavior(), leon3_funcat_trap::SUBXcc_imm.behavior(), leon3_funclt_trap::SUBXcc_imm.behavior(), leon3_funclt_trap::SRL_imm.behavior(), leon3_funcat_trap::SRL_imm.behavior(), leon3_funclt_trap::UMULcc_reg.behavior(), leon3_funcat_trap::UMULcc_reg.behavior(), leon3_funclt_trap::XOR_imm.behavior(), leon3_funcat_trap::XOR_imm.behavior(), leon3_funclt_trap::SMAC_reg.behavior(), leon3_funcat_trap::SMAC_reg.behavior(), leon3_funclt_trap::SUBcc_reg.behavior(), leon3_funcat_trap::SUBcc_reg.behavior(), leon3_funcat_trap::ADDcc_imm.behavior(), leon3_funclt_trap::ADDcc_imm.behavior(), leon3_funcat_trap::SRL_reg.behavior(), leon3_funclt_trap::SRL_reg.behavior(), leon3_funcat_trap::MULScc_reg.behavior(), leon3_funclt_trap::MULScc_reg.behavior(), leon3_funcat_trap::OR_imm.behavior(), leon3_funclt_trap::OR_imm.behavior(), leon3_funcat_trap::SUBXcc_reg.behavior(), leon3_funclt_trap::SUBXcc_reg.behavior(), leon3_funcat_trap::ADDX_imm.behavior(), leon3_funclt_trap::ADDX_imm.behavior(), leon3_funcat_trap::UMUL_reg.behavior(), leon3_funclt_trap::UMUL_reg.behavior(), leon3_funcat_trap::AND_reg.behavior(), leon3_funclt_trap::AND_reg.behavior(), leon3_funcat_trap::SRA_reg.behavior(), leon3_funclt_trap::SRA_reg.behavior(), leon3_funclt_trap::SLL_imm.behavior(), leon3_funcat_trap::SLL_imm.behavior(), leon3_funclt_trap::TADDcc_reg.behavior(), leon3_funcat_trap::TADDcc_reg.behavior(), leon3_funclt_trap::TADDcc_imm.behavior(), leon3_funcat_trap::TADDcc_imm.behavior(), leon3_funclt_trap::SDIV_imm.behavior(), leon3_funcat_trap::SDIV_imm.behavior(), leon3_funclt_trap::ORNcc_reg.behavior(), leon3_funcat_trap::ORNcc_reg.behavior(), leon3_funclt_trap::SDIVcc_reg.behavior(), leon3_funcat_trap::SDIVcc_reg.behavior(), leon3_funclt_trap::ADD_reg.behavior(), leon3_funcat_trap::ADD_reg.behavior(), leon3_funcat_trap::ADDXcc_reg.behavior(), leon3_funclt_trap::ADDXcc_reg.behavior(), leon3_funcat_trap::AND_imm.behavior(), leon3_funclt_trap::AND_imm.behavior(), leon3_funcat_trap::SMUL_imm.behavior(), leon3_funclt_trap::SMUL_imm.behavior(), leon3_funcat_trap::ADD_imm.behavior(), leon3_funclt_trap::ADD_imm.behavior(), leon3_funcat_trap::UMUL_imm.behavior(), leon3_funclt_trap::UMUL_imm.behavior(), leon3_funcat_trap::SMAC_imm.behavior(), leon3_funclt_trap::SMAC_imm.behavior(), leon3_funcat_trap::ANDN_reg.behavior(), leon3_funclt_trap::ANDN_reg.behavior(), leon3_funcat_trap::SETHI.behavior(), leon3_funclt_trap::SETHI.behavior(), leon3_funcat_trap::SRA_imm.behavior(), leon3_funclt_trap::SRA_imm.behavior(), leon3_funcat_trap::UDIVcc_reg.behavior(), leon3_funclt_trap::UDIVcc_reg.behavior(), leon3_funcat_trap::ORN_imm.behavior(), leon3_funclt_trap::ORN_imm.behavior(), leon3_funcat_trap::ANDNcc_imm.behavior(), leon3_funclt_trap::ANDNcc_imm.behavior(), leon3_funcat_trap::SUBX_reg.behavior(), leon3_funclt_trap::SUBX_reg.behavior(), leon3_funcat_trap::XNOR_imm.behavior(), leon3_funclt_trap::XNOR_imm.behavior(), leon3_funclt_trap::UDIV_imm.behavior(), leon3_funcat_trap::UDIV_imm.behavior(), leon3_funcat_trap::UMULcc_imm.behavior(), leon3_funclt_trap::UMULcc_imm.behavior(), leon3_funcat_trap::ORcc_reg.behavior(), leon3_funclt_trap::ORcc_reg.behavior(), leon3_funclt_trap::MULScc_imm.behavior(), leon3_funcat_trap::MULScc_imm.behavior(), leon3_funcat_trap::XORcc_reg.behavior(), leon3_funclt_trap::XORcc_reg.behavior(), leon3_funcat_trap::SUB_reg.behavior(), leon3_funclt_trap::SUB_reg.behavior(), leon3_funclt_trap::UMAC_imm.behavior(), leon3_funcat_trap::UMAC_imm.behavior(), leon3_funclt_trap::TSUBcc_reg.behavior(), leon3_funcat_trap::TSUBcc_reg.behavior(), leon3_funcat_trap::SMULcc_reg.behavior(), leon3_funclt_trap::SMULcc_reg.behavior(), leon3_funclt_trap::SUB_imm.behavior(), leon3_funcat_trap::SUB_imm.behavior(), leon3_funclt_trap::ADDcc_reg.behavior(), leon3_funcat_trap::ADDcc_reg.behavior(), leon3_funclt_trap::XOR_reg.behavior(), leon3_funcat_trap::XOR_reg.behavior(), leon3_funclt_trap::SUBcc_imm.behavior(), leon3_funcat_trap::SUBcc_imm.behavior(), leon3_funcat_trap::SDIV_reg.behavior(), leon3_funclt_trap::SDIV_reg.behavior(), leon3_funclt_trap::SMULcc_imm.behavior(), leon3_funcat_trap::SMULcc_imm.behavior(), leon3_funclt_trap::SUBX_imm.behavior(), leon3_funcat_trap::SUBX_imm.behavior(), leon3_funclt_trap::UMAC_reg.behavior(), leon3_funcat_trap::UMAC_reg.behavior(), leon3_funclt_trap::SMUL_reg.behavior(), leon3_funcat_trap::SMUL_reg.behavior(), leon3_funcat_trap::XORcc_imm.behavior(), leon3_funclt_trap::XORcc_imm.behavior(), leon3_funcat_trap::ORNcc_imm.behavior(), leon3_funclt_trap::ORNcc_imm.behavior(), leon3_funcat_trap::ADDX_reg.behavior(), leon3_funclt_trap::ADDX_reg.behavior(), leon3_funcat_trap::UDIV_reg.behavior(), leon3_funclt_trap::UDIV_reg.behavior(), leon3_funcat_trap::XNORcc_imm.behavior(), leon3_funclt_trap::XNORcc_imm.behavior(), leon3_funcat_trap::SLL_reg.behavior(), leon3_funclt_trap::SLL_reg.behavior(), leon3_funclt_trap::SDIVcc_imm.behavior(), leon3_funcat_trap::SDIVcc_imm.behavior(), leon3_funcat_trap::OR_reg.behavior(), leon3_funclt_trap::OR_reg.behavior(), leon3_funcat_trap::ORcc_imm.behavior(), leon3_funclt_trap::ORcc_imm.behavior(), leon3_funcat_trap::ANDcc_imm.behavior(), and leon3_funclt_trap::ANDcc_imm.behavior().
tuple LEON3Methods.WB_tv = trap.HelperOperation('WB_tv', opCode, exception = False)
Referenced by leon3_funcat_trap::TSUBccTV_imm.behavior(), leon3_funclt_trap::TSUBccTV_imm.behavior(), leon3_funcat_trap::TSUBccTV_reg.behavior(), leon3_funclt_trap::TSUBccTV_reg.behavior(), leon3_funclt_trap::TADDccTV_imm.behavior(), leon3_funcat_trap::TADDccTV_imm.behavior(), leon3_funcat_trap::TADDccTV_reg.behavior(), and leon3_funclt_trap::TADDccTV_reg.behavior().