SoCRocket: doxycomment Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
doxycomment Namespace Reference
Functions
def FindDoxygenComments
def ExtractCommentBlocks
def IsCommentBlockStart
def IsCommentBlockEnd
def IsInCommentBlock
def GetCommentBlock
def SplitLine
def BlockHandler
Variables
tuple fh = open(remainder[0])
list lineArray = [line.rstrip() for line in fh]
tuple FullBlocks = ExtractCommentBlocks(lineArray, options)
Function Documentation
def doxycomment.BlockHandler (lineArray, options, StartDelimiter, EndDelimiter, Processor)
References doxygen_preprocessor.CommandLineHandler(), ExtractCommentBlocks(), and find().
Referenced by comments.CommentsHandler(), enhancedtable.ProcessTable(), register.RegisterHandler(), and statemachine.StateMachineHandler().
def doxycomment.ExtractCommentBlocks (lineArray, options, CommentBlocks = None)
Extract the content of all Doxygen Comment Blocks in a file.
References FindDoxygenComments().
Referenced by BlockHandler().
def doxycomment.FindDoxygenComments (lineArray, options)
Find the location of all Doxygen Comment Blocks in a file.
Referenced by ExtractCommentBlocks().
def doxycomment.GetCommentBlock (LineNumber, CommentBlocks)
Referenced by SplitLine().
def doxycomment.IsCommentBlockEnd (LineNumber, CommentBlocks)
Referenced by statemachine.ProcessStateMachine(), and SplitLine().
def doxycomment.IsCommentBlockStart (LineNumber, CommentBlocks)
Referenced by statemachine.ProcessStateMachine(), and SplitLine().
def doxycomment.IsInCommentBlock (LineNumber, CommentBlocks)
Referenced by SplitLine().
def doxycomment.SplitLine (Line, LineNumber, CommentBlocks)
References GetCommentBlock(), IsCommentBlockEnd(), IsCommentBlockStart(), and IsInCommentBlock().
Variable Documentation
tuple doxycomment.fh = open(remainder[0])
tuple doxycomment.FullBlocks = ExtractCommentBlocks(lineArray, options)
list doxycomment.lineArray = [line.rstrip() for line in fh]