SoCRocket: usi.tools.args Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
usi.tools.args Namespace Reference
Functions
def get_args
def args
Variables
ARGS = None
tuple parser
Function Documentation
def usi.tools.args.args (k, kw)
References usi.tools.args.get_args().
def usi.tools.args.get_args ()
References usi.on().
Referenced by usi.tools.args.args(), usi.shell.args(), usi.cci.parse_args(), usi.cci.show_configuration(), usi.tools.execute.start_of_initialization(), and usi.tools.elf.start_of_simulation().
Variable Documentation
usi.tools.args.ARGS = None
tuple usi.tools.args.parser
Initial value:
 = argparse.ArgumentParser(
   usage=usage.USAGE,
   description=usage.HELP,
 )