SoCRocket: LEON3Arch Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
LEON3Arch Namespace Reference
Variables
string banner = r""
string destFolderName = 'processor'
standalone = False
tuple processor = trap.Processor('LEON3', version = '0.3', systemc = True, instructionCache = True, cacheLimit = 256)
tuple globalRegs = trap.RegisterBank('GLOBAL', 8, 32)
tuple windowRegs = trap.RegisterBank('WINREGS', 16*numRegWindows, 32)
dictionary psrBitMask = {'IMPL': (28, 31), 'VER': (24, 27), 'ICC_n': (23, 23), 'ICC_z': (22, 22), 'ICC_v': (21, 21), 'ICC_c': (20, 20), 'EC': (13, 13), 'EF': (12, 12), 'PIL': (8, 11), 'S': (7, 7), 'PS': (6, 6), 'ET': (5, 5), 'CWP': (0, 4)}
tuple psrReg = trap.Register('PSR', 32, psrBitMask)
dictionary wimBitMask = {}
tuple wimReg = trap.Register('WIM', 32, wimBitMask)
dictionary tbrBitMask = {'TBA' : (12, 31), 'TT' : (4, 11)}
tuple tbrReg = trap.Register('TBR', 32, tbrBitMask)
tuple yReg = trap.Register('Y', 32)
tuple pcReg = trap.Register('PC', 32)
tuple npcReg = trap.Register('NPC', 32)
tuple asrRegs = trap.RegisterBank('ASR', 32, 32)
tuple regs = trap.AliasRegBank('REGS', 32, ('GLOBAL[0-7]', 'WINREGS[0-23]'))
tuple FP = trap.AliasRegister('FP', 'REGS[30]')
tuple LR = trap.AliasRegister('LR', 'REGS[31]')
tuple SP = trap.AliasRegister('SP', 'REGS[14]')
tuple PCR = trap.AliasRegister('PCR', 'ASR[17]')
tuple irqPort = trap.Interrupt('IRQ', 32)
tuple irqAckPin = trap.Pins('irqAck', 32, inbound = False)
tuple fetchStage = trap.PipeStage('fetch')
tuple decodeStage = trap.PipeStage('decode')
tuple regsStage = trap.PipeStage('regs')
tuple executeStage = trap.PipeStage('execute')
tuple memoryStage = trap.PipeStage('memory')
tuple exceptionStage = trap.PipeStage('exception')
tuple wbStage = trap.PipeStage('wb')
tuple abi = trap.ABI('REGS[24]', 'REGS[24-29]', 'PC', 'LR', 'SP', 'FP')
string pre_code
string post_code
Variable Documentation
tuple LEON3Arch.abi = trap.ABI('REGS[24]', 'REGS[24-29]', 'PC', 'LR', 'SP', 'FP')
tuple LEON3Arch.asrRegs = trap.RegisterBank('ASR', 32, 32)
string LEON3Arch.banner = r""
tuple LEON3Arch.decodeStage = trap.PipeStage('decode')
list LEON3Arch.destFolderName = 'processor'
tuple LEON3Arch.exceptionStage = trap.PipeStage('exception')
tuple LEON3Arch.executeStage = trap.PipeStage('execute')
tuple LEON3Arch.fetchStage = trap.PipeStage('fetch')
tuple LEON3Arch.FP = trap.AliasRegister('FP', 'REGS[30]')
Referenced by leon3_funcat_trap::LEON3_ABIIf.readFP(), leon3_funclt_trap::LEON3_ABIIf.readFP(), leon3_funcat_trap::InvalidInstr.replicate(), leon3_funclt_trap::InvalidInstr.replicate(), leon3_funcat_trap::READasr.replicate(), leon3_funclt_trap::READasr.replicate(), leon3_funclt_trap::WRITEY_reg.replicate(), leon3_funcat_trap::WRITEY_reg.replicate(), leon3_funcat_trap::XNOR_reg.replicate(), leon3_funclt_trap::XNOR_reg.replicate(), leon3_funclt_trap::ANDNcc_reg.replicate(), leon3_funcat_trap::ANDNcc_reg.replicate(), leon3_funclt_trap::LDSB_imm.replicate(), leon3_funcat_trap::LDSB_imm.replicate(), leon3_funclt_trap::WRITEpsr_imm.replicate(), leon3_funcat_trap::WRITEpsr_imm.replicate(), leon3_funcat_trap::READy.replicate(), leon3_funclt_trap::READy.replicate(), leon3_funcat_trap::XNORcc_reg.replicate(), leon3_funclt_trap::XNORcc_reg.replicate(), leon3_funclt_trap::READpsr.replicate(), leon3_funcat_trap::READpsr.replicate(), leon3_funclt_trap::ANDN_imm.replicate(), leon3_funcat_trap::ANDN_imm.replicate(), leon3_funclt_trap::ANDcc_reg.replicate(), leon3_funcat_trap::ANDcc_reg.replicate(), leon3_funclt_trap::TSUBcc_imm.replicate(), leon3_funcat_trap::TSUBcc_imm.replicate(), leon3_funclt_trap::LDSBA_reg.replicate(), leon3_funcat_trap::LDSBA_reg.replicate(), leon3_funclt_trap::LDUH_imm.replicate(), leon3_funcat_trap::LDUH_imm.replicate(), leon3_funcat_trap::STA_reg.replicate(), leon3_funclt_trap::STA_reg.replicate(), leon3_funcat_trap::ORN_reg.replicate(), leon3_funclt_trap::ORN_reg.replicate(), leon3_funcat_trap::LDSHA_reg.replicate(), leon3_funclt_trap::LDSHA_reg.replicate(), leon3_funcat_trap::STBA_reg.replicate(), leon3_funclt_trap::STBA_reg.replicate(), leon3_funcat_trap::ST_imm.replicate(), leon3_funclt_trap::ST_imm.replicate(), leon3_funclt_trap::READtbr.replicate(), leon3_funcat_trap::READtbr.replicate(), leon3_funclt_trap::UDIVcc_imm.replicate(), leon3_funcat_trap::UDIVcc_imm.replicate(), leon3_funclt_trap::SWAPA_reg.replicate(), leon3_funcat_trap::SWAPA_reg.replicate(), leon3_funclt_trap::ADDXcc_imm.replicate(), leon3_funcat_trap::ADDXcc_imm.replicate(), leon3_funclt_trap::STB_imm.replicate(), leon3_funcat_trap::STB_imm.replicate(), leon3_funclt_trap::SUBXcc_imm.replicate(), leon3_funcat_trap::SUBXcc_imm.replicate(), leon3_funclt_trap::STH_reg.replicate(), leon3_funcat_trap::STH_reg.replicate(), leon3_funclt_trap::SRL_imm.replicate(), leon3_funcat_trap::SRL_imm.replicate(), leon3_funclt_trap::WRITEasr_imm.replicate(), leon3_funcat_trap::WRITEasr_imm.replicate(), leon3_funclt_trap::UMULcc_reg.replicate(), leon3_funcat_trap::UMULcc_reg.replicate(), leon3_funclt_trap::LDSTUB_reg.replicate(), leon3_funcat_trap::LDSTUB_reg.replicate(), leon3_funcat_trap::XOR_imm.replicate(), leon3_funclt_trap::XOR_imm.replicate(), leon3_funcat_trap::SMAC_reg.replicate(), leon3_funclt_trap::SMAC_reg.replicate(), leon3_funcat_trap::WRITEasr_reg.replicate(), leon3_funclt_trap::WRITEasr_reg.replicate(), leon3_funcat_trap::LD_reg.replicate(), leon3_funclt_trap::LD_reg.replicate(), leon3_funcat_trap::ST_reg.replicate(), leon3_funclt_trap::ST_reg.replicate(), leon3_funcat_trap::SUBcc_reg.replicate(), leon3_funclt_trap::SUBcc_reg.replicate(), leon3_funcat_trap::LDD_reg.replicate(), leon3_funclt_trap::LDD_reg.replicate(), leon3_funcat_trap::ADDcc_imm.replicate(), leon3_funclt_trap::ADDcc_imm.replicate(), leon3_funcat_trap::LDUH_reg.replicate(), leon3_funclt_trap::LDUH_reg.replicate(), leon3_funcat_trap::SRL_reg.replicate(), leon3_funclt_trap::SRL_reg.replicate(), leon3_funcat_trap::SAVE_imm.replicate(), leon3_funclt_trap::SAVE_imm.replicate(), leon3_funcat_trap::MULScc_reg.replicate(), leon3_funclt_trap::MULScc_reg.replicate(), leon3_funcat_trap::OR_imm.replicate(), leon3_funclt_trap::OR_imm.replicate(), leon3_funcat_trap::STD_imm.replicate(), leon3_funclt_trap::STD_imm.replicate(), leon3_funcat_trap::SUBXcc_reg.replicate(), leon3_funclt_trap::SUBXcc_reg.replicate(), leon3_funcat_trap::ADDX_imm.replicate(), leon3_funclt_trap::ADDX_imm.replicate(), leon3_funcat_trap::SWAP_imm.replicate(), leon3_funclt_trap::SWAP_imm.replicate(), leon3_funclt_trap::UMUL_reg.replicate(), leon3_funcat_trap::UMUL_reg.replicate(), leon3_funclt_trap::WRITEY_imm.replicate(), leon3_funcat_trap::WRITEY_imm.replicate(), leon3_funclt_trap::AND_reg.replicate(), leon3_funcat_trap::AND_reg.replicate(), leon3_funclt_trap::FLUSH_imm.replicate(), leon3_funcat_trap::FLUSH_imm.replicate(), leon3_funclt_trap::SRA_reg.replicate(), leon3_funcat_trap::SRA_reg.replicate(), leon3_funclt_trap::STH_imm.replicate(), leon3_funcat_trap::STH_imm.replicate(), leon3_funclt_trap::WRITEwim_imm.replicate(), leon3_funcat_trap::WRITEwim_imm.replicate(), leon3_funclt_trap::LDD_imm.replicate(), leon3_funcat_trap::LDD_imm.replicate(), leon3_funclt_trap::SLL_imm.replicate(), leon3_funcat_trap::SLL_imm.replicate(), leon3_funclt_trap::LDUHA_reg.replicate(), leon3_funcat_trap::LDUHA_reg.replicate(), leon3_funclt_trap::TADDcc_reg.replicate(), leon3_funcat_trap::TADDcc_reg.replicate(), leon3_funclt_trap::TADDcc_imm.replicate(), leon3_funcat_trap::TADDcc_imm.replicate(), leon3_funclt_trap::SDIV_imm.replicate(), leon3_funcat_trap::SDIV_imm.replicate(), leon3_funclt_trap::TSUBccTV_imm.replicate(), leon3_funcat_trap::TSUBccTV_imm.replicate(), leon3_funclt_trap::FLUSH_reg.replicate(), leon3_funcat_trap::FLUSH_reg.replicate(), leon3_funcat_trap::ORNcc_reg.replicate(), leon3_funclt_trap::ORNcc_reg.replicate(), leon3_funcat_trap::RETT_imm.replicate(), leon3_funclt_trap::RETT_imm.replicate(), leon3_funcat_trap::SDIVcc_reg.replicate(), leon3_funclt_trap::SDIVcc_reg.replicate(), leon3_funcat_trap::ADD_reg.replicate(), leon3_funclt_trap::ADD_reg.replicate(), leon3_funcat_trap::TRAP_imm.replicate(), leon3_funclt_trap::TRAP_imm.replicate(), leon3_funcat_trap::WRITEtbr_imm.replicate(), leon3_funclt_trap::WRITEtbr_imm.replicate(), leon3_funcat_trap::LDUB_reg.replicate(), leon3_funclt_trap::LDUB_reg.replicate(), leon3_funcat_trap::RESTORE_reg.replicate(), leon3_funclt_trap::RESTORE_reg.replicate(), leon3_funcat_trap::ADDXcc_reg.replicate(), leon3_funclt_trap::ADDXcc_reg.replicate(), leon3_funcat_trap::STB_reg.replicate(), leon3_funclt_trap::STB_reg.replicate(), leon3_funcat_trap::AND_imm.replicate(), leon3_funclt_trap::AND_imm.replicate(), leon3_funcat_trap::SMUL_imm.replicate(), leon3_funclt_trap::SMUL_imm.replicate(), leon3_funcat_trap::ADD_imm.replicate(), leon3_funclt_trap::ADD_imm.replicate(), leon3_funcat_trap::UMUL_imm.replicate(), leon3_funclt_trap::UMUL_imm.replicate(), leon3_funcat_trap::READwim.replicate(), leon3_funclt_trap::READwim.replicate(), leon3_funcat_trap::LDSTUB_imm.replicate(), leon3_funclt_trap::LDSTUB_imm.replicate(), leon3_funcat_trap::SMAC_imm.replicate(), leon3_funclt_trap::SMAC_imm.replicate(), leon3_funcat_trap::LDSB_reg.replicate(), leon3_funclt_trap::LDSB_reg.replicate(), leon3_funcat_trap::ANDN_reg.replicate(), leon3_funclt_trap::ANDN_reg.replicate(), leon3_funcat_trap::TSUBccTV_reg.replicate(), leon3_funclt_trap::TSUBccTV_reg.replicate(), leon3_funcat_trap::SETHI.replicate(), leon3_funclt_trap::SETHI.replicate(), leon3_funcat_trap::SRA_imm.replicate(), leon3_funclt_trap::SRA_imm.replicate(), leon3_funcat_trap::LDSH_reg.replicate(), leon3_funclt_trap::LDSH_reg.replicate(), leon3_funcat_trap::UDIVcc_reg.replicate(), leon3_funclt_trap::UDIVcc_reg.replicate(), leon3_funcat_trap::ORN_imm.replicate(), leon3_funclt_trap::ORN_imm.replicate(), leon3_funclt_trap::STD_reg.replicate(), leon3_funcat_trap::STD_reg.replicate(), leon3_funcat_trap::ANDNcc_imm.replicate(), leon3_funclt_trap::ANDNcc_imm.replicate(), leon3_funcat_trap::TADDccTV_imm.replicate(), leon3_funclt_trap::TADDccTV_imm.replicate(), leon3_funcat_trap::WRITEtbr_reg.replicate(), leon3_funclt_trap::WRITEtbr_reg.replicate(), leon3_funclt_trap::SUBX_reg.replicate(), leon3_funcat_trap::SUBX_reg.replicate(), leon3_funcat_trap::XNOR_imm.replicate(), leon3_funclt_trap::XNOR_imm.replicate(), leon3_funcat_trap::UDIV_imm.replicate(), leon3_funclt_trap::UDIV_imm.replicate(), leon3_funcat_trap::LDSH_imm.replicate(), leon3_funclt_trap::LDSH_imm.replicate(), leon3_funclt_trap::UNIMP.replicate(), leon3_funcat_trap::UNIMP.replicate(), leon3_funcat_trap::LDSTUBA_reg.replicate(), leon3_funclt_trap::LDSTUBA_reg.replicate(), leon3_funclt_trap::UMULcc_imm.replicate(), leon3_funcat_trap::UMULcc_imm.replicate(), leon3_funclt_trap::ORcc_reg.replicate(), leon3_funcat_trap::ORcc_reg.replicate(), leon3_funclt_trap::MULScc_imm.replicate(), leon3_funcat_trap::MULScc_imm.replicate(), leon3_funcat_trap::XORcc_reg.replicate(), leon3_funclt_trap::XORcc_reg.replicate(), leon3_funcat_trap::SUB_reg.replicate(), leon3_funclt_trap::SUB_reg.replicate(), leon3_funcat_trap::WRITEwim_reg.replicate(), leon3_funclt_trap::WRITEwim_reg.replicate(), leon3_funclt_trap::UMAC_imm.replicate(), leon3_funcat_trap::UMAC_imm.replicate(), leon3_funcat_trap::TSUBcc_reg.replicate(), leon3_funclt_trap::TSUBcc_reg.replicate(), leon3_funclt_trap::BRANCH.replicate(), leon3_funcat_trap::BRANCH.replicate(), leon3_funclt_trap::SMULcc_reg.replicate(), leon3_funcat_trap::SMULcc_reg.replicate(), leon3_funclt_trap::SUB_imm.replicate(), leon3_funcat_trap::SUB_imm.replicate(), leon3_funclt_trap::ADDcc_reg.replicate(), leon3_funcat_trap::ADDcc_reg.replicate(), leon3_funclt_trap::XOR_reg.replicate(), leon3_funcat_trap::XOR_reg.replicate(), leon3_funclt_trap::SUBcc_imm.replicate(), leon3_funcat_trap::SUBcc_imm.replicate(), leon3_funcat_trap::TADDccTV_reg.replicate(), leon3_funclt_trap::TADDccTV_reg.replicate(), leon3_funclt_trap::SDIV_reg.replicate(), leon3_funcat_trap::SDIV_reg.replicate(), leon3_funclt_trap::SMULcc_imm.replicate(), leon3_funcat_trap::SMULcc_imm.replicate(), leon3_funcat_trap::SWAP_reg.replicate(), leon3_funclt_trap::SWAP_reg.replicate(), leon3_funclt_trap::SUBX_imm.replicate(), leon3_funcat_trap::SUBX_imm.replicate(), leon3_funclt_trap::STDA_reg.replicate(), leon3_funcat_trap::STDA_reg.replicate(), leon3_funclt_trap::UMAC_reg.replicate(), leon3_funcat_trap::UMAC_reg.replicate(), leon3_funclt_trap::JUMP_imm.replicate(), leon3_funcat_trap::JUMP_imm.replicate(), leon3_funclt_trap::SMUL_reg.replicate(), leon3_funcat_trap::SMUL_reg.replicate(), leon3_funclt_trap::XORcc_imm.replicate(), leon3_funcat_trap::XORcc_imm.replicate(), leon3_funclt_trap::ORNcc_imm.replicate(), leon3_funcat_trap::ORNcc_imm.replicate(), leon3_funclt_trap::LDUBA_reg.replicate(), leon3_funcat_trap::LDUBA_reg.replicate(), leon3_funclt_trap::JUMP_reg.replicate(), leon3_funcat_trap::JUMP_reg.replicate(), leon3_funclt_trap::ADDX_reg.replicate(), leon3_funcat_trap::ADDX_reg.replicate(), leon3_funcat_trap::UDIV_reg.replicate(), leon3_funclt_trap::UDIV_reg.replicate(), leon3_funclt_trap::XNORcc_imm.replicate(), leon3_funcat_trap::XNORcc_imm.replicate(), leon3_funcat_trap::STBAR.replicate(), leon3_funclt_trap::STBAR.replicate(), leon3_funclt_trap::LDA_reg.replicate(), leon3_funcat_trap::LDA_reg.replicate(), leon3_funcat_trap::STHA_reg.replicate(), leon3_funclt_trap::STHA_reg.replicate(), leon3_funcat_trap::LDDA_reg.replicate(), leon3_funclt_trap::LDDA_reg.replicate(), leon3_funclt_trap::SLL_reg.replicate(), leon3_funcat_trap::SLL_reg.replicate(), leon3_funclt_trap::RESTORE_imm.replicate(), leon3_funcat_trap::RESTORE_imm.replicate(), leon3_funcat_trap::LD_imm.replicate(), leon3_funclt_trap::LD_imm.replicate(), leon3_funclt_trap::TRAP_reg.replicate(), leon3_funcat_trap::TRAP_reg.replicate(), leon3_funcat_trap::LDUB_imm.replicate(), leon3_funclt_trap::LDUB_imm.replicate(), leon3_funcat_trap::RETT_reg.replicate(), leon3_funclt_trap::RETT_reg.replicate(), leon3_funcat_trap::SDIVcc_imm.replicate(), leon3_funclt_trap::SDIVcc_imm.replicate(), leon3_funcat_trap::SAVE_reg.replicate(), leon3_funclt_trap::SAVE_reg.replicate(), leon3_funclt_trap::OR_reg.replicate(), leon3_funcat_trap::OR_reg.replicate(), leon3_funcat_trap::ORcc_imm.replicate(), leon3_funclt_trap::ORcc_imm.replicate(), leon3_funcat_trap::CALL.replicate(), leon3_funclt_trap::CALL.replicate(), leon3_funclt_trap::WRITEpsr_reg.replicate(), leon3_funcat_trap::WRITEpsr_reg.replicate(), leon3_funcat_trap::ANDcc_imm.replicate(), leon3_funclt_trap::ANDcc_imm.replicate(), leon3_funclt_trap::IRQ_IRQ_Instruction.replicate(), leon3_funcat_trap::IRQ_IRQ_Instruction.replicate(), leon3_funclt_trap::LEON3_ABIIf.setFP(), and leon3_funcat_trap::LEON3_ABIIf.setFP().
tuple LEON3Arch.globalRegs = trap.RegisterBank('GLOBAL', 8, 32)
tuple LEON3Arch.irqAckPin = trap.Pins('irqAck', 32, inbound = False)
tuple LEON3Arch.irqPort = trap.Interrupt('IRQ', 32)
tuple LEON3Arch.LR = trap.AliasRegister('LR', 'REGS[31]')
Referenced by leon3_funcat_trap::LEON3_ABIIf.readLR(), leon3_funclt_trap::LEON3_ABIIf.readLR(), leon3_funcat_trap::InvalidInstr.replicate(), leon3_funclt_trap::InvalidInstr.replicate(), leon3_funcat_trap::READasr.replicate(), leon3_funclt_trap::READasr.replicate(), leon3_funclt_trap::WRITEY_reg.replicate(), leon3_funcat_trap::WRITEY_reg.replicate(), leon3_funcat_trap::XNOR_reg.replicate(), leon3_funclt_trap::XNOR_reg.replicate(), leon3_funclt_trap::ANDNcc_reg.replicate(), leon3_funcat_trap::ANDNcc_reg.replicate(), leon3_funclt_trap::LDSB_imm.replicate(), leon3_funcat_trap::LDSB_imm.replicate(), leon3_funclt_trap::WRITEpsr_imm.replicate(), leon3_funcat_trap::WRITEpsr_imm.replicate(), leon3_funcat_trap::READy.replicate(), leon3_funclt_trap::READy.replicate(), leon3_funcat_trap::XNORcc_reg.replicate(), leon3_funclt_trap::XNORcc_reg.replicate(), leon3_funclt_trap::READpsr.replicate(), leon3_funcat_trap::READpsr.replicate(), leon3_funclt_trap::ANDN_imm.replicate(), leon3_funcat_trap::ANDN_imm.replicate(), leon3_funclt_trap::ANDcc_reg.replicate(), leon3_funcat_trap::ANDcc_reg.replicate(), leon3_funclt_trap::TSUBcc_imm.replicate(), leon3_funcat_trap::TSUBcc_imm.replicate(), leon3_funclt_trap::LDSBA_reg.replicate(), leon3_funcat_trap::LDSBA_reg.replicate(), leon3_funclt_trap::LDUH_imm.replicate(), leon3_funcat_trap::LDUH_imm.replicate(), leon3_funcat_trap::STA_reg.replicate(), leon3_funclt_trap::STA_reg.replicate(), leon3_funcat_trap::ORN_reg.replicate(), leon3_funclt_trap::ORN_reg.replicate(), leon3_funcat_trap::LDSHA_reg.replicate(), leon3_funclt_trap::LDSHA_reg.replicate(), leon3_funcat_trap::STBA_reg.replicate(), leon3_funclt_trap::STBA_reg.replicate(), leon3_funcat_trap::ST_imm.replicate(), leon3_funclt_trap::ST_imm.replicate(), leon3_funclt_trap::READtbr.replicate(), leon3_funcat_trap::READtbr.replicate(), leon3_funclt_trap::UDIVcc_imm.replicate(), leon3_funcat_trap::UDIVcc_imm.replicate(), leon3_funclt_trap::SWAPA_reg.replicate(), leon3_funcat_trap::SWAPA_reg.replicate(), leon3_funclt_trap::ADDXcc_imm.replicate(), leon3_funcat_trap::ADDXcc_imm.replicate(), leon3_funclt_trap::STB_imm.replicate(), leon3_funcat_trap::STB_imm.replicate(), leon3_funclt_trap::SUBXcc_imm.replicate(), leon3_funcat_trap::SUBXcc_imm.replicate(), leon3_funclt_trap::STH_reg.replicate(), leon3_funcat_trap::STH_reg.replicate(), leon3_funclt_trap::SRL_imm.replicate(), leon3_funcat_trap::SRL_imm.replicate(), leon3_funclt_trap::WRITEasr_imm.replicate(), leon3_funcat_trap::WRITEasr_imm.replicate(), leon3_funclt_trap::UMULcc_reg.replicate(), leon3_funcat_trap::UMULcc_reg.replicate(), leon3_funclt_trap::LDSTUB_reg.replicate(), leon3_funcat_trap::LDSTUB_reg.replicate(), leon3_funcat_trap::XOR_imm.replicate(), leon3_funclt_trap::XOR_imm.replicate(), leon3_funcat_trap::SMAC_reg.replicate(), leon3_funclt_trap::SMAC_reg.replicate(), leon3_funcat_trap::WRITEasr_reg.replicate(), leon3_funclt_trap::WRITEasr_reg.replicate(), leon3_funcat_trap::LD_reg.replicate(), leon3_funclt_trap::LD_reg.replicate(), leon3_funcat_trap::ST_reg.replicate(), leon3_funclt_trap::ST_reg.replicate(), leon3_funcat_trap::SUBcc_reg.replicate(), leon3_funclt_trap::SUBcc_reg.replicate(), leon3_funcat_trap::LDD_reg.replicate(), leon3_funclt_trap::LDD_reg.replicate(), leon3_funcat_trap::ADDcc_imm.replicate(), leon3_funclt_trap::ADDcc_imm.replicate(), leon3_funcat_trap::LDUH_reg.replicate(), leon3_funclt_trap::LDUH_reg.replicate(), leon3_funcat_trap::SRL_reg.replicate(), leon3_funclt_trap::SRL_reg.replicate(), leon3_funcat_trap::SAVE_imm.replicate(), leon3_funclt_trap::SAVE_imm.replicate(), leon3_funcat_trap::MULScc_reg.replicate(), leon3_funclt_trap::MULScc_reg.replicate(), leon3_funcat_trap::OR_imm.replicate(), leon3_funclt_trap::OR_imm.replicate(), leon3_funcat_trap::STD_imm.replicate(), leon3_funclt_trap::STD_imm.replicate(), leon3_funcat_trap::SUBXcc_reg.replicate(), leon3_funclt_trap::SUBXcc_reg.replicate(), leon3_funcat_trap::ADDX_imm.replicate(), leon3_funclt_trap::ADDX_imm.replicate(), leon3_funcat_trap::SWAP_imm.replicate(), leon3_funclt_trap::SWAP_imm.replicate(), leon3_funclt_trap::UMUL_reg.replicate(), leon3_funcat_trap::UMUL_reg.replicate(), leon3_funclt_trap::WRITEY_imm.replicate(), leon3_funcat_trap::WRITEY_imm.replicate(), leon3_funclt_trap::AND_reg.replicate(), leon3_funcat_trap::AND_reg.replicate(), leon3_funclt_trap::FLUSH_imm.replicate(), leon3_funcat_trap::FLUSH_imm.replicate(), leon3_funclt_trap::SRA_reg.replicate(), leon3_funcat_trap::SRA_reg.replicate(), leon3_funclt_trap::STH_imm.replicate(), leon3_funcat_trap::STH_imm.replicate(), leon3_funclt_trap::WRITEwim_imm.replicate(), leon3_funcat_trap::WRITEwim_imm.replicate(), leon3_funclt_trap::LDD_imm.replicate(), leon3_funcat_trap::LDD_imm.replicate(), leon3_funclt_trap::SLL_imm.replicate(), leon3_funcat_trap::SLL_imm.replicate(), leon3_funclt_trap::LDUHA_reg.replicate(), leon3_funcat_trap::LDUHA_reg.replicate(), leon3_funclt_trap::TADDcc_reg.replicate(), leon3_funcat_trap::TADDcc_reg.replicate(), leon3_funclt_trap::TADDcc_imm.replicate(), leon3_funcat_trap::TADDcc_imm.replicate(), leon3_funclt_trap::SDIV_imm.replicate(), leon3_funcat_trap::SDIV_imm.replicate(), leon3_funclt_trap::TSUBccTV_imm.replicate(), leon3_funcat_trap::TSUBccTV_imm.replicate(), leon3_funclt_trap::FLUSH_reg.replicate(), leon3_funcat_trap::FLUSH_reg.replicate(), leon3_funcat_trap::ORNcc_reg.replicate(), leon3_funclt_trap::ORNcc_reg.replicate(), leon3_funcat_trap::RETT_imm.replicate(), leon3_funclt_trap::RETT_imm.replicate(), leon3_funcat_trap::SDIVcc_reg.replicate(), leon3_funclt_trap::SDIVcc_reg.replicate(), leon3_funcat_trap::ADD_reg.replicate(), leon3_funclt_trap::ADD_reg.replicate(), leon3_funcat_trap::TRAP_imm.replicate(), leon3_funclt_trap::TRAP_imm.replicate(), leon3_funcat_trap::WRITEtbr_imm.replicate(), leon3_funclt_trap::WRITEtbr_imm.replicate(), leon3_funcat_trap::LDUB_reg.replicate(), leon3_funclt_trap::LDUB_reg.replicate(), leon3_funcat_trap::RESTORE_reg.replicate(), leon3_funclt_trap::RESTORE_reg.replicate(), leon3_funcat_trap::ADDXcc_reg.replicate(), leon3_funclt_trap::ADDXcc_reg.replicate(), leon3_funcat_trap::STB_reg.replicate(), leon3_funclt_trap::STB_reg.replicate(), leon3_funcat_trap::AND_imm.replicate(), leon3_funclt_trap::AND_imm.replicate(), leon3_funcat_trap::SMUL_imm.replicate(), leon3_funclt_trap::SMUL_imm.replicate(), leon3_funcat_trap::ADD_imm.replicate(), leon3_funclt_trap::ADD_imm.replicate(), leon3_funcat_trap::UMUL_imm.replicate(), leon3_funclt_trap::UMUL_imm.replicate(), leon3_funcat_trap::READwim.replicate(), leon3_funclt_trap::READwim.replicate(), leon3_funcat_trap::LDSTUB_imm.replicate(), leon3_funclt_trap::LDSTUB_imm.replicate(), leon3_funcat_trap::SMAC_imm.replicate(), leon3_funclt_trap::SMAC_imm.replicate(), leon3_funcat_trap::LDSB_reg.replicate(), leon3_funclt_trap::LDSB_reg.replicate(), leon3_funcat_trap::ANDN_reg.replicate(), leon3_funclt_trap::ANDN_reg.replicate(), leon3_funcat_trap::TSUBccTV_reg.replicate(), leon3_funclt_trap::TSUBccTV_reg.replicate(), leon3_funcat_trap::SETHI.replicate(), leon3_funclt_trap::SETHI.replicate(), leon3_funcat_trap::SRA_imm.replicate(), leon3_funclt_trap::SRA_imm.replicate(), leon3_funcat_trap::LDSH_reg.replicate(), leon3_funclt_trap::LDSH_reg.replicate(), leon3_funcat_trap::UDIVcc_reg.replicate(), leon3_funclt_trap::UDIVcc_reg.replicate(), leon3_funcat_trap::ORN_imm.replicate(), leon3_funclt_trap::ORN_imm.replicate(), leon3_funcat_trap::STD_reg.replicate(), leon3_funclt_trap::STD_reg.replicate(), leon3_funcat_trap::ANDNcc_imm.replicate(), leon3_funclt_trap::ANDNcc_imm.replicate(), leon3_funclt_trap::TADDccTV_imm.replicate(), leon3_funcat_trap::TADDccTV_imm.replicate(), leon3_funcat_trap::WRITEtbr_reg.replicate(), leon3_funclt_trap::WRITEtbr_reg.replicate(), leon3_funclt_trap::SUBX_reg.replicate(), leon3_funcat_trap::SUBX_reg.replicate(), leon3_funcat_trap::XNOR_imm.replicate(), leon3_funclt_trap::XNOR_imm.replicate(), leon3_funcat_trap::UDIV_imm.replicate(), leon3_funclt_trap::UDIV_imm.replicate(), leon3_funcat_trap::LDSH_imm.replicate(), leon3_funclt_trap::LDSH_imm.replicate(), leon3_funcat_trap::UNIMP.replicate(), leon3_funclt_trap::UNIMP.replicate(), leon3_funcat_trap::LDSTUBA_reg.replicate(), leon3_funclt_trap::LDSTUBA_reg.replicate(), leon3_funclt_trap::UMULcc_imm.replicate(), leon3_funcat_trap::UMULcc_imm.replicate(), leon3_funclt_trap::ORcc_reg.replicate(), leon3_funcat_trap::ORcc_reg.replicate(), leon3_funclt_trap::MULScc_imm.replicate(), leon3_funcat_trap::MULScc_imm.replicate(), leon3_funcat_trap::XORcc_reg.replicate(), leon3_funclt_trap::XORcc_reg.replicate(), leon3_funclt_trap::SUB_reg.replicate(), leon3_funcat_trap::SUB_reg.replicate(), leon3_funclt_trap::WRITEwim_reg.replicate(), leon3_funcat_trap::WRITEwim_reg.replicate(), leon3_funcat_trap::UMAC_imm.replicate(), leon3_funclt_trap::UMAC_imm.replicate(), leon3_funcat_trap::TSUBcc_reg.replicate(), leon3_funclt_trap::TSUBcc_reg.replicate(), leon3_funcat_trap::BRANCH.replicate(), leon3_funclt_trap::BRANCH.replicate(), leon3_funclt_trap::SMULcc_reg.replicate(), leon3_funcat_trap::SMULcc_reg.replicate(), leon3_funclt_trap::SUB_imm.replicate(), leon3_funcat_trap::SUB_imm.replicate(), leon3_funclt_trap::ADDcc_reg.replicate(), leon3_funcat_trap::ADDcc_reg.replicate(), leon3_funclt_trap::XOR_reg.replicate(), leon3_funcat_trap::XOR_reg.replicate(), leon3_funclt_trap::SUBcc_imm.replicate(), leon3_funcat_trap::SUBcc_imm.replicate(), leon3_funcat_trap::TADDccTV_reg.replicate(), leon3_funclt_trap::TADDccTV_reg.replicate(), leon3_funclt_trap::SDIV_reg.replicate(), leon3_funcat_trap::SDIV_reg.replicate(), leon3_funcat_trap::SMULcc_imm.replicate(), leon3_funclt_trap::SMULcc_imm.replicate(), leon3_funcat_trap::SWAP_reg.replicate(), leon3_funclt_trap::SWAP_reg.replicate(), leon3_funcat_trap::SUBX_imm.replicate(), leon3_funclt_trap::SUBX_imm.replicate(), leon3_funclt_trap::STDA_reg.replicate(), leon3_funcat_trap::STDA_reg.replicate(), leon3_funcat_trap::UMAC_reg.replicate(), leon3_funclt_trap::UMAC_reg.replicate(), leon3_funclt_trap::JUMP_imm.replicate(), leon3_funcat_trap::JUMP_imm.replicate(), leon3_funclt_trap::SMUL_reg.replicate(), leon3_funcat_trap::SMUL_reg.replicate(), leon3_funclt_trap::XORcc_imm.replicate(), leon3_funcat_trap::XORcc_imm.replicate(), leon3_funclt_trap::ORNcc_imm.replicate(), leon3_funcat_trap::ORNcc_imm.replicate(), leon3_funclt_trap::LDUBA_reg.replicate(), leon3_funcat_trap::LDUBA_reg.replicate(), leon3_funclt_trap::JUMP_reg.replicate(), leon3_funcat_trap::JUMP_reg.replicate(), leon3_funclt_trap::ADDX_reg.replicate(), leon3_funcat_trap::ADDX_reg.replicate(), leon3_funcat_trap::UDIV_reg.replicate(), leon3_funclt_trap::UDIV_reg.replicate(), leon3_funclt_trap::XNORcc_imm.replicate(), leon3_funcat_trap::XNORcc_imm.replicate(), leon3_funclt_trap::STBAR.replicate(), leon3_funcat_trap::STBAR.replicate(), leon3_funcat_trap::LDA_reg.replicate(), leon3_funclt_trap::LDA_reg.replicate(), leon3_funcat_trap::STHA_reg.replicate(), leon3_funclt_trap::STHA_reg.replicate(), leon3_funcat_trap::LDDA_reg.replicate(), leon3_funclt_trap::LDDA_reg.replicate(), leon3_funcat_trap::SLL_reg.replicate(), leon3_funclt_trap::SLL_reg.replicate(), leon3_funcat_trap::RESTORE_imm.replicate(), leon3_funclt_trap::RESTORE_imm.replicate(), leon3_funcat_trap::LD_imm.replicate(), leon3_funclt_trap::LD_imm.replicate(), leon3_funclt_trap::TRAP_reg.replicate(), leon3_funcat_trap::TRAP_reg.replicate(), leon3_funclt_trap::LDUB_imm.replicate(), leon3_funcat_trap::LDUB_imm.replicate(), leon3_funclt_trap::RETT_reg.replicate(), leon3_funcat_trap::RETT_reg.replicate(), leon3_funcat_trap::SDIVcc_imm.replicate(), leon3_funclt_trap::SDIVcc_imm.replicate(), leon3_funcat_trap::SAVE_reg.replicate(), leon3_funclt_trap::SAVE_reg.replicate(), leon3_funcat_trap::OR_reg.replicate(), leon3_funclt_trap::OR_reg.replicate(), leon3_funcat_trap::ORcc_imm.replicate(), leon3_funclt_trap::ORcc_imm.replicate(), leon3_funcat_trap::CALL.replicate(), leon3_funclt_trap::CALL.replicate(), leon3_funclt_trap::WRITEpsr_reg.replicate(), leon3_funcat_trap::WRITEpsr_reg.replicate(), leon3_funcat_trap::ANDcc_imm.replicate(), leon3_funclt_trap::ANDcc_imm.replicate(), leon3_funclt_trap::IRQ_IRQ_Instruction.replicate(), leon3_funcat_trap::IRQ_IRQ_Instruction.replicate(), leon3_funclt_trap::LEON3_ABIIf.returnFromCall(), leon3_funcat_trap::LEON3_ABIIf.returnFromCall(), leon3_funcat_trap::LEON3_ABIIf.setLR(), and leon3_funclt_trap::LEON3_ABIIf.setLR().
tuple LEON3Arch.memoryStage = trap.PipeStage('memory')
tuple LEON3Arch.npcReg = trap.Register('NPC', 32)
tuple LEON3Arch.PCR = trap.AliasRegister('PCR', 'ASR[17]')
Referenced by grtc_test(), leon3_funcat_trap::InvalidInstr.replicate(), leon3_funclt_trap::InvalidInstr.replicate(), leon3_funcat_trap::READasr.replicate(), leon3_funclt_trap::READasr.replicate(), leon3_funclt_trap::WRITEY_reg.replicate(), leon3_funcat_trap::WRITEY_reg.replicate(), leon3_funcat_trap::XNOR_reg.replicate(), leon3_funclt_trap::XNOR_reg.replicate(), leon3_funclt_trap::ANDNcc_reg.replicate(), leon3_funcat_trap::ANDNcc_reg.replicate(), leon3_funclt_trap::LDSB_imm.replicate(), leon3_funcat_trap::LDSB_imm.replicate(), leon3_funclt_trap::WRITEpsr_imm.replicate(), leon3_funcat_trap::WRITEpsr_imm.replicate(), leon3_funcat_trap::READy.replicate(), leon3_funclt_trap::READy.replicate(), leon3_funcat_trap::XNORcc_reg.replicate(), leon3_funclt_trap::XNORcc_reg.replicate(), leon3_funclt_trap::READpsr.replicate(), leon3_funcat_trap::READpsr.replicate(), leon3_funclt_trap::ANDN_imm.replicate(), leon3_funcat_trap::ANDN_imm.replicate(), leon3_funclt_trap::ANDcc_reg.replicate(), leon3_funcat_trap::ANDcc_reg.replicate(), leon3_funclt_trap::TSUBcc_imm.replicate(), leon3_funcat_trap::TSUBcc_imm.replicate(), leon3_funclt_trap::LDSBA_reg.replicate(), leon3_funcat_trap::LDSBA_reg.replicate(), leon3_funclt_trap::LDUH_imm.replicate(), leon3_funcat_trap::LDUH_imm.replicate(), leon3_funcat_trap::STA_reg.replicate(), leon3_funclt_trap::STA_reg.replicate(), leon3_funcat_trap::ORN_reg.replicate(), leon3_funclt_trap::ORN_reg.replicate(), leon3_funcat_trap::LDSHA_reg.replicate(), leon3_funclt_trap::LDSHA_reg.replicate(), leon3_funcat_trap::STBA_reg.replicate(), leon3_funclt_trap::STBA_reg.replicate(), leon3_funcat_trap::ST_imm.replicate(), leon3_funclt_trap::ST_imm.replicate(), leon3_funclt_trap::READtbr.replicate(), leon3_funcat_trap::READtbr.replicate(), leon3_funclt_trap::UDIVcc_imm.replicate(), leon3_funcat_trap::UDIVcc_imm.replicate(), leon3_funclt_trap::SWAPA_reg.replicate(), leon3_funcat_trap::SWAPA_reg.replicate(), leon3_funclt_trap::ADDXcc_imm.replicate(), leon3_funcat_trap::ADDXcc_imm.replicate(), leon3_funclt_trap::STB_imm.replicate(), leon3_funcat_trap::STB_imm.replicate(), leon3_funclt_trap::SUBXcc_imm.replicate(), leon3_funcat_trap::SUBXcc_imm.replicate(), leon3_funclt_trap::STH_reg.replicate(), leon3_funcat_trap::STH_reg.replicate(), leon3_funclt_trap::SRL_imm.replicate(), leon3_funcat_trap::SRL_imm.replicate(), leon3_funclt_trap::WRITEasr_imm.replicate(), leon3_funcat_trap::WRITEasr_imm.replicate(), leon3_funclt_trap::UMULcc_reg.replicate(), leon3_funcat_trap::UMULcc_reg.replicate(), leon3_funclt_trap::LDSTUB_reg.replicate(), leon3_funcat_trap::LDSTUB_reg.replicate(), leon3_funcat_trap::XOR_imm.replicate(), leon3_funclt_trap::XOR_imm.replicate(), leon3_funcat_trap::SMAC_reg.replicate(), leon3_funclt_trap::SMAC_reg.replicate(), leon3_funcat_trap::WRITEasr_reg.replicate(), leon3_funclt_trap::WRITEasr_reg.replicate(), leon3_funcat_trap::LD_reg.replicate(), leon3_funclt_trap::LD_reg.replicate(), leon3_funcat_trap::ST_reg.replicate(), leon3_funclt_trap::ST_reg.replicate(), leon3_funcat_trap::SUBcc_reg.replicate(), leon3_funclt_trap::SUBcc_reg.replicate(), leon3_funcat_trap::LDD_reg.replicate(), leon3_funclt_trap::LDD_reg.replicate(), leon3_funcat_trap::ADDcc_imm.replicate(), leon3_funclt_trap::ADDcc_imm.replicate(), leon3_funcat_trap::LDUH_reg.replicate(), leon3_funclt_trap::LDUH_reg.replicate(), leon3_funcat_trap::SRL_reg.replicate(), leon3_funclt_trap::SRL_reg.replicate(), leon3_funcat_trap::SAVE_imm.replicate(), leon3_funclt_trap::SAVE_imm.replicate(), leon3_funcat_trap::MULScc_reg.replicate(), leon3_funclt_trap::MULScc_reg.replicate(), leon3_funcat_trap::OR_imm.replicate(), leon3_funclt_trap::OR_imm.replicate(), leon3_funcat_trap::STD_imm.replicate(), leon3_funclt_trap::STD_imm.replicate(), leon3_funcat_trap::SUBXcc_reg.replicate(), leon3_funclt_trap::SUBXcc_reg.replicate(), leon3_funcat_trap::ADDX_imm.replicate(), leon3_funclt_trap::ADDX_imm.replicate(), leon3_funcat_trap::SWAP_imm.replicate(), leon3_funclt_trap::SWAP_imm.replicate(), leon3_funclt_trap::UMUL_reg.replicate(), leon3_funcat_trap::UMUL_reg.replicate(), leon3_funclt_trap::WRITEY_imm.replicate(), leon3_funcat_trap::WRITEY_imm.replicate(), leon3_funclt_trap::AND_reg.replicate(), leon3_funcat_trap::AND_reg.replicate(), leon3_funclt_trap::FLUSH_imm.replicate(), leon3_funcat_trap::FLUSH_imm.replicate(), leon3_funclt_trap::SRA_reg.replicate(), leon3_funcat_trap::SRA_reg.replicate(), leon3_funclt_trap::STH_imm.replicate(), leon3_funcat_trap::STH_imm.replicate(), leon3_funclt_trap::WRITEwim_imm.replicate(), leon3_funcat_trap::WRITEwim_imm.replicate(), leon3_funclt_trap::LDD_imm.replicate(), leon3_funcat_trap::LDD_imm.replicate(), leon3_funclt_trap::SLL_imm.replicate(), leon3_funcat_trap::SLL_imm.replicate(), leon3_funclt_trap::LDUHA_reg.replicate(), leon3_funcat_trap::LDUHA_reg.replicate(), leon3_funclt_trap::TADDcc_reg.replicate(), leon3_funcat_trap::TADDcc_reg.replicate(), leon3_funclt_trap::TADDcc_imm.replicate(), leon3_funcat_trap::TADDcc_imm.replicate(), leon3_funclt_trap::SDIV_imm.replicate(), leon3_funcat_trap::SDIV_imm.replicate(), leon3_funclt_trap::TSUBccTV_imm.replicate(), leon3_funcat_trap::TSUBccTV_imm.replicate(), leon3_funclt_trap::FLUSH_reg.replicate(), leon3_funcat_trap::FLUSH_reg.replicate(), leon3_funcat_trap::ORNcc_reg.replicate(), leon3_funclt_trap::ORNcc_reg.replicate(), leon3_funcat_trap::RETT_imm.replicate(), leon3_funclt_trap::RETT_imm.replicate(), leon3_funcat_trap::SDIVcc_reg.replicate(), leon3_funclt_trap::SDIVcc_reg.replicate(), leon3_funcat_trap::ADD_reg.replicate(), leon3_funclt_trap::ADD_reg.replicate(), leon3_funcat_trap::TRAP_imm.replicate(), leon3_funclt_trap::TRAP_imm.replicate(), leon3_funcat_trap::WRITEtbr_imm.replicate(), leon3_funclt_trap::WRITEtbr_imm.replicate(), leon3_funcat_trap::LDUB_reg.replicate(), leon3_funclt_trap::LDUB_reg.replicate(), leon3_funcat_trap::RESTORE_reg.replicate(), leon3_funclt_trap::RESTORE_reg.replicate(), leon3_funcat_trap::ADDXcc_reg.replicate(), leon3_funclt_trap::ADDXcc_reg.replicate(), leon3_funcat_trap::STB_reg.replicate(), leon3_funclt_trap::STB_reg.replicate(), leon3_funcat_trap::AND_imm.replicate(), leon3_funclt_trap::AND_imm.replicate(), leon3_funcat_trap::SMUL_imm.replicate(), leon3_funclt_trap::SMUL_imm.replicate(), leon3_funcat_trap::ADD_imm.replicate(), leon3_funclt_trap::ADD_imm.replicate(), leon3_funcat_trap::UMUL_imm.replicate(), leon3_funclt_trap::UMUL_imm.replicate(), leon3_funcat_trap::READwim.replicate(), leon3_funclt_trap::READwim.replicate(), leon3_funcat_trap::LDSTUB_imm.replicate(), leon3_funclt_trap::LDSTUB_imm.replicate(), leon3_funcat_trap::SMAC_imm.replicate(), leon3_funclt_trap::SMAC_imm.replicate(), leon3_funcat_trap::LDSB_reg.replicate(), leon3_funclt_trap::LDSB_reg.replicate(), leon3_funcat_trap::ANDN_reg.replicate(), leon3_funclt_trap::ANDN_reg.replicate(), leon3_funcat_trap::TSUBccTV_reg.replicate(), leon3_funclt_trap::TSUBccTV_reg.replicate(), leon3_funcat_trap::SETHI.replicate(), leon3_funclt_trap::SETHI.replicate(), leon3_funcat_trap::SRA_imm.replicate(), leon3_funclt_trap::SRA_imm.replicate(), leon3_funcat_trap::LDSH_reg.replicate(), leon3_funclt_trap::LDSH_reg.replicate(), leon3_funcat_trap::UDIVcc_reg.replicate(), leon3_funclt_trap::UDIVcc_reg.replicate(), leon3_funcat_trap::ORN_imm.replicate(), leon3_funclt_trap::ORN_imm.replicate(), leon3_funcat_trap::STD_reg.replicate(), leon3_funclt_trap::STD_reg.replicate(), leon3_funcat_trap::ANDNcc_imm.replicate(), leon3_funclt_trap::ANDNcc_imm.replicate(), leon3_funclt_trap::TADDccTV_imm.replicate(), leon3_funcat_trap::TADDccTV_imm.replicate(), leon3_funcat_trap::WRITEtbr_reg.replicate(), leon3_funclt_trap::WRITEtbr_reg.replicate(), leon3_funcat_trap::SUBX_reg.replicate(), leon3_funclt_trap::SUBX_reg.replicate(), leon3_funcat_trap::XNOR_imm.replicate(), leon3_funclt_trap::XNOR_imm.replicate(), leon3_funcat_trap::UDIV_imm.replicate(), leon3_funclt_trap::UDIV_imm.replicate(), leon3_funclt_trap::LDSH_imm.replicate(), leon3_funcat_trap::LDSH_imm.replicate(), leon3_funclt_trap::UNIMP.replicate(), leon3_funcat_trap::UNIMP.replicate(), leon3_funcat_trap::LDSTUBA_reg.replicate(), leon3_funclt_trap::LDSTUBA_reg.replicate(), leon3_funclt_trap::UMULcc_imm.replicate(), leon3_funcat_trap::UMULcc_imm.replicate(), leon3_funclt_trap::ORcc_reg.replicate(), leon3_funcat_trap::ORcc_reg.replicate(), leon3_funcat_trap::MULScc_imm.replicate(), leon3_funclt_trap::MULScc_imm.replicate(), leon3_funcat_trap::XORcc_reg.replicate(), leon3_funclt_trap::XORcc_reg.replicate(), leon3_funclt_trap::SUB_reg.replicate(), leon3_funcat_trap::SUB_reg.replicate(), leon3_funclt_trap::WRITEwim_reg.replicate(), leon3_funcat_trap::WRITEwim_reg.replicate(), leon3_funcat_trap::UMAC_imm.replicate(), leon3_funclt_trap::UMAC_imm.replicate(), leon3_funcat_trap::TSUBcc_reg.replicate(), leon3_funclt_trap::TSUBcc_reg.replicate(), leon3_funclt_trap::BRANCH.replicate(), leon3_funcat_trap::BRANCH.replicate(), leon3_funclt_trap::SMULcc_reg.replicate(), leon3_funcat_trap::SMULcc_reg.replicate(), leon3_funcat_trap::SUB_imm.replicate(), leon3_funclt_trap::SUB_imm.replicate(), leon3_funclt_trap::ADDcc_reg.replicate(), leon3_funcat_trap::ADDcc_reg.replicate(), leon3_funclt_trap::XOR_reg.replicate(), leon3_funcat_trap::XOR_reg.replicate(), leon3_funclt_trap::SUBcc_imm.replicate(), leon3_funcat_trap::SUBcc_imm.replicate(), leon3_funcat_trap::TADDccTV_reg.replicate(), leon3_funclt_trap::TADDccTV_reg.replicate(), leon3_funclt_trap::SDIV_reg.replicate(), leon3_funcat_trap::SDIV_reg.replicate(), leon3_funcat_trap::SMULcc_imm.replicate(), leon3_funclt_trap::SMULcc_imm.replicate(), leon3_funclt_trap::SWAP_reg.replicate(), leon3_funcat_trap::SWAP_reg.replicate(), leon3_funclt_trap::SUBX_imm.replicate(), leon3_funcat_trap::SUBX_imm.replicate(), leon3_funclt_trap::STDA_reg.replicate(), leon3_funcat_trap::STDA_reg.replicate(), leon3_funclt_trap::UMAC_reg.replicate(), leon3_funcat_trap::UMAC_reg.replicate(), leon3_funclt_trap::JUMP_imm.replicate(), leon3_funcat_trap::JUMP_imm.replicate(), leon3_funclt_trap::SMUL_reg.replicate(), leon3_funcat_trap::SMUL_reg.replicate(), leon3_funclt_trap::XORcc_imm.replicate(), leon3_funcat_trap::XORcc_imm.replicate(), leon3_funclt_trap::ORNcc_imm.replicate(), leon3_funcat_trap::ORNcc_imm.replicate(), leon3_funclt_trap::LDUBA_reg.replicate(), leon3_funcat_trap::LDUBA_reg.replicate(), leon3_funclt_trap::JUMP_reg.replicate(), leon3_funcat_trap::JUMP_reg.replicate(), leon3_funclt_trap::ADDX_reg.replicate(), leon3_funcat_trap::ADDX_reg.replicate(), leon3_funcat_trap::UDIV_reg.replicate(), leon3_funclt_trap::UDIV_reg.replicate(), leon3_funclt_trap::XNORcc_imm.replicate(), leon3_funcat_trap::XNORcc_imm.replicate(), leon3_funcat_trap::STBAR.replicate(), leon3_funclt_trap::STBAR.replicate(), leon3_funclt_trap::LDA_reg.replicate(), leon3_funcat_trap::LDA_reg.replicate(), leon3_funcat_trap::STHA_reg.replicate(), leon3_funclt_trap::STHA_reg.replicate(), leon3_funclt_trap::LDDA_reg.replicate(), leon3_funcat_trap::LDDA_reg.replicate(), leon3_funcat_trap::SLL_reg.replicate(), leon3_funclt_trap::SLL_reg.replicate(), leon3_funclt_trap::RESTORE_imm.replicate(), leon3_funcat_trap::RESTORE_imm.replicate(), leon3_funcat_trap::LD_imm.replicate(), leon3_funclt_trap::LD_imm.replicate(), leon3_funcat_trap::TRAP_reg.replicate(), leon3_funclt_trap::TRAP_reg.replicate(), leon3_funcat_trap::LDUB_imm.replicate(), leon3_funclt_trap::LDUB_imm.replicate(), leon3_funclt_trap::RETT_reg.replicate(), leon3_funcat_trap::RETT_reg.replicate(), leon3_funcat_trap::SDIVcc_imm.replicate(), leon3_funclt_trap::SDIVcc_imm.replicate(), leon3_funcat_trap::SAVE_reg.replicate(), leon3_funclt_trap::SAVE_reg.replicate(), leon3_funclt_trap::OR_reg.replicate(), leon3_funcat_trap::OR_reg.replicate(), leon3_funclt_trap::ORcc_imm.replicate(), leon3_funcat_trap::ORcc_imm.replicate(), leon3_funclt_trap::CALL.replicate(), leon3_funcat_trap::CALL.replicate(), leon3_funcat_trap::WRITEpsr_reg.replicate(), leon3_funclt_trap::WRITEpsr_reg.replicate(), leon3_funclt_trap::ANDcc_imm.replicate(), leon3_funcat_trap::ANDcc_imm.replicate(), leon3_funclt_trap::IRQ_IRQ_Instruction.replicate(), and leon3_funcat_trap::IRQ_IRQ_Instruction.replicate().
tuple LEON3Arch.pcReg = trap.Register('PC', 32)
string LEON3Arch.post_code
Initial value:
 = """
 unsigned int newCwp = ((unsigned int)(PSR[key_CWP] + 1)) % """
string LEON3Arch.pre_code
Initial value:
 = """
 unsigned int newCwp = ((unsigned int)(PSR[key_CWP] - 1)) % """
tuple LEON3Arch.processor = trap.Processor('LEON3', version = '0.3', systemc = True, instructionCache = True, cacheLimit = 256)
Referenced by filterprocessor.FilterFiles().
dictionary LEON3Arch.psrBitMask = {'IMPL': (28, 31), 'VER': (24, 27), 'ICC_n': (23, 23), 'ICC_z': (22, 22), 'ICC_v': (21, 21), 'ICC_c': (20, 20), 'EC': (13, 13), 'EF': (12, 12), 'PIL': (8, 11), 'S': (7, 7), 'PS': (6, 6), 'ET': (5, 5), 'CWP': (0, 4)}
tuple LEON3Arch.psrReg = trap.Register('PSR', 32, psrBitMask)
tuple LEON3Arch.regs = trap.AliasRegBank('REGS', 32, ('GLOBAL[0-7]', 'WINREGS[0-23]'))
Referenced by i2cmst_test(), spictrl_test(), spimctrl_test(), spw_test(), svgactrl_test(), and uhc_test().
tuple LEON3Arch.regsStage = trap.PipeStage('regs')
tuple LEON3Arch.SP = trap.AliasRegister('SP', 'REGS[14]')
Referenced by grtm_test(), leon3_funcat_trap::LEON3_ABIIf.readSP(), leon3_funclt_trap::LEON3_ABIIf.readSP(), leon3_funcat_trap::InvalidInstr.replicate(), leon3_funclt_trap::InvalidInstr.replicate(), leon3_funclt_trap::READasr.replicate(), leon3_funcat_trap::READasr.replicate(), leon3_funclt_trap::WRITEY_reg.replicate(), leon3_funcat_trap::WRITEY_reg.replicate(), leon3_funcat_trap::XNOR_reg.replicate(), leon3_funclt_trap::XNOR_reg.replicate(), leon3_funclt_trap::ANDNcc_reg.replicate(), leon3_funcat_trap::ANDNcc_reg.replicate(), leon3_funclt_trap::LDSB_imm.replicate(), leon3_funcat_trap::LDSB_imm.replicate(), leon3_funclt_trap::WRITEpsr_imm.replicate(), leon3_funcat_trap::WRITEpsr_imm.replicate(), leon3_funcat_trap::READy.replicate(), leon3_funclt_trap::READy.replicate(), leon3_funcat_trap::XNORcc_reg.replicate(), leon3_funclt_trap::XNORcc_reg.replicate(), leon3_funclt_trap::READpsr.replicate(), leon3_funcat_trap::READpsr.replicate(), leon3_funclt_trap::ANDN_imm.replicate(), leon3_funcat_trap::ANDN_imm.replicate(), leon3_funclt_trap::ANDcc_reg.replicate(), leon3_funcat_trap::ANDcc_reg.replicate(), leon3_funclt_trap::TSUBcc_imm.replicate(), leon3_funcat_trap::TSUBcc_imm.replicate(), leon3_funclt_trap::LDSBA_reg.replicate(), leon3_funcat_trap::LDSBA_reg.replicate(), leon3_funclt_trap::LDUH_imm.replicate(), leon3_funcat_trap::LDUH_imm.replicate(), leon3_funcat_trap::STA_reg.replicate(), leon3_funclt_trap::STA_reg.replicate(), leon3_funcat_trap::ORN_reg.replicate(), leon3_funclt_trap::ORN_reg.replicate(), leon3_funcat_trap::LDSHA_reg.replicate(), leon3_funclt_trap::LDSHA_reg.replicate(), leon3_funcat_trap::STBA_reg.replicate(), leon3_funclt_trap::STBA_reg.replicate(), leon3_funcat_trap::ST_imm.replicate(), leon3_funclt_trap::ST_imm.replicate(), leon3_funclt_trap::READtbr.replicate(), leon3_funcat_trap::READtbr.replicate(), leon3_funclt_trap::UDIVcc_imm.replicate(), leon3_funcat_trap::UDIVcc_imm.replicate(), leon3_funclt_trap::SWAPA_reg.replicate(), leon3_funcat_trap::SWAPA_reg.replicate(), leon3_funclt_trap::ADDXcc_imm.replicate(), leon3_funcat_trap::ADDXcc_imm.replicate(), leon3_funclt_trap::STB_imm.replicate(), leon3_funcat_trap::STB_imm.replicate(), leon3_funclt_trap::SUBXcc_imm.replicate(), leon3_funcat_trap::SUBXcc_imm.replicate(), leon3_funclt_trap::STH_reg.replicate(), leon3_funcat_trap::STH_reg.replicate(), leon3_funclt_trap::SRL_imm.replicate(), leon3_funcat_trap::SRL_imm.replicate(), leon3_funclt_trap::WRITEasr_imm.replicate(), leon3_funcat_trap::WRITEasr_imm.replicate(), leon3_funclt_trap::UMULcc_reg.replicate(), leon3_funcat_trap::UMULcc_reg.replicate(), leon3_funclt_trap::LDSTUB_reg.replicate(), leon3_funcat_trap::LDSTUB_reg.replicate(), leon3_funcat_trap::XOR_imm.replicate(), leon3_funclt_trap::XOR_imm.replicate(), leon3_funcat_trap::SMAC_reg.replicate(), leon3_funclt_trap::SMAC_reg.replicate(), leon3_funcat_trap::WRITEasr_reg.replicate(), leon3_funclt_trap::WRITEasr_reg.replicate(), leon3_funcat_trap::LD_reg.replicate(), leon3_funclt_trap::LD_reg.replicate(), leon3_funcat_trap::ST_reg.replicate(), leon3_funclt_trap::ST_reg.replicate(), leon3_funcat_trap::SUBcc_reg.replicate(), leon3_funclt_trap::SUBcc_reg.replicate(), leon3_funcat_trap::LDD_reg.replicate(), leon3_funclt_trap::LDD_reg.replicate(), leon3_funcat_trap::ADDcc_imm.replicate(), leon3_funclt_trap::ADDcc_imm.replicate(), leon3_funcat_trap::LDUH_reg.replicate(), leon3_funclt_trap::LDUH_reg.replicate(), leon3_funcat_trap::SRL_reg.replicate(), leon3_funclt_trap::SRL_reg.replicate(), leon3_funcat_trap::SAVE_imm.replicate(), leon3_funclt_trap::SAVE_imm.replicate(), leon3_funcat_trap::MULScc_reg.replicate(), leon3_funclt_trap::MULScc_reg.replicate(), leon3_funcat_trap::OR_imm.replicate(), leon3_funclt_trap::OR_imm.replicate(), leon3_funcat_trap::STD_imm.replicate(), leon3_funclt_trap::STD_imm.replicate(), leon3_funcat_trap::SUBXcc_reg.replicate(), leon3_funclt_trap::SUBXcc_reg.replicate(), leon3_funcat_trap::ADDX_imm.replicate(), leon3_funclt_trap::ADDX_imm.replicate(), leon3_funcat_trap::SWAP_imm.replicate(), leon3_funclt_trap::SWAP_imm.replicate(), leon3_funclt_trap::UMUL_reg.replicate(), leon3_funcat_trap::UMUL_reg.replicate(), leon3_funclt_trap::WRITEY_imm.replicate(), leon3_funcat_trap::WRITEY_imm.replicate(), leon3_funclt_trap::AND_reg.replicate(), leon3_funcat_trap::AND_reg.replicate(), leon3_funclt_trap::FLUSH_imm.replicate(), leon3_funcat_trap::FLUSH_imm.replicate(), leon3_funclt_trap::SRA_reg.replicate(), leon3_funcat_trap::SRA_reg.replicate(), leon3_funclt_trap::STH_imm.replicate(), leon3_funcat_trap::STH_imm.replicate(), leon3_funclt_trap::WRITEwim_imm.replicate(), leon3_funcat_trap::WRITEwim_imm.replicate(), leon3_funclt_trap::LDD_imm.replicate(), leon3_funcat_trap::LDD_imm.replicate(), leon3_funclt_trap::SLL_imm.replicate(), leon3_funcat_trap::SLL_imm.replicate(), leon3_funclt_trap::LDUHA_reg.replicate(), leon3_funcat_trap::LDUHA_reg.replicate(), leon3_funclt_trap::TADDcc_reg.replicate(), leon3_funcat_trap::TADDcc_reg.replicate(), leon3_funclt_trap::TADDcc_imm.replicate(), leon3_funcat_trap::TADDcc_imm.replicate(), leon3_funclt_trap::SDIV_imm.replicate(), leon3_funcat_trap::SDIV_imm.replicate(), leon3_funclt_trap::TSUBccTV_imm.replicate(), leon3_funcat_trap::TSUBccTV_imm.replicate(), leon3_funclt_trap::FLUSH_reg.replicate(), leon3_funcat_trap::FLUSH_reg.replicate(), leon3_funcat_trap::ORNcc_reg.replicate(), leon3_funclt_trap::ORNcc_reg.replicate(), leon3_funcat_trap::RETT_imm.replicate(), leon3_funclt_trap::RETT_imm.replicate(), leon3_funcat_trap::SDIVcc_reg.replicate(), leon3_funclt_trap::SDIVcc_reg.replicate(), leon3_funcat_trap::ADD_reg.replicate(), leon3_funclt_trap::ADD_reg.replicate(), leon3_funcat_trap::TRAP_imm.replicate(), leon3_funclt_trap::TRAP_imm.replicate(), leon3_funcat_trap::WRITEtbr_imm.replicate(), leon3_funclt_trap::WRITEtbr_imm.replicate(), leon3_funcat_trap::LDUB_reg.replicate(), leon3_funclt_trap::LDUB_reg.replicate(), leon3_funcat_trap::RESTORE_reg.replicate(), leon3_funclt_trap::RESTORE_reg.replicate(), leon3_funcat_trap::ADDXcc_reg.replicate(), leon3_funclt_trap::ADDXcc_reg.replicate(), leon3_funcat_trap::STB_reg.replicate(), leon3_funclt_trap::STB_reg.replicate(), leon3_funcat_trap::AND_imm.replicate(), leon3_funclt_trap::AND_imm.replicate(), leon3_funcat_trap::SMUL_imm.replicate(), leon3_funclt_trap::SMUL_imm.replicate(), leon3_funcat_trap::ADD_imm.replicate(), leon3_funclt_trap::ADD_imm.replicate(), leon3_funcat_trap::UMUL_imm.replicate(), leon3_funclt_trap::UMUL_imm.replicate(), leon3_funcat_trap::READwim.replicate(), leon3_funclt_trap::READwim.replicate(), leon3_funcat_trap::LDSTUB_imm.replicate(), leon3_funclt_trap::LDSTUB_imm.replicate(), leon3_funcat_trap::SMAC_imm.replicate(), leon3_funclt_trap::SMAC_imm.replicate(), leon3_funcat_trap::LDSB_reg.replicate(), leon3_funclt_trap::LDSB_reg.replicate(), leon3_funcat_trap::ANDN_reg.replicate(), leon3_funclt_trap::ANDN_reg.replicate(), leon3_funcat_trap::TSUBccTV_reg.replicate(), leon3_funclt_trap::TSUBccTV_reg.replicate(), leon3_funcat_trap::SETHI.replicate(), leon3_funclt_trap::SETHI.replicate(), leon3_funcat_trap::SRA_imm.replicate(), leon3_funclt_trap::SRA_imm.replicate(), leon3_funcat_trap::LDSH_reg.replicate(), leon3_funclt_trap::LDSH_reg.replicate(), leon3_funcat_trap::UDIVcc_reg.replicate(), leon3_funclt_trap::UDIVcc_reg.replicate(), leon3_funcat_trap::ORN_imm.replicate(), leon3_funclt_trap::ORN_imm.replicate(), leon3_funclt_trap::STD_reg.replicate(), leon3_funcat_trap::STD_reg.replicate(), leon3_funcat_trap::ANDNcc_imm.replicate(), leon3_funclt_trap::ANDNcc_imm.replicate(), leon3_funcat_trap::TADDccTV_imm.replicate(), leon3_funclt_trap::TADDccTV_imm.replicate(), leon3_funcat_trap::WRITEtbr_reg.replicate(), leon3_funclt_trap::WRITEtbr_reg.replicate(), leon3_funclt_trap::SUBX_reg.replicate(), leon3_funcat_trap::SUBX_reg.replicate(), leon3_funcat_trap::XNOR_imm.replicate(), leon3_funclt_trap::XNOR_imm.replicate(), leon3_funcat_trap::UDIV_imm.replicate(), leon3_funclt_trap::UDIV_imm.replicate(), leon3_funcat_trap::LDSH_imm.replicate(), leon3_funclt_trap::LDSH_imm.replicate(), leon3_funclt_trap::UNIMP.replicate(), leon3_funcat_trap::UNIMP.replicate(), leon3_funcat_trap::LDSTUBA_reg.replicate(), leon3_funclt_trap::LDSTUBA_reg.replicate(), leon3_funclt_trap::UMULcc_imm.replicate(), leon3_funcat_trap::UMULcc_imm.replicate(), leon3_funclt_trap::ORcc_reg.replicate(), leon3_funcat_trap::ORcc_reg.replicate(), leon3_funclt_trap::MULScc_imm.replicate(), leon3_funcat_trap::MULScc_imm.replicate(), leon3_funcat_trap::XORcc_reg.replicate(), leon3_funclt_trap::XORcc_reg.replicate(), leon3_funcat_trap::SUB_reg.replicate(), leon3_funclt_trap::SUB_reg.replicate(), leon3_funcat_trap::WRITEwim_reg.replicate(), leon3_funclt_trap::WRITEwim_reg.replicate(), leon3_funclt_trap::UMAC_imm.replicate(), leon3_funcat_trap::UMAC_imm.replicate(), leon3_funcat_trap::TSUBcc_reg.replicate(), leon3_funclt_trap::TSUBcc_reg.replicate(), leon3_funclt_trap::BRANCH.replicate(), leon3_funcat_trap::BRANCH.replicate(), leon3_funclt_trap::SMULcc_reg.replicate(), leon3_funcat_trap::SMULcc_reg.replicate(), leon3_funclt_trap::SUB_imm.replicate(), leon3_funcat_trap::SUB_imm.replicate(), leon3_funclt_trap::ADDcc_reg.replicate(), leon3_funcat_trap::ADDcc_reg.replicate(), leon3_funclt_trap::XOR_reg.replicate(), leon3_funcat_trap::XOR_reg.replicate(), leon3_funclt_trap::SUBcc_imm.replicate(), leon3_funcat_trap::SUBcc_imm.replicate(), leon3_funcat_trap::TADDccTV_reg.replicate(), leon3_funclt_trap::TADDccTV_reg.replicate(), leon3_funclt_trap::SDIV_reg.replicate(), leon3_funcat_trap::SDIV_reg.replicate(), leon3_funclt_trap::SMULcc_imm.replicate(), leon3_funcat_trap::SMULcc_imm.replicate(), leon3_funcat_trap::SWAP_reg.replicate(), leon3_funclt_trap::SWAP_reg.replicate(), leon3_funclt_trap::SUBX_imm.replicate(), leon3_funcat_trap::SUBX_imm.replicate(), leon3_funclt_trap::STDA_reg.replicate(), leon3_funcat_trap::STDA_reg.replicate(), leon3_funclt_trap::UMAC_reg.replicate(), leon3_funcat_trap::UMAC_reg.replicate(), leon3_funclt_trap::JUMP_imm.replicate(), leon3_funcat_trap::JUMP_imm.replicate(), leon3_funclt_trap::SMUL_reg.replicate(), leon3_funcat_trap::SMUL_reg.replicate(), leon3_funclt_trap::XORcc_imm.replicate(), leon3_funcat_trap::XORcc_imm.replicate(), leon3_funclt_trap::ORNcc_imm.replicate(), leon3_funcat_trap::ORNcc_imm.replicate(), leon3_funclt_trap::LDUBA_reg.replicate(), leon3_funcat_trap::LDUBA_reg.replicate(), leon3_funclt_trap::JUMP_reg.replicate(), leon3_funcat_trap::JUMP_reg.replicate(), leon3_funclt_trap::ADDX_reg.replicate(), leon3_funcat_trap::ADDX_reg.replicate(), leon3_funcat_trap::UDIV_reg.replicate(), leon3_funclt_trap::UDIV_reg.replicate(), leon3_funclt_trap::XNORcc_imm.replicate(), leon3_funcat_trap::XNORcc_imm.replicate(), leon3_funcat_trap::STBAR.replicate(), leon3_funclt_trap::STBAR.replicate(), leon3_funclt_trap::LDA_reg.replicate(), leon3_funcat_trap::LDA_reg.replicate(), leon3_funcat_trap::STHA_reg.replicate(), leon3_funclt_trap::STHA_reg.replicate(), leon3_funcat_trap::LDDA_reg.replicate(), leon3_funclt_trap::LDDA_reg.replicate(), leon3_funclt_trap::SLL_reg.replicate(), leon3_funcat_trap::SLL_reg.replicate(), leon3_funclt_trap::RESTORE_imm.replicate(), leon3_funcat_trap::RESTORE_imm.replicate(), leon3_funcat_trap::LD_imm.replicate(), leon3_funclt_trap::LD_imm.replicate(), leon3_funclt_trap::TRAP_reg.replicate(), leon3_funcat_trap::TRAP_reg.replicate(), leon3_funcat_trap::LDUB_imm.replicate(), leon3_funclt_trap::LDUB_imm.replicate(), leon3_funcat_trap::RETT_reg.replicate(), leon3_funclt_trap::RETT_reg.replicate(), leon3_funclt_trap::SDIVcc_imm.replicate(), leon3_funcat_trap::SDIVcc_imm.replicate(), leon3_funcat_trap::SAVE_reg.replicate(), leon3_funclt_trap::SAVE_reg.replicate(), leon3_funclt_trap::OR_reg.replicate(), leon3_funcat_trap::OR_reg.replicate(), leon3_funcat_trap::ORcc_imm.replicate(), leon3_funclt_trap::ORcc_imm.replicate(), leon3_funclt_trap::CALL.replicate(), leon3_funcat_trap::CALL.replicate(), leon3_funcat_trap::WRITEpsr_reg.replicate(), leon3_funclt_trap::WRITEpsr_reg.replicate(), leon3_funcat_trap::ANDcc_imm.replicate(), leon3_funclt_trap::ANDcc_imm.replicate(), leon3_funclt_trap::IRQ_IRQ_Instruction.replicate(), leon3_funcat_trap::IRQ_IRQ_Instruction.replicate(), leon3_funcat_trap::LEON3_ABIIf.setSP(), and leon3_funclt_trap::LEON3_ABIIf.setSP().
LEON3Arch.standalone = False
dictionary LEON3Arch.tbrBitMask = {'TBA' : (12, 31), 'TT' : (4, 11)}
tuple LEON3Arch.tbrReg = trap.Register('TBR', 32, tbrBitMask)
tuple LEON3Arch.wbStage = trap.PipeStage('wb')
dictionary LEON3Arch.wimBitMask = {}
tuple LEON3Arch.wimReg = trap.Register('WIM', 32, wimBitMask)
tuple LEON3Arch.windowRegs = trap.RegisterBank('WINREGS', 16*numRegWindows, 32)
tuple LEON3Arch.yReg = trap.Register('Y', 32)