SoCRocket: core.waf.common Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
core.waf.common Namespace Reference
Classes
class Macclean
Functions
def options
def configure
def conf
def macclean
def get_subdirs
def recurse_all
def recurse_all_tests
def get_testdirs
def getdirs
def getfiles
def base
def fetch
def dep_fetch
def dep_build
def dep_path
def export_hase_define
Function Documentation
def core.waf.common.base (self, k, kw)
Referenced by core.waf.common.dep_build(), core.waf.common.dep_fetch(), core.waf.common.dep_path(), HSORT(), InitU(), trap::sbrkSysCall< wordSize >.operator()(), trap::getenvSysCall< wordSize >.operator()(), pcif_test(), and gs::amba::amba_slave< 32 >.setAddress().
def core.waf.common.conf (f)
References core.waf.cmake.f().
Referenced by core.waf.common.dep_build(), core.waf.common.dep_fetch(), core.waf.common.dep_path(), core.waf.common.get_subdirs(), core.waf.common.recurse_all(), and core.waf.common.recurse_all_tests().
def core.waf.common.configure (self)
Standard tools needed for fetching and building
def core.waf.common.dep_build (self, k, kw)
Configure/Make/Make install to the dist directory
References core.waf.common.base(), core.waf.common.conf(), and core.waf.common.fetch().
def core.waf.common.dep_fetch (self, k, kw)
Fetches and extracts the source to dist
References core.waf.common.base(), core.waf.common.conf(), and core.waf.common.fetch().
def core.waf.common.dep_path (self, name, version, k, kw)
References core.waf.common.base(), and core.waf.common.conf().
def core.waf.common.export_hase_define (self)
def core.waf.common.fetch (self, k, kw)
Fetch Dependency Sourcen
Referenced by core.waf.common.dep_build(), and core.waf.common.dep_fetch().
def core.waf.common.get_subdirs (self, path = '.')
Return a list of all subdirectories from path
References core.waf.common.conf().
def core.waf.common.get_testdirs (path = '.')
Return a list of all test subdirectories of path
Referenced by core.waf.common.recurse_all_tests().
def core.waf.common.getdirs (base = '.', excludes = list())
For external resources
Not used at the moment, maybe with greenreg or grlib
Return recursively all subdirectories of base,
exept directories matching excludes.
def core.waf.common.getfiles (base = '.', ext = list('*'), excludes = list())
Return recursively all files in base with an extension in ext excluding all who matching excludes
def core.waf.common.macclean (self)
Clean garbage files from the source tree
def core.waf.common.options (self)
Setting default waf options right for SoCRocket
def core.waf.common.recurse_all (self)
Extend the Configuration to recurse all subdirectories
References core.waf.common.conf().
def core.waf.common.recurse_all_tests (self)
Extend the Configuration to recurse all subdirectories tests dirs
References core.waf.common.conf(), and core.waf.common.get_testdirs().