SoCRocket: pysc::api::cci Namespace Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
pysc::api::cci Namespace Reference
Classes
class CallbackAdapter
class ParamList
class USICCIParam
Functions
bool exists (std::string name)
std::string read (std::string name)
void write (std::string name, std::string value)
ParamList list (std::string name)
bool is_int (std::string name)
bool is_float (std::string name)
bool is_bool (std::string name)
bool is_array (std::string name)
std::string get_documentation (std::string name)
std::string get_type_string (std::string name)
PyObject * get_properties (std::string name)
void register_callback (std::string name, PyObject *callback, gs::cnf::callback_type type)
void unregister_callback (PyObject *callback)
Variables
std::map< PyObject
*, boost::shared_ptr
< gs::cnf::ParamCallbAdapt_b > > callback_map
Function Documentation
bool pysc::api::cci::exists (std::string name)
std::string pysc::api::cci::get_documentation (std::string name)
PyObject * pysc::api::cci::get_properties (std::string name)
References core.waf.dependency::base(), dict, and sr_param_base::getProperties().
std::string pysc::api::cci::get_type_string (std::string name)
bool pysc::api::cci::is_array (std::string name)
bool pysc::api::cci::is_bool (std::string name)
bool pysc::api::cci::is_float (std::string name)
bool pysc::api::cci::is_int (std::string name)
ParamList pysc::api::cci::list (std::string name)
Referenced by klasses.SubModule::__dir__(), klasses.Module::__dir__(), klasses.SubModule::__getattr__(), klasses.Module::__getattr__(), core.waf.boost::check_boost(), statemachine::DebugPrintCases(), usi::find(), core.waf.common::getfiles(), core.waf.cpplint::init_env_from_options(), core.tools.generator.wizard.template.TemplatePage::initializePage(), usi.tools.elf::load_elf_intrinsics_to_processor(), core.tools.generator.wizard::main(), MakeRelativePathsInFlagsAbsolute(), statemachine::ProcessStateCases(), log2db::read_log(), transcript2db::read_log(), usi.log.db_reporter::report(), statemachine::SanitiseDotLink(), usi.log.db_reporter.Logger::store_buffer(), usi.sc_object::usi_extend_delegate(), shell::vexecute(), tools.python.power::view(), and core.waf.clang_compilation_database::write_compilation_database().
std::string pysc::api::cci::read (std::string name)
Referenced by Mctrl::exec_func(), readIntrinsic< wordSize >::operator()(), trap::readSysCall< wordSize >::operator()(), sr_signal::signal_infield< TYPE, MODULE >::operator[](), and sc_register_field_b< T >::print().
void pysc::api::cci::register_callback (std::string name, PyObject * callback, gs::cnf::callback_type type)
References callback_map.
void pysc::api::cci::unregister_callback (PyObject * callback)
References callback_map.
void pysc::api::cci::write (std::string name, std::string value)
Referenced by sc_register_b< T >::check_and_init(), core.tools.fixheaderguards::clean_include_guard(), sc_register_b< T >::mask_write(), writeIntrinsic< wordSize >::operator()(), trap::writeSysCall< wordSize >::operator()(), sr_signal::signal_out_if< TYPE >::operator=(), trap::GDBConnectionManager::processRequest(), TcpIO::sendChar(), and trap::GDBConnectionManager::sendResponse().
Variable Documentation
std::map<PyObject *, boost::shared_ptr<gs::cnf::ParamCallbAdapt_b> > pysc::api::cci::callback_map
Referenced by pysc::api::cci::USICCIParam::cci_register_callback(), pysc::api::cci::USICCIParam::cci_unregister_callback(), register_callback(), and unregister_callback().