SoCRocket: core/software/grlib_tests/pcif.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
pcif.c File Reference
Functions
int pcif_test (unsigned int base_addr, unsigned int conf_addr, unsigned int apb_addr)
Function Documentation
int pcif_test (unsigned int base_addr, unsigned int conf_addr, unsigned int apb_addr)
References core.waf.common::base(), conf, fail, report_device(), and report_subtest().