SoCRocket: core/software/fft64/radix4_input_gen.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
radix4_input_gen.c File Reference
#include "defines.h"
#include <asm-leon/irq.h>
#include "./input/data.h"
#include "results.h"
#include "stdio.h"
#include "../grlib_tests/irqmp.h"
Macros
#define OUTFILENAME "com3"
#define tol 10
Functions
void irqhandler_f (int irq)
void init_irqmp (struct irqmp *lr)
void socw_transfer (unsigned int address, unsigned int length)
void fft_radix4 (complex32 samples[], complex32 twiddles[], complex32 inplace[], int N)
int main ()
Variables
struct irqmp * irqmp_base
volatile int inputdev_irq = 0
volatile int socwire_irq = 0
Macro Definition Documentation
#define OUTFILENAME "com3"
#define tol 10
Function Documentation
void fft_radix4 (complex32 samples[], complex32 twiddles[], complex32 inplace[], int N)
References complex32::imag, N, complex32::real, and scale.
Referenced by main().
void init_irqmp (struct irqmp * lr)
Referenced by gptimer_test(), and main().
void irqhandler_f (int irq)
Referenced by main().
int main (void)
References catch_interrupt(), fft_radix4(), init_irqmp(), inplace, irqhandler_f(), irqmp::irqmask, N, r, samples, socw_transfer(), and twiddles.
void socw_transfer (unsigned int address, unsigned int length)
Referenced by main().
Variable Documentation
volatile int inputdev_irq = 0
struct irqmp* irqmp_base
Referenced by gptimer_test().
volatile int socwire_irq = 0