SoCRocket: core/software/grlib_tests/ramfill.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
ramfill.c File Reference
#include "cache.h"
#include <stdio.h>
Functions
void cache_disable (void)
void cache_enable (void)
void ramfill (void)
Function Documentation
void cache_disable (void)
Referenced by cramtest(), gptimer_test(), main(), and ramfill().
void cache_enable (void)
Referenced by cramtest(), and ramfill().
void ramfill (void)
References cache_disable(), cache_enable(), dcconf, dfill(), flush(), icconf, ifill(), and rsysreg().
Referenced by main().