SoCRocket: core/software/grlib_tests/ramtest.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
ramtest.c File Reference
#include "testmod.h"
#include "cache.h"
#include <stdlib.h>
#include <stdio.h>
Macros
#define CCTRL_IFP (1<<15)
#define CCTRL_DFP (1<<14)
Functions
int ddramtest1 (int, volatile double *, int)
int ddramtest2 (int, volatile double *, int)
int dtramtest (int, int, int, int, int)
int idramtest (int, int)
int itramtest (int, int, int, int)
int cramtest ()
Macro Definition Documentation
#define CCTRL_DFP (1<<14)
Referenced by cramtest().
#define CCTRL_IFP (1<<15)
Referenced by cramtest().
Function Documentation
int cramtest ()
References cache_disable(), cache_enable(), CCTRL_DFP, CCTRL_IFP, dcconf, DDAT_TEST, ddramtest1(), ddramtest2(), DTAG_TEST, dtramtest(), fail, flush(), icconf, IDAT_TEST, idramtest(), ITAG_TEST, itramtest(), report_subtest(), and rsysreg().
Referenced by leon3_test(), and main().
int ddramtest1 (int , volatile double * , int)
Referenced by cramtest().
int ddramtest2 (int , volatile double * , int)
Referenced by cramtest().
int dtramtest (int , int , int , int , int)
Referenced by cramtest().
int idramtest (int , int)
Referenced by cramtest().
int itramtest (int , int , int , int)
Referenced by cramtest().