SoCRocket: core/software/grlib_tests/report_device.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
report_device.c File Reference
Functions
report_start ()
report_end ()
report_device (int dev)
report_subtest (int dev)
fail (int dev)
Variables
volatile int * grtestmod = (volatile int *) 0x20000000
Function Documentation
fail (int dev)
report_device (int dev)
Referenced by apbps2_test(), apbuart_test(), brm_1553_test(), can_oc_test(), dsu3_tb_check(), ehc_test(), gpio_test(), gptimer_test(), grcan_test(), greth_test(), grhcan_test(), grpwm_test(), grtc_test(), grtm_test(), grusbdc_test(), i2c_test(), i2cmst_test(), i2cslv_test(), irqtest(), l2irqtest(), l2timers_test(), leon2_test(), leon3_test(), pci_test(), pcif_test(), rt_1553_test(), satcan_test(), spictrl_test(), spimctrl_test(), spw_test(), svgactrl_test(), and uhc_test().
report_end (void)
Referenced by main().
report_start (void)
Referenced by main().
report_subtest (int dev)
Referenced by apbps2_test(), brm_1553_test(), check_tbuf(), cramtest(), divtest(), ehc_test(), fputest(), gptimer_test(), grfpu_test(), grhcan_test(), grpwm_test(), grtc_test(), grtm_test(), i2c_test(), i2cmst_test(), i2cslv_test(), l2timers_test(), leon2_test(), leon3_test(), mmu_test(), mptest(), mptest_end(), multest(), pcif_test(), rt_1553_test(), spictrl_test(), spimctrl_test(), spw_test(), svgactrl_test(), and uhc_test().
Variable Documentation
volatile int* grtestmod = (volatile int *) 0x20000000