SoCRocket: core/software/grlib_tests/rt_1553.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
rt_1553.c File Reference
#include <stdlib.h>
Macros
#define ICLEAR 0x20c
#define IMASK 0x240
#define IFORCE 0x208
Functions
void * catch_interrupt (void func(), int irq)
enable_irq_rt (int irq)
disable_irq_rt (int irq)
force_irq_rt (int irq)
void irqhandler_rt (int irq)
error_rt (char *message, int *count)
void sync (volatile unsigned int *gpio, int gpio_sync, int gpio_ack)
int rt_1553_test (unsigned int brm_addr, unsigned int mem_addr, unsigned int gpio_addr, int gpio_sync, int gpio_ack)
Variables
volatile int * lreg_rt = (int *) 0x80000000
volatile int * rt_stat = (int *) 0x80000d00
volatile int * rt_ctrl = (int *) 0x80000d04
volatile int * rt_vword = (int *) 0x80000d08
volatile int * rt_intvect = (int *) 0x80000d0c
volatile int * rt_addrreg = (int *) 0x80000d10
volatile int * rt_irq = (int *) 0x80000d14
volatile unsigned short * rtmem
volatile int rt_done
unsigned int logbuf [1024]
unsigned int log_i =0
Macro Definition Documentation
#define ICLEAR 0x20c
Referenced by enable_irq_rt(), irqhandler_rt(), and rt_1553_test().
#define IFORCE 0x208
Referenced by force_irq_rt().
#define IMASK 0x240
Referenced by disable_irq_rt(), and enable_irq_rt().
Function Documentation
void* catch_interrupt (void func(), int irq)
Referenced by gptimer_test(), irqtest(), l2irqtest(), main(), and rt_1553_test().
disable_irq_rt (int irq)
References IMASK, and irq.
enable_irq_rt (int irq)
References ICLEAR, IMASK, and irq.
Referenced by rt_1553_test().
error_rt (char * message, int * count)
Referenced by rt_1553_test().
force_irq_rt (int irq)
References IFORCE, and irq.
void irqhandler_rt (int irq)
References i, ICLEAR, irq, and rt_intvect.
Referenced by rt_1553_test().
int rt_1553_test (unsigned int brm_addr, unsigned int mem_addr, unsigned int gpio_addr, int gpio_sync, int gpio_ack)
References catch_interrupt(), enable_irq_rt(), error_rt(), fail, i, ICLEAR, irqhandler_rt(), mem, report_device(), report_subtest(), rtmem, and sync().
void sync (volatile unsigned int * gpio, int gpio_sync, int gpio_ack)
Referenced by rt_1553_test().
Variable Documentation
unsigned int log_i =0
unsigned int logbuf[1024]
volatile int* lreg_rt = (int *) 0x80000000
volatile int* rt_addrreg = (int *) 0x80000d10
volatile int* rt_ctrl = (int *) 0x80000d04
volatile int rt_done
volatile int* rt_intvect = (int *) 0x80000d0c
Referenced by irqhandler_rt().
volatile int* rt_irq = (int *) 0x80000d14
volatile int* rt_stat = (int *) 0x80000d00
volatile int* rt_vword = (int *) 0x80000d08
volatile unsigned short* rtmem
Referenced by rt_1553_test().