SoCRocket: core/software/grlib_tests/irqmp.h File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
irqmp.h File Reference
#include <asm-leon/irq.h>
Classes
struct irqmp
Functions
void init_irqmp (struct irqmp *lr)
int irqtest (int addr)
Variables
struct irqmp * irqmp_base
Function Documentation
void init_irqmp (struct irqmp * lr)
References irqmp::irqclear, irqmp::irqlevel, and irqmp::irqmask.
Referenced by gptimer_test(), irqtest(), and main().
int irqtest (int addr)
References catch_interrupt(), fail, init_irqmp(), irqmp::irqclear, irqmp::irqforce, irqhandler_f(), irqmp::irqlevel, irqmp::irqmask, report_device(), setpsr(), success(), and xgetpsr().
Referenced by base_test(), base_test_tirq(), and main().
Variable Documentation
struct irqmp* irqmp_base
Referenced by gptimer_test().