SoCRocket: core/software/grlib_tests/spwtest.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
spwtest.c File Reference
#include "testmod.h"
#include <stdlib.h>
Classes
struct spwregs
Functions
int spw_test (int addr)
Function Documentation
int spw_test (int addr)
References spwregs::clkdiv, spwregs::ctrl, spwregs::destkey, spwregs::dmactrl, fail, spwregs::nodeaddr, LEON3Arch::regs, report_device(), report_subtest(), rsysreg(), spwregs::rxdesc, spwregs::rxmaxlen, SPW_NOSNOOP_TEST, SPW_RMAP_TEST, SPW_SNOOP_TEST, SPW_TIME_TEST, spwregs::status, spwregs::time, and spwregs::txdesc.