SoCRocket: core/software/grlib_tests/standalone.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
standalone.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include "grcommon.h"
#include "standalone.h"
Functions
void report_start (void)
void report_end (void)
void report_device (int dev)
void report_subtest (int test)
void fail (int dev)
void success (int dev)
char * dev_to_string (unsigned int dev)
char * dev_to_subtest (int dev, int test)
Variables
int device = 0
Function Documentation
char* dev_to_string (unsigned int dev)
References ESA_L2IRQ, ESA_LEON2, ESA_MCTRL, GAISLER_APBUART, GAISLER_CANAHB, GAISLER_ETHMAC, GAISLER_FTAHBRAM, GAISLER_FTMCTRL, GAISLER_FTSRCTRL, GAISLER_GPTIMER, GAISLER_GRGPIO, GAISLER_I2CMST, GAISLER_IRQMP, GAISLER_LEON3, GAISLER_LEON3FT, GAISLER_PCIFBRG, GAISLER_SPICTRL, and GAISLER_SPW.
Referenced by report_device().
char* dev_to_subtest (int dev, int test)
References ESA_LEON2, GAISLER_GPTIMER, GAISLER_LEON3, GAISLER_LEON3FT, and VENDOR_GAISLER.
Referenced by report_subtest().
void fail (int dev)
void report_device (int dev)
References dev_to_string().
void report_end (void)
void report_start (void)
References get_pid.
void report_subtest (int test)
References dev_to_subtest().
void success (int dev)
Referenced by gptimer_test(), irqtest(), gs::cnf::gs_config_t< sc_dt::sc_uint< W > >::setString(), and gs_config< sc_core::sc_attribute< T > >::setString().
Variable Documentation
int device = 0
Referenced by APBCtrl::getPNPReg(), and Mctrl::start_of_simulation().