SoCRocket: pci_config_access_functions Struct Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
pci_config_access_functions Struct Reference
#include <pcitest.h>
Public Attributes
int(* read_config_byte)(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char *)
int(* read_config_word)(unsigned char, unsigned char, unsigned char, unsigned char, unsigned short *)
int(* read_config_dword)(unsigned char, unsigned char, unsigned char, unsigned char, unsigned int *)
int(* write_config_byte)(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
int(* write_config_word)(unsigned char, unsigned char, unsigned char, unsigned char, unsigned short)
int(* write_config_dword)(unsigned char, unsigned char, unsigned char, unsigned char, unsigned int)
Member Data Documentation
int(* pci_config_access_functions::read_config_byte)(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char *)
Referenced by pci_read_config_byte().
int(* pci_config_access_functions::read_config_dword)(unsigned char, unsigned char, unsigned char, unsigned char, unsigned int *)
Referenced by pci_read_config_dword().
int(* pci_config_access_functions::read_config_word)(unsigned char, unsigned char, unsigned char, unsigned char, unsigned short *)
Referenced by pci_read_config_word().
int(* pci_config_access_functions::write_config_byte)(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
Referenced by pci_write_config_byte().
int(* pci_config_access_functions::write_config_dword)(unsigned char, unsigned char, unsigned char, unsigned char, unsigned int)
Referenced by pci_write_config_dword().
int(* pci_config_access_functions::write_config_word)(unsigned char, unsigned char, unsigned char, unsigned char, unsigned short)
Referenced by pci_write_config_word().
The documentation for this struct was generated from the following file:
core/software/grlib_tests/pcitest.h