SoCRocket: core/software/grlib_tests/testmod.h File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
testmod.h File Reference
Macros
#define START_TEST 0
#define STOP_TEST 1
#define TEST_FAIL 2
#define REGFILE 3
#define MUL_TEST 4
#define DIV_TEST 5
#define CACHE_TEST 6
#define MP_TEST 7
#define FPU_TEST 8
#define ITAG_TEST 9
#define DTAG_TEST 10
#define IDAT_TEST 11
#define DDAT_TEST 12
#define GRFPU_TEST 13
#define MMU_TEST 14
#define APBUART_TEST 7
#define FTSRCTRL 8
#define GPIO 9
#define CMEM_TEST 10
#define IRQ_TEST 11
#define SPW_TEST 12
#define MCTRL_BYTE 3
#define MCTRL_EDAC 4
#define MCTRL_WPROT 5
#define SPW_SNOOP_TEST 1
#define SPW_NOSNOOP_TEST 2
#define SPW_RMAP_TEST 3
#define SPW_TIME_TEST 4
Functions
void report_device (int)
void report_subtest (int)
void fail (int)
Variables
int irqmp_addr
void(* mpfunc [16])(int index)
Macro Definition Documentation
#define APBUART_TEST 7
#define CACHE_TEST 6
#define CMEM_TEST 10
#define DDAT_TEST 12
Referenced by cramtest().
#define DIV_TEST 5
Referenced by divtest().
#define DTAG_TEST 10
Referenced by cramtest().
#define FPU_TEST 8
Referenced by fputest().
#define FTSRCTRL 8
#define GPIO 9
#define GRFPU_TEST 13
Referenced by grfpu_test().
#define IDAT_TEST 11
Referenced by cramtest().
#define IRQ_TEST 11
#define ITAG_TEST 9
Referenced by cramtest().
#define MCTRL_BYTE 3
#define MCTRL_EDAC 4
#define MCTRL_WPROT 5
#define MMU_TEST 14
Referenced by mmu_test().
#define MP_TEST 7
Referenced by mptest(), and mptest_end().
#define MUL_TEST 4
Referenced by multest().
#define REGFILE 3
Referenced by leon2_test(), and leon3_test().
#define SPW_NOSNOOP_TEST 2
Referenced by spw_test().
#define SPW_RMAP_TEST 3
Referenced by spw_test().
#define SPW_SNOOP_TEST 1
Referenced by spw_test().
#define SPW_TEST 12
#define SPW_TIME_TEST 4
Referenced by spw_test().
#define START_TEST 0
#define STOP_TEST 1
#define TEST_FAIL 2
Function Documentation
void fail (int)
void report_device (int)
References dev_to_string().
Referenced by apbps2_test(), apbuart_test(), brm_1553_test(), can_oc_test(), dsu3_tb_check(), ehc_test(), gpio_test(), gptimer_test(), grcan_test(), greth_test(), grhcan_test(), grpwm_test(), grtc_test(), grtm_test(), grusbdc_test(), i2c_test(), i2cmst_test(), i2cslv_test(), irqtest(), l2irqtest(), l2timers_test(), leon2_test(), leon3_test(), pci_test(), pcif_test(), rt_1553_test(), satcan_test(), spictrl_test(), spimctrl_test(), spw_test(), svgactrl_test(), and uhc_test().
void report_subtest (int)
References dev_to_subtest().
Referenced by apbps2_test(), brm_1553_test(), check_tbuf(), cramtest(), divtest(), ehc_test(), fputest(), gptimer_test(), grfpu_test(), grhcan_test(), grpwm_test(), grtc_test(), grtm_test(), i2c_test(), i2cmst_test(), i2cslv_test(), l2timers_test(), leon2_test(), leon3_test(), mmu_test(), mptest(), mptest_end(), multest(), pcif_test(), rt_1553_test(), spictrl_test(), spimctrl_test(), spw_test(), svgactrl_test(), and uhc_test().
Variable Documentation
int irqmp_addr
void(* mpfunc[16])(int index)
Referenced by leon3_test().