SoCRocket: core/software/trapgen/tolstoy.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
tolstoy.c File Reference
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
Classes
struct complex
struct filter
Macros
#define MYMATH_H
#define RTOLS_H
#define RTOLS_ERROR_GENERAL -1
#define RTOLS_ERROR_RESTART_FAILED -2
#define RTOLS_ERROR_SHARED_INPUT -4
#define RTOLS_ERROR_UNSHARED_INPUT -8
#define RTOLS_SHARED_NONE 0
#define RTOLS_SHARED_FFT 1
#define RTOLS_SHARED_INPUT 2
#define RTOLS_SHARED_FILTER 4
#define RTOLS_SHARED_OUTPUT_ADD 8
#define TOLS_H
#define TWOPI 6.28318530717959
#define SWAP(a, b) temp = (a); (a) = (b); (b) = temp
#define SWAP(a, b) temp = (a); (a) = (b); (b) = temp
Typedefs
typedef double real
Functions
complex cadd (complex x, complex y)
complex csub (complex x, complex y)
complex cmult (complex x, complex y)
complex cdiv (complex x, complex y)
real cmag (complex x)
real mycarg (complex x)
complex mycexp (real mag, real arg)
int r2c (real *in, complex *out, int len)
int c2r (complex *in, real *out, int len, int mode)
int bitrev (int i, int m)
void ffw (complex *w, int idir, int n)
void perm (complex *x, int m)
void permrev (complex *x, int m)
void permcpy (complex *x, complex *y, int m)
void permrevcpy (complex *x, complex *y, int m)
void fft1d (complex *x, complex *w, int idir, int n)
void fft (complex *x, complex *w, int m)
void fftrev (complex *x, complex *w, int m)
void ifft (complex *x, complex *w, int m)
void fftcpy (complex *x, complex *y, complex *w, int m)
void ifftcpy (complex *x, complex *y, complex *w, int m)
void fconv (complex *x, complex *h, complex *y, complex *wf, complex *wi, int m)
void fwconv (complex *x, complex *h, complex *y, int m)
void tconv (complex *x, int xlen, complex *h, int ylen, complex *y)
void printcvec (complex *x, int n)
void printrvec (real *x, int n)
void printbits (int n)
int rtols_prepare (filter *filt, complex *h, int hlen, int m)
int rtols_prepare_sigshare (filter *filt, complex *h, int hlen, complex *wf, complex *wi, complex **XX, int R, int m, int addout)
int rtols_prepare_filtshare (filter *filt, complex *wf, complex *wi, complex **HH, int R, int hlen, int m)
int rtols_filter (filter *filt, real *inbuf, real *outbuf)
int rtols_filter_sigshare (filter *filters, int nfilt, real *inbuf, real **outbuf, int outoffset)
int rtols_filter_update (filter *filt, complex *h, int hlen, int transition)
int rtols_finish (filter *filt, int len)
int rtols_restart (filter *filt)
int rtols_cleanup (filter *filt)
void ols (complex *x, int xlen, complex *h, int hlen, complex *y, int ylen, int m)
int tols (complex *x, int xlen, complex *h, int hlen, complex *y, int ylen, int m)
void segment_ir (complex *h, int hlen, int m, complex *wf, complex **HH)
int rtconv ()
void make_irs (complex ***hh, int P, int Q, int hlen)
int rtwfs ()
void conv3 ()
void testperm ()
int main (int argc, char **argv)
Macro Definition Documentation
#define MYMATH_H
#define RTOLS_ERROR_GENERAL -1
#define RTOLS_ERROR_RESTART_FAILED -2
#define RTOLS_ERROR_SHARED_INPUT -4
Referenced by rtols_filter().
#define RTOLS_ERROR_UNSHARED_INPUT -8
Referenced by rtols_filter_sigshare().
#define RTOLS_H
#define RTOLS_SHARED_FFT 1
Referenced by rtols_cleanup(), rtols_prepare_filtshare(), and rtols_prepare_sigshare().
#define RTOLS_SHARED_FILTER 4
Referenced by rtols_cleanup(), and rtols_prepare_filtshare().
#define RTOLS_SHARED_INPUT 2
Referenced by rtols_cleanup(), rtols_filter(), rtols_filter_sigshare(), and rtols_prepare_sigshare().
#define RTOLS_SHARED_NONE 0
Referenced by rtols_prepare().
#define RTOLS_SHARED_OUTPUT_ADD 8
Referenced by rtols_filter_sigshare(), and rtols_prepare_sigshare().
#define SWAP (a, b) temp = (a); (a) = (b); (b) = temp
Referenced by perm(), permrev(), and testperm().
#define SWAP (a, b) temp = (a); (a) = (b); (b) = temp
#define TOLS_H
#define TWOPI 6.28318530717959
Referenced by ffw().
Typedef Documentation
typedef double real
real data type (float or double)
Function Documentation
int bitrev (int i, int m)
bit reversal
Parameters
i number with bits
m number of total bits (=ld of size of fft n=2^m).
Referenced by perm(), and permrev().
int c2r (complex * in, real * out, int len, int mode)
conversion from complex to real
Parameters
in complex input
out real output
len buffer lengths
mode uses Re(z) if 0, Im(z) if 1, |z| if 2, arg(z) if 3
Returns
error code <0 or 0.
References cmag(), i, and mycarg().
complex cadd (complex x, complex y)
complex multiplication
Parameters
x
y
Returns
x * y
References complex::im, complex::re, and z.
Referenced by tconv(), and tols().
complex cdiv (complex x, complex y)
complex division
Parameters
x
y
Returns
x * y
References complex::im, complex::re, and z.
real cmag (complex x)
magnitude of a complex number
Parameters
x
Returns
|x|
References complex::im, and complex::re.
Referenced by c2r().
complex cmult (complex x, complex y)
complex multiplication
Parameters
x
y
Returns
x * y
References complex::im, complex::re, and z.
Referenced by fconv(), ols(), rtols_filter(), tconv(), and tols().
void conv3 ()
Tolstoy: Time-partitioned OverLap-Save TOY application for the hArtes project.
test test overlap / save algorithm and its time-partitioned equivalent.
References h, i, complex::im, printcvec(), complex::re, tols(), and x.
Referenced by main().
complex csub (complex x, complex y)
complex subtraction
Parameters
x
y
Returns
x * y
References complex::im, complex::re, and z.
void fconv (complex * x, complex * h, complex * y, complex * wf, complex * wi, int m)
frequency-domain convolution
Parameters
x [in] time-domain signal x, length 2^(m-1)
h [in] impulse response h, length 2^(m-1)
y [out] convolved time-domain signal y = x ** h, length 2^m
wf phase factors for fft
wf phase factors for inverse fft
m ld of fft size
References cmult(), fftcpy(), i, and ifftcpy().
Referenced by fwconv().
void fft (complex * x, complex * w, int m)
complete in-place fft
Parameters
x [in/out] time/freq
w phase factors for transformation
References fft1d(), and perm().
Referenced by ols(), rtols_filter(), segment_ir(), and tols().
void fft1d (complex * x, complex * w, int idir, int n)
fft core routine. (must be prepended by a permutation)
Parameters
[in/out] time/freq domain vector
direction (forward = 1, backward = -1)
size of fft (should be 2^N)
References i, complex::im, complex::re, and z.
Referenced by fft(), fftcpy(), fftrev(), ifft(), and ifftcpy().
void fftcpy (complex * x, complex * y, complex * w, int m)
complete fft preserving input
Parameters
x [in] time
y [out] freq
w phase factors for transformation
References fft1d(), and permcpy().
Referenced by fconv().
void fftrev (complex * x, complex * w, int m)
complete in-place fft with reversed half-frame order
Parameters
x [in/out] time (with reversed half-frame order)/freq
w phase factors for transformation
References fft1d(), and permrev().
void ffw (complex * w, int idir, int n)
calculate phase factors
Parameters
w [out] array of phase factors (fft size / 2)
idir direction (forward = 1, backward = -1)
size of fft
References i, complex::im, complex::re, and TWOPI.
Referenced by fwconv(), ols(), rtols_prepare(), rtwfs(), and tols().
void fwconv (complex * x, complex * h, complex * y, int m)
frequency-domain convolution with internal weights calculation
Parameters
x [in] time-domain signal x, length 2^(m-1) plus zero padding to length 2^m
h [in] impulse response h, length 2^(m-1) plus zero padding to length 2^m
y [out] convolved time-domain signal y = x ** h, length 2^m
m ld of fft size
References fconv(), and ffw().
void ifft (complex * x, complex * w, int m)
complete in-place ifft
Parameters
x [in/out] freq/time
w phase factors for inverse transformation
References fft1d(), and perm().
Referenced by ols(), rtols_filter(), and tols().
void ifftcpy (complex * x, complex * y, complex * w, int m)
complete ifft preserving input
Parameters
x [in] freq
y [out] time
w phase factors for transformation
References fft1d(), and permcpy().
Referenced by fconv().
int main (int argc, char ** argv)
References conv3(), i, rtconv(), and testperm().
void make_irs (complex *** hh, int P, int Q, int hlen)
for rtwfs(): make dummy irs (here: time domain, but easy to change to transfer functions)
References i, complex::im, P, and complex::re.
Referenced by rtwfs().
real mycarg (complex x)
phase of a complex number
Parameters
x
Returns
arg(x)
References complex::im, and complex::re.
Referenced by c2r().
complex mycexp (real mag, real arg)
complex number from magnitude and phase
Parameters
mag magnitude
Returns
mag * exp(j arg)
References complex::im, complex::re, and z.
void ols (complex * x, int xlen, complex * h, int hlen, complex * y, int ylen, int m)
References cmult(), fft(), ffw(), H, i, ifft(), complex::im, M, and complex::re.
void perm (complex * x, int m)
permutation from data order to butterfly order,
Parameters
x [in/out] data
m ld of fft size
References bitrev(), i, and SWAP.
Referenced by fft(), ifft(), permcpy(), and testperm().
void permcpy (complex * x, complex * y, int m)
permutation from data order to butterfly order into provided array.
Parameters
x [in] data
y [out] data
m ld of fft size
References perm().
Referenced by fftcpy(), and ifftcpy().
void permrev (complex * x, int m)
permutation from data order to butterfly order using reversed half- frames
Parameters
x [in/out] data whose actual order is x[2^(m-1):2^m-1]x[0:2^(m-1)]
m ld of fft size
References bitrev(), i, s, and SWAP.
Referenced by fftrev(), permrevcpy(), and testperm().
void permrevcpy (complex * x, complex * y, int m)
permutation from data order to butterfly order using reversed half- frames, copies into the provided array.
Parameters
x [in/out] data whose actual order is x[2^(m-1):2^m-1]x[0:2^(m-1)]
m ld of fft size
References permrev().
void printbits (int n)
print 8 lowest significant bits
References i.
void printcvec (complex * x, int n)
print complex vector of length n
Referenced by conv3(), rtconv(), testperm(), and tols().
void printrvec (real * x, int n)
print real vector of length n
Referenced by rtconv(), and rtwfs().
int r2c (real * in, complex * out, int len)
conversion from real to complex
Parameters
in real input
out complex output
len buffer lengths
Returns
error code <0 or 0.
References i, complex::im, and complex::re.
Referenced by rtols_filter().
int rtconv ()
driver function for a filter that can be hooked to audio i/o buffers and callback: When the audio i/o framework has finished filling a new input buffer, one step in the while loop of this method is done, after the while step has been finished (after a call to rtols_filter), the i/o framework is notified and can play its output buffer.
A note about conversion from tolstoy: Both versions of the program are included in the toy application in order to pursue the development process, which started at non-realtime algorithm development and then was structured to be converted into a real-time capable approach. The annotations made hint at the conversion steps.
Variable name conventions: used common sense and avoided naming rule mania, instead document with comments what's being done. Some conventions: array sizes and other dimensions – capital (mid alphabet) or *len; constant – uppercase; signals – time domain lowercase, frequency domain uppercase (h and end of alphabet): names after symbols common in associated math, e.g., h, x, y, X, Y; arrays – duplicate symbols, e.g., hh is an array of h, i.e., impulse responses.
Task annotation conventions: TODO: planned task, FIXME: known bug.
References h, filter::hassignal, i, complex::im, printcvec(), printrvec(), complex::re, rtols_cleanup(), rtols_filter(), rtols_finish(), rtols_prepare(), samples, and x.
Referenced by main().
int rtols_cleanup (filter * filt)
deallocates the internal filter memory (inbuf and outbuf must be freed).
Parameters
filter to be destoyed
Returns
error code <0 or 0
References filter::HH, r, filter::R, RTOLS_SHARED_FFT, RTOLS_SHARED_FILTER, RTOLS_SHARED_INPUT, filter::sharemode, filter::wf, filter::wi, filter::x, filter::XX, and filter::Y.
Referenced by rtconv().
int rtols_filter (filter * filt, real * inbuf, real * outbuf)
time-partitioned OLS convolution, streaming mode.
Triggers the algorithm that a new frame has been written into inbuf and last result will be read from outbuf. Important: Do not use for sharing inputs between filters, otherwise this is ignored and -4 returned.
Parameters
filters the filters to be triggered.
inbuf real input buffer where the frame is read from (size 2^(m-1) = fftsize/2 expected). After calling rtols_finish and the returned number of frames, inbuf is ignored (as there is no signal left).
outbuf real output buffer where the result is written to (size 2^(m-1) expected). If not the full buffer is filled with signal, it is zero-padded.
Returns
number of samples in the output buffer that are the signal or -1 if there is no signal left or error code <-1. This is especially useful after calls to rtols_finish().
BEGIN process frame
END process frame
References cmult(), fft(), filter::finishing, filter::hassignal, filter::hastail, filter::HH, filter::i, ifft(), complex::im, filter::K, filter::m, r, filter::R, r2c(), complex::re, RTOLS_ERROR_SHARED_INPUT, RTOLS_SHARED_INPUT, filter::S, filter::sharemode, filter::wf, filter::wi, filter::x, filter::xframes, filter::xlen, filter::XX, filter::Y, and filter::ylen.
Referenced by rtconv().
int rtols_filter_sigshare (filter * filters, int nfilt, real * inbuf, real ** outbuf, int outoffset)
time-partitioned OLS convolution, streaming mode.
Triggers the algorithm that a new frame has been written into inbuf and last result will be read from outbuf.
Parameters
filters the filters to be triggered.
nfilt number of filters (and output buffers)
inbuf real input buffer where the frame is read from (size 2^(m-1) = fftsize/2 expected). After calling rtols_finish and the returned number of frames, inbuf is ignored (as there is no signal left).
outbuf real output buffers where the result is written to (size 2^(m-1) expected).
outoffset offset to each output buffer (internal: pointer addition on each single buffer)
Returns
number of samples in the output buffer that are the signal or -1 if there is no signal left or error code <-1. This is especially useful after calls to rtols_finish().
References i, RTOLS_ERROR_UNSHARED_INPUT, RTOLS_SHARED_INPUT, and RTOLS_SHARED_OUTPUT_ADD.
Referenced by rtwfs().
int rtols_filter_update (filter * filt, complex * h, int hlen, int transition)
time-partitioned OLS convolution, streaming mode.
Updates the filter coefficients now
Parameters
h new impulse response
hlen length of new IR
transition number of frames that the IR will be crossfaded from the old one (frequency-domain interpolation)
Returns
error code <0 or 0
int rtols_finish (filter * filt, int len)
time-partitioned OLS convolution, streaming mode.
finishes the filter operation. Afterwards, the filter can be reused by calling rtols_restart. If the filter is shared by its input, finishes all filters that belong to the signal.
Parameters
filter filter to be finished
len the length of the input signal that remains to be filtered
Returns
number of times that rtols_filter must be called before the signal ends (and can be restarted).
References filter::finishing, filter::hlen, filter::i, filter::S, filter::xlen, and filter::ylen.
Referenced by rtconv(), and rtwfs().
int rtols_prepare (filter * filt, complex * h, int hlen, int m)
time-partitioned OLS convolution, streaming mode.
Prepares the filtering by allocating internal memory of a filter and setting up the transformations. The input and output buffers are complex arrays inbuf and outbuf. Therefore, the streaming framework that calls trigger must call the appropriate conversion methods rtols_*2*(in, out, len). TODO: fix this to avoid this inner-loop conversion.
In the system, two internal i/o buffers of type complex are generated, one of size 2^m for the input data, and one of size 2^(m-1) for the output data.
Parameters
filter the structure that contains all information for filtering
h impulse response
hlen length of h
m ld of fft size used to partition the signals, note that input and output buffers are fftsize/2
Returns
error code <0 or 0
References ffw(), filter::finishing, filter::hassignal, filter::hastail, filter::HH, filter::hlen, i, filter::i, filter::K, filter::L, filter::m, r, filter::R, RTOLS_SHARED_NONE, filter::S, segment_ir(), filter::sharemode, filter::wf, filter::wi, filter::x, filter::XX, filter::Y, and filter::ylen.
Referenced by rtconv().
int rtols_prepare_filtshare (filter * filt, complex * wf, complex * wi, complex ** HH, int R, int hlen, int m)
time-partitioned OLS convolution, streaming mode with shared resources for fft and filter transfer function.
Prepares the filtering by allocating internal memory of a filter and setting up the transformations. The input and output buffers are complex arrays inbuf and outbuf. Therefore, the streaming framework that calls trigger must call the appropriate conversion methods rtols_*2*(in, out, len). TODO: fix this to avoid this inner-loop conversion.
In the system, two internal i/o buffers of type complex are generated, one of size 2^m for the input data, and one of size 2^(m-1) for the output data.
Parameters
filter the structure that contains all information for filtering
wf forward fft structure
wi inverse fft structure
HH filter transfer functions (frame spectra), size R x 2^m
R number of filter frames
hlen original length of filter impulse response
m ld of fft size used to partition the signals, note that input and output buffers are fftsize/2
Returns
error code <0 or 0
References RTOLS_SHARED_FFT, RTOLS_SHARED_FILTER, and filter::sharemode.
int rtols_prepare_sigshare (filter * filt, complex * h, int hlen, complex * wf, complex * wi, complex ** XX, int R, int m, int addout)
time-partitioned OLS convolution, streaming mode with shared resources for fft and input buffer. Sharing the input buffer requires that the rtols_filter_sigshare method be used instead of rtols_filter, which will return -1 and ignore the call.
Prepares the filtering by allocating internal memory of a filter and setting up the transformations. The input and output buffers are complex arrays inbuf and outbuf. Therefore, the streaming framework that calls trigger must call the appropriate conversion methods rtols_*2*(in, out, len). TODO: fix this to avoid this inner-loop conversion.
In the system, two internal i/o buffers of type complex are generated, one of size 2^m for the input data, and one of size 2^(m-1) for the output data.
Parameters
filter the structure that contains all information for filtering
h impulse response
hlen length of h
wf forward fft structure
wi inverse fft structure
XX circular frame spectrum buffer of size R x 2^m, R is checked if it is compatible with hlen: R = ceil(hlen * 2^(-m+1)), if not, -2 as the error code is returned.
m ld of fft size used to partition the signals, note that input and output buffers are fftsize/2
addout 0 if outgoing signals overwrite the output buffer, 1 if they are added.
Returns
error code <0 or 0
References RTOLS_SHARED_FFT, RTOLS_SHARED_INPUT, RTOLS_SHARED_OUTPUT_ADD, and filter::sharemode.
Referenced by rtwfs().
int rtols_restart (filter * filt)
after a call to rtols_finish, the filter is restarted by a new signal at its input buffer.
Parameters
filter the filter to be reinitialised
Returns
error code <0 or 0, -1 is returned if the signal is still finishing and the restart is ignored
References filter::finishing, filter::hassignal, filter::hastail, i, filter::i, filter::K, complex::re, filter::x, and filter::ylen.
int rtwfs ()
outline for wave field synthesis run-time.
: This function only shows the organisation principle of filters and parallel handling requirements. An actual implementation needs to handle other things in addition, e.g., calculation of impulse responses. Special care must be taken in interaction between the hardware architecture (esp. memory interaction) and the software.
BEGIN allocation and initialisation
END allocation and initialisation
BEGIN main loop
BEGIN filtering step
END filtering step
END main loop
BEGIN deallocation
END deallocation
References core.waf.cmake::f(), ffw(), i, make_irs(), P, printrvec(), rtols_filter_sigshare(), rtols_finish(), rtols_prepare_sigshare(), samples, and filter::XX.
void segment_ir (complex * h, int hlen, int m, complex * wf, complex ** HH)
void stols_finish();
/* private for tols:
segment the impulse response into ceil(hlen/K) frames, where K is half the length of the FFT used.
Parameters
h complex impulse response
hlen length of complex impulse response
m ld of fft size (ld L); the impulse response frames fill only half of this (K)
wf fft weights (ffw)
HH [out] resulting ceil(hlen/K) transfer functions where K = 2^(m-1) = 1 << (m - 1)
References fft(), i, complex::im, and complex::re.
Referenced by rtols_prepare(), and tols().
void tconv (complex * x, int xlen, complex * h, int ylen, complex * y)
time-domain convolution
Parameters
x [in] time-domain signal x
xlen length of x
h [in] impulse response h
hlen length of h
y [out] convolved time-domain signal y = x ** h, length ylen = xlen + hlen - 1
References cadd(), cmult(), i, complex::im, and complex::re.
void testperm ()
References i, complex::im, N, perm(), permrev(), printcvec(), complex::re, SWAP, and x.
Referenced by main().
int tols (complex * x, int xlen, complex * h, int hlen, complex * y, int ylen, int m)
time-partitioned OLS convolution
Parameters
x input signal (time domain)
xlen length of x
h impulse response
hlen length of h
y output (length >= xlen + hlen)
m ld of fft size used to partition the signals.
Returns
error code <0 or 0.
General considerations
variable declarations
References cadd(), cmult(), fft(), ffw(), i, ifft(), complex::im, printcvec(), r, complex::re, segment_ir(), and Y.
Referenced by conv3().