SoCRocket: core/software/grlib_tests/top_ram_test.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
top_ram_test.c File Reference
#include "standalone.h"
#include "cache.h"
Functions
void cramtest ()
int main ()
Function Documentation
void cramtest ()
References cache_disable(), cache_enable(), CCTRL_DFP, CCTRL_IFP, dcconf, DDAT_TEST, ddramtest1(), ddramtest2(), DTAG_TEST, dtramtest(), fail, flush(), icconf, IDAT_TEST, idramtest(), ITAG_TEST, itramtest(), report_subtest(), and rsysreg().
Referenced by leon3_test(), and main().
int main (void)
References cramtest(), ramfill(), report_end(), and report_start().