SoCRocket: core/software/grlib_tests/top_reg_test.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
top_reg_test.c File Reference
#include "standalone.h"
Functions
void regtest ()
int main ()
Function Documentation
int main (void)
References regtest(), report_end(), and report_start().
void regtest ()
Referenced by leon2_test(), leon3_test(), and main().