SoCRocket: core/software/grlib_tests/top_mmu_test.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
top_mmu_test.c File Reference
#include "standalone.h"
#include "cache.h"
Functions
void ramfill ()
int mmu_test ()
int main ()
Function Documentation
int main (void)
References mmu_test(), ramfill(), report_end(), and report_start().
int mmu_test ()
References a_30041000, a_30041004, a_30042000, a_30043000, a_30080000, a_31000000, ctx, fail, func, g0, i, leon_flush_cache_all(), leon_flush_tlb_all(), l2regs::leonconf, MMU_CONF_BIT, mmu_double, mmu_func1(), MMU_TEST, mmugetpagesize(), p0, page0, page2, PAGE_SIZE, PAGE_SIZE_MAX, pg0, PGD_IDX, pgd_m, pm0, pmd_m, pt0, pte_m, pth_addr, pth_addr1, REAL_PAGE_SIZE, report_subtest(), rsysreg(), SRMMU_CACHE, SRMMU_DIRTY, SRMMU_ET_PTE, SRMMU_EXEC, SRMMU_PGD_TABLE_SIZE, SRMMU_PMD_TABLE_SIZE, SRMMU_PRIV, SRMMU_PRIV_RDONLY, SRMMU_PTE_TABLE_SIZE, SRMMU_PTRS_PER_CTX, SRMMU_REF, SRMMU_WRITE, and TLBNUM.
Referenced by leon2_test(), leon3_test(), and main().
void ramfill ()
References cache_disable(), cache_enable(), dcconf, dfill, flush(), icconf, ifill, and rsysreg().
Referenced by main().