SoCRocket: core/software/trapgen/wavelt.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
wavelt.c File Reference
#include <stdio.h>
#include <stdlib.h>
Functions
void fwt97 (double *x, int n)
void iwt97 (double *x, int n)
int main ()
Variables
double * tempbank =0
Function Documentation
void fwt97 (double * x, int n)
fwt97 - Forward biorthogonal 9/7 wavelet transform (lifting implementation)
x is an input signal, which will be replaced by its output transform. n is the length of the signal, and must be a power of 2.
The first half part of the output signal contains the approximation coefficients. The second half part contains the detail coefficients (aka. the wavelets coefficients).
See also iwt97.
Referenced by main().
void iwt97 (double * x, int n)
iwt97 - Inverse biorthogonal 9/7 wavelet transform
This is the inverse of fwt97 so that iwt97(fwt97(x,n),n)=x for every signal x of length n.
See also fwt97.
Referenced by main().
int main (void)
References fwt97(), iwt97(), and x.
Variable Documentation
double* tempbank =0
dwt97.c - Fast discrete biorthogonal CDF 9/7 wavelet forward and inverse transform (lifting implementation)
This code is provided "as is" and is given for educational purposes. 2006 - Gregoire Pau - grego.nosp@m.ire..nosp@m.pau@e.nosp@m.bi.a.nosp@m.c.uk