SoCRocket: core/software/trapgen/whets.c File Reference
SoCRocket
Transaction-Level Modeling Framework for Space Applications
whets.c File Reference
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
Macros
#define SPDP float
#define Precision "Single"
Functions
void whetstones (long xtra, long x100, int calibrate)
void pa (SPDP e[4], SPDP t, SPDP t2)
void po (SPDP e1[4], long j, long k, long l)
void p3 (SPDP *x, SPDP *y, SPDP *z, SPDP t, SPDP t1, SPDP t2)
void pout (char title[22], float ops, int type, SPDP checknum, SPDP time, int calibrate, int section)
int main (int argc, char *argv[])
void pout (char title[18], float ops, int type, SPDP checknum, SPDP time, int calibrate, int section)
Macro Definition Documentation
#define Precision "Single"
Referenced by main().
#define SPDP float
Referenced by main(), pout(), and whetstones().
Function Documentation
int main (int argc, char * argv[])
References Precision, SPDP, and whetstones().
void p3 (SPDP * x, SPDP * y, SPDP * z, SPDP t, SPDP t1, SPDP t2)
References y, and z.
Referenced by whetstones().
void pa (SPDP e[4], SPDP t, SPDP t2)
Referenced by whetstones().
void po (SPDP e1[4], long j, long k, long l)
Referenced by whetstones().
void pout (char title[22], float ops, int type, SPDP checknum, SPDP time, int calibrate, int section)
void pout (char title[18], float ops, int type, SPDP checknum, SPDP time, int calibrate, int section)
References SPDP.
void whetstones (long xtra, long x100, int calibrate)
References p3(), pa(), po(), SPDP, x, y, and z.
Referenced by main().